### ISSUE TITLE
[Bugs] SMF set a wrong QFI in NGAP/PDUSessionResourceSetupRequest.

### ISSUE THREAD

**Issue by am677** [free5gc/free5gc#100]
## Describe the bug
The value of the QoS Flow identifier in a NAS message toward UE(note 1) and the one of a NGAP IE toward gNB(note 2) are inconsistent.
This led to some gNB(+UE) simulator being not able to send user traffic to a UPF becasue of the incorrect qos parameter.

(note 1) NGAP/PDUSessionResourceSetupRequest
-> PDUSessionResourceSetupListSUReq
-> PDUSessionResourceSetupItemSUReq
-> PDUSessionNAS-PDU/PDU session establishment accept
-> QoS Rules - Authorized QoS Rules
-> QoS flow identifer: 9 <<<<
(note 2) NGAP/PDUSessionResourceSetupRequest
-> PDUSessionResourceSetupRequestTransfer
-> QosFlowSetupRequestList
-> QosFlowSetupRequestItem
-> qosFlowIdentifier: 0 <<<<

## To Reproduce
1. Change config '...'
2. Code patch '...' (You can fork the project and give us the patch diff you have modified)
3. Run command './run.sh'
4. Dump packet '...'

## Expected behavior
(note 1) should be equal to (note 2).

## Environment (please complete the following information):
- free5GC Version: [v3.0.3]
- OS: [Ubuntu 18.04 Server]
- Kernel version [5.0.0-23-generic]
- go version [1.12.9 linux/amd64]

### Configuration File
I changed IP and PLMN settings only.

### PCAP File
[free5gc-pcap.zip](https://github.com/free5gc/free5gc/files/5142304/free5gc-pcap.zip)

### Log File
Provide the program log file here.

If you do not know what to do, copy the log print on the screen and put it here.

## Additional context
See `3GPP TS 24.501 -> Table 9.11.4.12.1: QoS flow descriptions information element` regarding (note 1)
> QoS flow identifier (QFI) (bits 6 to 1 of octet 4)
QFI field contains the QoS flow identifier.
Bits
6 5 4 3 2 1
0 0 0 0 0 0 no QoS flow identifier assigned
0 0 0 0 0 1 QFI 1
to
1 1 1 1 1 1 QFI 63
The network shall not set the QFI value to 0.

and `3GPP TS 38.413-> 9.3.1.51 QoS Flow Identifier` regarding (note 2).
> This IE identifies a QoS flow within a PDU Session. The definition and use of the QoS Flow Identifier is specified in TS 23.501 [9].

I confirmed that when I changed the hard corded value below to `9` which is same value of (note 1) , the UE+gNB simulator could send user traffic to a DN.
https://github.com/free5gc/smf/blob/812249dc3ee527bf6e327b64aa5f1ed2146c9ae3/context/ngap_build.go#L61-L63

#### Related issue
#101

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/error-in-the-procedure-of-pdu-session-resource-setup-response/619/5

**Comment by free5gc-org** [comment]
It was already fixed in free5GC v3.0.5.

**Comment by am677** [comment]
Thank you for fixing this issue.
I confirmed that the simulator could send user traffic to a UPF.
