### ISSUE TITLE
[Feat] UPF verification of user traffic with QFI in the GTP-U extension header

### ISSUE THREAD

**Issue by am677** [free5gc/free5gc#101]
### What's the version are you using
v3.0.3

### Is your feature request related to a problem? Please describe.
UPF can not handle the user traffic properly over GTP-U with the extension header properly.
> WARN[2020-04-17T20:05:19+09:00] c/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util

(UE->)AN->UPF user traffic
![extension_header](https://user-images.githubusercontent.com/66290148/91566776-1c1cf680-e97f-11ea-9ceb-9df9c8c55bfb.png)

### Describe the solution you'd like
UPF should handle user traffic over the GTP-U with QFI in the extension header properly.

See 3GPP TS23.501 5.7.1.7 UL Traffic
> UPF verifies whether QFIs in the UL PDUs are aligned with the QoS Rules provided to the UE or implicitly derived by the UE in the case of Reflective QoS).

### Describe alternatives/workarounds you've considered
None.

### Additional context
3GPP TS23.501
5.7.1.7 UL Traffic
> (R)AN transmits the PDUs over N3 tunnel towards UPF. When passing an UL packet from (R)AN to CN, the (R)AN includes the QFI value, in the encapsulation header of the UL PDU, and selects the N3 tunnel.

8.3.1 User Plane Protocol Stack for a PDU Session
-> GPRS Tunnelling Protocol for the user plane (GTP-U):
> GTP shall encapsulate all end user PDUs. It provides encapsulation on a per PDU Session level. This layer carries also the marking associated with a QoS Flow defined in clause 5.7.

#### Log
[gtp.zip](https://github.com/free5gc/free5gc/files/5142322/gtp.zip)

#### Related issue
#100 
I suppose that the Q/A topic below is related to this issue. 
https://forum.free5gc.org/t/gtp-data-not-forwarded-by-upf/74/4

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by mmadnac1313** [comment]
Dear am677:
From upf/src/up/up_path.c GtpHandler(), the handler of G-PDU was not implemented yet. How did you get log of gtpnoqfi.pcap? Did you get the log with Free5GC?

**Comment by muthuramanecs03g** [comment]
Hi Am677,

We decap and encap the GTP-U header based on the extension header as well as the QER rule in the latest source code of free5GC and gtp5g. 

But, no QoS implementation is done in the gtp5g kernel module, we add the GTP-U header with extension iff QER is present.

Please, verify it with the latest source code and let us know.

Thanks,
Muthuraman

**Comment by free5gc-org** [comment]
@am677 

The issue is already fixed.
Please update [gtp5g](https://github.com/PrinzOwO/gtp5g) to v0.3.1 and [upf](https://github.com/free5gc/upf) to the latest hash: 21e7446926108a5e4a70a0f7aece0cf4b0b0108e

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/free5gc-gtp-payload-doesnt-contain-pdu-session-container-in-ul-and-dl/863/3
