### ISSUE TITLE
UPF Start error

### ISSUE THREAD

**Issue by syluofeng** [free5gc/free5gc#102]
My upf is failing to start. Below is the log. Can you please help here:

lf@oai:~/free5gc/src/upf/build/bin$ sudo -E ./free5gc-upfd -f ~/free5gc/src/upf/build/config/upfcfg.yaml 
INFO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/src/upf_init.c:164 UpfInit() Config: /home/lf/free5gc/src/upf/build/config/upfcfg.yaml  UPF=Util
INFO[2020-08-30T15:09:17+08:00] Set log level: trace                          UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_socket.c:89 SockNodeListAdd() Pool alloc successful, total capacity[512], available[511]  UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/gtpv1/src/gtp_link.c:92 Gtpv1DevListAdd() Pool alloc successful, total capacity[64], available[63]  UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:98 SelectBufblkOption() Pool alloc successful, total capacity[128], available[125]  UPF=Util
TRAC[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:98 SelectBufblkOption() Buffer Alloc Size[256]  UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:96 SelectBufblkOption() Pool Free successful, total capacity[128], available[126]  UPF=Util
TRAC[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:96 SelectBufblkOption() Buffer Free Size[128]  UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:94 SelectBufblkOption() Pool alloc successful, total capacity[128], available[127]  UPF=Util
TRAC[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:94 SelectBufblkOption() Buffer Alloc Size[64]  UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:94 SelectBufblkOption() Pool alloc successful, total capacity[128], available[126]  UPF=Util
TRAC[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_buff.c:94 SelectBufblkOption() Buffer Alloc Size[64]  UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_thread.c:67 ThreadCreate() Pool alloc successful, total capacity[128], available[127]  UPF=Util
DEBU[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/utlt/src/utlt_socket.c:40 SocketAlloc() Pool alloc successful, total capacity[1024], available[1023]  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/gtpv1/src/gtp_link.c:27 GtpLinkCreate() GTP device named upfgtp0 Create fail  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:49 GtpTunCreate() GtpLinkCreate fail  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:144 GtpDevListCreate() GTPv1 tunnel create fail : IP[127.0.0.1], ifname[upfgtp0]  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/src/up/up_path.c:74 GTPv1ServerInit() GtpLinkListCreate Fail  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/src/upf_init.c:170 UpfInit() UPF - GTP-U Server error when UPF initializes  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/src/upf.c:28 main() UPF failed to initialize  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/src/up/up_path.c:233 BufferServerTerminate() epoll deregister error  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/src/upf_init.c:183 UpfTerm() UPF - Buffer Server error when UPF terminates  UPF=Util
ERRO[2020-08-30T15:09:17+08:00] /home/lf/free5gc/src/upf/src/upf.c:36 main() UPF terminate error  UPF=Util

uname -a 
Linux oai 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by free5gc-org** [comment]
The issue does not follow the issue template.

Also, this is not a bug report, feature request or doc request. Please ask the question on free5GC's [forum](https://forum.free5gc.org)
