### ISSUE TITLE
[Bugs] AMF Encrypts SecurityModeCommand message.

### ISSUE THREAD

**Issue by aligungr** [free5gc/free5gc#104]
Hello everyone. Recently [an issue](https://github.com/aligungr/UERANSIM/issues/100) has been created in our [UERANSIM](https://github.com/aligungr/UERANSIM) repository. I wanted to report this bug here, because I think it is caused by free5gc.

AMF encrypts Security Mode Command message when ciphering algorithm NEA2 selected in `amfcfg.conf`. However Security Mode Command shall not be encrypted. It shall be only integrity protected, even if some ciphering algorithm is going to be selected.

## To Reproduce
1. Change config `cipheringOrder` to `NEA2` in `amfcfg.conf`.
2. Run free5gc.
3. Run UERANSIM and trigger `initial-registration`.

## Expected behavior
AMF should send `SecurityModeCommand` as integrity protected and **not** ciphered. AMF should start using encryption **after receiving** `SecurityModeComplete` message from UE. Therefore, `SecurityModeCommand` itself should not be encrypted.

See TS 24.501 for more details.

## Environment:
 - free5GC Version: 3.0.3
 - OS: Ubuntu 20.04
 - Kernel version: 5.4

### Configuration File
[config.zip](https://github.com/free5gc/free5gc/files/5190011/config.zip)

### PCAP File
See [here](https://github.com/aligungr/UERANSIM/issues/100) for pcap file.

### Log File
See [here](https://github.com/aligungr/UERANSIM/issues/100) for log file.

**Comment by calee0219** [comment]
Reference to TS 24.501 4.4.2.6

> When the AMF initiates a re-authentication to create a new 5G NAS security context, the messages exchanged during the authentication procedure are integrity protected and ciphered using the current 5G NAS security context, if any.
>
> Both UE and AMF shall continue to use the current 5G NAS security context, until the AMF initiates a security mode control procedure. The SECURITY MODE COMMAND message sent by the AMF includes the ngKSI of the new 5G NAS security context to be used. The AMF shall send the SECURITY MODE COMMAND message integrity protected with the new 5G NAS security context, but unciphered. When the UE responds with a SECURITY MODE COMPLETE message, it shall send the message integrity protected and ciphered with the new 5G NAS security context.
> 
> The AMF can also modify the current 5G NAS security context or take the non-current native 5G NAS security context, if any, into use, by sending a SECURITY MODE COMMAND message including the ngKSI of the 5G NAS security context to be modified and including a new set of selected NAS security algorithms. In this case the AMF shall send the SECURITY MODE COMMAND message integrity protected with the modified 5G NAS security context, but unciphered. When the UE replies with a SECURITY MODE COMPLETE message, it shall send the message integrity protected and ciphered with the modified 5G NAS security context.

**Comment by free5gc-org** [comment]
Hi, we has fixed this bug in v3.0.4
Can you upgrade free5gc to v3.0.4 and test if this problem is still happened ?
