### ISSUE TITLE
Segmentation on start SCTP server on NGAP while running TestRegistration script

### ISSUE THREAD

**Issue by Prema-NA** [free5gc/free5gc#106]
ubuntu@5gc-vm:~/free5gc$  ./test.sh TestRegistration
INFO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/src/upf_init.c:164 UpfInit() Config: /home/ubuntu/free5gc/src/upf/build/config/upfcfg.test.yaml  UPF=Util
INFO[2020-09-10T17:00:26+05:30] Set log level: info                           UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/lib/gtpv1/src/gtp_link.c:27 GtpLinkCreate() GTP device named upfgtp0 Create fail  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:49 GtpTunCreate() GtpLinkCreate fail  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:144 GtpDevListCreate() GTPv1 tunnel create fail : IP[10.200.200.102], ifname[upfgtp0]  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/src/up/up_path.c:74 GTPv1ServerInit() GtpLinkListCreate Fail  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/src/upf_init.c:170 UpfInit() UPF - GTP-U Server error when UPF initializes  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/src/upf.c:28 main() UPF failed to initialize  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/src/up/up_path.c:236 BufferServerTerminate() epoll deregister error  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/src/upf_init.c:183 UpfTerm() UPF - Buffer Server error when UPF terminates  UPF=Util
ERRO[2020-09-10T17:00:26+05:30] /home/ubuntu/free5gc/src/upf/src/upf.c:36 main() UPF terminate error  UPF=Util
unable to write file on filehook open ../../log/nf/n3iwf.log: permission deniedunable to write file on filehook open ../../log/nf/amf.log: permission deniedunable to write file on filehook open ../../log/nf/ausf.log: permission deniedunable to write file on filehook open ../../log/nf/nrf.log: permission deniedunable to write file on filehook open ../../log/nf/nssf.log: permission deniedunable to write file on filehook open ../../log/nf/pcf.log: permission deniedunable to write file on filehook open ../../log/nf/smf.log: permission deniedunable to write file on filehook open ../../log/nf/udm.log: permission deniedunable to write file on filehook open ../../log/nf/udr.log: permission deniedCommonConfig file: ../../config/free5GC.conf
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/nas/logger/logger.go:60 free5gc/lib/nas/logger.SetLogLevel() set log level : info                          NAS=message
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/nas/logger/logger.go:65 free5gc/lib/nas/logger.SetReportCaller() set report call : true                        NAS=message
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/fsm/logger/logger.go:56 free5gc/lib/fsm/logger.SetLogLevel() set log level : info                          fsm=fsm
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/fsm/logger/logger.go:61 free5gc/lib/fsm/logger.SetReportCaller() set report call : true                        fsm=fsm
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/ngap/logger/logger.go:56 free5gc/lib/ngap/logger.SetLogLevel() set log level : info                          NGAP=NGAP
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/ngap/logger/logger.go:61 free5gc/lib/ngap/logger.SetReportCaller() set report call : true                        NGAP=NGAP
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Namf_Communication/logger/logger.go:57 free5gc/lib/openapi/Namf_Communication/logger.SetLogLevel() set log level : info                          Namf=Comm
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Namf_Communication/logger/logger.go:62 free5gc/lib/openapi/Namf_Communication/logger.SetReportCaller() set report call : true                        Namf=Comm
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Namf_EventExposure/logger/logger.go:57 free5gc/lib/openapi/Namf_EventExposure/logger.SetLogLevel() set log level : info                          Namf=Event
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Namf_EventExposure/logger/logger.go:62 free5gc/lib/openapi/Namf_EventExposure/logger.SetReportCaller() set report call : true                        Namf=Event
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Nsmf_PDUSession/logger/logger.go:57 free5gc/lib/openapi/Nsmf_PDUSession/logger.SetLogLevel() set log level : info                          Nsmf=PDUSession
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Nsmf_PDUSession/logger/logger.go:62 free5gc/lib/openapi/Nsmf_PDUSession/logger.SetReportCaller() set report call : true                        Nsmf=PDUSession
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Nudr_DataRepository/logger/logger.go:57 free5gc/lib/openapi/Nudr_DataRepository/logger.SetLogLevel() set log level : info                          Nudr=datarepository
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/Nudr_DataRepository/logger/logger.go:62 free5gc/lib/openapi/Nudr_DataRepository/logger.SetReportCaller() set report call : true                        Nudr=datarepository
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/logger/logger.go:57 free5gc/lib/openapi/logger.SetLogLevel() set log level : info                          OpenApi=OpenApi
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/openapi/logger/logger.go:62 free5gc/lib/openapi/logger.SetReportCaller() set report call : true                        OpenApi=OpenApi
INFO[2020-09-10T17:00:35+05:30] set log level : info                          aper=aper
INFO[2020-09-10T17:00:35+05:30] set report call : true                        aper=aper
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/CommonConsumerTestData/logger/logger.go:60 free5gc/lib/CommonConsumerTestData/logger.SetLogLevel() set log level : info                          CommonTest=comm
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/lib/CommonConsumerTestData/logger/logger.go:65 free5gc/lib/CommonConsumerTestData/logger.SetReportCaller() set report call : true                        CommonTest=comm
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/src/nrf/factory/factory.go:35 free5gc/src/nrf/factory.InitConfigFactory() Successfully initialize configuration ../../config/nrfcfg.conf  NRF=init
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/src/nrf/service/init.go:79 free5gc/src/nrf/service.(*NRF).Initialize() Log level is set to [info] level              NRF=init
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/src/nrf/service/init.go:104 free5gc/src/nrf/service.(*NRF).Start() Server started                                NRF=init
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/src/nrf/context/nrf_context.go:20 free5gc/src/nrf/context.InitNrfContext() nrfconfig Info: Version[1.0.0] Description[NRF initial local configuration]  NRF=init
INFO[2020-09-10T17:00:35+05:30]/home/ubuntu/free5gc/src/nrf/service/init.go:117 free5gc/src/nrf/service.(*NRF).Start() 127.0.0.1:29510                               NRF=init
INFO[2020-09-10T17:00:36+05:30]/home/ubuntu/free5gc/src/amf/factory/factory.go:35 free5gc/src/amf/factory.InitConfigFactory() Successfully initialize configuration ../../config/amfcfg.conf  AMF=init
INFO[2020-09-10T17:00:36+05:30]/home/ubuntu/free5gc/src/amf/service/amf_init.go:90 free5gc/src/amf/service.(*AMF).Initialize() Log level is set to [info] level              AMF=init
INFO[2020-09-10T17:00:36+05:30]/home/ubuntu/free5gc/src/amf/service/amf_init.go:115 free5gc/src/amf/service.(*AMF).Start() Server started                                AMF=init
INFO[2020-09-10T17:00:36+05:30]/home/ubuntu/free5gc/src/amf/util/init_context.go:15 free5gc/src/amf/util.InitAmfContext() amfconfig Info: Version[1.0.0] Description[AMF initial local configuration]  AMF=Util
INFO[2020-09-10T17:00:36+05:30]/home/ubuntu/free5gc/src/amf/util/init_context.go:43 free5gc/src/amf/util.InitAmfContext() Error parsing ServerIPv4 address as string. Using the 0.0.0.0 address as default.  AMF=Util
ERRO[2020-09-10T17:00:36+05:30]/home/ubuntu/free5gc/lib/ngap/ngapSctp/sctp.go:78 free5gc/lib/ngap/ngapSctp.Server() failed to listen: address already in use      NGAP=NGAP
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb47fe4]

goroutine 38 [running]:
git.cs.nctu.edu.tw/calee/sctp.(*SCTPListener).Addr(...)
        /home/ubuntu/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.0.0/sctp.go:636
free5gc/lib/ngap/ngapSctp.Server(0xc000096630, 0x9, 0xc000097000)
        /home/ubuntu/free5gc/lib/ngap/ngapSctp/sctp.go:80 +0x344
free5gc/src/amf/ngap/sctp.Server(0xc000096630, 0x9, 0xc0000a9d68)
        /home/ubuntu/free5gc/src/amf/ngap/sctp/sctp.go:27 +0x39
free5gc/src/amf/service.(*AMF).Start(0x260fc60)
        /home/ubuntu/free5gc/src/amf/service/amf_init.go:148 +0x4cf
created by free5gc/src/test_test.init.0
        /home/ubuntu/free5gc/src/test/ngsetup_test.go:67 +0x22a
exit status 2
FAIL    free5gc/src/test        0.258s
free5gc-upfd: no process found

**Comment by Prema-NA** [comment]
ngapSctp.Server() failed to listen: address already in use      NGAP=NGAP
Seg fault

**Comment by free5gc-org** [comment]
This issue does not follow the issue template.
