### ISSUE TITLE
[Bugs] Handle security mode complete NULL and cannot process InitialUEmessage which includes two registration request.

### ISSUE THREAD

**Issue by ChiehChun** [free5gc/free5gc#108]
Dear community,
I found some problems when testing with gNB and 5gUE.
For the normal case, UE send the initialUEmessage which only includes one registration request and can pass all the messages as defined by spec.
![](https://i.imgur.com/5Ch1bXV.png)
For the abnormal case, the UE send the initialUEmessage which is including two registration request, and UE will be release after security mode complete.
![](https://i.imgur.com/0WkPSL8.png)

## Environment (please complete the following information):
 - free5GC Version: v3.0.3
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: 1.14.4

### PCAP File
See [here](https://drive.google.com/open?id=1k7NA6cZf00KGgURsUJY5R86sXfvzAJWC)e for pcapng file.

### Log File
<img width="1141" alt="截圖 2020-09-15 下午11 02 49" src="https://user-images.githubusercontent.com/40885182/93228304-ea41c780-f7a7-11ea-8f14-8c6fc97a9c8a.png">
<img width="1148" alt="截圖 2020-09-15 下午11 04 29" src="https://user-images.githubusercontent.com/40885182/93228316-eca42180-f7a7-11ea-89f0-b1bdcf37b745.png">

**Comment by free5gc-org** [comment]
Hi,
we have refactored GMM architecture at AMF
and fix this bug in v3.0.4
can you upgrade free5gc to v3.0.4 and test if this problem is still exist?
