### ISSUE TITLE
[Feat]

### ISSUE THREAD

**Issue by jiajun80** [free5gc/free5gc#110]
when I test pdu sesssion request report error:
ERRO[2020-09-18T05:40:10Z]/src/smf/context/user_plane_information.go:245 free5gc/src/smf/context.(*UserPlaneInformation).GenerateDefaultPath() Can't find UPF with DNN [internet]            SMF=Context
ERRO[2020-09-18T05:40:10Z]/src/smf/context/user_plane_information.go:178 free5gc/src/smf/context.GenerateDataPath() invalid path   SMF=Context

**Comment by free5gc-org** [comment]
Duplicate with https://forum.free5gc.org/t/cant-find-upf-with-dnn-internet/326/25 and don't follow the issue template.
