### ISSUE TITLE
[Docs] Add docs with implemented and not implemented function

### ISSUE THREAD

**Issue by zhonglin6666** [free5gc/free5gc#112]
## Documentation request

Increase realization function，progressing function and pending function，which can let us understand free5gc project

## Suggestion

Can free5gc add in the document which functions are implemented and which functions are not implemented?
As follows:
#### Complete
```
N3, N4, N6, N9 interfacing
PDR, FAR
...
```

#### Progressing
```
PCC
```

#### Pending
```
QER
```

**Comment by free5gc-org** [comment]
This is kind of difficult because there is no well define what is a function.

And using the sample as you provided, even is saying PDR, we have implement some of the IE, but others are not.
