### ISSUE TITLE
[Feat] NITZ: Inform UE of current time and operator name using configuration update command.

### ISSUE THREAD

**Issue by am677** [free5gc/free5gc#113]
### What's the version are you using
v3.0.3

### Is your feature request related to a problem? Please describe.
UE can not receive the time that should be synchronized from a network and it may cause large time lag between UE and current time.

### Describe the solution you'd like
I expect
1) AMF to send a `Configuration update command` **shortly after** the `Registration complete` and periodic registration update.

and

2) this `Configuration update command` includes long and short operator names, universal time, local time zone and daylight saving time.

and then, UE can synchronize with this time and time zone and get operator names of a core network.

### Describe alternatives/workarounds you've considered
None.

### Additional context
See 3GPP TS24.501 5.4.4 Generic UE configuration update procedure -> 5.4.4.1 General
```
This procedure is initiated by the network and can only be used when the UE has an established 5GMM context, and the UE is in 5GMM-CONNECTED mode. 
```
```
The following parameters are supported by the generic UE configuration update procedure without the need to request the UE to perform the registration procedure for mobility and periodic registration update:
d)	Network identity and time zone information (Full name for network, short name for network, local time zone, universal time and local time zone, network daylight saving time);
```
See also 3GPP TS22.042 Network Identity and TimeZone (NITZ); Service description; Stage 1.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by brianchennn** [comment]
@am677 
We are implementing `Configuration Update Command` now, so I reopened this issue.
