### ISSUE TITLE
[Bugs] AMF rejecting the registration if 5GMM Capability info missing

### ISSUE THREAD

**Issue by bertuola** [free5gc/free5gc#114]
## Describe the bug
Procedure rejected if 5GMM Capability info missing in _Registration Request_ message.

## Expected behavior
According to 3GPP TS 24.501, the 5GMM Capability info in _Registration Request_ message is optional.

## Environment
 - free5GC Version: v3.0.4
 - OS: Ubuntu 200.04.1 Server
 - Kernel version: 5.4.0-48-generic
 - go version: go1.14.4 linux/amd64

### PCAP File
[free5gc_Missing_Capability5GMM.pcap.zip](https://github.com/free5gc/free5gc/files/5300963/free5gc_Missing_Capability5GMM.pcap.zip)

### Log File
[AMF.log](https://github.com/free5gc/free5gc/files/5300975/AMF.log)

**Comment by free5gc-org** [comment]
Hi @bertuola ,

How to reproduce this issue?

**Comment by bertuola** [comment]
Hi. I understand you can reproduce the scenario generating a request with missing Capability5GMM in the request. At my side, I am using a commercial simulator provided by Ixia.

**Comment by bertuola** [comment]
Hi. 
Thanks for the return. 
I agree the **5GMM Capability** information shall be included in the registration. Now, checking the traces, I don't see this info in clear, so I understand it is contained in **UplinkNASTransport** message, which has the content encrypted. I tried to enabled debugging at core side to check if it is was possible to have visibility about the content of this message to verify if this information was actually missing or there is an issue in decoding it.
Is there any way at Free5GC side to see the encrypted content of the NGAP messages?

**Comment by free5gc-org** [comment]
Hi,
If you use 5G-EA0 as the NAS ciphering algorithm,
then you can configure wireshark to decode EA0 NAS messages

Open wireshark then go through Edit->Preferences -> Protocols -> enable the option "Try to detect and decode 5G-EA0 ciphered messages"
![image](https://user-images.githubusercontent.com/60502770/96962657-d8d3a400-1539-11eb-94c9-951abd0eb6fd.png)

**Comment by LordDraga** [comment]
Hello there in TS 124.501 section 4.4.6 says

 "The 5GS supports protection of initial NAS messages as specified in 3GPP TS 33.501 [24]. The protection of initial NAS messages applies to the REGISTRATION REQUEST and SERVICE REQUEST message, and is achieved as follows: a)   If the UE does not have a valid 5G NAS security context, the UE sends a REGISTRATION REQUEST message including cleartext IEs only. After activating a 5G NAS security context resulting from a security mode control procedure: 1)  if the UE needs to send non-cleartext IEs, the UE shall include the entire REGISTRATION REQUEST message (i.e. containing both cleartext IEs and non-cleartext IEs) in the NAS message container IE and shall include the NAS message container IE in the SECURITY MODE COMPLETE message"

And in the same section we have seen that the cleartext IEs of REGISTRATION REQUEST message are:

"When the initial NAS message is a REGISTRATION REQUEST message, the cleartext IEs are: 
-    Extended protocol discriminator; 
-    Security header type;
 -    Spare half octet; 
-    Registration request message identity;
 -    5GS registration type;
 -    ngKSI;    -    5GS    mobile    identity;
    -    UE security capability;
 -    Additional    GUTI; 
   -    UE status; and - 
   EPS NAS message container. "

It can also be observed in TS 33.501 in section 6.4.6 where there is a message flow figure

![image](https://user-images.githubusercontent.com/63735674/98836871-83a4f700-2442-11eb-97fe-8d972675f735.png)

As it is observable in the first Initial Message in step 1. The message should carry also the non-cleartext IEs so if the MAC fails the AMF should put the bit RINMR to 1 so the UE will retransmit the initial NAS message in the Security mode complete. 

Step 3: After a successful authentication of the UE, the AMF shall send the NAS Security Mode Command message. If the initial NAS message was protected but did not pass the integrity check  (due either to a MAC failure or the AMF not being able to find the used security context) orthe AMF could not decrypt the complete initial NAS message in the NAS container, then the AMF shall include in the Security Mode Command message a flag requesting the UE to send the complete initial NAS message in the NAS Security Mode Complete message. "


The use case of the bit RINMR is in TS 24.501 4.4.4.3 or in 5.4.2.2:

"If, during an ongoing registration procedure, the AMF is initiating a SECURITY MODE COMMAND (i.e. after receiving the REGISTRATION REQUEST message, but before sending a response to that message) and the REGISTRATION REQUEST message does not successfully pass the integrity check at the AMF, the AMF shall include the Additional 5G security information IE with the RINMR bit set to "Retransmission of the initial NAS message requested" in the SECURITY MODE COMMAND message requesting the UE to send the entire REGISTRATION REQUEST message in the SECURITY MODE COMPLETE message as described in 3GPP TS 33.501 [24]."

"If, during an ongoing registration procedure or service request procedure, the SECURITY MODE COMMAND message includes the Additional 5G security information IE with the RINMR bit set to "Retransmission of the initial NAS message requested", the UE shall include the entire unciphered REGISTRATION REQUEST message or SERVICE REQUEST message, which the UE had previously included in the NAS message container IE of the initial NAS message (i.e. REGISTRATION REQUEST message or SERVICE REQUEST message, respectively), in the NAS message container IE of the SECURITY MODE COMPLETE message."

**Comment by bertuola** [comment]
I verified the info you provided and I confirm the Ixia simulator is not sending the 5GMM Capability information element. I opened a ticket to them. Really thanks for your support. This issue can be closed.
