### ISSUE TITLE
[Bugs] AMF getting in loop during Registration

### ISSUE THREAD

**Issue by bertuola** [free5gc/free5gc#115]
## Describe the bug
Trying the free5gc core against an external emulator. During the registration, AMF gets stuck due to an internal infinite loop.

## Environment (please complete the following information):
 - free5GC Version: v3.0.4
 - OS: Ubuntu 200.04.1 Server
 - Kernel version: 5.4.0-48-generic
 - go version: go1.14.4 linux/amd64

### Configuration File
[amfcfg.conf.txt](https://github.com/free5gc/free5gc/files/5301244/amfcfg.conf.txt)

### PCAP File
[Registration_Error_Loop.pcap.zip](https://github.com/free5gc/free5gc/files/5301248/Registration_Error_Loop.pcap.zip)

### Log File
[AMF.log](https://github.com/free5gc/free5gc/files/5301249/AMF.log)

**Comment by free5gc-org** [comment]
Hi @bertuola ,

How to reproduce this issue?

**Comment by bertuola** [comment]
Hi. I am using a commercial simulator provided by Ixia. I believe the issue is in the info provided encrypted in _UplinkNASTransport_ message. I tried to use debug for AMF and NAS, but I was not able to get the content of this part of the message decoded at AMF side.

**Comment by free5gc-org** [comment]
Hi,
we have confirmed this problem and are working on it
we will fix this bug at the next release
