### ISSUE TITLE
[Bugs] UPF address of Send PFCP Association Request in SMF log is corrupted.

### ISSUE THREAD

**Issue by sh-sekigawa** [free5gc/free5gc#117]
## Describe the bug
When using IP address as Node ID, the UPF address of Send PFCP Association Request in SMF log is displayed as corrupted character.

## To Reproduce
1. Run ./test.sh TestRegistration.
2. You will find SMF shows the log as below.
```
[INFO][SMF][App] Send PFCP Association Request to UPF[??e]
```

## Expected behavior
The log should be as below.
```
[INFO][SMF][App] Send PFCP Association Request to UPF[10.200.200.101]
```

## Environment (please complete the following information):
 - free5GC Version: v3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: 1.14.7
 - c compiler version (Option): 7.5.0

### Configuration File
Not modified.

### Log File

[test.log](https://github.com/free5gc/free5gc/files/5324963/test.log)

**Comment by free5gc-org** [comment]
Hi @sh-sekigawa ,

I think the PR fix this issue, so we can close this issue right?

**Comment by sh-sekigawa** [comment]
That's fine, Thanks :)
