### ISSUE TITLE
Nnrf_NFDiscovery Service

### ISSUE THREAD

**Issue by JoanaConde** [free5gc/free5gc#12]
Greetings,

I'm currently testing NFDiscovery Service, and when it is done a discovery for a target-nfType that is not existed in the NRF yet the response return a SearchResult with {"validityPeriod":100,"nfInstances":null"}.

My question is: 
the nfInstances returned shouldn't it be an empty array instead of a null?

Thank you for your time.

**Comment by free5gc-org** [comment]
Hi,

True, it should be an empty array returned.

Thanks for your bug report

**Comment by free5gc-org** [comment]
hi @JoanaConde ,

We have patch this bug, please try the new version of v3.0.1.

Thanks a lot.
