### ISSUE TITLE
[Feat] Function to modify UE's SNSSAIs and DNN in mongodb documents

### ISSUE THREAD

**Issue by shigeki-yamano** [free5gc/free5gc#120]
### What's the version are you using

v3.0.4

### Is your feature request related to a problem? Please describe.

free5gc's webconsole does not provide the function to modify UE's SNSSAIs and DNN.

### Describe the solution you'd like

webconsole or CLI tool provides the function to modify UE's SNSSAIs and DNN.

### Describe alternatives/workarounds you've considered

None

### Additional context

The current mongodb document format has two problems.

- **Problem 1** : defaultSingleNssais and singleNssais include the same SNSSAI.

In `subscriptionData.provisionedData.amData`, defaultSingleNssais and singleNssais include the same SNSSAI.

`TS 29.503 version 15.7.0 / 6.1.6.2.2 Type: Nssai` says

```
defaultSingleNssais : A list of Single Nssais used as default 
singleNssais : List of non default Single Nssais. 
```

So, defaultSingleNssais and singleNssais are exclusive.
If defaultSingleNssais includes a SNSSAI (SST=1 & SD=010203), singleNssais should not include the SNSSAI (SST=1 & SD=010203).

- **Problem 2** : SNSSAI string format does not conform to 3GPP specification

`subscriptionData.provisionedData.smfSelectionSubscriptionData`'s subscribedSnssaiInfos and
`policyData.ues.smData`'s smPolicySnssaiData have the string formatted snssai key such as "01010203".

`TS 29.571 version 15.6.0 / 5.4.4.2 Type: Snssai` says

```
When Snssai needs to be converted to string (e.g. when used in maps as key), the string shall be composed of one to
three digits "sst" optionally followed by "-" and 6 hexadecimal digits "sd", and shall match the following pattern:
^([0-9]|[1-9][0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))(-[A-Fa-f0-9]{6})?$
Example 1: "255-19CDE0"
Example 2: "29"
```

So, "01010203" should be formatted as "1-010203".

### If willing to resolve an issue by submitting Pull request, please consider the points below.

I've created a sample implementation of CLI tool which register the mongodb document for UE.

[uetool.zip](https://github.com/free5gc/free5gc/files/5389878/uetool.zip)

Installation, Configuration and Usage is described in README.md

This tool solves Problem 1.
the first snssai is set to defaultSingleNnsai, and the others are set to singleNssai.

But it doesn't solve Problem 2 because of compatibility.
To comforming to 3GPP specification, fix `subscribeUE.go` as follows.

```
-                keystring := fmt.Sprintf("%02d%s",cfg.Snssais[i].Sst,cfg.Snssais[i].Sd)
+                keystring := fmt.Sprintf("%d-%s",cfg.Snssais[i].Sst,cfg.Snssais[i].Sd)
```

**Comment by shigeki-yamano** [comment]
Because free5gc sets defaultSingleNnsai to Allowed NSSAI,
I've modified uetool as follows.

The 1st to 8th SNSSAI is set to defaultSingleNnsai,
the 9th or later SNSSAI is set to singleNssai.

[uetool2.zip](https://github.com/free5gc/free5gc/files/5405555/uetool2.zip)

**Comment by noormohammedli** [comment]
Hello Sir, 
Thanks for sharing this code. 
what do you mean in this section below ?

"
The 1st to 8th SNSSAI is set to defaultSingleNnsai,
the 9th or later SNSSAI is set to singleNssai.
"
Is these the number of the slices that the UE can connect to the 5G core network ?? 

>>>>>>>>>>>>>>>>>>>>>>>>>>>

So, in this case (CLI tool), I will run this code to add UE information to the network with NSSF (SST, SD) to 5G core without using the webconsole and also with out run the UE and RAN on other VM right?? 

Now, I will do >>>
>>> cd free5gc 
>>>  ./run.sh 
to run the 5G core then i will go to the >>> cd uetool  the run the ./build.sh ..... 
after that will go the uetool floder to add the UE.. 
>>>> cd ~/free5gc/src/uetool
>>> ./subscribeUE     to add UE to 5Gcore

Thanks, 
Noor

**Comment by noormohammedli** [comment]
Hello Sir, 
I get this problem when i run the code 

<img width="830" alt="Screenshot 2021-07-25 at 8 12 36 pm" src="https://user-images.githubusercontent.com/34620715/126910734-25309672-c331-4c18-9224-bedc94c1165f.png">

Thanks

**Comment by shigeki-yamano** [comment]
Hi @noormohammedli,

>what do you mean in this section below ?
>
>>The 1st to 8th SNSSAI is set to defaultSingleNnsai,
>>the 9th or later SNSSAI is set to singleNssai.
> Is these the number of the slices that the UE can connect to the 5G core network ??
UE can have eight slices at most. the other slices is optional setting.

> So, in this case (CLI tool), I will run this code to add UE information to the network with NSSF (SST, SD) to 5G core without 
> using the webconsole and also with out run the UE and RAN on other VM right??

This tool is for registering and deregistering UE information to mongodb without webconsole.
You need to set up nssf configuration manually. 

And these tool is for v3.0.4.
If you use v3.0.5, use the following uetool305.zip.

[uetool305.zip](https://github.com/free5gc/free5gc/files/7125941/uetool305.zip)
