### ISSUE TITLE
[Bugs] NAS 5GS mobile identity 5G-GUTI octet 4 (first four 1bits) must be handled

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#124]
## Describe the bug
In TS 24.501 9.11.3.4. "5G-GUTI" has four 1bit in octet 4 (bit 8-5).
It is not properly encoded/decoded.
``` text
  8   7   6   5   4   3   2   1 
+------------------------------+
| 1 | 1 | 1 | 1 | 0 |Type of id| octet 4
+------------------------------+
5GS mobile identity information element for type of identity "5G-GUTI"
````
## To Reproduce
Just simply dump 5G-GUIT IEI.

## Expected behavior
First 4 bit of octet 4 must be filled in 1.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/nas/pull/5) for the fix.

**Comment by free5gc-org** [comment]
The PR has been merged.

Thanks a lot for the contribution!
