### ISSUE TITLE
[Feat] There should be multiple UserPlaneIPResourceInformation fields in the structure of PFCPAssociationSetupRequest

### ISSUE THREAD

**Issue by zhonglin6666** [free5gc/free5gc#125]
###  Issue Description
May be UPF has multiple nic，represent n3 n6 and cp interface in TS 29.244， UPF response Association with multiple UserPlaneIPResourceInformation，so there should be multiple UserPlaneIPResourceInformation fields in the structure of PFCPAssociationSetupRequest

### What's the version are you using
  free5gc 3.0.4

### Is your feature request related to a problem? Please describe.
   func (dataPath *DataPath) ActivateTunnelAndPDR(smContext *SMContext)，which should select access，core，N6 interface fill in PDR and FAR  

### Describe the solution you'd like
  The structure of PFCPAssociationSetupRequest in message.go file，like this

type PFCPAssociationSetupRequest struct {
	NodeID                         *pfcpType.NodeID                         `tlv:"60"`
	RecoveryTimeStamp              *pfcpType.RecoveryTimeStamp              `tlv:"96"`
	UPFunctionFeatures             *pfcpType.UPFunctionFeatures             `tlv:"43"`
	CPFunctionFeatures             *pfcpType.CPFunctionFeatures             `tlv:"89"`
	UserPlaneIPResourceInformations []*pfcpType.UserPlaneIPResourceInformation `tlv:"116"`
}

  Need to modify other using UserPlaneIPResourceInformation

**Comment by free5gc-org** [comment]
This **UserPlaneIPResourceInformation** IE does not contain the **type of interface** (N3, N6, N9)  and it will be removed in R16, so we decided to use pre-configuration on the SMF.

**Comment by zhonglin6666** [comment]
got it !

R15 Association Response in TS 29.244 8.2.2, response from UPF like this:
```
User Plane IP Resource Interface: CP-function
    Network Instance: N4
       Source Interface: CP-functino

User Plane IP Resource Interface: Access
   Network Instance: N3
       Source Interface: Access

User Plane IP Resource Interface: SGI-LAN/N6-LAN
   Network Instance: N6
       Source Interface: SGI-LAN/N6-LAN
```
Network Instance can rename

R16 remove UserPlaneIPResourceInformation IE
