### ISSUE TITLE
[Bugs] AMF Crashes on accessing null nsiInformation

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#127]
## Describe the bug
AMF Crashes when it access to null `nsiInformation`

## To Reproduce
1. Change config '...'
2. Code patch '...' (You can fork the project and give us the patch diff you have modified)
3. Run command '...'
4. Dump packet '...'

## Expected behavior
No crash.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: 1.14.4 linux/amd64

## Pull Request

[Pull Request](https://github.com/free5gc/amf/pull/9) for the fix

**Comment by free5gc-org** [comment]
The PR has been merged.
Thanks a lot for the contribution!
