### ISSUE TITLE
Is there any 5G AKA test data can be provided?

### ISSUE THREAD

**Issue by kimi20071025** [free5gc/free5gc#129]
I'd like to verify my 5g aka code is correct or not. So I want to ask if anybody can help me to provide any test data of 5g-aka.
Thanks.

**Comment by free5gc-org** [comment]
free5GC mainly uses GitHub for issue tracking. Information regarding to general questions or technical support. It will be highly considered if forward to the [forum](https://forum.free5gc.org).

The issue will be closed due to it does not follow the issue template.
