### ISSUE TITLE
[Feat] Function to update configuration while NF is running

### ISSUE THREAD

**Issue by shigeki-yamano** [free5gc/free5gc#131]
### What's the version are you using

v3.0.4

### Is your feature request related to a problem? Please describe.

Free5gc's NF does not support the function to update configuration after the NF started.
So we cannot add new SNSSAI to AMF and NSSF while AMF and NSSF are running.

### Describe the solution you'd like

AMF and NSSF support the function to reload configuration and to notice the configuration update.

### Describe alternatives/workarounds you've considered

None

### Additional context

None

### If willing to resolve an issue by submitting Pull request, please consider the points below.

I've created a sample implementation for updating configuration.

[updateconfig.zip](https://github.com/free5gc/free5gc/files/5455543/updateconfig.zip)

**How to patch and build**

```
unzip updateconfig.zip
cd updateconfig
mv updateconfig.patch ~/
cd ~/
patch -p1 -d free5gc < updateconfig.patch
cd free5gc
go build -o bin/nssf -x src/nssf/nssf.go
go build -o bin/amf -x src/amf/amf.go
```

**How to use**

AMF Configuration Update

```
curl http://(AMF SBI IP Address):(AMF SBI Port)/namf-oam/v1/update-config
```

- After the above command is executed, this command returns `{"Slices":(supported slice number)}`.
- Then AMF executes the following procedures.
   - Reload `amfcfg.conf` in default config path.
   - Register "NfProfile" to NRF
   - Send "AMF Configuration Update" to gNB
   - Send "Configuration Update Command" to UE

NSSF Configuration Update

```
curl http://(NSSF SBI IP Address):(NSSF SBI Port)/nnssf-oam/v1/update-config
```

- After the above command is executed, this command returns `{"Slices":(supported slice number)}`.
- Then NSSF executes the following procedures.
   - Reload `nssfcfg.conf` in default config path.
   - Register "NfProfile" to NRF

**Comment by weekendzhang** [comment]
hi, i do this like your steps and can see the register "NFProfile" to NRF.
One question is i found the AMF configuration changes, AMF still use the PUT method to update the NFProfile not the PATCH method, if i want to get a PATCH example, how can do it? thanks

**Comment by shigeki-yamano** [comment]
> hi, i do this like your steps and can see the register "NFProfile" to NRF.
> One question is i found the AMF configuration changes, AMF still use the PUT method to update the NFProfile not the PATCH method, if i want to get a PATCH example, how can do it? thanks

AMF does not support PATCH-type NFUpdate, but NRF has PATCH-type NFUpdate.
The following functions in NRF may help you to implement PATCH-type NFUpdate in AMF.

- HTTPUpdateNFInstance (src/nrf/management/api_nf_instance_id_document.go)
- HandleUpdateNFInstanceRequest (src/nrf/producer/nf_management.go)
- UpdateNFInstanceProcedure (src/nrf/producer/nf_management.go)

**Comment by weekendzhang** [comment]
Thanks and i will try
