### ISSUE TITLE
[Bugs] AMF creates wrong InitialContextSetupRequest message

### ISSUE THREAD

**Issue by ralfkundel** [free5gc/free5gc#132]
I observed that the AMF creates wrong InitialContextSetupRequest messages, in detail the id-UESecurityCapabilites are not correct.

## Expected behavior
The first 3 bits of the Capabilities bitstream should be used for encoding (one-hot) if NEA1, NEA2, NEA3 is supported. Same for NIA1, NIA2, NIA3.

## Describe the bug
The AMF sets bit 8 of the bitstream to 1 if one of the three is supported. However, bit nr 4 to 16 (starting numbering at 1) should be 0 as they are reserved. The GetEA1_128_5G function returns either 0 or 1. This value is written directly into the variable nrEncryptionAlgorighm[0]  which should contain a bitmask instead. (in src/amf/ngap/message/build.go)

## Reproduce it:
This behavior can be reproduced by the default free5gc configuration running the test script:
`
./test.sh -o TestRegistration
`
on
Ubuntu 18.04 Server
free5gc v3.0.4

## Screenshot
![image](https://user-images.githubusercontent.com/16240312/97859842-73ce3a00-1d01-11eb-84ed-8dc6392cecf9.png)

# suggested solution
in src/amf/ngap/message/build.go
adding a bitshift by 5,6,7 bits should solve the problem. (in total 3 times within this module)

`
	nrEncryptionAlgorighm := []byte{0x00, 0x00}
	nrEncryptionAlgorighm[0] |= amfUe.UESecurityCapability.GetEA1_128_5G() << 7
	nrEncryptionAlgorighm[0] |= amfUe.UESecurityCapability.GetEA2_128_5G() << 6
	nrEncryptionAlgorighm[0] |= amfUe.UESecurityCapability.GetEA3_128_5G() << 5
	ueSecurityCapabilities.NRencryptionAlgorithms.Value =
		ngapConvert.ByteToBitString(nrEncryptionAlgorighm, 16)

	nrIntegrityAlgorithm := []byte{0x00, 0x00}
	nrIntegrityAlgorithm[0] |= amfUe.UESecurityCapability.GetIA1_128_5G() << 7
	nrIntegrityAlgorithm[0] |= amfUe.UESecurityCapability.GetIA2_128_5G() << 6
	nrIntegrityAlgorithm[0] |= amfUe.UESecurityCapability.GetIA3_128_5G() << 5
	ueSecurityCapabilities.NRintegrityProtectionAlgorithms.Value =
		ngapConvert.ByteToBitString(nrIntegrityAlgorithm, 16)
`

## tested
the suggested solution is tested only very rudimentary. However, the right bits are set  to 1 now (at least where I have seen them).

**Comment by free5gc-org** [comment]
Hi,

Thanks for the report. We'll fix it in our next release.

**Comment by ralfkundel** [comment]
bugfix pull request:
[https://github.com/free5gc/amf/pull/15](fix)

**Comment by calee0219** [comment]
The PR has been merged

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/trying-to-connect-to-commercial-ran-but-initial-context-setup-failure-radionetwork30/598/5
