### ISSUE TITLE
[Bugs] NAS LastVisitedRegisteredTAI length should be 7

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#134]
## Describe the bug
NAS LastVisitedRegisteredTAI length should be 7

## To Reproduce
Dump LastVisitedRegisteredTAI

## Expected behavior
NAS LastVisitedRegisteredTAI length is 7

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/nas/pull/6) for the fix.

**Comment by free5gc-org** [comment]
The PR has been merged.

Thanks a lot for the contribution!
