### ISSUE TITLE
[Bugs] AMF fails to decode id-UERadioCapability in InitialContextSetupRequest

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#135]
## Describe the bug
AMF fails to decode id-UERadioCapability in InitialContextSetupRequest

## To Reproduce
Decode id-UERadioCapability in InitialContextSetupRequest

## Expected behavior
Field must be decoded as Hex (OCTET STRING) not as String

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/10) for the fix.

**Comment by free5gc-org** [comment]
The PR has been merged.

Thanks a lot for the contribution!
