### ISSUE TITLE
[Bugs] UPF fails to free BufPacket when repeatedly setting and releasing PDU session

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#136]
## Describe the bug
UPF fails to free BufPacket when repeatedly setting and releasing PDU session.

## To Reproduce
PDU session set & release several times.  Current code does not properly free BufPacket.

## Expected behavior
When session goes down, the corresponding BufPacket should be freed.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/upf/pulls) for the fix.

**Comment by free5gc-org** [comment]
[PR#12](https://github.com/free5gc/upf/pull/12) was already merged.
Thanks for the PR.
