### ISSUE TITLE
[Bugs] AMF panics at HandleRegistrationComplete when Mobility/PeriodicUpdateRegistration

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#138]
## Describe the bug
AMF panics at HandleRegistrationComplete() when Mobility/PeriodicUpdateRegistration.  We believes that HandleRegistrationComplete() is trying to refer RegistrationRequest's data but that is cleared before hand.
The fix is not call ue.ClearRegistrationRequestData(anType).

## To Reproduce
Handle Mobility/PeriodicUpdateRegistration.

## Expected behavior
No panic.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/11) for the fix.

**Comment by free5gc-org** [comment]
The PR has been merged.

Thanks for the contribution!!! 👍
