### ISSUE TITLE
[Bugs] AMF ServiceRequest occurs two times when CM-CONNECTED transition

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#139]
## Describe the bug
AMF ServiceRequest occurs two times when CM-CONNECTED transition.  In specification:

> TS 24.501 8.2.6.21: if the UE is sending a REGISTRATION REQUEST message as an initial NAS message,
> the UE has a valid 5G NAS security context and the UE needs to send non-cleartext IEs
> TS 24.501 4.4.6: When the UE sends a REGISTRATION REQUEST or SERVICE REQUEST message that includes a NAS message container IE, the UE shall set the security header type of the initial NAS message to "integrity protected"

It seems some part of the processing in 4.4.6 is not implemented.  We've implemented and fixed the issue.

## To Reproduce
Process CM-CONNECTED transition.

## Expected behavior
ServiceRequest occurs only once when CM-CONNECTED transition.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/12) for the fix.

**Comment by free5gc-org** [comment]
The PR has been merged.
Thanks a lot for the contribution!
