### ISSUE TITLE
Need clarification on the smf and ue routing configuration for ULCL

### ISSUE THREAD

**Issue by sudhir-intc** [free5gc/free5gc#14]
Hi,
I am trying to validate the ULCL configuration with 3 UPF's  - 1 Branching UPF and 2 Anchoring UPF's. Please refer to the diagram attached for the setup.  I see the ULCL not working correctly. Need your help on identifying any issues with the configuration.

The rules I want to set is as below:
- Any traffic from UE to destination IP 60.60.0.101 : Traffic to through to Branching UPF -  Anchoring UPF-1
- Any traffic from UE to destination IP 60.60.0.102 : Traffic to break-out from Branching UPF 
- Any traffic from UE to destination IP 60.60.0.103 : Traffic to through to Branching UPF - Anchoring UPF-2

I have set the UE routing rules as below in uerouting.yml
ueRoutingInfo:
  - SUPI: imsi-2089300007487
    AN: 10.200.200.2
    PathList:
      - DestinationIP: 60.60.0.102
        UPF: !!seq
          - BranchingUPF
          - BranchingUPF

      - DestinationIP: 60.60.0.101        
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 60.60.0.103        
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2

I have set the userplane information in smfconfig as below:

userplane_information:
    up_nodes:
      gNB1:
        type: AN
        an_ip: 10.200.200.2
      BranchingUPF:
        type: UPF
        node_id: 10.200.200.102        
      AnchorUPF1:
        type: UPF
        node_id: 10.200.200.101        
      AnchorUPF2:
        type: UPF
        node_id: 10.200.200.103        
    links:
      - A: gNB1
        B: BranchingUPF
      - A: BranchingUPF
        B: AnchorUPF1
      - A: BranchingUPF
        B: AnchorUPF2
  ue_subnet: 60.60.0.0/16
  nrfUri: https://localhost:29510
  ulcl: true

![image](https://user-images.githubusercontent.com/56033524/79484374-2b834f00-8031-11ea-945b-011cd3babafc.png)

**Comment by sudhir-intc** [comment]
Attaching the pcaps from the 3 UPF's
[ulcl_upfs_pcap.zip](https://github.com/free5gc/free5gc/files/4488689/ulcl_upfs_pcap.zip)

**Comment by daniel-garciasanchez** [comment]
Hi Sudhir, I've checked your files (have same issue here). I think the code should have generated some SDF filters into PDIs for the uplink traffic you've defined at SUPI but it is not correctly populating them.

**Comment by free5gc-org** [comment]
Agree,
It seems like SDF filter does not set down.
We are check for the issue.

**Comment by free5gc-org** [comment]
hi @sudhir-intc @daniel-garciasanchez ,

There is some limitation of our SMF to run ULCL. Check our [new document](https://github.com/free5gc/free5gc/wiki/SMF-Config) to make your setting works.

Also, it is welcome to contribute our SMF to make your ULCL env works. For now, we have open all our source code for community.

Best Regards

**Comment by sudhir-intc** [comment]
Thanks for sharing the wiki pages it helps to understand the configuration further. Further to the information shared could you please help updating the Representing Topology diagram for Example 2 to show-case where the up_resource_ip: 192.188.2.2, up_resource_ip: 192.188.2.23, up_resource_ip: 192.188.2.24 map to.

**Comment by free5gc-org** [comment]
hi @sudhir-intc ,
We have updated our [document](https://github.com/free5gc/free5gc/wiki/SMF-Config) for more explanation. 
In a nutshell,  up_resource_ip won't affect Representing Topology in this version.

**Comment by infinitydon** [comment]
So when `ulcl` is enabled in `smfcfg.conf`, where should `uerouting.yaml` be placed? Is there a command flag to specify the location of `uerouting.yaml` ?

**Comment by free5gc-org** [comment]
hi @infinitydon , `uerouting.yaml` should be placed under the `config` folder. 
If you are running the test.sh, there is no command flag to specify it.

**Comment by infinitydon** [comment]
Thanks @free5gc-org

**Comment by free5gc-org** [comment]
@sudhir-intc 
I thinks this can be close?

**Comment by sajidkhan2067** [comment]
> @sudhir-intc I thinks this can be close?

@free5gc-org , I am using smf1, smf2 in the same VM, upf1, and upf2 in two different VM. How can I config ueroutign.yaml?
