### ISSUE TITLE
[Bugs] AMF fails to set NAS security header in service accept

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#140]
## Describe the bug
AMF fails to set NAS security header in service accept.  It seems current code set NAS Type Integrity and ciphered to NAS Type even if it is plain NAS message processing.

## To Reproduce
Process Plain NAS 5GS Message

## Expected behavior
Return plain NAS 5GS Message as NAS type.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/13) for the fix.

**Comment by free5gc-org** [comment]
The PR has been merged.

Thanks a lot for the contribution!
