### ISSUE TITLE
[Docs]Can gNB send the packets to more than one UPF simultaneously in ULCL version

### ISSUE THREAD

**Issue by ChaiYuHerng** [free5gc/free5gc#148]
**If the design issue template is not followed, the issue might be closed.**

## Documentation request

In the ULCL version, I want let gNB to send UDP packet to both Anchor point1 and Anchor point2 simultaneously. But when the  Anchor point1 is sending the traffic to DN1, the Anchor point2 will have some error like this 
![image](https://user-images.githubusercontent.com/48347290/101613931-49317880-3a47-11eb-8a8b-7a577178baa7.png)

Or can I let one SMF connect to 3 UPF without using ULCL version?

Another question is that if I want to send the packet to the DN, in my uerouting.yaml my DestinationI{ should be the last UPF's IP or the DN's IP?

## Suggestion

no Suggestion

## Additional context
here is my smf config and uerouting.yaml
![image](https://user-images.githubusercontent.com/48347290/101615719-69facd80-3a49-11eb-838d-5073480550ca.png)
![image](https://user-images.githubusercontent.com/48347290/101615499-2738f580-3a49-11eb-9ce9-a52b01e53198.png)

**Comment by calee0219** [comment]
I believe that SMF connect to 3 UPF without using ULCL.

In this case, 3 of the UPF should with the DNN of internet. Can you try to test in this case?
