### ISSUE TITLE
Is Traffic Steering supported by the UPF - IE related to UPF supported features is missing so cant conclude

### ISSUE THREAD

**Issue by sudhir-intc** [free5gc/free5gc#15]
Does the UPF support the traffic steering functionality defined in 3GPP 29.244 Chapter 5.4.8 Traffic Steering.  In the PFCP Association Responses from the UPF the IE related to UP Function Features(as defined in 3GPP 29.244 8.2.25 UP Function Features)  is missing. Hence this query.

**Comment by free5gc-org** [comment]
hi @sudhir-intc ,

We are sorry to say that we didn't implement Forwarding Policy Identifier yet and we have no traffic steering feature in this moment.

For recent, we are fixing some reminding bug. Maybe this could be a good feature in the future.

BR

**Comment by sudhir-intc** [comment]
Thanks for the feedback.
