### ISSUE TITLE
[Bugs] AMF Registration Status Update Error happens when AMF receives Registration Request with Requested NSSAI.

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#154]
## Describe the bug
AMF Registration Status Update Error happens when AMF receives Registration Request with Requested NSSAI.  This is due to a bug of comparing pointer with entity.

## To Reproduce
Send UE Registration request with Requested NSSAI to AMF.  Comparison of Requested NSSAI and Subscribed NSSAI always fail due to a bug of comparing pointer with entity.

## Expected behavior
Requested NSSAI and Subscribed NSSAI are properly compared

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/18) for the fix.

**Comment by free5gc-org** [comment]
Thanks for contribution!
