### ISSUE TITLE
[Bugs] AMF DeepEqual between pointer with entity bug.

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#156]
## Describe the bug
AMF uses DeepEqual between pointer with entity when comparing TargetAmfSet in handleRequestedNssai().

## To Reproduce
Specify TargetAmfSet in Registration with AMF re-allocation.

## Expected behavior
Properly compare TrgetAmfSet with configured AMF.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/20) for the fix.

**Comment by free5gc-org** [comment]
Thanks for the PR!
