### ISSUE TITLE
[Bugs] AMF TestPDUSessionReleaseRequest fails due to missing PDUsessionResourceSetupRequest

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#158]
## Describe the bug
AMF TestPDUSessionReleaseRequest sometimes fails due to missing PDUsessionResourceSetupRequest.  This is due to missing proper locking.

## To Reproduce
Run TestPDUSessionReleaseRequest multiple times.

## Expected behavior
TestPDUSessionReleaseRequest must success all the time.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/25) for the fix. - PR is updated for main branch

**Comment by free5gc-org** [comment]
Thanks for the PR!
