### ISSUE TITLE
[Bugs] AMF There is a memory increase in AMF due to the IDGenerator's leakage to Allocate

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#159]
## Describe the bug
Memory leak in func (ranUe *RanUe) Remove() due to missing IDGenerator clean up.

## To Reproduce
Add/delete RanUe and see usage of the memory.

## Expected behavior
No memory leak.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/23) for the fix.

**Comment by free5gc-org** [comment]
Thanks for the PR!
