### ISSUE TITLE
N3IWF test NAS message issues

### ISSUE THREAD

**Issue by bjoern-r** [free5gc/free5gc#16]
the binary only library function `nasTestpacket.GetUlNasTransport_PduSessionEstablishmentReques` does not put the PDU-SessionType IE into the nas message.

**Comment by free5gc-org** [comment]
hi @bjoern-r ,

In TS 24.501, this IE is defined as optional, so we didn't provide this IE.

Is there any procedure must using this IE?

**Comment by bjoern-r** [comment]
sorry you are right. the other core which i tested with your network function expected a pdu-sessionType. i was able to add a fallback to ipv4 to make it work.
thankyou. anyway as you are expecting to establish a ipv4 pdu session it would make sense to add this IE.

**Comment by free5gc-org** [comment]
hi @bjoern-r ,

For now, we have open source all our library. If there is some needed to add new IE, it's welcome to contribute and help us to improve the program. 😃

**Comment by bjoern-r** [comment]
thanks!
i will have a look however i'm not an go expert..
