### ISSUE TITLE
[Bugs] SMF There is a memory increase in AMF due to the IDGenerator's leakage to Allocate

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#160]
## Describe the bug
There is a memory increase in SMF due to the IDGenerator's leakage to Allocate

## To Reproduce
Activate/Deactivate uplink tunnel and/or downlink tunnel cause memory leak.

## Expected behavior
No memory leak.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/smf/pull/12) for the fix. - PR is updated.

**Comment by free5gc-org** [comment]
Thanks for the PR!
