### ISSUE TITLE
[Bugs] UPF crash with SEGV when the UE send registration and deregistration repeatedly

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#161]
## Describe the bug
UPF crash with SEGV when the UE send registration and deregistration repeatedly

## To Reproduce
UE to send registration and deregistration repeatedly.  UPF will crash due to missing lock of TimerList.

## Expected behavior
No crash.

## Environment (please complete the following information):
 - free5GC Version: 3.0.4
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/upf/pull/14/commits/f4f1fa029a759cc415918da8909e525effcdd9d7) for the fix.

**Comment by aligungr** [comment]
> **Expected behavior**: No crash

Nice description :smile:

**Comment by muthuramanecs03g** [comment]
Hi Kishiguro,

Thanks for the fix, we are reviewing your fix.

The root cause of this issue is the timer list referenced in two different-context 
-> PacketReceiverThread()
-> eventConsumer

We are reviewing more on this issue and get back to you once it has done.

Thanks & Regards,
Muthuraman

**Comment by free5gc-org** [comment]
Thanks for the contribution!
