### ISSUE TITLE
free5gc version 3.0.4

### ISSUE THREAD

**Issue by pragnyakiri** [free5gc/free5gc#163]
Could you provide the github link to install free5gc version 3.0.4 ?
The current github has been updated with the newer version 3.0.5 and I could not find the older version anywhere.

Thanks,
Pradnya

**Comment by calee0219** [comment]
You can use git tag to checkout to v3.0.4 version
```bash
cd free5gc
git checkout v3.0.4
```
And the commit of v3.0.4 is 847f033... The following is web page for v3.0.4
https://github.com/free5gc/free5gc/tree/847f0337f512d88bb35596038397e6d378f8a2f4

**Comment by pragnyakiri** [comment]
Ok Thank you

**Comment by pragnyakiri** [comment]
There is no bin folder. I am getting below error while "make".
make: *** No rule to make target 'bin/amf', needed by 'amf'.  Stop.

**Comment by free5gc-org** [comment]
Try this to get v3.0.4:
```
git clone --recursive -b v3.0.4 -j `nproc` https://github.com/free5gc/free5gc.git
```
And follow the README in v3.0.4 to build and run it.

**Comment by pragnyakiri** [comment]
I tried to install free5gc as written on page : https://github.com/free5gc/free5gc/tree/847f0337f512d88bb35596038397e6d378f8a2f4
using the git clone --recursive -b v3.0.4 -j `nproc` https://github.com/free5gc/free5gc.git command.

For all packages I am getting the below error:

"fatal: clone of 'git@bitbucket.org:free5gc-team/util_3gpp.git' into submodule path '/home/pradnya/free5gc/lib/util_3gpp' failed
Failed to clone 'lib/util_3gpp'. Retry scheduled
Cloning into '/home/pradnya/free5gc/src/amf'...
git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists. "

Further, since bin folder does not exist, I am getting error on running the "make" command:
make: *** No rule to make target 'bin/amf', needed by 'amf'.  Stop.

**Comment by j13tw** [comment]
Hello pragnyakiri,
I build the free5gc stage 3.0.4 version, and also get the same error
I watch the free5gc update commit for version v3.0.4 to v3.0.5
for free5gc v3.0.4 branch, it has a newest commit to update the git submodule file
so, you need to try the change commit-it to old version and download the git submodule
There is my fix command, you can try it to get the free5gc stage v3.0.4

```
git clone -b v3.0.4 https://github.com/free5gc/free5gc.git
cd free5gc/
git reset --hard 3ca89b18e
git submodule init
git submodule update
```

**Comment by calee0219** [comment]
Maybe the other ways is to change the URL of .gitmodules.

There is `git@bitbucket.org:free5gc-team/...` in .gitmodules, but it should be `https://github.com/free5gc/...`

Maybe using sed to replace it

```bash
sed -i 's/git@bitbucket.org:free5gc-team/https:\/\/github.com\/free5gc/g' .gitmodules
```

**Comment by free5gc-org** [comment]
We retag v3.0.4 to commit: 371216e0. Please use git clone -b v3.0.4 https://github.com/free5gc/free5gc.git to build again.

**Comment by pragnyakiri** [comment]
I tried cloning and building again.
I am getting error on running the "make" command:
make: *** No rule to make target 'bin/amf', needed by 'amf'. Stop.

**Comment by free5gc-org** [comment]
@pragnyakiri you need to init and update submodule:
```
git submodule init
git submodule update
```

**Comment by pragnyakiri** [comment]
It is building now. But on running TestRegistration, I am getting below error:
2021-01-25T11:59:44+05:30 [ERRO][AMF][Gmm] Nausf_UEAU Authenticate Request Error: server no response
2021-01-25T11:59:44+05:30 [ERRO][AMF][Gmm] Authentication procedure failed

I have'nt changed any of the free5gc configuration settings.

**Comment by manoj1919** [comment]
Hi I am facing the same issue as @pragnyakiri ,
2021-01-25T12:04:16+05:30 [WARN][PCF][Init] AMF status subscribe Error[http://127.0.0.18:8000: server no response]
2021-01-25T12:04:16+05:30 [WARN][PCF][Init] AMF status subscribe Error[http://127.0.0.18:8000: server no response]
2021-01-25T12:04:16+05:30 [WARN][PCF][Init] AMF status subscribe Error[http://127.0.0.18:8000: server no response]
2021-01-25T12:04:16+05:30 [WARN][PCF][Init] AMF status subscribe Error[http://127.0.0.18:8000: server no response]
and then in the end, same error:
2021-01-25T12:06:07+05:30 [ERRO][AMF][Gmm] Nausf_UEAU Authenticate Request Error: server no response
2021-01-25T12:06:07+05:30 [ERRO][AMF][Gmm] Authentication procedure failed

**Comment by free5gc-org** [comment]
@manoj1919 

Are you using free5gc v3.0.5? This thread discussing is based on v3.0.4.

**Comment by manoj1919** [comment]
I am trying to use v3.0.4. 
I followed the steps discussed in this thread.
step 1:
git clone -b v3.0.4 https://github.com/free5gc/free5gc.git
step 2 and 3:
git submodule init
git submodule update
step 4:
in thefree5gc folder ran this command
./test.sh Test registration
Thanks
Manoj

**Comment by free5gc-org** [comment]
@manoj1919 
This problem may cause by running v3.0.5 before v3.0.4, and we modified some configuration files. When it finds the data in the configuration file is different from the data in MongoDB, the Authentication procedure will fail.
It will be fixed by deleting data in MongoDB as following:
`mongo`
`use free5gc`
`db.dropDatabase()`
Then, you can use `show dbs` to see if free5gc in MongoDB is deleted or not.

**Comment by manoj1919** [comment]
@free5gc-org , Thank you.
It solved the problem.

**Comment by free5gc-org** [comment]
> @manoj1919
> This problem may cause by running v3.0.5 before v3.0.4, and we modified some configuration files. When it finds the data in the configuration file is different from the data in MongoDB, the Authentication procedure will fail.
> It will be fixed by deleting data in MongoDB as following:
> `mongo`
> `use free5gc`
> `db.dropDatabase()`
> Then, you can use `show dbs` to see if free5gc in MongoDB is deleted or not.

@pragnyakiri please drop the DB and add subscriber again via webconsole.

**Comment by pragnyakiri** [comment]
@free5gc-org :+1: It is working after dropping the database. TestRegistration got Passed. Thank you.
