### ISSUE TITLE
Release 3.0.5 won't build on fresh install per instructions

### ISSUE THREAD

**Issue by nagilum2007** [free5gc/free5gc#165]
### Description
We attempted to build Release 3.0.5 on **a fresh system** by following the install instructions at https://github.com/free5gc/free5gc/wiki/Installation/b9e8196fdd58cc152bdcd9b7151841b58adbeb8d. However, the build process fails saying (emphasis added):
Start building amf....
cd NFs/amf && \
CGO_ENABLED=0 go build -ldflags "-X github.com/free5gc/version.VERSION=v3.0.5 -X github.com/free5gc/version.BUILD_TIME=2021-01-27T18:58:26Z -X github.com/free5gc/version.COMMIT_HASH=a7019d1e -X github.com/free5gc/version.COMMIT_TIME=2021-01-18T14:29:14Z" -o /home/free5gc/free5gc/bin/amf amf.go
**amf.go:10:2: cannot find package "github.com/free5gc/amf/logger"** in any of:
	/usr/local/go/src/github.com/free5gc/amf/logger (from $GOROOT)
	/home/free5gc/go/src/github.com/free5gc/amf/logger (from $GOPATH)
amf.go:11:2: cannot find package "github.com/free5gc/amf/service" in any of:
	/usr/local/go/src/github.com/free5gc/amf/service (from $GOROOT)
	/home/free5gc/go/src/github.com/free5gc/amf/service (from $GOPATH)
Makefile:43: recipe for target 'bin/amf' failed
make: *** [bin/amf] Error 1

### Steps to Reproduce

1. Complete Part A of the Install Documentation
2. cd ~
3. git clone --recursive -b v3.0.5 -j `nproc` https://github.com/free5gc/free5gc.git
4. cd free5gc
5. make

### Expected Behavior
Successful Build

### Environment
- free5GC Version: 3.0.5
- OS: Ubuntu 18.04.5 LTS
- Kernel Version: 5.0.0-23-generic
- Go Version: go1.14.4 linux/amd64
- C Compiler Version: 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by endrigoshi** [comment]
I think that's because you have not enables (or have explicitly disabled) go modules. Try setting the environment variable GO11MMODULES=on.

**Comment by nagilum2007** [comment]
Thanks!

Adding that to my .bashrc file and starting a new terminal got me further. There is also a missing dependency of g++.

**Comment by free5gc-org** [comment]
@nagilum2007 @endrigoshi 

We updated our wiki for that:
```
echo 'export GO111MODULE=auto' >> ~/.bashrc
```
Thanks for your reply.
If no more issue, please help close this issue.
