### ISSUE TITLE
[Bugs] Data Network Name value in DNN Configurations cannot be changed from the default "internet"

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#168]
Hi @free5gc-org 

When I registered the subscriber information using WebConsole, even if I changed the value of **Data Network Name** of **DNN Configurations** from the default `internet` to another string (eg. `internet2`), when I checked the contents of mongodb, it was still `internet`.

Also, the function to change subscriber information does not work properly.

When will the these major bugs in WebConsole are fixed?

Thank you very much in advance.

**Comment by s5uishida** [comment]
Hi @free5gc-org 

For your reference, I will tell you a little more about the bug.

For example, when `SST=1` and `SD=101023`,  even if registered `internet2` to DNN (Data Network Name)  using WebConsole, `DNN=internet` (default) is always set in MongoDB as follows.

---

free5gc.policyData.ues.smData.smPolicySnssaiData.01010203.smPolicyDnnData.**internet**.dnn=**internet**

---

Please fix it. 

Thank you very much in advance.

**Comment by s5uishida** [comment]
Hi @free5gc-org 

Now, I'm using free5GC to confirm the operation of the facility of ULCL.

In the process, first of all, I have confirmed the operation of free5GC with the following simple configuration (no ULCL).
In addition, as this above I modify the data in MongoDB registered using WebConsole and use it. 

https://github.com/s5uishida/free5gc_ueransim_sample_config

FYI.

**Comment by free5gc-org** [comment]
@s5uishida 

Thanks for your report.
We're in CNY holidays.
We'll try to fix it ASAP.

**Comment by free5gc-org** [comment]
@s5uishida 
We fixed the issue, please update webconsole to v1.0.1:
https://github.com/free5gc/webconsole/releases/tag/v1.0.1

**Comment by s5uishida** [comment]
Hi @free5gc-org 

Thank you very much for your quick response!

I have confirmed that the data is registered correctly in MongoDB and free5GC works properly.

By the way I have two questions.

1) Please allow this modified webconsole to be installed using the normal installation procedure for free5GC v3.0.5.
Currently, when v3.0.5 was git cloned, the source version before this fix was got.

2) The registered data editing function does not work properly, so please correct this as well.

Anyway, this fix is very helpful.

Thank you very much again!!

**Comment by free5gc-org** [comment]
@s5uishida 

1. We updated the wiki: https://github.com/free5gc/free5gc/wiki/Installation#d-install-webconsole
2. We'll check it.

**Comment by free5gc-org** [comment]
@s5uishida 

About registered data issue, please follow steps as below:

1. Drop mongoDB:
```
mongo --eval "db.dropDatabase()" free5gc
```
2. Run free5gc
```
./run.sh
```
3. Run WebConsole
```
./webconsole/bin/webconsole
```
4. Check "Registered UEs" page

It should be workable.

**Comment by s5uishida** [comment]
Hi @free5gc-org 

OK.

As an installation procedure, I edited my sample configuration to refer to the above URL.

Also,

> 2. The registered data editing function does not work properly, so please correct this as well.

Please do not forget to deal with this matter. Perhaps this bug has existed unfixed since free5GC v3.0.0.

Thank you very much in advance.

**Comment by free5gc-org** [comment]
> > 1. The registered data editing function does not work properly, so please correct this as well.
> 
> Please do not forget to deal with this matter. Perhaps this bug has existed unfixed since free5GC v3.0.0.

@s5uishida 
Please follow [here](https://github.com/free5gc/free5gc/issues/168#issuecomment-776075165) to resolve it.

**Comment by s5uishida** [comment]
Hi @free5gc-org 

The following steps describe the situation here.

1) After deleting the data of MongoDB, login to WebConsole and register the data.

2) Logout of the WebConsole and restart the browser.

3) Login to the WebConsole again and click `SUBSCRIBERS`.

4) Select UE ID(`imsi-001010000000000`) and click the `Modify` button.

![webconsole_1](https://user-images.githubusercontent.com/52230356/107601169-44688b00-6c69-11eb-9656-892ffea10ee3.png)

5) The edit screen of `208930000000003`, which is different from `001010000000000`, is displayed.

![webconsole_2](https://user-images.githubusercontent.com/52230356/107601175-49c5d580-6c69-11eb-954e-47496f30e494.png)

In addition, UEs are not connected to free5GC yet.

I cannot modify the various data of the selected IMSI. If select another IMSI and press the `Modify` button, the same screen will be displayed.

Is this situation reproduced there?

**Comment by free5gc-org** [comment]
@s5uishida 

There are some issues for subscriber modification.
If you want to modify subscriber, please delete first and new again for now.

**Comment by s5uishida** [comment]
Hi @free5gc-org 

> There are some issues for subscriber modification.
> If you want to modify subscriber, please delete first and new again for now.

Could you please write the above in the following URL?

https://github.com/free5gc/free5gc/wiki/New-Subscriber-via-webconsole

I think that registering subscriber data is a basic task when using free5GC. At this time, not being able to edit the registered data is important information for the user, so please make something clear this.

After that, please close this issue.

Thank you very much in advance.

**Comment by free5gc-org** [comment]
> Could you please write the above in the following URL?
> 
> https://github.com/free5gc/free5gc/wiki/New-Subscriber-via-webconsole
> I think that registering subscriber data is a basic task when using free5GC. At this time, not being able to edit the registered data is important information for the user, so please make something clear this.
> 
> After that, please close this issue.

Wiki has been updated. Thanks.
