### ISSUE TITLE
[Bugs] Stage3.0.4 test in UERANSimulator in AMF got Capability5GMM is nil message.

### ISSUE THREAD

**Issue by j13tw** [free5gc/free5gc#169]
## Describe the bug
free5gc stage3.0.4 use UERANSimulator to Send UDP Packet
Got the Message Pending on the ```Encode ExtendedProtocolConfigurationOptions in EncodePDUSessionEstablishmentRequest```
and watch amf log, got the ```Capability5GMM is nil (/go/src/free5gc/src/amf/gmm/sm.go:274 free5gc/src/amf/gmm.ContextSetup)```

## To Reproduce
1. git clone the ```free5gmano``` project, and go to /free5gmano/deploy/free5gc-stage3.0.4/k8s-cni
2. fix amfcfg ```ngapIpList``` to ```amfIp``` and change ```node_id``` to ```upfIp``` in the 00-free5gc-configmap.yaml
3. use free5gmano give's deploy file number to deploy free5gc-3.0.4 with kubernetes CNI (Flannel)
4. go to the testEnv, fix the free5gc/src/test/rawudp.go
5. go to the testEnv, fix the ```free5gc/src/test/ueRanEmulator/config/ueranem.conf```
6. go to the testEnv, fix the ```free5gc/src/test/ueRanEmulator/main.go```
7. login free5gc-webUI website, add the subscriber (IMSI, OPc, K) by default.
8. run ```go run main.go``` , and log the ```amf```, and the smf will crash.

## Expected behavior
1. ```go run main.go``` complete UE initial, and create pduSession, then send GTP<UDP> packet to UPF

## Environment (please complete the following information):
 - free5GC Version: v3.0.4
 - OS: Ubuntu 20.04 Server
 - Kernel version: 5.4.0-62-generic
 - go version:  go1.14.4 linux/amd64
 
### Configuration File

1. All of free5gc vNFs ConfigureFile
[00-free5gc-configmap.txt](https://github.com/free5gc/free5gc/files/5911124/00-free5gc-configmap.txt)

2. free5gc/test/rawudp.go
[rawudp.txt](https://github.com/free5gc/free5gc/files/5911184/rawudp.txt)

3. free5gc/test/uesimulator/main.go
[main.txt](https://github.com/free5gc/free5gc/files/5911190/main.txt)

4. free5gc/test/uesimulator/ueranem.conf
[ueranem.txt](https://github.com/free5gc/free5gc/files/5911176/ueranem.txt)

### PCAP File

[amf-0202.pcap.zip](https://github.com/free5gc/free5gc/files/5911104/amf-0202.pcap.zip)

### Log File

1. amf.log
[amf-0202.log](https://github.com/free5gc/free5gc/files/5911133/amf-0202.log)

2. smf.log
[smf-0202.log](https://github.com/free5gc/free5gc/files/5911315/smf-0202.log)

3. UERANSimulator
[ueransim.log](https://github.com/free5gc/free5gc/files/5911143/ueransim.log)

## System architecture (Option)
1. kubernetes 1.18.5 with docker 20.10.1
2. all of free5gc vNFs are in same node

**Comment by free5gc-org** [comment]
We didn't maintain ueRanEmulator.
Please try the the third-party UE simulator:
https://github.com/aligungr/UERANSIM
https://github.com/hhorai/gnbsim

And also try our the latest version v3.0.5.
