### ISSUE TITLE
[Question] About the order to start SMF and UPF

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#170]
Hi @free5gc-org 

I have one question.

After starting C-Plane (except for UPF) on one VM first, then starting U-Plane (UPF only) on another VM, and then trying to register UE after NG-Setup of gNB, the following error occurred between SMF and UPF. As a result, creating a PDU session failed.
```
2021-02-04T06:36:25Z [ERRO][SMF][CTX] In ActivateUpLinkTunnel UPF IP:  192.168.100.43
2021-02-04T06:36:25Z [ERRO][SMF][CTX] Allocate PDR Error:  this upf do not associate with smf
2021-02-04T06:36:25Z [WARN][SMF][CTX] Add PDR failed: this upf do not associate with smf
```
On the other hand, if starting UPF first and then C-Plane, the PDU session was created successfully.

Is this the specification? Or am I misunderstanding?

If it is the specification, I think it will be very easy to use if the specification is changed so that it does not depend on the order of starting SMF and UPF.

Thank you very much in advance.

**Comment by calee0219** [comment]
In 3GPP's specification, both UPF and SMF can send PFCP Association Setup Request.

But in free5GC's recently design, only SMF will send PFCP Association Setup Request according to the UPF's IP inside the config file. As the result, UPF should start before SMF.

**Comment by s5uishida** [comment]
Hi @calee0219 

Thank you very much for your information.

OK. I will start and use it in the order of SMF after UPF.

For your reference, I'm using the following for the VM for UPF here.

- OS : Ubuntu 20.04.1 `Linux 5.4.0-65-lowlatency #73-Ubuntu SMP PREEMPT Mon Jan 18 18:17:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Mem : 1GB
- HDD : 20GB

**Comment by s5uishida** [comment]
Hi @free5gc-org , @calee0219 

Please close this issue when this information was written on the Wiki.

Thank you very much in advance.

**Comment by free5gc-org** [comment]
@s5uishida 

We updated it in:
https://github.com/free5gc/free5gc/wiki/Run

**Comment by sajidkhan2067** [comment]
> Hi @free5gc-org
> 
> I have one question.
> 
> After starting C-Plane (except for UPF) on one VM first, then starting U-Plane (UPF only) on another VM, and then trying to register UE after NG-Setup of gNB, the following error occurred between SMF and UPF. As a result, creating a PDU session failed.
> 
> ```
> 2021-02-04T06:36:25Z [ERRO][SMF][CTX] In ActivateUpLinkTunnel UPF IP:  192.168.100.43
> 2021-02-04T06:36:25Z [ERRO][SMF][CTX] Allocate PDR Error:  this upf do not associate with smf
> 2021-02-04T06:36:25Z [WARN][SMF][CTX] Add PDR failed: this upf do not associate with smf
> ```
> 
> On the other hand, if starting UPF first and then C-Plane, the PDU session was created successfully.
> 
> Is this the specification? Or am I misunderstanding?
> 
> If it is the specification, I think it will be very easy to use if the specification is changed so that it does not depend on the order of starting SMF and UPF.
> 
> Thank you very much in advance.

I am using two UPF in different VM and two SMF in the same VM. Though I started two upf first but getting the same error !!!

**Comment by sajidkhan2067** [comment]
@free5gc-org can you please give me the solution?

**Comment by calee0219** [comment]
Maybe is better to create another issue and reference to this issue so that it will not be ignore easily. :slightly_smiling_face:
