### ISSUE TITLE
[Bugs] Warning message in AMF while running ./run.sh in v3.0.5

### ISSUE THREAD

**Issue by manoj1919** [free5gc/free5gc#171]
## Describe the bug
I recently upgraded my free5gc from v3.0.4 to v3.0.5. all the tests after installation are running fine. Yet, I am getting a warning in AMF. Can this warning be ignored?

## To Reproduce
1. Install free5gc as per instructins in the wiki page
2. run ./run.sh
## Expected behavior
All NFs should start without any error/warning messages 
## Screenshots
Even though all the tests are running fine and it passes all the tests, I get the following warning message on console:
2021-02-10T06:38:29+05:30 [WARN][AMF][NGAP] RAN context has been removed[addr: <nil>]
2021-02-10T06:38:29+05:30 [INFO][AMF][NGAP] Handle SCTP Notification[addr: <nil>]
2021-02-10T06:38:29+05:30 [WARN][AMF][NGAP] RAN context has been removed[addr: <nil>]

## Environment (please complete the following information):
 - free5GC Version: [e.g. v3.0.5]
 - OS: [ Ubuntu 20.04.1 LTS]
 - Kernel version: [5.4.0-42-generic]
 - go version: [go1.14.4]
 - c compiler version (Option): [gcc version 9.3.0]

### Configuration File
have not edited any config files

### PCAP File
Dump the packet and provide the pcap file here.

[free5gc.zip](https://github.com/free5gc/free5gc/files/5955324/free5gc.zip)

**Comment by free5gc-org** [comment]
Ran context will be removed when receiving SCTP SHUTDOWN or SHUTDOWN_COMPLETE.
So, this is not a bug and you can ignore the warning.
