### ISSUE TITLE
[Bugs] SMF does not return proper EndPoint IP Address when PDUSessionTypeIPv4IPv6 is specified

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#173]
## Describe the bug
SMF does not return proper EndPoint IP Address when PDUSessionTypeIPv4IPv6 is specified

## To Reproduce
Request EndPoint IP Address with PDUSessionTypeIPv4IPv6.  SMF does not return IP Address at all even SMF has the configuration.

## Expected behavior
Return proper EndPoint IP Address

## Environment (please complete the following information):
 - free5GC Version: 3.0.5
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/smf/pull/13) for the fix.

**Comment by free5gc-org** [comment]
@kishiguro 

Could you provide the full log?
It should be an error happened when checking PDU session type in HandlePDUSessionEstablishmentRequest().

**Comment by kishiguro** [comment]
Yes, we are expecting SMF to return IPv4 address for EndPoint when receiving PDUSessionTypeIPv4IPv6.

**Comment by free5gc-org** [comment]
@kishiguro 

Is it ok that SMF sends response to reject the UE request with PDUSessionTypeIPv4IPv6?

**Comment by kishiguro** [comment]
According to spec 3GPP TS 23.501 V15.12.0 (2020-12) 5.8.2.2.1 General.

> The SMF selects PDU Session Type of the PDU Session as follows:
> - If the SMF receives a request with PDU Session Type set to "IPv4v6", the SMF selects either PDU Session Type "IPv4" or "IPv6" or "IPv4v6" based on DNN configuration, subscription data and operator policies.

before this paragraph:

> - A UE which supports IPv6 and IPv4 shall set the requested PDU Session Type "IPv4v6".

So here is a scenario:

* UE support both IPv4 and IPv6: UE send PDU Session Type "IPv4v6"
* SMF support only IPv4: Need to response with PDU Session Type "IPv4"

If SMF rejects the "IPv4IPv6" request, SMF can't establish a connection with UE which support both IPv6 and IPv4.  I guess it  is not an expected behavior.

**Comment by free5gc-org** [comment]
@kishiguro 

Yes, you are right.
Could you help to check if PDU Session Type is "IPv4" in PDU session establishment accept?
If not, it should also be fixed.

**Comment by kishiguro** [comment]
sure! let us check it.

**Comment by kishiguro** [comment]
We double check with commercially available gNodeB solution which send "IPv4IPv6" to SMF.  It seems even if SMF select only "IPv4" address we would establish PDU session with "IPv4IPv6".  I think the behavior conforms to:

> - If the SMF receives a request with PDU Session Type set to "IPv4v6", the SMF selects either PDU Session Type "IPv4" or "IPv6" or "IPv4v6" based on DNN configuration, subscription data and operator policies.

We've update the PR to handle FQDN configuration case.

**Comment by free5gc-org** [comment]
Thanks for the PR!
