### ISSUE TITLE
InfluenceOnTrafficRouting feature in PCF

### ISSUE THREAD

**Issue by sudhir-intc** [free5gc/free5gc#18]
Hi,
In the PCF code as part of pcf_policyAuthorization.go:PostAppSessionsContext() I have seen the code for the trafficRouting. I wanted to understand the correct configuration to enable the traffic routing in PCF, I tried by changing the below configurations in the default pcfcfg.conf but this does not seem to work
    - serviceName: npcf-smpolicycontrol
       suppFeat: 1
    - serviceName: npcf-policyauthorization
       suppFeat: 1

When a request to sent to the PCF N5 I/f I can see an error in the PCF logs that traffic routing is not enabled:
ERRO[2020-04-21T18:51:22+05:30]/src/pcf/pcf_producer/pcf_policyauthorization.go:1571 free5gc/src/pcf/pcf_producer.sendProblemDetail() Traffic routing not supported                 PCF=PolicyAuthorization 

Could you let me what is the correct configuration to enable TrafficRouting in PCF. Also please let me know if there needs to be any additional configurations to be done in the other NF's.

**Comment by free5gc-org** [comment]
Hi,

We didn't implement this feature yet.

**Comment by sudhir-intc** [comment]
Thanks for the answer. Could you please let me know the roadmap plan on when this feature is planned to be made available.

**Comment by grzegorzpnk** [comment]
Hi, any update on this procedure?

**Comment by linpoyi** [comment]
Hi, @grzegorzpnk, 
The AF on influence routing feature has been implemented, we will release it in the near future.
BRs,
Linpoyi

**Comment by ntnguyencse** [comment]
Hi @linpoyi, Could you tell me which date you will release AF on influence routing

> Hi, @grzegorzpnk,  The AF on influence routing feature has been implemented, we will release it in the near future. BRs, Linpoyi
Hi @linpoyi , Could you please let me know the date you will release these features? 
Thanks.

**Comment by linpoyi** [comment]
Hi @ntnguyencse , 
NEF is scheduled to be released in v3.3.2, which is 2 versions from now (v3.3.0). I'll say it probably takes 3 months or more.
BRs,
Linpoyi

**Comment by xiongkai0920** [comment]
> 嗨，NEF 计划在 v3.3.2 中发布，从现在开始是 2 个版本 （v3.3.0）。我会说这可能需要 3 个月或更长时间。 BRs， 临波伊

您好，想咨询一下，NEF网元发布了吗？

**Comment by linpoyi** [comment]
Hi @xiongkai0920,
NEF is not out yet. It will be released with the R17 update. Probably be later this year.
BRs,
Linpoyi
