### ISSUE TITLE
[Docs] Installation / User-plane Supporting Packages

### ISSUE THREAD

**Issue by lclee3390** [free5gc/free5gc#180]
**If the design issue template is not followed, the issue might be closed.**

## Documentation request

It looks like " Installation / 4. User-plane Supporting Packages " need to install g++ .

Thanks.

## Suggestion

--
## Additional context
![pic_01](https://user-images.githubusercontent.com/36539988/108484832-39e86a00-72d7-11eb-95e2-4e601de564a0.png)

**Comment by free5gc-org** [comment]
@lclee3390 

We didn't meet any error when compiling UPF with installing these packages.
Could you provide more information? Ex: Ubuntu version, compilation error, ...etc.

**Comment by free5gc-org** [comment]
@lclee3390 

We didn't use any c++, so g++ should not be needed.
If no more question, please close this issue.
Thanks.

**Comment by lclee3390** [comment]
OS : ubuntu 20

![err_pic](https://user-images.githubusercontent.com/36539988/112002719-28ef7a80-8b5b-11eb-8b87-ddcdc22cee6a.png)
