### ISSUE TITLE
[Bugs]DB contents are not read when Modifying with Webconsole.

### ISSUE THREAD

**Issue by ex8664** [free5gc/free5gc#182]
I am using free5gc ver3.0.5.

1. I registered the UE from the Web Console.
2. After that, I logged out and logged in again.
3. After that, press the change button and confirm the input data

I wanted to see the IMSI number data I entered in 1.
However, the default value was displayed.
In the correct operation, I think that when you press the Modify button,
the data on the DB should be read and displayed.

**Comment by free5gc-org** [comment]
There are some issues for subscriber modification.
If you want to modify subscriber, please delete first and new again for now.

**Comment by ex8664** [comment]
I've confirmed in v3.1.0 that this issue has been resolved, so I'll close it.
