### ISSUE TITLE
[Bugs]Session-AMBR is not in effect

### ISSUE THREAD

**Issue by juststrive007** [free5gc/free5gc#183]
## Describe the bug
the Configuration of  Session-AMBR （Aggregate Maximum Bit Rate）is not in effect

## To Reproduce
1. I changed  the ue subscribe info in mogodb, and  the table name is subscriptionData.provisionedData.smData. 
2.  sessionAmbr:{
      "uplink":"1000Kbps",
      "downlink":"1000Kbps"
     }
3. Run the free5gc functions use the recommended script  run.sh

## Expected behavior
The uplink and downlink rate of UE should be controlled within 1000Kbps

## Screenshots
However, the rate at which UE can actually receive and transmit is not limited

## Environment :
 - free5GC Version: [v3.0.5]
 - OS: [Ubuntu 18.04 Server]
 - Kernel version: [5.0.0-23-generic]
 - go version: [1.14.4 linux/amd64]

**Comment by free5gc-org** [comment]
@juststrive007 
Yes, UPF QoS is not supported.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/throughput-with-free5gc/1431/2
