### ISSUE TITLE
[Bugs] ERROR SMF CTX this upf do not associate with smf

### ISSUE THREAD

**Issue by Trauck** [free5gc/free5gc#184]
## Describe the bug
When i run the ./test.sh TestRegistration i got the error "this upf do not associate with smf", with upf ip : 10.200.200.101. And the test finish on a panic: test timed out after 10min.

## To Reproduce
1. Install the free5gc package 
2. Follow the step and being at the testing one
3. ./test.sh TestRegistration

## Expected behavior
Expect SUCCESS at the end of the test.

## Screenshots
![image](https://user-images.githubusercontent.com/38696298/108993908-73d0bc00-769b-11eb-819a-cb8fe029e56c.png)

## Environment (please complete the following information):
- free5GC Version v3.0.5
- OS Ubuntu 20.04.1
- Kernel version 5.8.0-43-generic
- go version: 1.16 linux/amd64
- gcc version 9.3.0
- mongo 3.6.8
I'm working on Windows with VmWare.

### Configuration File
The configuration file for the SMF is the classic one given in the package free5gc. I didn't modify anything.

But the TestRegistration add a new UE ID, like we can saw on this screen (the second one, the first was made with the webconsole).
![image](https://user-images.githubusercontent.com/38696298/108994481-23a62980-769c-11eb-92a2-3faadeb859d0.png)

**Comment by free5gc-org** [comment]
@Trauck 

You need to execute `make upf` under free5gc folder to build upf binary first, and then run `./test.sh TestRegistration`
If no more issue, please close this issue.
Thanks.
