### ISSUE TITLE
[Bugs][UDM] supi/suci: protection scheme Profile A hardcoded in UDM

### ISSUE THREAD

**Issue by mrlnc** [free5gc/free5gc#185]
## Description
UE Identification will fail if SUCI is encrypted with Profile B public key. This because UDM always selects Profile A key.

The issue is this line: https://github.com/free5gc/udm/blob/e89dcbf12b4adc1f2b745122b55723089a1d4c45/producer/generate_auth_data.go#L162
Profile A key is passed no matter if SUCI is protected with profile A or B.

## Steps to Reproduce
1.) configure USIM with protection scheme Profile B.
3.) perform authentication to free5gc.

The authentication will fail because the UDM always tries Subscription-Identifier Deconcealing (SIDF) with Profile A.

## Expected behavior

UDM deconceals SUCI with either Profile A or Profile B.

If the Profile B key is passed to `suci.ToSupi()`, the SIDF works as expected.

## Workaround

UDM deconceals SUCI with either Profile A or Profile B.

As a quick workaround, I'm passing both keys to `suci.toSupi`:

https://github.com/mrlnc/udm/commit/9b602ba06fb190754d41ceb94d6d2d2a022ef833
https://github.com/mrlnc/util_3gpp/commit/aeb97ebdd18daa3f06c9ac7acee1b8cacafae0c1

## Environment
 - free5GC Version: v3.0.5

**Comment by mrlnc** [comment]
Actually, operators could have many keys that are distinguished by `HomeNetworkPublicKeyIdentifier`. I guess the key configuration could look like this:
```golang
@@ -34,7 +34,7 @@ type Configuration struct {
        Sbi             *Sbi     `yaml:"sbi,omitempty"`
        ServiceNameList []string `yaml:"serviceNameList,omitempty"`
        NrfUri          string   `yaml:"nrfUri,omitempty"`
-       Keys            *Keys    `yaml:"keys,omitempty"`
+       KeyList         []Key    `yaml:"keyList,omitempty"`
 }
...
-type Keys struct {
-       UdmProfileAHNPrivateKey string `yaml:"udmProfileAHNPrivateKey,omitempty"`
-       UdmProfileAHNPublicKey  string `yaml:"udmProfileAHNPublicKey,omitempty"`
-       UdmProfileBHNPrivateKey string `yaml:"udmProfileBHNPrivateKey,omitempty"`
-       UdmProfileBHNPublicKey  string `yaml:"udmProfileBHNPublicKey,omitempty"`
+type Key struct {
+       HomeNetworkPublicKeyIdentifier int    `yaml:"homeNetworkPublicKeyIdentifier,omitempty"`
+       ProtectionScheme               string `yaml:"protectionScheme,omitempty"`
+       PrivateKey                     string `yaml:"privateKey,omitempty"`
+       PublicKey                      string `yaml:"publicKey,omitempty"`
 }
```

Looking back, this is more a feature request than a small bug; I wasn't really aware of that.

**Comment by free5gc-org** [comment]
@mrlnc 

This issue was already fixed by https://github.com/free5gc/udm/pull/6 and https://github.com/free5gc/util_3gpp/pull/5.
Thanks for your report!

**Comment by mrlnc** [comment]
Great! Thanks @oommcclee
