### ISSUE TITLE
[Bugs]GTP Tunnel sequence number issue

### ISSUE THREAD

**Issue by frankieky888** [free5gc/free5gc#186]
## Describe the bug - GTP Tunnel sequence number issue
According to 3GPP TS 29.281
GTP Tunnel sequence number should be same
"The Sequence Number in a signalling response message shall be copied from the signalling request message that the GTP-U entity is replying to"
![image](https://user-images.githubusercontent.com/26329788/110272881-39094500-8006-11eb-9eee-d0e692b2296d.png)

In your implementation, upf/src/up/up_path.c.  line 105
           ` ._seqNum = (gtpRespHrd.flags & 0x02) ? htons(ntohs(opthrd->_seqNum) + 1) : 0,`

there may be something wrong for the seqNum +1

We are tying to attach a 5G SA UE to free5GC UPF (via one of the vendor's RAN & Core), the PDU session will be deleted by SMF, and the reason seems to be incorrect sequence number in GTP_Echo_Response

## Environment (please complete the following information):
 - free5GC Version: 3.0.5
 - OS: Ubuntu

**Comment by frankieky888** [comment]
has verified the seqNum should remove +1, after we changed the line 105 to ._seqNum = (gtpRespHrd.flags & 0x02) ? htons(ntohs(opthrd->_seqNum) ) : 0,

**Comment by frankieky888** [comment]
@free5gc-org

**Comment by muthuramanecs03g** [comment]
Hi @frankieky888 ,

Your fix is a valid one and also verified with 3GPP TS 29.281 V15.3.0 (2018-06).

Please, send a PR.

Thanks & Regards,
Muthuraman

**Comment by free5gc-org** [comment]
Thanks for [PR#23](https://github.com/free5gc/upf/pull/23). It was merged.
