### ISSUE TITLE
Configuring different IPs for NFs

### ISSUE THREAD

**Issue by ameet-17** [free5gc/free5gc#19]
Hi there!

Can I configure different individual IPs to all the NFs such as AMF, SMF, UPF, PCF etc.,
Ex:
AMF running on 172.15.25.1
SMF running on 172.15.25.2

Can you please share the procedure?

**Comment by free5gc-org** [comment]
Yes you can configure different individual IPs to different NF.

You need to change the ip of {NF}cfg.conf in the [config folder](https://github.com/free5gc/free5gc/tree/master/config).

For example, change the sib/ipv4Addr in smfcfg.conf to make SMF's sbi to listen on different IP.

**Comment by ameet-17** [comment]
Thanks, Why is there lot of these branches under userplane_information.
  userplane_information:
    up_nodes:
      gNB1:
        type: AN
        an_ip: 192.188.2.3
      ANUPF:
        type: UPF
        node_id:  127.0.0.3
        up_resource_ip: 192.188.2.2
      IUPF1:
        type: UPF
        node_id:  127.0.0.4
        up_resource_ip: 192.188.2.4
      BranchingUPF1:
        type: UPF
        node_id:  127.0.0.5
        up_resource_ip: 192.188.2.5
      BranchingUPF2:
        type: UPF
        node_id:  127.0.0.6
        up_resource_ip: 192.188.2.6
      AnchorUPF1:
        type: UPF
        node_id:  127.0.0.7
        up_resource_ip: 192.188.2.7
      AnchorUPF2:
        type: UPF
        node_id:  127.0.0.8
        up_resource_ip: 192.188.2.8
      AnchorUPF3:
        type: UPF
        node_id:  127.0.0.9
        up_resource_ip: 192.188.2.9
      AnchorUPF4:
        type: UPF
        node_id:  127.0.0.10
        up_resource_ip: 192.188.2.10
      AnchorUPF5:
        type: UPF
        node_id:  127.0.0.11
        up_resource_ip: 192.188.2.11
      ANUPF2:
        type: UPF
        node_id:  127.0.0.12
        up_resource_ip: 192.188.2.12

**Comment by free5gc-org** [comment]
hi @ameet-17 ,

We have update our document [here](https://github.com/free5gc/free5gc/wiki/SMF-Config)

Feel free to tell us if there's something not clear enough.

Thanks

**Comment by free5gc-org** [comment]
@ameet-17 if the document is clear enough, maybe we can close the issue?

**Comment by ameet-17** [comment]
Please close the issue.
