### ISSUE TITLE
[Bugs] AMF config file 1.0.0 or 1.0.1

### ISSUE THREAD

**Issue by weekendzhang** [free5gc/free5gc#194]
## Describe the bug
AMF Config file is given,  there is a "version", when gives the verison 1.0.0, sometimes it says, 
[ERRO][AMF][CFG]  [0mconfig version is [1.0.0], but expected is [1.0.1].
but if changes to 1.0.1, it sometimes says:
[ERRO][AMF][CFG] [0mconfig version is [1.0.1], but expected is [1.0.0].

I am not sure if this is a bug, because maybe i miss something. this two version config file not compatible?

**Comment by free5gc-org** [comment]
@weekendzhang 
You have already pulled AMF to the latest commit.
Please also pull free5gc repo to the latest commit.

**Comment by weekendzhang** [comment]
yeah, finally i resolve this issue by changing a stable v3.0.5, thanks and i close this issue.
