### ISSUE TITLE
[Bugs] AMF processes entire plaintext initial NAS message

### ISSUE THREAD

**Issue by p1-bmu** [free5gc/free5gc#196]
## Describe the bug
While testing the free5gc AMF for some NAS security features introduced in the 5G specifications, I found that the AMF processes any plaintext initial NAS message entirely (all IEs in the message are processed), without further check or warning. While the AMF still requests the replay of the initial NAS message in the Security Mode Complete, it does not care in case nothing is replayed, or a different message than the initial one, what seems contradictory to the "spirit" of the 5G security specification.

You can refer to 3GPP TS 33.501 section 6.4.6 for the global overview of the feature (while it is not saying anything specific to do in case the initial NAS message is not replayed or different), and TS 24.501 section 4.4.6 for the list of IEs that are to be processed in plaintext initial NAS message.

There are 2 main risks with this:
- The early processing of all IEs in the AMF, and missing check against the replayed message, could potentially enable some man-in-the-middle attack at the radio interface, where some cellular capabilities of a targeted subscriber are downgraded by the attacker.
- Processing all IEs, before subscriber's authentication has happened, may expose the AMF more than needed ; e.g. I could reach many assertions, and a memory corruption in the AMF demon, with malformed IEs in initial NAS messages.

## To Reproduce
No easy way to reproduce with available open-source tools. A modification of a gNB / UE emulator can be done to send the entire initial NAS message in clear-text, and not replaying it (or replaying with a different message) in the Security Mode Complete message.

## Expected behavior
I believe only "clear-text" IEs from the initial NAS message should be processed in the first place, then other IEs should be processed from the replayed message in the Security Mode Complete which is security protected. In case this replayed message is not provided, I believe the NAS connection should be dropped.

## Environment (please complete the following information):
 - free5GC Version: v3.0.5
 - OS: Ubuntu 20.04
 - Kernel version: 5.4.0-62-generic
 - go version: go1.14.4 linux/amd64

### Configuration File
No specific configuration required.

### PCAP File
A pcap is provided, where the complete initial NAS message is in clear text, and is not replayed in the Security Mode Complete message. The AMF does not issue any specific logging related to this issue, it processes all IEs from the initial NAS message.

[free5gc_nas-init-nosec.pcap.gz](https://github.com/free5gc/free5gc/files/6376764/free5gc_nas-init-nosec.pcap.gz)

### Log File
No specific log exists for this issue.

**Comment by wilson30139** [comment]
Hello @p1-bmu ,the current version of free5GC is upgraded to 3.3.0. Please try again to see if the same bug will appear when using free5GC version 3.3.0, thank you.
Link: https://github.com/free5gc/free5gc
