### ISSUE TITLE
n3iwf: GTPu handler does not chek for extension header

### ISSUE THREAD

**Issue by bjoern-r** [free5gc/free5gc#20]
The Go GTPu packet handler does not check the existence of a GTPu extensionm header in the PDU-Data frame. If such a Header is present it results in invalid IP frames being send to the UE via the ipsec tunnel.

**Comment by free5gc-org** [comment]
hi,

Thanks for the issue report. Though this is an optional item, we think this can been fix by modifying src/n3iwf/n3iwf_data_relay/relay.go

We may patch this feature in the future. Or it's also welcome to contribute. 😃

**Comment by dayal007** [comment]
@bjoern-r Which UE did you use to connect to the n3iwf?
