### ISSUE TITLE
[Bugs] UDM HTTP GET TS29503_Nudm_SDM.yaml:/{supi} method's parameter plmn-id is prone to injection

### ISSUE THREAD

**Issue by H21lab** [free5gc/free5gc#201]
## Describe the bug
UDM HTTP GET TS29503_Nudm_SDM.yaml:/{supi} method's parameter plmn-id is prone to injection

The following message
`GET','/nudm-sdm/v1/imsi-2089300007487?plmn-id=authentication-data/authentication-subscription?`
results into sending later HTTP GET /authentication-data/authentication-subscription/ message from UDR towards UDM.

This means that plmn-id parameter is injectable and not properly sanitized after receiving by UDM.

## To Reproduce
1. Run free5gc locally
2. Sent HTTP `GET','/nudm-sdm/v1/imsi-2089300007487?plmn-id=authentication-data/authentication-subscription?` to UDM 127.0.0.3:8000

## Expected behavior
plmn-id parameter should be sanitized by UDM.

## Environment (please complete the following information):
 - free5GC Version: [e.g. v3.0.5]
 - OS: [e.g. Ubuntu 20.04.2 LTS]
 - Kernel version: [e.g. 5.4.0-72-generic]
 - go version: [e.g. 1.14.4 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 9.3.0]

## Trace File
_(can be provided if needed)_

### Configuration File
_(can be provided if needed)_

### PCAP File
_(can be provided if needed)_

### Log File
_(can be provided if needed)_

## System architecture (Option)
free5gc installed locally. All nodes running in single VM.

**Comment by Leon777-coder** [comment]
Hello:

May I ask if you have tried the latest version of the free-5GC(version 3.30)?  

Best wishes,
Leon

**Comment by H21lab** [comment]
Thank you for your feedback. This is related to 5G SBA signalling. The OAuth will not solve all the problems, but can help against attacks from internal network. If the 5GC will be opened for roaming over SEPP via N32 interface, the illegitimate signalling could be still received from external networks. The messages received over H-SEPP would be properly authenticated over OAuth but could still contain malicious signalling which was received from V-SEPP. The best is to fix this injection vulnerability. And another protection is to have 5G signalling firewall on the network perimeter doing application layer filtering (for more details refer to GSMA FS.36 guidelines).

**Comment by brianchennn** [comment]
Thanks for your advise. But free5gc doesn't plan to support roaming in near future.
