### ISSUE TITLE
[Bugs] n3iwf ike exchange types are inconsistent with standard values

### ISSUE THREAD

**Issue by Silverbullet9** [free5gc/free5gc#202]
## Describe the bug
The setting of ike exchange type in n3iwf/ike/message/types.go is inconsistent with the formal setting of ike protocol.

## To Reproduce
I tried to connected my phone with n3iwf through wi-fi. After setting the network config, n3iwf received the ike request from my phone. But n3iwf returned the warning "Unimplemented IKE message type, exchange type: 2". However, the setting of ike exchange type of n3iwf is 34-37, which is shown in screenshot 1. The standard setting of ike exchanged type from offical website is shown in screenshot 2. The ike exchange type of an ipsec request should be in 0-5.

## Screenshots
![free5gc exchange type](https://user-images.githubusercontent.com/69676171/117433680-543cf600-af5e-11eb-93b3-fa318ba101f1.png)
screenshot 1
![ike exchange type standard](https://user-images.githubusercontent.com/69676171/117434033-beee3180-af5e-11eb-8a47-47d5256249ad.png)
screenshot 2

## Environment (please complete the following information):
 - free5GC Version:  v3.0.5
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: 1.14.4 linux/amd64
 - wireless route: TL-WVR1200G

### PCAP File
Here are some pcap files. Src.ip is my phone. Det.ip is ikeBindAddress of n3iwf.
[pcaps.zip](https://github.com/free5gc/free5gc/files/6440769/pcaps.zip)

**Comment by yt8956gh** [comment]
In the 3GPP standard TS 23.502, it mentions that the IKE part of N3IWF is based on RFC-7296 namely IKEv2.
Screenshot 2 looks like the constants defined by the IANA for IKE(v1) rather than IKEv2.

Please refer to [IKEV2IANA](https://www.iana.org/assignments/ikev2-parameters/ikev2-parameters.xhtml)
![image](https://user-images.githubusercontent.com/26867223/117577821-f6570c80-b11d-11eb-9196-396b9bc3f9dd.png)

**Comment by Silverbullet9** [comment]
\

**Comment by Silverbullet9** [comment]
You are right. N3IWF is based on ikev2. Thanks for correcting.

My phone is in default of sending ikev1 request. Is the version of ike request decided by the types of UE?

**Comment by dayal007** [comment]
@Silverbullet9 Can you please let me know how did you configured your phone to connect to the n3iwf?

**Comment by Silverbullet9** [comment]
> @Silverbullet9 Can you please let me know how did you configured your phone to connect to the n3iwf?

I used the IPsec VPN to connect to n3iwf. Please refer to the following link.

[](https://www.wipro.com/network-edge-providers/untrusted-non-3gpp-access-network-interworking-with-5g-core/)

**Comment by Silverbullet9** [comment]
> @Silverbullet9 Can you please let me know how did you configured your phone to connect to the n3iwf?

I used the IPsec VPN to connect to n3iwf. Please refer to the following link.

[https://www.wipro.com/network-edge-providers/untrusted-non-3gpp-access-network-interworking-with-5g-core/](url)

**Comment by Silverbullet9** [comment]
> @Silverbullet9 Can you please let me know how did you configured your phone to connect to the n3iwf?

I set the IPsec VPN on my phone. Please refer to the following link.

[https://www.wipro.com/network-edge-providers/untrusted-non-3gpp-access-network-interworking-with-5g-core/](https://www.wipro.com/network-edge-providers/untrusted-non-3gpp-access-network-interworking-with-5g-core/)
