### ISSUE TITLE
[Bugs] Empty Network instance value during SessionEstablishment request

### ISSUE THREAD

**Issue by diallama** [free5gc/free5gc#204]
pcap: [NetWorkInstanceValue_Empty.gz](https://github.com/free5gc/free5gc/files/6524343/NetWorkInstanceValue_Empty.gz)

I noticed that during the sessionablishmentRequest the network instance field of the first create PDR is empty. Is it possible to initialize it? Thanks in advance 

free5gc version: v3.0.5

![emptyInstance](https://user-images.githubusercontent.com/34651525/119180679-dfdf7800-ba70-11eb-83e8-75a46d619e0f.png)

**Comment by oommcclee** [comment]
Hi @diallama,
Do you mean the value of Network Instance is empty instead of "00"?
I didn't see the empty value in the PCAP file you uploaded.

**Comment by free5gc-org** [comment]
@diallama 

There is a PR(https://github.com/free5gc/smf/pull/24) to fix this issue.
Please update the SMF to this hash (949c94fda470ec9e6c8509e1230eea43b835aafc) and test again.
If the patch works, please close this issue.
Thanks.

**Comment by diallama** [comment]
Hi all,
Thank you for your answers, I was able to manage the problem on the UPF.
yes @oommcclee  I meant the field is empty.

thanks @oommcclee  @free5gc-org
