### ISSUE TITLE
[Feat] UE to connect to n3iwf

### ISSUE THREAD

**Issue by dayal007** [free5gc/free5gc#206]
## Issue Description
I want a UE which can connect to free5gc through n3iwf

### What's the version are you using
v3.0.5

### Is your feature request related to a problem? Please describe.
I tried using a UE from the other git repo but it has issues connecting to free5gc core.

### Describe the solution you'd like
I want a UE which can connect to free5gc

### Describe alternatives/workarounds you've considered
None

### If willing to resolve an issue by submitting Pull request, please consider the points below.

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by free5gc-org** [comment]
We are focusing on developing 5GC and we don't have any N3GPP UE.
Maybe you can try to cowork with
https://github.com/my5G/my5G-non3GPP-access
