### ISSUE TITLE
[Bugs]How do I decrypt TLS

### ISSUE THREAD

**Issue by lilongfei168** [free5gc/free5gc#207]
When testing, the following error appears?
cannot access '*sslkey.log': No such file or directory, and
in the testkeylog directory, all log files have a size of 0

**Comment by zakyi** [comment]
Have you solved this problem? I have the same problem

**Comment by jordan0210** [comment]
Sorry that we haven't encrypted by TLS for a couple of versions and we forgot to remove this from test.sh.
Please just ignore this error message. Thanks.
