### ISSUE TITLE
[Bugs]  The NAS layer of NGAP packet is encrypted. How not to encrypt it

### ISSUE THREAD

**Issue by lilongfei168** [free5gc/free5gc#208]
The NAS layer of NGAP packet is encrypted. How not to encrypt it

**Comment by anvi55** [comment]
use NULL ciphering at AMF and collect wireshark. Open it on windows will help you. It helped me

**Comment by free5gc-org** [comment]
@lilongfei168 

Set NEA0 in UE and AMF.
