### ISSUE TITLE
AMF Fails after activation of UE

### ISSUE THREAD

**Issue by zalfia** [free5gc/free5gc#209]
## Describe the bug
got a working free5gc docker-compose setup that I've adapted to K8s
used aligungr's UERANSIM
- invoking the gNB - OK
- when invoking the UE - errors appear on the gNB console and connection to AMF fails

I've opened a UERANSIM issue (https://github.com/aligungr/UERANSIM/issues/346) and aligungr stated that it's an AMF failure.

attached
CONSOLE output from: UERANSIM (gNB, UE)
CONSOLE output of all free5gc components
SNIFFER capture on UERANSIM site (showing the SCTP and RLS communication)
CONFIG files of all free5gc components

[RLS.SCTP.zip](https://github.com/free5gc/free5gc/files/6653784/RLS.SCTP.zip)
[UERANSIM console.zip](https://github.com/free5gc/free5gc/files/6653785/UERANSIM.console.zip)
[free5gc console.zip](https://github.com/free5gc/free5gc/files/6653786/free5gc.console.zip)

## To Reproduce
1. set free5gc config as attached
2. run gNB
3. run UE

## Environment (please complete the following information):
 - free5GC Version: don't know how to check this. I think the info appears in the console logs attached.
 - OS & Kernel:
      $ cat /etc/redhat-release 
      CentOS Linux release 8.3.2011

      $ uname -a
      Linux d50d-sa-app28 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zalfia** [comment]
attached configuration files of the setup
[free5gc config.zip](https://github.com/free5gc/free5gc/files/6653960/free5gc.config.zip)

**Comment by zalfia** [comment]
attached configuration files of the setup
[free5gc config.zip](https://github.com/free5gc/free5gc/files/6653967/free5gc.config.zip)

**Comment by zalfia** [comment]
having rectified the NSSF's nrfId the crashes stopped and the issue now is different

on UE side I'm seeing:

[nas] [debug] Sending PDU Session Establishment Request
[nas] [warning] Retransmitting PDU Session Establishment Request due to T3580 expiry
[nas] [warning] Retransmitting PDU Session Establishment Request due to T3580 expiry
[nas] [warning] Retransmitting PDU Session Establishment Request due to T3580 expiry
[nas] [warning] Retransmitting PDU Session Establishment Request due to T3580 expiry
[nas] [error] PDU Session Establishment procedure failure, no response from the network after 5 attempts
[nas] [debug] Aborting SM procedure for PTI[1], PSI[1]



in addition AMF seemd to constantly try to set up an SCTP session with 10.0.0.1 (the ipsec address in N3IWF configuration)

**Comment by free5gc-org** [comment]
@zalfia 

AMF can't reach NRF to search SMF because the URI of `nsiInformation.NrfId` is `http://nrf.free5gc.org:8000`, not `http://free5gc-nrf:8000`.
You should fix the URI of nrfId in nssfcfg.yaml.

**Comment by free5gc-org** [comment]
@zalfia 
If no more question, we'll close this issue.

**Comment by zalfia** [comment]
yes, can close.
thanks !
