### ISSUE TITLE
[Docs] Differentiate/Identify traffic flows from UEs

### ISSUE THREAD

**Issue by EmanueleGallone** [free5gc/free5gc#211]
## Documentation request

How to differentiate UE traffic outside the UPF, since the UPF NATs all the traffic being generated by the UEs.

Hi,
I need to differentiate the network traffic being generated by multiple UEs but when I capture the traffic through tcpdump, going to the DN, I can see that it's all natted, therefore unable to understand who-generated-what. Do you have any kind of suggestion on how to solve my issue?
My final goal is to map the generated traffic by the UEs to the emulated SIM card present within the HSS database; this way I can perform whitelist policing.

**Comment by oommcclee** [comment]
Hi @EmanueleGallone ,
NAT is optional in "Setup environment". You can try to skip that step, thank you.

**Comment by EmanueleGallone** [comment]
Thank you @oommcclee. Are you referring to https://github.com/free5gc/free5gc/wiki/Installation? more precisely on 
```
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o <dn_interface> -j MASQUERADE
sudo iptables -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1400
sudo systemctl stop ufw
```
Because I tried removing this part but then I lose the Internet connectivity (e.g. ping 8.8.8.8 from UE doesn't work anymore)

**Comment by oommcclee** [comment]
Oh! Sorry, i didn't explain clearly. I am refering to [https://github.com/free5gc/upf](url)
You can try to skip the "Using NAT for UE to access data network" part as the screenshot below.
![image](https://user-images.githubusercontent.com/45915078/126756989-5e575d1c-6d0a-4e71-9297-99f672160f33.png)

And if it still don't work, feel free to ask me again, thank you.

**Comment by free5gc-org** [comment]
@EmanueleGallone 
Remove the NAT setting, you will not access to the Internet because the UE's IP is private IP.
Traffic flows via NAT will have the same IP but different ports.
You can try to mapping the port to find out each flow.

**Comment by EmanueleGallone** [comment]
@free5gc-org thank you. I already tried that, the problem is that those ports are not static. Whenever a new TCP connection is requested, a new port will be used by the NAT, hence shifting the problem.

**Comment by oommcclee** [comment]
Hi @EmanueleGallone ,
we do not have a confirmed solution for your case, sorry. But you can try using a gateway instead of NAT to reach the internet.
Thank you.
