### ISSUE TITLE
[Feat] Handle extended value of ENUMERATED type in NGAP messages

### ISSUE THREAD

**Issue by YoheiKonno** [free5gc/free5gc#212]
## Issue Description
free5GC v3.0.5 discards NGAP messages that contain extended value of ENUMERATED type in it.
Some gNBs send such messages.

### What's the version are you using
free5GC v3.0.5

### Is your feature request related to a problem? Please describe.
It's a problem. UE cannot access via such gNBs. 

### Describe the solution you'd like
I've sent PR's:
- https://github.com/free5gc/aper/pull/1
- https://github.com/free5gc/ngap/pull/4

### Describe alternatives/workarounds you've considered
Nothing

### Additional context
Nothing

### If willing to resolve an issue by submitting Pull request, please consider the points below.

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by free5gc-org** [comment]
Thanks for PR!
