### ISSUE TITLE
[Bugs]AMF panics when receiving UeContextReleaseComplete continuously

### ISSUE THREAD

**Issue by RyuichiNamba-fj** [free5gc/free5gc#214]
## Describe the bug
AMF panics when it receives a UE Context Release Complete NGAP message while it has already received a UE Context Release Complete NGAP message related to the same UE.  
Some gNBs don't send UEContextReleaseComplete to UEContextReleaseCommand immediately and they might send InitialUEMessage before sending UEContextReleaseComplete.

## To Reproduce
1. RegistrationRequest ~ PDUsessionResourceSetupResponse
2. gNB -> 5GC   UEContextReleaseRequest
3. gNB <- 5GC   UEContextReleaseCommand
4. UE/gNB -> 5GC InitialUEmessage/ServiceRequest
5. UE/gNB <- 5GC  InitialContextSetupRequest/ServiceAccept
6. gNB -> 5GC InitialContextSetupResponse
7. gNB -> 5GC   UEContextReleaseRequest
8. gNB <- 5GC   UEContextReleaseCommand
9. gNB -> 5GC   UEContextReleaseComplete(Response to 3.UEContextReleaseCommand)
10. gNB -> 5GC   UEContextReleaseComplete(Response to 8.UEContextReleaseCommand)

#### AMF panic log
```
2021-06-30T19:54:51+09:00 [INFO][AMF][NGAP][127.0.0.1:9487] Handle UE Context Release Complete (/home/ubuntu/devel305/free5gc/NFs/amf/ngap/handler.go:413 github.com/free5gc/amf/ngap.HandleUEContextReleaseComplete)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10658bc]

goroutine 307 [running]:
github.com/free5gc/amf/ngap.HandleUEContextReleaseComplete(0xc00063a000, 0xc000d605c0)
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/handler.go:532 +0x32c
github.com/free5gc/amf/ngap.Dispatch(0x1c058a0, 0xc00057dd40, 0xc000d64000, 0x26, 0x2000)
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/dispatcher.go:103 +0x841
github.com/free5gc/amf/ngap/service.handleConnection(0xc00057dd40, 0x2000, 0x179e548, 0x179e550)
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/service/service.go:204 +0x700
created by github.com/free5gc/amf/ngap/service.listenAndServe
        /home/ubuntu/devel305/free5gc/NFs/amf/ngap/service/service.go:136 +0xc43
```

## Expected behavior
No panic.

## Root cause
`amfUe.ReleaseCause[ran.AnType]` is set to nil when AMF receives UEContextReleaseComplete.  
Therefore, AMF panics by nil pointer dereference of `amfUe.ReleaseCause[ran.AnType]` when receiving next UEContextReleaseComplete.

## Environment (please complete the following information):
 - free5GC Version: 3.0.5
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: go version go1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/34) for the fix.

**Comment by free5gc-org** [comment]
Thanks for PR!

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 
Could you provide fail and pass pcap? We want to check more details.

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
I attach fail and pass pcap.
In case of failure, AMF panics when receiving last UEcontextreleaseComplete.
[test214.zip](https://github.com/free5gc/free5gc/files/6775373/test214.zip)

**Comment by free5gc-org** [comment]
![issue214](https://user-images.githubusercontent.com/60502770/124726853-b99e6a80-df40-11eb-97e9-3b88d3fd9fe5.PNG)

@RyuichiNamba-fj 
There is no more UEContextReleaseRequest after ServiceRequest.
We wonder it is the RAN issue:
1. Send ServiceRequest before sending UEcontextreleaseComplete
2. Send UEcontextreleaseComplete twice when first issue happened.

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
Yes, I recognize it's a RAN issue. 
However, I consider this fix is necessary to deal with such semi-normal operation.

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 

Thanks for your response and your PR again.
