### ISSUE TITLE
[Bugs] AMF fails to decode Registration Request(GUTI) after restart

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#215]
## Describe the bug
If AMF restarts after establishment of 5G NAS security context with ue, AMF fails to decode Registration Request in NAS message container IE of Registration Request(GUTI) and stops Registration Procecure.

### Preparation
1. Change AMF config  
 see [Configuration File](#Configuration-File)
2. Change `TestGUTIRegistrationRequest` in `test/registration_test.go` as follows:
   ```go
	// New UE
	//	ue := test.NewRanUeContext("imsi-2089300007487", 1, security.AlgCiphering128NEA0, security.AlgIntegrity128NIA2)
	ue := test.NewRanUeContext("imsi-2089300007487", 1, security.AlgCiphering128NEA2, security.AlgIntegrity128NIA2)
   ```
   After sending ngap UE Context Release Complete, set sleep to restart AMF and connect AMF
   ```go
	// restart AMF (kill and restart AMF process from another window)
	fmt.Println("###")
	time.Sleep(30 * time.Second)

	// close Connection
	// RAN connect to AMF
	// send NGSetupRequest Msg
	// receive NGSetupResponse Msg
   ```
   Change Registration Request in Second Registration (Register with GUTI)  
   according to TS 24.501 v15.06 4.4.6 Protection of initial NAS signalling messages b) 1) 

   ``` go
	innerRegistrationRequest := nasTestpacket.GetRegistrationRequest(nasMessage.RegistrationType5GSInitialRegistration,
		GUTI5GS, nil, ue.GetUESecurityCapability(), ue.Get5GMMCapability(), nil, nil)
	// encrypt inner Registration Request
	m := nas.NewMessage()
	err = m.PlainNasDecode(&innerRegistrationRequest)
	require.Nil(t, err)
	payload, err := m.PlainNasEncode()
	require.Nil(t, err)
	err = security.NASEncrypt(ue.CipheringAlg, ue.KnasEnc, ue.ULCount.Get(), security.Bearer3GPP,
		security.DirectionUplink, payload)
	require.Nil(t, err)
	// add security header to outer Registration Request
	registrationRequest = nasTestpacket.GetRegistrationRequest(nasMessage.RegistrationType5GSInitialRegistration,
		GUTI5GS, nil, ueSecurityCapability, nil, payload, nil)
	// change ue.CipheringAlg to set security header, not to encrypt outer Registration Request
	ue.CipheringAlg = security.AlgCiphering128NEA0
	pdu, err = test.EncodeNasPduWithSecurity(ue, registrationRequest, nas.SecurityHeaderTypeIntegrityProtected, true, false)
	// restore ue.CipheringAlg
	ue.CipheringAlg = security.AlgCiphering128NEA2
	require.Nil(t, err)
	sendMsg, err = test.GetInitialUEMessage(ue.RanUeNgapId, pdu, "")
	require.Nil(t, err)
	_, err = conn.Write(sendMsg)
	require.Nil(t, err)
   ```

### Execution
1. Start NFs as separeted process and start test with "-args noinit" option.

2. Restart AMF after establishment of 5G NAS security context.

3. Send Registration Request with GUTI from UE.

## Expected behavior
Authenticate subscriber before processing the registration request.  
(TS 24.501 v15.06 4.4.4.3 Integrity checking of NAS signalling messages in the AMF)

## Environment (please complete the following information):
 - free5GC Version: v3.0.5
 - OS: Ubuntu 18.04.4 LTS
 - Kernel version: 5.0.0-23-generic
 - go version: 1.14.4

### Configuration File
amfcfg.yaml
```yaml
  security:  # NAS security parameters
    cipheringOrder: # the priority of ciphering algorithms
      - NEA2
```
### PCAP File
[free5gc_fails-to-decode-reg.pcap.gz](https://github.com/free5gc/free5gc/files/6753114/free5gc_fails-to-decode-reg.pcap.gz)

### Log File
```
2021-07-02T02:27:50Z [INFO][AMF][NGAP][127.0.0.1:9487] Handle Initial UE Message
2021-07-02T02:27:50Z [WARN][NAS][Security] Integrity NIA0 is emergency.
2021-07-02T02:27:50Z [WARN][AMF][NAS][AMF_UE_NGAP_ID:1] NAS MAC verification failed(received: 0x6f572c2e, expected: 0x00000000)
2021-07-02T02:27:50Z [INFO][AMF][GMM][AMF_UE_NGAP_ID:1] Handle Registration Request
2021-07-02T02:27:50Z [ERRO][AMF][GMM] NAS decode Fail: MsgType[31] doesn't exist in GMM Message
```

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/35) for the fix.

**Comment by free5gc-org** [comment]
@mariakagi 
Could you provide the successful pcap?

**Comment by mariakagi** [comment]
[free5gc_success_to_decode_reg.pcap.gz](https://github.com/free5gc/free5gc/files/6798709/free5gc_success_to_decode_reg.pcap.gz)

**Comment by free5gc-org** [comment]
Thanks for your contribution!
