### ISSUE TITLE
[Bugs] PFCP Session Establishment Request not handled by UPF

### ISSUE THREAD

**Issue by srac0** [free5gc/free5gc#218]
## Describe the bug
When registering many UE’s (with UERANSIM), some are not registered. This is not systematic, but this always happens after some UE’s rebooting. Unregistered UEs are due to unhandled PFCP Session Establishment Request. These requests can be seen in PCAP traces but not UPF’s log.

## To Reproduce
1. Start all NFs + gNB.
2. Start many UEs (e.g. 30).
3. Restart some UEs.

## Expected behavior
All UEs should be registered, and UPF should handle all PFCP Session Establishment Requests.

## Environment (please complete the following information):
 - free5GC Version: last version (b1172c3)
 - OS: Ubuntu server 20.04
 - Kernel version: 5.4.0-77-generic
 - go version: 1.14.4
 - UERANSIM version: v3.2.2

### PCAP File
[pcap.zip](https://github.com/free5gc/free5gc/files/6800188/pcap.zip)

### Log File

```log
UERANSIM v3.2.2
[info] UE switches to state [MM-DEREGISTERED/PLMN-SEARCH]
[debug] New signal detected for cell[1], total [1] cells in coverage
[info] Selected cell plmn[208/93] tac[1] category[SUITABLE]
[info] UE switches to state [MM-DEREGISTERED/PS]
[info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
[debug] Initial registration required due to [MM-DEREG-NORMAL-SERVICE]
[debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[debug] Sending Initial Registration
[info] UE switches to state [MM-REGISTER-INITIATED]
[debug] Sending RRC Setup Request
[info] RRC connection established
[info] UE switches to state [RRC-CONNECTED]
[info] UE switches to state [CM-CONNECTED]
[debug] Authentication Request received
[debug] Sending Authentication Failure due to SQN out of range
[debug] Authentication Request received
[debug] Security Mode Command received
[debug] Selected integrity[2] ciphering[0]
[debug] Registration accept received
[info] UE switches to state [MM-REGISTERED/NORMAL-SERVICE]
[debug] Sending Registration Complete
[info] Initial Registration is successful
[debug] Sending PDU Session Establishment Request
[debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[warning] Retransmitting PDU Session Establishment Request due to T3580 expiry
[debug] UAC access attempt is allowed for identity[0], category[MO_sig]
[warning] Retransmitting PDU Session Establishment Request due to T3580 expiry
[debug] UAC access attempt is allowed for identity[0], category[MO_sig]
```

[log.zip](https://github.com/free5gc/free5gc/files/6800190/log.zip)

**Comment by free5gc-org** [comment]
You can refer to this to modify:
https://forum.free5gc.org/t/how-many-number-of-ues-does-an-free5gc-support/144/12

**Comment by srac0** [comment]
Bigger buffers don’t fix the issue. They prevent UPF from crashing, but UEs are still not registering after some time.
Is a bigger buffer a good solution to scale up the UPF? Won't this create new issues?

**Comment by srac0** [comment]
Bigger buffers don’t fix the issue. They prevent UPF from crashing, but UEs are still not registering after some time.
Is a bigger buffer a good solution to scale up the UPF? Won't this create new issues?
