### ISSUE TITLE
[Bugs] Synch Failure with some SQNs

### ISSUE THREAD

**Issue by baleeiro17** [free5gc/free5gc#219]
## Describe the bug
The problem occurrs in authentication synchronization. The UE sends its SQN value as part of resynchronization process. But the UDM does not use these values in authentication request and results in authentication reject

## To Reproduce
1. Start all NFs + gNB
2. Start UE with SQN stored as 0b604a81eca8, f1e8a523a36d and 16f3b3f70fc2. See the 3GPP TS 35.208 version 15.0.0 Release 15 for more test data
3. Run registration
4. Get authentication reject after receive two authentication request request and authentication failure(synch failure)

## Expected behavior
In resynchronization process UDM should get valid SQN(48bits) from UE and update it to UDM.

## Root cause

In udm/producer/generate_auth_data.go. The variable SqnMAx limit the range of SQN accepted by UDM.

```
const (
	SqnMAx int64 = 0x7FFFFFFFFFF
)
```

## Environment :
 - free5GC Version: 3.0.5
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: go version go1.14.4 linux/amd64

### PCAP File
[free5gc_synch_failure.zip](https://github.com/free5gc/free5gc/files/6825706/free5gc_synch_failure.zip)

## Pull request
https://github.com/free5gc/udm/pull/5 for the fix.

**Comment by anvi55** [comment]
I added the above fix locally, still in my case its not working. Also SQN in authentication request after sync failure is in range

[sync_failure.zip](https://github.com/free5gc/free5gc/files/6877881/sync_failure.zip)

**Comment by baleeiro17** [comment]
Did you compile again the udm.go?

**Comment by anvi55** [comment]
i did make clean and make all

**Comment by baleeiro17** [comment]
Hi @anvi55, did you use an external emulator?  What the value of SQN send by UE to free5gc?

**Comment by anvi55** [comment]
I am using real UE oneplus8 mobile

**Comment by free5gc-org** [comment]
@baleeiro17 

Thanks for the PR!
