### ISSUE TITLE
[Bugs] MSIN format in the "supiORsuci" (IMSI-based SUPI) parameter

### ISSUE THREAD

**Issue by JasonKim14** [free5gc/free5gc#220]
## Describe the bug
Regarding the "supiORsuci" (IMSI-based SUPI) parameter in Nausf or so on SBI messages, its MSIN field should be encoded with BCD format. (For more details, please refer Section C.4 in TS33.501.) However, AMF encodes it as plain string format. 

## To Reproduce
1. Start NRF, NSSF, AUSF, PCF and UDM Simulators over my own Tester 1.
2. Start AMF, SMF and UPF NFs of free5GC S/W.
3. Start UE/gNB Simulator over my own Tester 2.
4. From the UE/gNB Simulator, start "Initial Registration" Test Case.
5. Monitor and check the N1/N2 and SBI messages through WireShark

## Expected behavior
MSIN field should be encoded with BCD format, not plain string format.

## Environment (please complete the following information):
 - free5GC Version: [e.g. v3.0.100]
 - OS: [e.g. Ubuntu 200.04 Server]
 - Kernel version: [e.g. 5.200.0-0-generic]
 - go version: [e.g. 1.10.0 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 1.1.0]

### PCAP File
[1-1_20210625144656_SBI-TestCase-Ph1.1.zip](https://github.com/free5gc/free5gc/files/6845049/1-1_20210625144656_SBI-TestCase-Ph1.1.zip)
- Log No 1138 : 5GMM-RegistrationRequest Message
- Log No 1163 : Nausf-UEAU-AuthenticateRequest Contents

## System architecture (Option)
![TestArchitecture](https://user-images.githubusercontent.com/87639393/126253232-c8727962-c289-4b5d-a610-08bf35841ae1.png)

**Comment by oommcclee** [comment]
Hi @JasonKim14,
First of all, thanks for your report, but i think there is something wrong with your issue.
In spec  TS 29.571 A.2,  it defines "supiORsuci" should be string (as screenshot below). TS 33.501 is not the specification that defines SBI msg.
![image](https://user-images.githubusercontent.com/45915078/132187034-98c965d8-4622-4d53-bda8-67799c45961f.png)

**Comment by JasonKim14** [comment]
Hi.

Thank you for the response.
But, my issue point was not "supiORsuci" parameter itself, which is defined as string" as your mention.
My point is a "MSIN" field within the "supiORsuci" parameter. (See the below image.)
The MSIN field is defined as BCD String Format in the TS24.501. (See the below image.)
But, your AMF encodes it "plain" String Format and sends to AUSF. This is what I pointed out.
This is explained well with examples in the TS33.501 (See the below image.)
This MSIN encoding applies equally regardless of Concealment Schemes (Null, ECIES Profile A or B).
I hope you understand my issue point correctly.


![detailedFormat_supiORsuci_Pattern](https://user-images.githubusercontent.com/87639393/132274734-bd9823a1-097d-4536-b475-24f0e250d7e2.png)
![TS24501_MSIN_Format](https://user-images.githubusercontent.com/87639393/132275505-2e7bd66e-06d9-4e34-a77b-04c34a820d09.png)
![TS33501_MSIN_for_Null_Scheme](https://user-images.githubusercontent.com/87639393/132275515-40bc24d8-411a-4506-850d-3582acd14655.png)

**Comment by JasonKim14** [comment]
p{margin-top:0;margin-bottom:0}
    


    Hi.
Thank you for the response.But, my issue point was not "supiORsuci" parameter itself, which is defined as string" as your mention.My point is a "MSIN" field within the "supiORsuci" parameter. (See the below image.)The MSIN field is defined as BCD String Format in the TS24.501. (See the below image.)But, your AMF encodes it "plain" String Format and sends to AUSF. This is what I pointed out.This is explained well with examples in the TS33.501 (See the below image.)This MSIN encoding applies equally regardless of Concealment Schemes (Null, ECIES Profile A or B).I hope you understand my issue point correctly.
BR,
Jason Kim...

--------- 원본 메일 ---------

    
        보낸사람: oommcclee ***@***.***>
        받는사람: free5gc/free5gc ***@***.***>
        
            참조: JasonKim14 ***@***.***>, Mention ***@***.***>
        
        날짜: 21.09.06 17:45 GMT +0900
        제목: Re: [free5gc/free5gc] [Bugs] MSIN format in the "supiORsuci" (IMSI-based SUPI) parameter (#220)
        
        
    
    
        
Hi @JasonKim14,
First of all, thanks for your report, but i think there is something wrong with your issue.
In spec  TS 29.571 A.2,  it defines "supiORsuci" should be string (as screenshot below). TS 33.501 is not the specification that defines SBI msg.

**Comment by oommcclee** [comment]
Hi @JasonKim14 , 
In my comprehension, the encode format as you mentioned is for NAS msg instead of SBI msg. You may refer to 29.503 Annex C (SUCI encoding). Please tell me if i'm still wrong, thanks again.

**Comment by JasonKim14** [comment]
p{margin-top:0;margin-bottom:0}
    


    
Hi.

Please understand SBI msg can include(encapsulate) NAS, NGAP or so on protocol messages.
Regarding the MSIN, which is a field of NAS protocol message, its encoding format is described well in the TS29.503 as your indication.
Also, please refer TS33.501 Annex C.4.

MSIN: 9876543210 (coded as 10 hexadecimal digits
using 5 octets packed BCD coding: 89, 67, 45, 23, 01)

So, when AMF receives MSIN from UE (through "5GS Mobile identity" IE), because it is encoded as BCD format, AMF converts it as plain String.

If MSIN is odd-numbered (ex "1234567"), then Filler (0b1111) is padded for the octet alignment (as like as 21 43 65 F7).

BR,

Jason Kim.
--------- 원본 메일 ---------

    
        보낸사람: oommcclee ***@***.***>
        받는사람: free5gc/free5gc ***@***.***>
        
            참조: JasonKim14 ***@***.***>, Mention ***@***.***>
        
        날짜: 21.09.09 16:03 GMT +0900
        제목: Re: [free5gc/free5gc] [Bugs] MSIN format in the "supiORsuci" (IMSI-based SUPI) parameter (#220)
        
        
    
    
        
Hi @JasonKim14 ,
In my comprehension, the encode format as you mentioned is for NAS msg instead of SBI msg. You may refer to 29.503 Annex C (SUCI encoding). Please tell me if i'm still wrong, thanks again.

**Comment by free5gc-org** [comment]
@JasonKim14 

> So, when AMF receives MSIN from UE (through "5GS Mobile identity" IE), because it is encoded as BCD format, AMF converts it as plain String.
> 
> If MSIN is odd-numbered (ex "1234567"), then Filler (0b1111) is padded for the octet alignment (as like as 21 43 65 F7).

You can see the string format for imsi is **imsi-[0-9]{5,15}**.
There is no possible to encode as 214365f7 (f is not inclued in [0-9]).
So, we don't think MSIN of imsi for SBI should be encoded as BCD format.

**Comment by JasonKim14** [comment]
p{margin-top:0;margin-bottom:0}
    


    Hi.

My point is NOT SUPI (imsi-[0-9]{5,15}) case. Of course, it plain string format.
My point is SUCI case, especially I meant "Scheme Output" portion of it.

I will explained again with Figures. Please see the attached PPTx File.
- First Slide: I depicted the MSIN format and the relationship with SUCI value,
* BCD Format: Odd-positioned digits and Even-positioned digits are reversed.
                      (Wireshark Log is already attached in the initial comment.)
- Second Slide: I described the total supiORsuci pattern,
the configuration for each cases, and 
relationship among { MSIN, Scheme Input, Scheme Output } values in the SUCI,

I hope you can catch My Issue Point.

BR,

Jason...
--------- 원본 메일 ---------

    
        보낸사람: free5GC ***@***.***>
        받는사람: free5gc/free5gc ***@***.***>
        
            참조: JasonKim14 ***@***.***>, Mention ***@***.***>
        
        날짜: 21.09.09 18:19 GMT +0900
        제목: Re: [free5gc/free5gc] [Bugs] MSIN format in the "supiORsuci" (IMSI-based SUPI) parameter (#220)
        
        
    
    
        
@JasonKim14

So, when AMF receives MSIN from UE (through "5GS Mobile identity" IE), because it is encoded as BCD format, AMF converts it as plain String.
If MSIN is odd-numbered (ex "1234567"), then Filler (0b1111) is padded for the octet alignment (as like as 21 43 65 F7).

You can see the string format for imsi is imsi-[0-9]{5,15}.
There is no possible to encode as 214365f7 (f is not inclued in [0-9]).
So, we don't think MSIN of imsi for SBI should be encoded as BCD format.

**Comment by free5gc-org** [comment]
@JasonKim14 

We didn't see any attached PPTx file. Please attach it via Github website (not via email).
Thanks.

**Comment by JasonKim14** [comment]
I attached PPTx.

[free5gc Issue 220.pptx](https://github.com/free5gc/free5gc/files/7142212/free5gc.Issue.220.pptx)

**Comment by free5gc-org** [comment]
@JasonKim14 

Thanks for clarification. We'll fix it.

**Comment by JasonKim14** [comment]
Let's read carefully the "NOTE".

![20210914_173526](https://user-images.githubusercontent.com/87639393/133224799-7532742c-50cf-489d-90e4-683b3b9a25e1.png)

**Comment by JasonKim14** [comment]
Hi. Again,

I read carefully again TS29.503 (UDM). [below the 1st image, yellow letters]
In NULL Scheme case, its Scheme Output is described definitely.
"Regardless of the format of Scheme Input (i.e., packed BCD or another), its output is decimal string."
But, in the TS33.501 [below the 2nd image], both Scheme Input & output are represented as the same as packed BCD Format.
Due to the example of TS33.501, I think I was confused.

However, in Protection Scheme "Profile A" and "Profile B" cases, they are different with "NULL" scheme case.
Scheme Input is formatted as BCD Format, and Scheme Output is encrypted from it. [below the 1st image, blue letters]
Therefore, when UDM decrypts Scheme Output and obtains MSIN value, UDM should consider the Format of Scheme Input.

![TS29503 Annex C](https://user-images.githubusercontent.com/87639393/133383601-34ca2458-1db9-4486-945a-76fbdc788d0d.png)

![TS33501 Annex C 4 2](https://user-images.githubusercontent.com/87639393/133383639-e329a5c0-ee71-427e-82f5-ea6b7197ae1b.png)

**Comment by oommcclee** [comment]
Hi @JasonKim14 , 
Very thank you for your patience, i will work on it.
