### ISSUE TITLE
[Feat] UPF selection according to connected gNB

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#226]
### What's the version are you using
v3.0.5

### Is your feature request related to a problem? Please describe.
SMF selects UPF by DNN and S-NSSAI, without considering the location of gNB.  
IF UE connects to gNB in Area1, SMF should select UPF in Area1.
![image](https://user-images.githubusercontent.com/72726417/127084556-77e23ed3-5cdb-4da8-9dc7-fd07e3b94f22.png)

#### Preparation
1. Locate AMF, SMF and UPF in each area.
2. Set same "locality" to amfcfg.yaml and smfcfg.yaml in each area.
#### Execution
1. SMF registers NF Profile with the locality
2. AMF selects SMF by Nnrf_NFDiscovery_Request including preferred-locality
![image](https://user-images.githubusercontent.com/72726417/127084583-fb278e2b-e982-4fbd-9d68-68f453127f6c.png)

### Pull Request
Pull Request for the feature.
- [free5gc](https://github.com/free5gc/free5gc/pull/225)
- [amf](https://github.com/free5gc/amf/pull/37)
- [smf](https://github.com/free5gc/smf/pull/25)

### Describe alternatives/workarounds you've considered
None

### Additional context
None

**Comment by s5uishida** [comment]
Hi @mariakagi 

I think it's very useful.

For example, is it possible to select UPF by adding the Cell_ID of gNB to the PFCP parameter instead of `locality`?

Best regards,

--Shigeru

**Comment by mariakagi** [comment]
Thank you @s5uishida.

At first, I considered the way to use "targetID" element in the CreateSMContext Request from AMF for SMF to know which gNB the UE connecting to.  
For UPF selection in SMF using "targetID", change smfcfg.yaml: 
* Adding node_id which represents a gNB ID under up_node conf which is for an AN node.​
* The configurations for the node topology are the same as current.​
```
  userplane_information:
    up_nodes:
      gNB1:
        type: AN
        node_id: 000102
...
links:
      - A: gNB1
        B: UPF1
...
```
 In the above figure if gNB3 is added to Area1, node_id and links should be updated in the idea of using "targetID". But using "locality" no need to update configuration.  
The idea of using "the Cell_ID of gNB" looks like  using "targetID", so I think using "locality" is better.

**Comment by free5gc-org** [comment]
@mariakagi 

Thanks for the PR!

**Comment by s5uishida** [comment]
Hi @mariakagi 

I also thought that `smfcfg.yaml` needed to be modified to support Cell_ID.

At this time, I made a suggestion with reference to the following Open5GS `smf.yaml`.

https://github.com/open5gs/open5gs/blob/main/configs/open5gs/smf.yaml.in
```
#  <SMF Selection - 5G Core only>
...
#  o UPF selection by CellID(e_cell_id: 28bit, nr_cell_id: 36bit)
#    (either single enb_id or multiple enb_ids, HEX representation)
...
```
I think `locality` is also very useful. 

Best regards,

--Shigeru
