### ISSUE TITLE
[Feat] Add Network Instance IE encoding Option In SMF

### ISSUE THREAD

**Issue by infinitydon** [free5gc/free5gc#228]
## Issue Description
Some UPF uses APN instead DNN as such PDR session request will not be possible.

### What's the version are you using
https://github.com/travelping/upg-vpp/issues/118#issuecomment-834344277 - This issue can shed more light on this, it is not specific to a free5gc version rather it is about having the feature

### Is your feature request related to a problem? Please describe.
This will make it easier to use other UPF with Free5gc control plane components.

### Describe the solution you'd like
Place a conditional flag in the UPF section of SMF configuration to use APN instead of DNN format for that particular UPF.
Maybe something like the snapshot below:

![image](https://user-images.githubusercontent.com/6318992/127970136-e2ae23c5-2cb6-49e6-b906-68a931828aae.png)

### Describe alternatives/workarounds you've considered
I don't think there is an existing workaround yet on Free5gc side

### Additional context
None

### If willing to resolve an issue by submitting Pull request, please consider the points below.

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance. _**- I don't have much programming background but I am open to suggestions on where this can be changed in the code**_
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by free5gc-org** [comment]
@infinitydon 

We think the APN should be encoded as DNN.
Maybe you can ask the 3rd-party upf to support DNN encoding.
Thanks.

**Comment by infinitydon** [comment]
Ok.. thanks
