### ISSUE TITLE
[ AMF ] NGAP Error: No RanUe Context[AmfUeNgapID: 1]

### ISSUE THREAD

**Issue by endrigoshi** [free5gc/free5gc#23]
Hi @all,

I was testing the free5gc deployment by running the Deregestration test multiple times in a row.
I noticed that the second run finishes ok (Test PASS) but with the following error from AMF:

`ERRO[2020-04-23T18:49:02+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:475 free5gc/src/amf/amf_ngap/ngap_handler.HandleUEContextReleaseComplete() No RanUe Context[AmfUeNgapID: 1]              AMF=NGAP`

I run only the test multiple times. The NFs are running only once throughout the entire test.

While going through the code, I noticed that in **func** `HandleInitialContextSetupResponse` and in  **func** `HandleUEContextReleaseComplete`, you use two different functions to obtain the `ranUe` object:

`HandleInitialContextSetupResponse` - `ranUe := ran.RanUeFindByRanUeNgapID(rANUENGAPID.Value)`

`HandleUEContextReleaseComplete` - `ranUe := amf_context.AMF_Self().RanUeFindByAmfUeNgapID(aMFUENGAPID.Value)  ---> This one throws the error.`

I also tried replacing the above call in class `HandleUEContextReleaseComplete` with `ranUe := ran.RanUeFindByRanUeNgapID(rANUENGAPID.Value)`. In that case the error was not occuring.

Why are two different functions used in this case? And why is the Test throwing this error when run for the second time?

Thank you!

**Comment by free5gc-org** [comment]
Hi,
For the first question, why are two different function used in this case?
in general, AMF should use amfUeNgapID to find the UE context,
but in our implementation, use ranUeNgapID or amfUeNgapID is ok to find the same UE context.
So this is not the real reason for the error.

And why is the Test throwing this error when run for the second time?
Because we hard code some data in our test, e.g amfUeNgapID of UE. If you run the test for second time without restarting the CN, the state of CN will mismatch the test data, and the test will fail.

**Comment by endrigoshi** [comment]
Hi again!

Thank you for the detailed answer. 

However, since you said that both `amfUeNgapID` and `ranUeNgapID` can be used, what is then the reason that `amf_context.AMF_Self().RanUeFindByAmfUeNgapID(aMFUENGAPID.Value)` returns `nil` and `ran.RanUeFindByRanUeNgapID(rANUENGAPID.Value)` doesn't?

One more thing that I would like to add is that the Test does PASS, but I can see the following Error in the AMF side. And I would also like to note that the Registration procedure works with no Error. The error is seen when the functions performing Deregistration are called.

**Comment by free5gc-org** [comment]
Hi,
First, our AMF assign amfUeNgapID from 1, 2, 3, ... (increase 1 every time)
As mentioned earlier, our test just use fake data in the test, so the fake ue context always has amfUeNgapID = 1, that means it won't update amfUeNgapID no matter how the core network assign amfUeNgapID
you can check the test code here:
https://github.com/free5gc/free5gc/blob/ecb48718062ecfd3f53715219ba1746d147b62ca/src/test/registration_test.go#L117
on the other hand, ranUeNgapID is assigned by fake ran, so AMF can update UE's ranUeNgapID correctly, then use ranUeNgapID to find the UE, but fake ran didn't update UE's amfUeNgapID which is assigned by AMF.

If you don't restart CN and run the test for second time, AMF will assign this ue with amfUeNgapID = 2 (amfUeNgapID 1 has assigned in the previous test), but remember that in the test, the fake ue always has amfUeNgapID = 1, so AMF cannot find the UE by amfUeNgapID.

In fact, if you trace our test code, you will find that we just utilize "go test" command to run our test, and we did not check the output of the core network. The "pass test" message is reported by go testing package, not by us. So the correct way to check the test pass or not is to see if there is any error log in the terminal. Just ignore "pass" message reported by go testing package

**Comment by endrigoshi** [comment]
Thank you! The explanation was really helpful!
I’m closing the issue now.
