### ISSUE TITLE
FYI: Sample configuration - Select nearby UPF according to the connected gNodeB

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#231]
Hi @free5gc-org @mariakagi @aligungr and everyone

I wrote a very simple configuration that uses free5GC and UERANSIM to select the nearby UPF according to the connected gNodeB.

https://github.com/s5uishida/free5gc_ueransim_nearby_upf_sample_config

This feature was added to free5GC last month, so this time I compared the configurations for Open5GS and free5GC simply.

Best regards,

--Shigeru

**Comment by free5gc-org** [comment]
@s5uishida 

We shared your link on our wiki page.
Thanks.
