### ISSUE TITLE
[Bugs] UPF send multiple buffered packet by 1 GTP packet when paging

### ISSUE THREAD

**Issue by matsumu-y** [free5gc/free5gc#237]
## Describe the bug
Multiple packets bufferd during the UE is in CM-IDLE state are packed in GTP-U and sent as one packet to the UE after the UE goes in CM-CONNECTED state.

## To Reproduce
1. Add a sleep to `TestPaging()` in `registration_test.go` in order to wait UPF buffers downlink packets to the UE.   
   ```go
   // Registration -> Pdu Session Establishment -> AN Release due to UE Idle -> Send downlink data
   func TestPaging(t *testing.T) {
        :
       // UE is CM-IDLE now
       time.Sleep(60 * time.Second)	★Add
   ```
2. Run `test.sh -o TestPaging` and wait the following log is output.  
   ```
   [INFO][AMF][NGAP][127.0.0.1:9487] Release UE[imsi-2089300007487] Context : N2 Connection Release
   ```
3. Ping to the UE from UPFns.  
   ```
   # ip netns exec UPFns ping -c 5 60.60.0.1
   ```
4. Check the pcap after the test is finished.

## Expected behavior
Each packet in the buffer is sent to the UE as one GTP-U packet separately.

## Environment (please complete the following information):
- free5GC Version: 3.0.5
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/upf/pull/37) for the fix.

**Comment by free5gc-org** [comment]
Thanks for the PR!
