### ISSUE TITLE
[Bugs] The sm-context is not modified when a service request (mo-data) is received

### ISSUE THREAD

**Issue by matsumu-y** [free5gc/free5gc#238]
## Describe the bug
AMF does not send a modify sm-context request to SMF when a Service Request (mo-data) is received.

## To Reproduce
1. Make a UE in CM-IDLE state.
2. Send a Initial UE Message, Service Request (mo-data) from the UE
```go
   func TestPaging(t *testing.T) {
              :
        // send NAS Service Request
        pdu = nasTestpacket.GetServiceRequest(nasMessage.ServiceTypeData)     ★
        pdu, err = test.EncodeNasPduWithSecurity(ue, pdu, nas.SecurityHeaderTypeIntegrityProtectedAndCiphered, true, false)
   ```
3. Check the pcap. You can't see the following packet;  
   `POST /nsmf-pdusession/v1/sm-contexts/urn:uuid:.../modify`

## Expected behavior
AMF send a modify sm-context request to SMF when a Service Request (mo-data) is received, and the UE becomes to be able to send uplink data traffic afterwards.

## Environment (please complete the following information):
- free5GC Version: 3.0.5
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/38) for the fix.

**Comment by free5gc-org** [comment]
Merged. Thanks for the PR!
