### ISSUE TITLE
Issue with N3IWF

### ISSUE THREAD

**Issue by ameet-17** [free5gc/free5gc#24]
When I run ./run.sh to start all the NFs of 5GC, My N3IWF is failing to start and throwing these errors. How do I resolve this issue?
ERRO[2020-04-23T23:57:20Z]/src/n3iwf/n3iwf_ngap/n3iwf_sctp/n3iwf_sctp.go:58 free5gc/src/n3iwf/n3iwf_ngap/n3iwf_sctp.(*SCTPSession).Connect() [SCTP] DialSCTP(): connection refused         N3IWF=NGAP
ERRO[2020-04-23T23:57:20Z]/src/n3iwf/n3iwf_ngap/n3iwf_sctp/n3iwf_sctp.go:193 free5gc/src/n3iwf/n3iwf_ngap/n3iwf_sctp.SetupSCTPConnection() [SCTP] Failed to connect given AMF.           N3IWF=NGAP
ERRO[2020-04-23T23:57:20Z]/src/n3iwf/n3iwf_data_relay/relay.go:278 free5gc/src/n3iwf/n3iwf_data_relay.SetupNASTCPServer() Listen TCP address failed: listen tcp 10.0.0.1:20000: bind: cannot assign requested address  N3IWF=relay
ERRO[2020-04-23T23:57:20Z]/src/n3iwf/n3iwf_service/n3iwf_init.go:115 free5gc/src/n3iwf/n3iwf_service.(*N3IWF).Start() Listen N1 control plane traffic failed: Listen failed  N3IWF=init
ERRO[2020-04-23T23:57:20Z]/src/n3iwf/n3iwf_data_relay/relay.go:63 free5gc/src/n3iwf/n3iwf_data_relay.ListenN1UPTraffic() Error setting listen socket on 10.0.0.1: listen ip4:gre 10.0.0.1: bind: cannot assign requested address  N3IWF=relay
ERRO[2020-04-23T23:57:20Z]/src/n3iwf/n3iwf_service/n3iwf_init.go:121 free5gc/src/n3iwf/n3iwf_service.(*N3IWF).Start() Listen N1 user plane traffic failed: ListenPacket failed  N3IWF=init

**Comment by free5gc-org** [comment]
hi,

This seems to be cause by AMF not init complete yet. Please reference to Troubleshooting.

https://github.com/free5gc/free5gc#trouble-shooting

**Comment by ameet-17** [comment]
Thanks!
