### ISSUE TITLE
support H2C (http2 clear text without TLS)

### ISSUE THREAD

**Issue by Dorian1982** [free5gc/free5gc#25]
In the current version, the http2 with TLS works fine. But actually in the real 5G core network environment, usually the H2C is used, as the PDI or some other requirements. Please add this support and make it optional in the conf and the next release. 

Thanks,
Daolin

**Comment by Dorian1982** [comment]
I changed some related code today, and it seemed that H2C works when I run TestRegistration. If you like, I can share my changes to your group, and you can continue to add the parameter in conf to control this feature.

**Comment by free5gc-org** [comment]
That sounds great!
How about give us a pull request and if there are something need to be added into the config, we could work together to complete this feature. 😃

**Comment by Dorian1982** [comment]
Hi,

I didn't know how to use pull request. I attached the src and lib folder including all my changes (I didn't changed any other source code and config files). You can compare to 
your base version.

[src.zip](https://github.com/free5gc/free5gc/files/4534438/src.zip)
[lib.zip](https://github.com/free5gc/free5gc/files/4534440/lib.zip)

**Comment by free5gc-org** [comment]
Hi,

We have patch an H2C version in v3.0.2.

Thanks for your inspiration. 👍
