### ISSUE TITLE
[Bugs] http2: server connection error from .....: connection error: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by minziran** [free5gc/free5gc#252]
I met the following errors while running free5gc-docker-compose:
containers running order is like :

`Attaching to upfb, upf2, upf1, mongodb, nrf, webui, ausf, pcf, nssf, udr, smf, amf, udm, n3iwf

nrf              | 2021/09/12 23:18:05 http2: server connection error from 10.100.200.9:46048: connection error: PROTOCOL_ERROR

`

**Comment by nathalie21005** [comment]
Hello, @noormohammedli , @minziran 

You was able to solve this issue? thanks

**Comment by eduardocalfaia** [comment]
Hi guys,
I have the same error, any clue?
Thanks

**Comment by danielh1204** [comment]
Hi @minziran, 
I suggest you run free5gc-compose v3.3.0
https://github.com/free5gc/free5gc-compose

**Comment by ianchen0119** [comment]
Hi @minziran 
This issue would be closed due to there being no interaction for 2 weeks.
If you have any further questions,
please let me know, and I will re-open this issue.

Thanks a lot.
