### ISSUE TITLE
[Bugs] SMF crashes when connecting a UE using a different DNN from "internet"

### ISSUE THREAD

**Issue by inkms** [free5gc/free5gc#253]
## Description
When the UE requests a PDU session, the SMF crashes with an error "runtime error: invalid memory address or nil pointer dereference"

## To Reproduce
1. Use Free5GC v3.0.5
2. Change config of the amf, smf, upf and ue to change the dnn "internet" to "default". Example configs working and another version with the minimal changes to make it fail is attached in the zip below.
3. Populate the database with an entry for the UE, specifying the dnn default
3. Using UERANSIM, with the provided configurations, try to connect

## Expected behavior
The UE establishes a PDU session, or the core networks returns an understandable error

## Screenshots
UE provisioned in DB:
![image](https://user-images.githubusercontent.com/44236455/133121618-40fded17-14f8-433e-960c-e405f4f8c66f.png)

## Environment:
 - free5GC Version: v3.0.5
 - Kernel in control plane: 4.15.0-154-generic
 - Kernel in user plane: 5.4.0-84-generic
 - OS in control plane: Ubuntu 18.04.5 LTS
 - OS in user plane: Ubuntu 20.04.1 LTS
 - C compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 - Go version: go version go1.14.4 linux/amd64

### Configuration Files
[config.zip](https://github.com/free5gc/free5gc/files/7155799/config.zip)

### Log File
SMF logs:
[smf.txt](https://github.com/free5gc/free5gc/files/7155873/smf.txt)

**Comment by anvi55** [comment]
even with latest free5gc version also facing same issue

**Comment by iamelisahi** [comment]
Hi, you can consider updating to the latest version of free5gc, which is v3.3.0. This update may assist you in resolving the problem.
