### ISSUE TITLE
[Docs] Update Wiki - Installation

### ISSUE THREAD

**Issue by dmat93** [free5gc/free5gc#254]
Please update the wiki installation section. On the official web-site (https://www.free5gc.org/installations/stage-3-free5gc-install/) there is the procedure for installation using kernel 5.4.x instead of 5.0.23.

Thnks

**Comment by free5gc-org** [comment]
@dmat93 

Both kernel versions are ok to install free5gc.
You can find the comment as below:

`Please make sure your kernel version is 5.0.0-23-generic or newer than 5.4.0.`
