### ISSUE TITLE
Error while create BDTPolicy

### ISSUE THREAD

**Issue by ishanshahnio** [free5gc/free5gc#255]
Hello,

I have installed latest version of free5gc on ubuntu system and trying to create BDT Policy but fails.

--------terminal output-----
root@zs22:~# curl -X 'POST' -H 'Accept: application/json' -H 'Content-Type: application/json' -i 'http://127.0.0.7:8000/npcf-bdtpolicycontrol/v1/bdtpolicies' --data '{"aspId": "123456","desTimeInt": {"startTime": "2021-08-12 16:09:25","stopTime": "2021-08-12 16:10:27"},"numOfUes": 5,"volPerUe": {"duration": 60,"totalVolume": 50,"downlinkVolume": 30,"uplinkVolume": 20},"suppFeat": "123456"}'
HTTP/1.1 500 Internal Server Error
Date: Mon, 20 Sep 2021 20:22:11 GMT
Content-Length: 0

root@zs22:~# 
root@zs22:~# 
root@zs22:~# curl -X 'POST' -H 'Accept: application/json' -H 'Content-Type: application/json' -i 'http://127.0.0.7:8000/npcf-bdtpolicycontrol/v1/bdtpolicies' --data '{"bdtReqData": [{"aspId": "123456","desTimeInt": {"startTime": "2021-08-12 16:09:25","stopTime": "2021-08-12 16:10:27"},"numOfUes": 5,"volPerUe": {"duration": 60,"totalVolume": 50,"downlinkVolume": 30,"uplinkVolume": 20},"suppFeat": "123456"}]}'
HTTP/1.1 500 Internal Server Error
Date: Mon, 20 Sep 2021 20:22:21 GMT
Content-Length: 0

root@zs22:~# 
root@zs22:~# curl -X 'POST' -H 'Accept: application/json' -H 'Content-Type: application/json' -i 'http://127.0.0.7:8000/npcf-bdtpolicycontrol/v1/bdtpolicies' --data '{"bdtReqData": {"aspId": "123456","desTimeInt": {"startTime": "2021-08-12 16:09:25","stopTime": "2021-08-12 16:10:27"},"numOfUes": 5,"volPerUe": {"duration": 60,"totalVolume": 50,"downlinkVolume": 30,"uplinkVolume": 20},"suppFeat": "123456"}}'
HTTP/1.1 500 Internal Server Error
Date: Mon, 20 Sep 2021 20:22:29 GMT
Content-Length: 0

root@zs22:~# 

----------------------------LOGS----------------------------------------

2021-09-20T14:22:29-06:00 [INFO][PCF][Bdtpolicy] Handle CreateBDTPolicyContext
2021-09-20T14:22:29-06:00 [INFO][UDR][DRepo] Handle PolicyDataBdtDataGet
2021-09-20T14:22:29-06:00 [INFO][UDR][GIN] | 200 |       127.0.0.1 | GET     | /nudr-dr/v1/policy-data/bdt-data |

2021/09/20 14:22:29 [Recovery] 2021/09/20 - 14:22:29 panic recovered:
interface conversion: interface {} is **models.BdtReqData, not *models.BdtReqData
/usr/local/go/src/runtime/iface.go:260 (0x409b71)
	panicdottypeE: panic(&TypeAssertionError{iface, have, want, ""})
/root/free5gc/NFs/pcf/producer/bdtpolicy.go:200 (0xe02059)
	createBDTPolicyContextProcedure: response.BdtReqData = deepcopy.Copy(&request).(*models.BdtReqData)
/root/free5gc/NFs/pcf/producer/bdtpolicy.go:151 (0xe00e66)
	HandleCreateBDTPolicyContextRequest: header, response, problemDetails := createBDTPolicyContextProcedure(&requestMsg)
/root/free5gc/NFs/pcf/bdtpolicy/api_bdt_policies_collection_routers.go:56 (0xe2404e)
	HTTPCreateBDTPolicy: rsp := producer.HandleCreateBDTPolicyContextRequest(req)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x99faaa)
	(*Context).Next: c.handlers[c.index](c)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x9b1e7f)
	RecoveryWithWriter.func1: c.Next()
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x99faaa)
	(*Context).Next: c.handlers[c.index](c)
/root/go/pkg/mod/github.com/free5gc/logger_util@v1.0.0/logger_util.go:65 (0x9b3a2d)
	ginToLogrus.func1: c.Next()
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x99faaa)
	(*Context).Next: c.handlers[c.index](c)
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x9a9555)
	(*Engine).handleHTTPRequest: c.Next()
/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x9a8c6c)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/root/go/pkg/mod/golang.org/x/net@v0.0.0-20201209123823-ac852fbbde11/http2/h2c/h2c.go:98 (0xa0f049)
	h2cHandler.ServeHTTP: s.Handler.ServeHTTP(w, r)
/usr/local/go/src/net/http/server.go:2807 (0x789e52)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1895 (0x7857cb)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x463420)
	goexit: BYTE	$0x90	// NOP

2021-09-20T14:22:29-06:00 [INFO][PCF][GIN] | 500 |       127.0.0.1 | POST    | /npcf-bdtpolicycontrol/v1/bdtpolicies |

-------------------------------------------------------------------------

kindly help me here.

**Comment by ishanVshah** [comment]
Any update ?

**Comment by ishanshahnio** [comment]
2021/09/20 14:22:29 [Recovery] 2021/09/20 - 14:22:29 panic recovered:
interface conversion: interface {} is **models.BdtReqData, not *models.BdtReqData
/usr/local/go/src/runtime/iface.go:260 (0x409b71)
panicdottypeE: panic(&TypeAssertionError{iface, have, want, ""})
/root/free5gc/NFs/pcf/producer/bdtpolicy.go:200 (0xe02059)
createBDTPolicyContextProcedure: response.BdtReqData = deepcopy.Copy(&request).(*models.BdtReqData)
/root/free5gc/NFs/pcf/producer/bdtpolicy.go:151 (0xe00e66)


kindly provide the solution of deepcopy. what is the issue ?

**Comment by free5gc-org** [comment]
already fixed in https://github.com/free5gc/pcf/pull/4
