### ISSUE TITLE
Issue with DNN if the number of the DNN more than 9 

### ISSUE THREAD

**Issue by noormohammedli** [free5gc/free5gc#256]
Hello Sir, 

I tried the new free5gc version. 
I did as in the video and I have issues with the SMF in the demo the UE does not connect to the server as in the images below. 
For the first UE, the server did not respond and the second UE was not subscribed.
I added both of them through the web counsel.  
Could you please help me to solve the problem?

<img width="976" alt="Screenshot 2021-10-03 at 3 26 42 pm" src="https://user-images.githubusercontent.com/34620715/135772463-a20c82da-0a3f-4c8e-9134-038abada287f.png">

<img width="995" alt="Screenshot 2021-10-03 at 3 26 59 pm" src="https://user-images.githubusercontent.com/34620715/135772465-bab737dd-5eea-4c15-877d-6c568bdefd9c.png">

<img width="954" alt="Screenshot 2021-10-03 at 3 27 17 pm" src="https://user-images.githubusercontent.com/34620715/135772466-09776499-b35a-4a60-a4e7-cb2b2833e065.png">

<img width="962" alt="Screenshot 2021-10-03 at 3 33 16 pm" src="https://user-images.githubusercontent.com/34620715/135772467-9726ba32-0880-41c6-abc6-647ec3116bf1.png">

<img width="990" alt="Screenshot 2021-10-03 at 3 33 27 pm" src="https://user-images.githubusercontent.com/34620715/135772469-7fb484cb-649a-4ed0-a3f7-4911df83dec7.png">

Thanks, 
Noor Mohammedali.

**Comment by jordan0210** [comment]
Hi @noormohammedli,

This problem is not due to the number of DNNs. It's because you run too many UEs at the same time. 
You can modify the buffer value in `./free5gc/NFs/upf/lib/utlt/src/utlt_buff.c` as below to fix this problem.
![image](https://user-images.githubusercontent.com/46536142/141980357-a2952391-66de-49a0-b63b-e7d08d1a7e27.png)

**Comment by noormohammedli** [comment]
Hello @jordan0210, 

Thanks for your reply. 

I will check that thanks. 

I run one UE connected to 9 UPF on different tunnels 

Regards, 
Noor

**Comment by anvi55** [comment]
can anyone please share how to do configuration to support multiple DNN at smf and upf

**Comment by Leon777-coder** [comment]
> can anyone please share how to do configuration to support multiple DNN at smf and upf

Hello:
There are detailed setup tutorials on our website:Please take a look: 

https://www.youtube.com/watch?v=AEMrjKRWarw

https://free5gc.org/guide/

Regards,
Leon
