### ISSUE TITLE
[Service Reject received with cause [UE_IDENTITY_CANNOT_BE_DERIVED_FROM_NETWORK]

### ISSUE THREAD

**Issue by ayoub-tl** [free5gc/free5gc#258]
Hi,

Please I am having issues running ueransim with Free5gc. Any ideas what could be the issue?
when trying service request
./nr-cli UERANSIM-gnb-208-93-1 -e "ue-release 1"

nr_ue | [2021-10-03 19:13:02.995] [rrc] [debug] Sending RRC Setup Request
nr_ue | [2021-10-03 19:13:02.995] [nas] [info] UE switches to state [MM-SERVICE-REQUEST-INITIATED]
nr_ue | [2021-10-03 19:13:02.995] [rrc] [info] RRC connection established
nr_ue | [2021-10-03 19:13:02.995] [rrc] [info] UE switches to state [RRC-CONNECTED]
nr_ue | [2021-10-03 19:13:02.995] [nas] [info] UE switches to state [CM-CONNECTED]
nr_ue | [2021-10-03 19:13:03.008] [nas] [warning] Not protected Service Reject message received
nr_ue | [2021-10-03 19:13:03.008] [nas] [error] Service Reject received with cause [UE_IDENTITY_CANNOT_BE_DERIVED_FROM_NETWORK]
nr_ue | [2021-10-03 19:13:03.009] [nas] [info] UE switches to state [5U2-NOT-UPDATED]
nr_ue | [2021-10-03 19:13:03.009] [nas] [info] UE switches to state [MM-DEREGISTERED/PS]
nr_ue | [2021-10-03 19:13:03.009] [nas] [debug] Initial registration required due to [DUE-TO-SERVICE_REJECT]
nr_ue | [2021-10-03 19:13:03.009] [nas] [info] UE switches to state [MM-DEREGISTERED/NORMAL-SERVICE]
nr_ue | [2021-10-03 19:13:03.009] [nas] [debug] Sending Initial Registration
nr_ue | [2021-10-03 19:13:03.009] [nas] [info] UE switches to state [MM-REGISTER-INITIATED]
nr_ue | [2021-10-03 19:13:03.013] [rrc] [debug] RRC Release received

gnb

nr_gnb | [2021-10-03 19:13:15.078] [ngap] [warning] Sending an error indication with cause: radio-network/unknown-local-UE-NGAP-ID
nr_gnb | [2021-10-03 19:13:21.077] [ngap] [warning] Sending an error indication with cause: radio-network/unknown-local-UE-NGAP-ID
nr_gnb | [2021-10-03 19:13:27.077] [ngap] [warning] Sending an error indication with cause: radio-network/unknown-local-UE-NGAP-ID

@namssob pointed out that 
According to 38.413 8.6.1.2
When the NG-RAN node has received from the radio interface the 5G-S-TMSI IE, it shall include it in the INITIAL UE MESSAGE messagev
the pcap file
![image](https://user-images.githubusercontent.com/68382823/136016799-c46fc1a4-49f5-4edc-8341-4df5c9aef6f1.png)
expected:
![image](https://user-images.githubusercontent.com/68382823/136016820-82e19866-95b1-4ea4-b4db-ef7fc4ad9c20.png)

**Comment by free5gc-org** [comment]
@ayoub-tl 

Yes, as @namssob said, RAN should include 5G-TMSI IE in NGAP InitialUEMessage after initial registration is completed.
If there is 5G-TMSI in NGAP InitialUEMessage, AMF will use it to find the existed UE context.
Otherwise, AMF will treat it as the new UE context.

**Comment by free5gc-org** [comment]
@ayoub-tl 

Yes, this is a bug in UERANSIM.
We tested free5gc with real RAN, and the RAN will include 5G-TMSI in NGAP InitialUEMessage except for Initial registration.

**Comment by ayoub-tl** [comment]
this wasnt a free5gc error
