### ISSUE TITLE
UL CL issue

### ISSUE THREAD

**Issue by Dorian1982** [free5gc/free5gc#26]
I changed the destination IP from 60.60.0.101 to 60.60.0.103 in the TestRegistration function, but still send to the anchor UPF1. Probably the SDF issue in the ko module?

**Comment by free5gc-org** [comment]
Can you provide the pcap file and config file so that we can check the SDF filter and the config whom is generated from?

Thanks a lot.

**Comment by Dorian1982** [comment]
Hi,

I attached the pcap files. I used the default config file, and didn't change any parameters. I just changed the line 267 from 60.60.0.101 to 60.60.0.103 in the registration_test.go

I think you can reproduce this issue in your side easily.

[pcap.zip](https://github.com/free5gc/free5gc/files/4534429/pcap.zip)

**Comment by abousselmi** [comment]
@Dorian1982 did you tried to update your `uerouting.yaml` config file. It needs to be updated since it also sets the `DestinationIP` to `60.60.0.101`

**Comment by Dorian1982** [comment]
@abousselmi Sorry, I didn't change uerouting.yaml. I found that there are two DestinationIP in this file (60.60.0.101 and 60.60.0.103), so in my opinion, I don't need to change anything. Did you mean that I need to change both of DestinationIP  to 60.60.0.101?

**Comment by abousselmi** [comment]
No I meant that if you update the test configuration you need also to update the ue routing.

**Comment by Dorian1982** [comment]
@abousselmi As my previous post, I used the default config file, and didn't change any parameters. I just changed the line 267 from 60.60.0.101 to 60.60.0.103 in the registration_test.go

**Comment by free5gc-org** [comment]
Hi @Dorian1982 ,

We have release v3.0.3 and fix the bug from SMF. Can you try to test it again? 

Thanks a lot!
