### ISSUE TITLE
Connect to the interent (UERANSIM can't access to the internet)

### ISSUE THREAD

**Issue by noormohammedli** [free5gc/free5gc#260]
Hello sir, 
I followed your instructions based on the video "https://www.youtube.com/watch?v=AEMrjKRWarw". 

<img width="976" alt="Screenshot 2021-10-06 at 2 15 26 pm" src="https://user-images.githubusercontent.com/34620715/136373655-96c0309e-5396-490d-973e-46908e925c19.png">

![image](https://user-images.githubusercontent.com/34620715/136373704-d7780f64-a2e8-47ca-8ca2-ca4f2586fa3f.png)

Ping successful with 8.8.8.8 as in the image. Also, I can ping google with his IP address (142.250.187.206), but it failed when I try to ping the real-word internet with (google.com) or download a document for example. 

Could you please help me with this? 

I have a problem with the NAT 

sudo sysctl -w net.ipv4.ip_forward=1

sudo iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE

sudo systemctl stop ufw

sudo iptables -I FORWARD 1 -j ACCEPT

I used NAT this command as well >>  " iptables -t nat -A POSTROUTING -s 60.61.0.0/24 ! -o upfgtp -j MASQUERADE "  the UPF but the ping still not working. 

<img width="705" alt="Screenshot 2021-10-13 at 2 38 56 pm" src="https://user-images.githubusercontent.com/34620715/137144317-fe6d036c-3aa6-4e8e-830e-c82977916a1d.png">

<img width="547" alt="Screenshot 2021-10-13 at 2 40 31 pm" src="https://user-images.githubusercontent.com/34620715/137144354-1e2d0156-aa0e-40cc-abfd-f684f236d2a0.png">

Thanks
Noor

**Comment by JiMMyMatrix** [comment]
Hi,
Could you open resolv.conf with sudo vim:
```
sudo vim /etc/resolv.conf
```
Ensure there is google.com nameserver:
```
nameserver 8.8.8.8
```
And restart:
```
sudo systemctl restart systemd-resolved.service
```
If you have any problem, please contact us.
