### ISSUE TITLE
[Feat]relay some pcap packages 

### ISSUE THREAD

**Issue by hxx-98** [free5gc/free5gc#262]
now i want to relay NAGP packages, how can i do this? are there some tools or commands
thx~

**Comment by ianchen0119** [comment]
This GitHub issue is duplicated with Forum discussion [Relay NGAP packsges](https://forum.free5gc.org/t/relay-ngap-packsges/1149).
If you have more questions, please let me know, and I will re-open this issue.

Thanks.
