### ISSUE TITLE
Failed to listen: listen udp, panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by noormohammedli** [free5gc/free5gc#266]
Hello Sir, 
How could I connect 3 upf (different VM upf1, upf2 and upf3 ) with different SMF (smf1, smf2 and smf3) on VM for the core? 
When I try to add new upf (upf4 with IP: 172.16.4.105 ) with (smf4), I get an error as in the image below. 

" Failed to listen: listen udp 172.16.4.105:8805: bind: cannot assign requested address
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb43884]
"

<img width="1309" alt="Screenshot 2021-10-17 at 7 34 35 pm" src="https://user-images.githubusercontent.com/34620715/137644792-64e782cd-d41a-440f-bd0a-7979437a80e2.png">

I checked the configurations files all fine but i don't know why i get this error.

Could you please help?

Regards, 
Noor

**Comment by linpoyi** [comment]
Hi @noormohammedli,
here's a quick guide [Environment setup of multiple SMF, DNN, and UPF](https://www.youtube.com/watch?v=AEMrjKRWarw). For the question about slice limitation, there's no slice limitation in our code.

BRs,
Linpoyi
