### ISSUE TITLE
Log files: clear the log file 

### ISSUE THREAD

**Issue by noormohammedli** [free5gc/free5gc#271]
Hello Sir, 

How can I clear the log files without having an issue or error? 
I have VM with 5Gcore with 10 GB and after one week of work and testing the free5gc, I get no space available in my VM. 
I tried to clear the log file or create the file again but i still have the same issue. 

<img width="797" alt="Screenshot 2021-10-25 at 10 43 53 pm" src="https://user-images.githubusercontent.com/34620715/138775798-0d23b77b-3bdb-4879-9d3a-beb2d456a6b0.png">

Thanks, 
Noor

**Comment by yashihh** [comment]
Hi @noormohammedli,
Please check your vm's disk with `$ df -hl`. 
Check if the main space you are using is full.
If it's full, maybe you can delete some large and redundant files.

Hope it's useful to you.
Br yashihh

**Comment by brianchennn** [comment]
@noormohammedli 
check log directory's usage by `$ du -hs log` in `free5gc/`
And execute `$ rm -r log/{log name}` to clean the specific log.
