### ISSUE TITLE
[Bugs] AUSF does not handle when res* is received in uppercase format

### ISSUE THREAD

**Issue by valMary** [free5gc/free5gc#274]
**We will advise people to follow the issue template set, otherwise the issue might be disregarded.**
**free5GC mainly uses GitHub for issue tracking. Information regarding to general questions or technical support. It will be highly considered if forward to the [forum](https://forum.free5gc.org).**
**free5GC will appreciate it, if people can refer to [TS](https://github.com/free5gc/free5gc/wiki/Trouble_Shooting) and [forum](https://forum.free5gc.org) prior to bug reporting**

## Describe the bug
AUSF does not handle when res* is received in uppercase format

## To Reproduce
Need an AMF that will send res* in uppercase format

## Expected behavior
From 3gpp (TS 29.509) res* is in format '[A-Fa-f0-9]{32}' so uppercase should be accepted

##Correction
In function Auth5gAkaComfirmRequestProcedure of the file ue_authentication.go 
changing the condition if strings.Compare(updateConfirmationData.ResStar, ausfCurrentContext.XresStar) == 0 
to
if strings.Compare(strings.ToLower(updateConfirmationData.ResStar), strings.ToLower(ausfCurrentContext.XresStar)) == 0 

Solves this issue

**Comment by tim-ywliu** [comment]
Fixed in https://github.com/free5gc/ausf/pull/15
