### ISSUE TITLE
free5gc with k8s, ueransim-user can't access to the internet

### ISSUE THREAD

**Issue by liyinxin** [free5gc/free5gc#276]
## Describe the bug
I deploy the free5gc:v3.0.6 with k8s 1.22.3, and my ueransim-user can have ip address(which is 60.60.0.1), but when I ping www.baidu.com -I uesimtun0, I find the ue can't access to the internet. I use docker-compose to deploy the free5gc:v3.0.6 the ue can access to the internet. I do this in the upf:
**iptables -I FORWARD 1 -j ACCEPT
iptables -t nat -A POSTROUTING -s 60.60.0.0/16 ! -o upfgtp -j MASQUERADE
iptables -t nat -A POSTROUTING -s 60.61.0.0/16 ! -o upfgtp -j MASQUERADE
iptables -t nat -A POSTROUTING -s 60.62.0.0/16 ! -o upfgtp -j MASQUERADE**

and i compare with the docker-compose deploy free5gc with k8s deploy free5gc,the UPF's iptables rules are different:

docker-compose:UPF's iptbales rules:
****Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination**         

**Chain INPUT (policy ACCEPT)
target     prot opt source               destination**         

**Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER_OUTPUT  all  --  anywhere             127.0.0.11**          

**Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER_POSTROUTING  all  --  anywhere             127.0.0.11          
MASQUERADE  all  --  60-60-0-0.rev.home.ne.jp/16  anywhere            
MASQUERADE  all  --  60-61-0-0.rev.home.ne.jp/16  anywhere            
MASQUERADE  all  --  60.62.0.0/16         anywhere**            

**Chain DOCKER_OUTPUT (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:53 to:127.0.0.11:43101
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:53 to:127.0.0.11:46333**

**Chain DOCKER_POSTROUTING (1 references)
target     prot opt source               destination         
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:43101 to::53
SNAT       udp  --  127.0.0.11           anywhere             udp spt:46333 to::53****

k8s:UPF's iptables rules:
**Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination**         

**Chain INPUT (policy ACCEPT)
target     prot opt source               destination**         

**Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER_OUTPUT  all  --  anywhere             127.0.0.11**          

**Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER_POSTROUTING  all  --  anywhere             127.0.0.11          
MASQUERADE  all  --  60-60-0-0.rev.home.ne.jp/16  anywhere            
MASQUERADE  all  --  60-61-0-0.rev.home.ne.jp/16  anywhere            
MASQUERADE  all  --  60.62.0.0/16         anywhere**            

**Chain DOCKER_OUTPUT (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:53 to:127.0.0.11:43101
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:53 to:127.0.0.11:46333**

**Chain DOCKER_POSTROUTING (1 references)
target     prot opt source               destination         
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:43101 to::53
SNAT       udp  --  127.0.0.11           anywhere             udp spt:46333 to::53**

## Expected behavior
I want my ue can access to the internet

## Environment (please complete the following information):
 - free5GC Version: [e.g. v3.0.6]
 - OS: [e.g. Ubuntu 18.04 Server]
 - Kernel version: [e.g. 5.200.0-0-generic]
 - go version: [e.g. 1.10.0 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 1.1.0]

**Comment by ayoub-tl** [comment]
any luck with this ?

**Comment by JiMMyMatrix** [comment]
Hello,
Please follow [freeg5c k8s guide](https://free5gc.org/blog/IntroduceKubernetesAndDeploymentfree5GConKubernetesWithHelm/main/) and try to ping internet again.
If you have any problem, we are willing to answer.
