### ISSUE TITLE
[Bugs] NSSAI (SD) in the NG setup doesnt match the one used in the Registration request

### ISSUE THREAD

**Issue by ayoub-tl** [free5gc/free5gc#278]
Hi i am having some trouble ,
the UE and gnb are configured with sst 01 and SSD 010203 which can be seen in the ng setup request and response
But when it come ti registration request/response or pdu seestion establishment it uses a different SD
can someone help and confirm if it is in fact a problem on the software, or I am missing something ?
![image](https://user-images.githubusercontent.com/68382823/141102138-5eed3655-6982-4a98-9379-fd4a14bdb776.png)
![image](https://user-images.githubusercontent.com/68382823/141102153-771effce-fe52-4be4-a327-d3bed2595a93.png)

![image](https://user-images.githubusercontent.com/68382823/141102177-3350ef92-95da-422e-86e7-670d697635f4.png)
![image](https://user-images.githubusercontent.com/68382823/141102721-5a53e70b-7f32-4317-8bd9-dec1d36c3c9c.png)
![image](https://user-images.githubusercontent.com/68382823/141102199-833767f6-d2a2-4a9d-aaa6-6ac85089f69a.png)

**Comment by noormohammedli** [comment]
Hi, 
I checked it, I have the same problem.

**Comment by free5gc-org** [comment]
@ayoub-tl @noormohammedli 

Actually, 66051 is decimal, and it equals to heximal 000102.
This is not a bug.

**Comment by ayoub-tl** [comment]
hello @free5gc-org , i just want to ask, is this a normal behavior ?

**Comment by free5gc-org** [comment]
@ayoub-tl 

This is decoded by wireshark. You may report the issue to the wireshark develop team.
