### ISSUE TITLE
Nnrf_AccessToken Service API

### ISSUE THREAD

**Issue by JoanaConde** [free5gc/free5gc#28]
Hi,

I'm currently testing AccessToken Service API and upon receiving the AccessTokenRsp that contains the access token (jwt), I must verify it by using the same key that was used to sign it. But how do I get this key? Or how do I determine the key that was employed for the signature?

By analyzing your code I found that this key is []byte("NRF").
Another question that I have is: for using signing method HS256 your key (byte array) length shouldn't be >= 256 bits (32 bytes)?

Once again, thank you for your time. 
Any doubt please inform me, so I can attempt to better explain it.

**Comment by wilson30139** [comment]
Hello @JoanaConde. For the first question, the NRF private key can be obtained in the `cert/nrf.key`. For the second question, it is normal for the key length to be greater than 256 bits when using the signing method HS256.

You can see it in the Figure 1. **`BlockSize()` must be able to accept any amount of data, but it may operate more efficiently if all writes are a multiple of the block size**.
 
![NRF 8](https://github.com/free5gc/free5gc/assets/43327415/ca97968f-29d0-4038-9898-1d6f6f659b5a)
Figure 1. New Function

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/oauth2-implementation-in-free5gc/2660/2
