### ISSUE TITLE
[Bugs] The UPF logging function is not thread-safe, so the contents of another log may be overwritten during logging

### ISSUE THREAD

**Issue by shugo-h** [free5gc/free5gc#280]
## Describe the bug
The logging function of UPF, `UTLT_LogPrint()` is not thread-safe.
The log message buffer is possible to be overwritten by another thread during a thread is running it.

As a result, unexpected log message may be shown.

## To Reproduce
It is not easy to explain the way to reproduce it intentionally.
So many PDU session establishment / release messages will cause it.

## Expected behavior
`UTLT_LogPrint()` is thread-safe, and each log message is not overwritten by other threads.

## Environment (please complete the following information):
- free5GC Version: 3.0.5
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Additional context
I have sent a [PR](https://github.com/free5gc/upf/pull/43).

**Comment by free5gc-org** [comment]
Thanks for the PR!
