### ISSUE TITLE
[Bugs] Old PFCP Session left in SMF and UPF

### ISSUE THREAD

**Issue by RyuichiNamba-fj** [free5gc/free5gc#281]
## Describe the bug
If PDU Session is established without releasing previous PFCP session, PDUSessionResourceSetupRequest message is sent when sending DL data with the IP address of the previously allocated UE.

## To Reproduce
1. Initial Registration ~ establish PDUSession
2. AN Release(UE Context Release Request ~ UE Context Release Complete)
3. Initial Registration ~ establish PDUSession(same UE as 1.)
4. Sending DL data with the IP address of the previously(1.) allocated UE

## Expected behavior
Release old PFCP Session and not sending PDUSessionResourceSetupRequest message.

## Environment (please complete the following information):
- free5GC Version: 3.0.6  
- OS: Ubuntu 18.04  
- Kernel version: 5.0.0-23-generic  
- go version go1.14.4 linux/amd64  

### PCAP File
[Bugs_OldPFCPSessionLeft.zip](https://github.com/free5gc/free5gc/files/7544948/Bugs_OldPFCPSessionLeft.zip)

## Additional context
I have sent a [PR](https://github.com/free5gc/smf/pull/33).

**Comment by free5gc-org** [comment]
The merged https://github.com/free5gc/smf/pull/34 solved the same issue.
Anyway, thanks for the PR.
