### ISSUE TITLE
[Feat] PCF selection according to locality

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#284]
### What's the version are you using
v3.0.6

### Is your feature request related to a problem? Please describe.
No.
This feature is related to [issue/226](https://github.com/free5gc/free5gc/issues/226).

#### Preparation
1. Locate AMF, SMF, PCF and UPF in each area.
2. Set same "locality" to amfcfg.yaml, smfcfg.yaml and pcfcfg.yaml in each area.
#### Execution
1. PCF registers NF Profile with the locality
2. AMF and SMF select PCF by Nnrf_NFDiscovery_Request including preferred-locality

### Pull Request
Pull Request for the feature.
- [free5gc](https://github.com/free5gc/free5gc/pull/283)
- [amf](https://github.com/free5gc/amf/pull/51)
- [smf](https://github.com/free5gc/smf/pull/35)
- [pcf](https://github.com/free5gc/pcf/pull/3)

### Describe alternatives/workarounds you've considered
None

### Additional context
None

### If willing to resolve an issue by submitting Pull request, please consider the points below.

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by free5gc-org** [comment]
Thanks for the PRs! All are already merged.
