### ISSUE TITLE
webUI always show loading

### ISSUE THREAD

**Issue by liyinxin** [free5gc/free5gc#288]
## Describe the bug
when i want to Subscribers a new UE in the webUI, i find this problem
![Screenshot from 2021-11-29 10-59-50](https://user-images.githubusercontent.com/27272076/143803123-f3cb7467-d2a3-4396-aa2d-9b7c8ccb537a.png)

## Expected behavior
It can susscessfuly subcribe a UE information

## Screenshots

![Screenshot from 2021-11-29 10-59-50](https://user-images.githubusercontent.com/27272076/143803144-2ff34511-89b6-4fc9-b297-91380d9630a0.png)

## Environment (please complete the following information):
 - free5GC Version: [e.g. v3.0.6]
 - OS: [e.g. Ubuntu 18.04 Server]
 - Kernel version: [e.g. 5.0.0-23-generic]
 - go version: [e.g. 1.17.3 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 7.5.0]

### Configuration File
Provide the configuration file here.

If not clear of what to do, the `config` folder can be zip and upload it here.

### PCAP File
Dump the packet and provide the pcap file here.

If not clear of what to do, this command can be used `sudo tcpdump -i any -w free5gc.pcap` prior to running bug reproduce. Then upload the pcap file `free5gc.pcap`.

### Log File
Provide the program log file here.

If not clear of what to do, copy the printed log on the screen and upload it here.

## System architecture (Option)
Please provide the draft architecture, including the scenario, use cases, installation environment(bare metal, vm, container, or k8s), etc.

## Walkthrough (Option)
free5GC will be interested on the research or finding in brief.

## Additional context
It will be appreciated if other context can be added here.

**Comment by free5gc-org** [comment]
@liyinxin 

Please follow https://github.com/free5gc/free5gc/wiki/Installation#d-install-webconsole to build webconsole:
```
cd ~/free5gc
make webconsole
```
and https://github.com/free5gc/free5gc/wiki/New-Subscriber-via-webconsole to run:
```
$ cd ~/free5gc/webconsole
$ ./bin/webconsole
```
