### ISSUE TITLE
any document to explain deployment by k8s?

### ISSUE THREAD

**Issue by zhujq** [free5gc/free5gc#29]
Hi u,
       First thank u for the great projict of free5GC。
        I have readed carefully on free5gmano/kube5gnfvo,and I have setup a k8s cluster for test,I have deploy the mano in k8s and tested,I can visit the 30888 port to access mano。Is  there a detail document to explain how to deploy 5GC via k8s? I plan to deploy amf、ausf、smf、nrf、pcf、udm、udr、upf，free5gmano/free5gmano tell the docker image，but I don‘t know how the docker image created，and the requirement （such as net and netcard）of  image to run，I think I can deploy this by mano，the example is deploy a nssi，Is there a example to show use mano to deploy amf(or other F)?
        Thx。

**Comment by cewuandy** [comment]
Hello,
I'm free5gmano member.
You can refer to [free5gmano#getting-started](https://github.com/free5gmano/free5gmano#getting-started) and step by step, you can get a free5gc NSSI.
We have build free5gc docker image and uploaded on docker hub.
[free5gmano#docker-repository](https://github.com/free5gmano/free5gmano#docker-repository)
If you want to build free5gc docker image by yourself. Please refer this link.
[free5gmano-docker](https://github.com/free5gmano/free5gmano/tree/master/docker)

If you have any other questions for deploying free5gc on k8s, you can also comment issue on [free5gmano](https://github.com/free5gmano/free5gmano) or [kube5gnfvo](https://github.com/free5gmano/kube5gnfvo).
Thanks.
