### ISSUE TITLE
Does Free5gc support Different Registration Mode?

### ISSUE THREAD

**Issue by wheam2002** [free5gc/free5gc#292]
In 3.0.5 release note, there is a bug fix about mobility and periodicUpdate Registration, so i wonder if free5gc supports different registration mode?
If supported, how do i test them? 

Thank You! 
![vdRLzZC](https://user-images.githubusercontent.com/71239799/145752540-081b0d56-bccf-4a83-af29-cd42b2a10a6b.png)

**Comment by free5gc-org** [comment]
Yes, it supports.
You can test with real 5G SA phone and RAN, or license commercial simulation tools (ex: Spirent Landslide) to test.
