### ISSUE TITLE
[Question] How do I test 5QI parameters in free5gc, thanks

### ISSUE THREAD

**Issue by chung0623** [free5gc/free5gc#295]
**We will advise people to follow the issue template set, otherwise the issue might be disregarded.**
**free5GC mainly uses GitHub for issue tracking. Information regarding to general questions or technical support. It will be highly considered if forward to the [forum](https://forum.free5gc.org).**
**free5GC will appreciate it, if people can refer to [TS](https://github.com/free5gc/free5gc/wiki/Trouble_Shooting) and [forum](https://forum.free5gc.org) prior to bug reporting**

## Describe the bug
How can I test 5QI parameters in free5gc

**Comment by free5gc-org** [comment]
Now free5GC doesn't support QoS and 5QI.

**Comment by ianchen0119** [comment]
Hi @chung0623 

free5GC supports QoS and 5QI allocation (control plane only) since v3.3.0.
You can try our latest version when you feel free, thanks.

**Comment by mickwubs97** [comment]
> free5GC supports QoS and 5QI allocation (control plane only) since v3.3.0.
> You can try our latest version when you feel free, thanks.

Hello, do you have any documentation about how to configure 5QI?

**Comment by brianchennn** [comment]
@mickwubs97 You can use webconsole to configure 5QI, see https://free5gc.org/guide/Webconsole/Create-Subscriber-via-webconsole/

**Comment by mickwubs97** [comment]
Is there any way for free5gc to support QoS flow? Do I need to modify the UPF?
