### ISSUE TITLE
[Feat] NAS Security with NIA3 and NEA3

### ISSUE THREAD

**Issue by wHangsHuGe** [free5gc/free5gc#299]
## Issue Description
NAS package in your repository has supported NIA3 and NEA3, which version is v1.0.4, but the free5gc uses v1.0.0, when will update it?

### What's the version are you using
Version 3.0.6

### Is your feature request related to a problem? Please describe.
NAS Security:

### Describe the solution you'd like
Just change the NAS package version in "free5gc/NFs/amf/go.mod", and rebuild amf, will it cause error?

**Comment by free5gc-org** [comment]
@wHangsHuGe 

It is fixed on v3.1.0.
Please get v3.1.0 and try.
