### ISSUE TITLE
How can i Test the Bandwidth between the UE (ueransim0) interface and the 5G Core 

### ISSUE THREAD

**Issue by noormohammedli** [free5gc/free5gc#305]
Hello 

I am working on the 5G core and it is connected to the UE and RAN. 
ping for me I want to use iperf to send TCP and UDP packets. 
>> the UPF in VM1
>> 5G core in VM2 
>> UERANSIM in VM3 

ping -I uesimtun0 google.com -c3 >>> work but with IP address for google, NAT does not work for me. 
ping -I uesimtun0 UPF -c3 >> instead of UPF i but the IP address of the UPF .. its work for me. 

Know, I want to use UPF as a server and uesimtun0 as a client and send UDP packets using iperf3 or iperf. 

I check when the firewall is on and oof and I have the same issues. 
 
If there is another tool that I could use to generate traffic from uesimtun0 to UPF. 

I use  iperf as the flowing but i get broken pips. 

<img width="637" alt="Screenshot 2022-02-01 at 4 55 07 pm" src="https://user-images.githubusercontent.com/34620715/152014815-c186825f-9a3e-493c-a117-2e0f62816982.png">

 
<img width="646" alt="Screenshot 2022-02-01 at 4 56 01 pm" src="https://user-images.githubusercontent.com/34620715/152014827-f81f5ca9-8a8b-405f-800e-fa4531d3a0d0.png">

If you have an idea, please let me know 
Regards, 
Noor

**Comment by wilson30139** [comment]
Hello, I suggest you install the iperf3 package and try it out. I attach the reference URL below for your reference. In addition, I have set up environment. I provide my example for you. As described below:

VM
| VM Number  | VM Name | IP Address | OS | Memory | HDD |
| :-------------: | :---------: | :---------: | :--: | :-------: | :---: |
| VM1 | free5GC-CP | 192.168.56.101 | Ubuntu 20.04.6 | 2GB | 10GB |
| VM2 | UERANSIM | 192.168.56.102 | Ubuntu 20.04.6 | 2GB | 10GB |
| VM3 | UPF | 192.168.56.103 | Ubuntu 20.04.6 | 2GB | 10GB |

<br/>
Other Software Version Information:<br/>
VirtualBox Version: 7.0.8<br/>
Go Version: 1.17.8<br/>
free5GC Version: 3.3.0<br/>
gtp5g Version: 0.8.2<br/>
UERANSIM Version: 3.2.6

<br/>
<br/>

I see UPF as the server and uesimtun0 as the client. I send packets using iperf3. The figure shown as follows:
![image](https://github.com/free5gc/free5gc/assets/43327415/06649dcf-5cc1-458c-86d8-f2718abac2cd)
![image](https://github.com/free5gc/free5gc/assets/43327415/13b31d53-172e-49ec-9bdd-94b7da787701)

Reference URL: [https://blog.gtwang.org/useful-tools/iperf-network-bandwidth-testing-tool-tutorial](https://blog.gtwang.org/useful-tools/iperf-network-bandwidth-testing-tool-tutorial/)
