### ISSUE TITLE
GTP Traffic Generation

### ISSUE THREAD

**Issue by RKR-11** [free5gc/free5gc#306]
Hi,

I want to test the upf and know the gtp traffic generation.
Iam in a search of GTP traffic generator to send gtp packets to upf.
Please suggest me that how can i generate the gtp traffic or a tool that generate the gtp traffic.

**Comment by noormohammedli** [comment]
Hello, 

I want a tool to generate traffic from the UE tunnel to the UPF. 
If you have an idea, please let me know. 

Thanks.

**Comment by calee0219** [comment]
Hi,
In my experience, I use [MoonGen](https://github.com/emmericp/MoonGen) to generate GTP traffic.
The process is first I run test script with tcpdump to get a single GTP packet, then put the packet into MoonGen program to duplicate these GTP packet to make traffic.

**Comment by RKR-11** [comment]
Hi calee,

I'm not familiar with LUA Language to write the test script, if possible can you help me by providing the script file.

Thanks.

**Comment by calee0219** [comment]
You don't need to write any Lua language.
First of all, run the test script that free5GC provide, in the meantime, turn on tcpdump and get the packet. If you just need GTP packet, filter it. After that, just used MoonGen CLI to generate the traffic.

BTW, if you want to modify the GTP packet information, you may use python scapy library to modify the packet before using MoonGen.

**Comment by infinitydon** [comment]
@calee0219 - Please can the same procedure be used if the UPF is running on a separate system?

**Comment by pirog-spb** [comment]
Hi,

If you don't expect high performance from traffic generator, you just can use scapy. But you need to be familiar with python.
If the question is still relevant, I can share some examples.

**Comment by zzylol** [comment]
> You don't need to write any Lua language. First of all, run the test script that free5GC provide, in the meantime, turn on tcpdump and get the packet. If you just need GTP packet, filter it. After that, just used MoonGen CLI to generate the traffic.
> 
> BTW, if you want to modify the GTP packet information, you may use python scapy library to modify the packet before using MoonGen.

May I ask how to use tcpdump to get GTP packets from free5GC?
