### ISSUE TITLE
[Bugs]

### ISSUE THREAD

**Issue by LaurentThomas** [free5gc/free5gc#307]
The binary free5gc-upfd is not produced in the right directory
I use ubuntu 20.04, up to date (apt upgrade) and cmake -GNinja ..

My patch:

> 
```
> > diff --git a/CMakeLists.txt b/CMakeLists.txt
> > index 6522fe2..91aa49c 100644
> > --- a/CMakeLists.txt
> > +++ b/CMakeLists.txt
> > @@ -37,7 +37,7 @@ add_compile_options(-Wall -Werror -Wno-address-of-packed-member)
> >  set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -g3 -O0")
> >  
> >  # Submodules
> > -add_subdirectory(src)
> > +add_subdirectory(src ${BUILD_BIN_DIR})
> >  add_subdirectory(updk)
> >  add_subdirectory(lib/pfcp)
> >  add_subdirectory(lib/pfcp/test)
> > diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
> > index 6dfbcf2..0414aa5 100644
> > --- a/src/CMakeLists.txt
> > +++ b/src/CMakeLists.txt
> > @@ -9,12 +9,14 @@ file(GLOB SRC_FILES
> >      "*.c"
> >      "n4/*.c"
> >      "up/*.c"
> > -)
> > +    )
> > +  
> >  add_executable(${PROJECT_NAME} ${SRC_FILES})
> > +message( "${BUILD_BIN_DIR}/free5gc-upfd")
> >  set_target_properties(
> >      ${PROJECT_NAME}
> >      PROPERTIES
> > -        OUTPUT_NAME "${BUILD_BIN_DIR}/free5gc-upfd"
> > +        RUNTIME_OUTPUT_NAME "free5gc-upfd"
> >          SUFFIX ""
> >  )
```

 

**We will advise people to follow the issue template set, otherwise the issue might be disregarded.**
**free5GC mainly uses GitHub for issue tracking. Information regarding to general questions or technical support. It will be highly considered if forward to the [forum](https://forum.free5gc.org).**
**free5GC will appreciate it, if people can refer to [TS](https://github.com/free5gc/free5gc/wiki/Trouble_Shooting) and [forum](https://forum.free5gc.org) prior to bug reporting**

## To Reproduce
1. Change config '...'
2. Code patch '...' (You can fork the project and give us the patch diff you have modified)
3. Run command '...'
4. Dump packet '...'

## Screenshots
If applicable, add screenshots to help explain the problem.

## Environment (please complete the following information):
 - free5GC Version: [e.g. v3.0.100]
 - OS: [e.g. Ubuntu 200.04 Server]
 - Kernel version: [e.g. 5.200.0-0-generic]
 - go version: [e.g. 1.10.0 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 1.1.0]

### Configuration File
Provide the configuration file here.

If not clear of what to do, the `config` folder can be zip and upload it here.

### PCAP File
Dump the packet and provide the pcap file here.

If not clear of what to do, this command can be used `sudo tcpdump -i any -w free5gc.pcap` prior to running bug reproduce. Then upload the pcap file `free5gc.pcap`.

### Log File
Provide the program log file here.

If not clear of what to do, copy the printed log on the screen and upload it here.

## System architecture (Option)
Please provide the draft architecture, including the scenario, use cases, installation environment(bare metal, vm, container, or k8s), etc.

## Walkthrough (Option)
free5GC will be interested on the research or finding in brief.

## Additional context
It will be appreciated if other context can be added here.

**Comment by Jerry0666** [comment]
Hello! Now we switch to go-upf, c-upf is no longer maintained.
