### ISSUE TITLE
Enabling the complete PCF's Npcf_PolicyAuthorization service to support edge deployments

### ISSUE THREAD

**Issue by sudhir-intc** [free5gc/free5gc#31]
This a request to enable the complete policy authorization service(Npcf_PolicyAuthorization) from the PCF. This will help in having free5GC enablement for  edge deployments by supporting the traffic steering feature as described in the whitepaper : https://www.etsi.org/images/files/ETSIWhitePapers/etsi_wp28_mec_in_5G_FINAL.pdf.

Npcf_PolicyAuthorization enables multiple features like traffic steering, sponsored data connectivity, application-specific QoS, etc.. The request here is to support traffic steering.

To support traffic steering in Npcf_PolicyAuthorization the following minimum is required.

1.  Identifying an applicaiton : Provided through a combination of DNN[AppSessionContextReqData.Dnn] and optionally S-NSSAI[AppSessionContextReqData.SliceInfo], and application identifier[AppSessionContextReqData.AfAppId] . 
2. Identifying an user : Provided through an individual UE[AppSessionContextReqData.supi], a group of UE represented by Internal Group Identifier[AppSessionContextReqData.gpsi] with a combination of IP address [UeIpv4, UeIPv6, UeMac]
3. Identifying the location of where the traffic to be steered: Provided through routing information [AppSessionContextReqData.AfRoutReq]
4. Notifications from SMF on successful UP path change: Provided through routing information [AppSessionContextReqData.AfRoutReqUpPathChgSub]

Attached are some pics on how a simple edge deployment could be done through the MEC controller and illustration of traffic flow before and after traffic steering.

![image](https://user-images.githubusercontent.com/56033524/80600076-806b9000-8a49-11ea-8dd6-c64062174ec6.png)

![image](https://user-images.githubusercontent.com/56033524/80600113-8cefe880-8a49-11ea-8092-3faa0a52e683.png)

**Comment by sudhir-intc** [comment]
Dear free5gc team, could you please help share an update on this request.

**Comment by rubenfrancaa** [comment]
@sudhir-intc / @free5gc-org  is Npcf_PolicyAuthorization completely enabled ?

**Comment by danielh1204** [comment]
Hi,
for the current version of free5GC (v3.3.0),  
> Notifications from SMF on successful UP path change: Provided through routing information [AppSessionContextReqData.AfRoutReqUpPathChgSub]

only this one of the minimum requirements is not implemented yet.
