### ISSUE TITLE
No flowrule is returned from MongoDB while establishing PDU session.

### ISSUE THREAD

**Issue by vigneshblossoms** [free5gc/free5gc#310]
## Describe the bug
My setup consists of all the free5gc network functions and I'm using gnbsim for emulating the procedures. The registration process is smooth and I didn't find any discrepancy in the flows. However, for the PDU session establishment, with reference to **3gpp.TS.23.502(section 4.3.2.2.1)**, there is a flow from **SMF -> PCF for PCF selection (step 7a)**. During this flow, there is a request from **PCF to mongoDB** for flowrule selection from the collection **policyData.ues.flowRule**. During subscription or registration, I didn't find any steps for inserting any flowrules. (Please correct me here, if Im wrong). Kindly let me know or point me to the documentation related to this, if I'm missing something.

## To Reproduce
1. Insert subscriber information and register the UE. Run the comm PDU session establishment procedure. 
2. And analyse the packets using wireshark destined to mongoDB instance.

## Expected behavior
Expecting a flowrule in the mongoDB query **()** from PCF-> mongoDB query.

## Screenshots
The following screenshot (packet no:129) is the request from PCF to mongo instance requesting policyData.ues.flowRule for a particular ueId.

![Screenshot from 2022-02-13 10-50-41](https://user-images.githubusercontent.com/17174735/153747836-de771bb6-adef-4894-a4a2-a558227b90ec.png)

In the wireshark screenshot, we can see the return of **empty document** from mongoDB instance.

![Screenshot from 2022-02-13 10-51-01](https://user-images.githubusercontent.com/17174735/153747850-288e4452-8645-47be-b524-fbb26c1c49f0.png)

## Environment (please complete the following information):
 - K8s/Docker container deployment (4 node cluster with single master)
 - OS: [e.g. Ubuntu 18.04 Server]
 - Kernel version: [e.g. 5.200.0-0-generic]

### Configuration File
The associated source file calling this request can be seen in line:177
https://github.com/free5gc/pcf/blob/72c023f88ab53d899e46edfb883b9c6055de27b7/producer/smpolicy.go

### Log File
![Screenshot from 2022-02-13 11-07-05](https://user-images.githubusercontent.com/17174735/153748284-a2ffdbb0-6439-4c68-b93e-b4b7ee046a97.png)

**Comment by brianchennn** [comment]
This feature has been supported in v3.3.0
