### ISSUE TITLE
[Bugs] Can't pass any test, upf error, illigal option: f

### ISSUE THREAD

**Issue by fennih** [free5gc/free5gc#312]
I was following the passes described in the official site (https://www.free5gc.org/installations/stage-3-free5gc-install/) but I can't pass any test.

When I run any test, for example TestRegistration, I get the following outputs:

./bin/free5gc-upfd: invalid option -- 'f'

NAME:
   upf - 5G User Plane Function (UPF)

USAGE:
   main [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   -c FILE  Load configuration from FILE
   -l FILE  Output NF log to FILE
   -g FILE  Output free5gc log to FILE
   -h       show help
2022-02-18T18:13:06Z [ERRO][UPF][Util] Illigal option: f
2022-02-18T18:13:06Z [ERRO][UPF][Util] Error parsing args
...

And then the test stay stuck on Remove Request Transaction [1]

Others error I can retrieve, before the Remove Request Transaction [1] are:
2022-02-18T18:13:58Z [ERRO][SMF][CTX] In ActivateUpLinkTunnel UPF IP:  10.200.200.101
2022-02-18T18:13:58Z [ERRO][SMF][CTX] Allocate PDR Error:  this upf do not associate with smf

To Reproduce it, just follow the steps as described on official site (https://www.free5gc.org/installations/stage-3-free5gc-install/)

I know Stage 3 is not the actual, but the steps seems to be coherent with documentation here on github.

## Environment (please complete the following information):
 - free5GC Version: v3.0.6
 - OS: Ubuntu 20.0.04 
 - Kernel version: 5.4.0-100-generic
 - go version: go version go1.15.8 linux/amd64
 - gtp:
gtp5g                 118784  0
udp_tunnel         16384   1 gtp5g

**Comment by SOANykun** [comment]
Hello，I meet this problem yesterday，and now I have solved it through vim test.sh and modify it code cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -f to cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -c. It's modify its param f to c. Then you can see PASS.

**Comment by TulebaevTemirlan** [comment]
Hello. Sorry, maybe I misunderstood. I enter command "NFs/upf/build && ${EXEC_UPFNS}" in the "free5gc" folder. But I can't understand how modify from "./bin/free5gc-upfd -f" -> "./bin/free5gc-upfd -c". Could you tell me which commands to use and where, please?

**Comment by TulebaevTemirlan** [comment]
> Hello，I meet this problem yesterday，and now I have solved it through vim test.sh and modify it code cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -f to cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -c. It's modify its param f to c. Then you can see PASS.

**Comment by TulebaevTemirlan** [comment]
> Hello，I meet this problem yesterday，and now I have solved it through vim test.sh and modify it code cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -f to cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -c. It's modify its param f to c. Then you can see PASS.

I modified tesh.sh file through nano, is it ok? Because after modification I didn't receive PASS and still receiving FAIL, but now for another purpose(two lines) - "
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
"

**Comment by TulebaevTemirlan** [comment]
> 



> Hi all,
> 
> Please get the latest release v3.0.7 and try again:
> 
> ```
> git clone --recursive -b v3.0.7 -j `nproc` https://github.com/free5gc/free5gc.git
> ```

Hello. Yeah, it fixed the problem with ./test.sh TestRegistration and all other tests also PASS. Thank you so much:)

But I have FAIL only for this last test - ./test_ulcl.sh -om 3 TestRegistration. Is this test important to PASS? Could you tell me what this test -  ./test_ulcl.sh -om 3 TestRegistration?

Output of the - ./test_ulcl.sh -om 3 TestRegistration

FAIL    test    602.088s
free5gc-upfd: no process found
ls: cannot access '*sslkey.log': No such file or directory
87 packets captured
87 packets received by filter
0 packets dropped by kernel
71 packets captured
71 packets received by filter
0 packets dropped by kernel
64 packets captured
64 packets received by filter
0 packets dropped by kernel

**Comment by free5gc-org** [comment]
@TulebaevTemirlan 

It is fixed on v3.1.0.
Please get v3.1.0 and try again:
```
Usage: ./test_ulcl.sh [ TestRequestTwoPDUSessions ]
```
