### ISSUE TITLE
[Docs] Has any tests been conducted with hardware?

### ISSUE THREAD

**Issue by chainhead** [free5gc/free5gc#313]
## Documentation request

Is this content [here](https://github.com/free5gc/free5gc/wiki/Environment#hardware-tested) still valid?

> In the market today, there are neither hardware gNB nor hardware UEs that interface directly with a standalone 5GC, so no hardware testing has yet been performed against free5gc.

`open5gs` seems to have some [hardware](https://open5gs.org/open5gs/docs/hardware/01-genodebs) listed.

## Suggestion

Maybe, add tests with a `gNodeB` or even [UERANSIM](https://github.com/aligungr/UERANSIM) ?

## Additional context
None.

**Comment by ianchen0119** [comment]
Hi @chainhead 

please check the free5gc official page, it provides [the tutorial](https://www.free5gc.org/installations/stage-3-sim-install/) for testing.

**Comment by free5gc-org** [comment]
@chainhead 

Thanks for your suggestion.
We'll work on it.

**Comment by free5gc-org** [comment]
@chainhead 

https://github.com/free5gc/free5gc/wiki/Environment#hardware-tested
