### ISSUE TITLE
[Bugs] Wrong parameters set for PDU session status IE in Registration Accept for Mobility Registration Updating.

### ISSUE THREAD

**Issue by matsumu-y** [free5gc/free5gc#314]
## Describe the bug
When a Mobility registration updating is received, it returns a Registration Accept, but may incorrectly set the PDU session status IE.
AMF responds with INACTIVE in a RegistratonAccept even if the PDU Session status of AMF is in ACTIVE state.

## To Reproduce
1. RegistrationRequest ~ establish PDUSession
2. UE Context Release Request ~ UE Context Release Complete
3. UE/gNB -> 5GC InitialUEMessage, Registration request, Registration request(mobility registration updating)
4. UE/gNB <- 5GC InitialContextSetupRequest, Registration accept
Incorrect PDU session status IE settings.

## Expected behavior
PDU session status IE set to Registration Accept correctly.

## Environment (please complete the following information):
- free5GC Version: v3.0.6
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/62) for the fix.

**Comment by free5gc-org** [comment]
Thanks for the PR.
