### ISSUE TITLE
[Bugs] "5GSM Cause" IE of "PDU Session Release Command" NAS Message is incorrect.

### ISSUE THREAD

**Issue by matsumu-y** [free5gc/free5gc#315]
## Describe the bug
When a PDU session release request is received, a PDU session release command is sent, but the 5GSM cause is set to unknown (0).
This is not the value specified in 3GPP TS 24.501 9.11.4.2 5GSM cause.

## To Reproduce
1. Run test.sh -o TestPDUSessionReleaseRequest
2. Check the pcap after the test is finished.

## Expected behavior
Sets 5GSM cause value according to 6.3.3.2 Network-requested PDU session release procedure initiation in TS24.501.

## Environment (please complete the following information):
- free5GC Version: v3.0.6
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/smf/pull/42) for the fix.

**Comment by free5gc-org** [comment]
Thanks for the PR.
