### ISSUE TITLE
How can we add multiple 5QI during registration

### ISSUE THREAD

**Issue by hafizullah475** [free5gc/free5gc#316]
Using free5gc v3.0.6 and UERANSIM.
Registration is happening with DefaultNonGBR5QI . Here how can we add multiple 5QI (like 6, 7, 8) during registration...

**Comment by ianchen0119** [comment]
Hi @hafizullah475

UERANSIM hasn't supported QoS Flow handling,
You can check this opened [issue](https://github.com/aligungr/UERANSIM/issues/353) for more informations.
