### ISSUE TITLE
How can we trigger network initiated UE release..

### ISSUE THREAD

**Issue by hafizullah475** [free5gc/free5gc#317]
Using free5gc v3.0.6 and UERANSIM.
Here how can we trigger network-initiated UE release...

**Comment by ianchen0119** [comment]
Hi @hafizullah475 
Did you mean network-initiated deregistration request?
if yes, you can check the `source code of udm`, and `TS 29.503 Clause 5.3.2.2.2 / 5.3.2.2.3 `
- https://github.com/free5gc/udm/blob/main/producer/ue_context_management.go#L246-L256
