### ISSUE TITLE
Can't pass any test, TestRegistration

### ISSUE THREAD

**Issue by aluminum711** [free5gc/free5gc#318]
I was following the process https://www.free5gc.org/installations/stage-3-free5gc-install/
But get fail state in ./test.sh TestRegistration

Environment (please complete the following information):

    free5GC Version: v3.0.6
    OS: Ubuntu 20.0.04
    Kernel version: 5.4.0-100-generic
    go version: go version go1.15.8 linux/amd64

Error logs:

        === RUN   TestRegistration
            registration_test.go:50: 
        	        Error Trace:	registration_test.go:50
        	        Error:      	Expected nil, but got: 0x6f
        	        Test:       	TestRegistration
        --- FAIL: TestRegistration (0.00s)
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda2397]
        
        goroutine 169 [running]:
        testing.tRunner.func1.1(0x1545a00, 0x22d3250)
	        /usr/local/go/src/testing/testing.go:1072 +0x30d
        testing.tRunner.func1(0xc000552780)
	        /usr/local/go/src/testing/testing.go:1075 +0x41a
        panic(0x1545a00, 0x22d3250)
	        /usr/local/go/src/runtime/panic.go:969 +0x1b9
        git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).fd(...)
	        /home/noah/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:430
        git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).SCTPWrite(0x0, 0xc0004ff200, 0x39, 0x40, 0x0, 0x0, 0x0, 0x1)
	        /home/noah/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp_linux.go:88 +0x57
        git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).Write(...)
	        /home/noah/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:442
        test_test.TestRegistration(0xc000552780)
	        /home/noah/free5gc/test/registration_test.go:59 +0x299
        testing.tRunner(0xc000552780, 0x17b3c98)
	        /usr/local/go/src/testing/testing.go:1123 +0xef
        created by testing.(*T).Run
	        /usr/local/go/src/testing/testing.go:1168 +0x2b3
        exit status 2
        FAIL	test	1.687s

**Comment by 0x41gawor** [comment]
Exactly the same issue occurred in my case.

Env:
```
free5GC Version: v3.0.6
OS: Ubuntu 20.04.4 LTS
Kernel version: 5.4.0-104-generic
go version: go version go1.14.4 linux/amd64
```
Error logs:
```
=== RUN   TestRegistration
    TestRegistration: registration_test.go:50:
                Error Trace:    registration_test.go:50
                Error:          Expected nil, but got: 0x6f
                Test:           TestRegistration
--- FAIL: TestRegistration (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd5d8ee]

goroutine 176 [running]:
testing.tRunner.func1.1(0x153ee40, 0x26fbea0)
        /usr/local/go/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0006d2900)
        /usr/local/go/src/testing/testing.go:943 +0x3f9
panic(0x153ee40, 0x26fbea0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).fd(...)
        /home/ejek/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:430
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).SCTPWrite(0x0, 0xc0006cab80, 0x39, 0x40, 0x0, 0x0, 0x0, 0x1)
        /home/ejek/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp_linux.go:88 +0x4e
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).Write(...)
        /home/ejek/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:442
test_test.TestRegistration(0xc0006d2900)
        /home/ejek/free5gc/test/registration_test.go:59 +0x295
testing.tRunner(0xc0006d2900, 0x17c3768)
        /usr/local/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1042 +0x357
exit status 2
FAIL    test    1.659s
free5gc-upfd: no process found
```

I think that also this part of logs migh be noteworthy:
```
ejek@free5gc:~/free5gc$ ./test.sh TestRegistration
./bin/free5gc-upfd: invalid option -- 'f'

NAME:
   upf - 5G User Plane Function (UPF)

USAGE:
   main [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   -c FILE  Load configuration from FILE
   -l FILE  Output NF log to FILE
   -g FILE  Output free5gc log to FILE
   -h       show help
2022-03-09T20:03:22Z [ERRO][UPF][Util] Illigal option: f
2022-03-09T20:03:22Z [ERRO][UPF][Util] Error parsing args
```

**Comment by 0x41gawor** [comment]
The `./bin/free5gc-upfd: invalid option -- 'f'` part of my previous comment can be resolved by modifying `test.sh` file. 
All you need to do is to replace this line:
```
cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -f config/upfcfg.test.yaml &
```
with the line below
```
cd NFs/upf/build && ${EXEC_UPFNS} ./bin/free5gc-upfd -c config/upfcfg.test.yaml &
```
> Yes, only one letter changes.

The issue with `Expected nil, but got: 0x6f` still remains,

**Comment by Zhaodl1** [comment]
I also encountered the same issue, have you solved it?

=== RUN   TestRegistration
    registration_test.go:50: 
        	Error Trace:	registration_test.go:50
        	Error:      	Expected nil, but got: 0x6f
        	Test:       	TestRegistration
--- FAIL: TestRegistration (0.06s)

**Comment by aluminum711** [comment]
not yet resolved

**Comment by TulebaevTemirlan** [comment]
> Maybe you can try to update the version of submodules by following commands:
> 
> ```
> $ git submodule foreach git checkout main
> $ git submodule foreach git pull
> ```

Hello. I have the same problem. I tried to update the version of submodules as you recommended, but nothing changed

=== RUN   TestRegistration
    registration_test.go:50:
                Error Trace:    registration_test.go:50
                Error:          Expected nil, but got: 0x6f
                Test:           TestRegistration
--- FAIL: TestRegistration (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda72d7]

goroutine 171 [running]:
testing.tRunner.func1.1(0x154ea80, 0x22df270)
        /usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc00071b680)
        /usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x154ea80, 0x22df270)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).fd(...)
        /home/ubuntu/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:430
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).SCTPWrite(0x0, 0xc00057f9c0, 0x39, 0x40, 0x0, 0x0, 0x0, 0x1)
        /home/ubuntu/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp_linux.go:88 +0x57
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).Write(...)
        /home/ubuntu/go/pkg/mod/git.cs.nctu.edu.tw/calee/sctp@v1.1.0/sctp.go:442
test_test.TestRegistration(0xc00071b680)
        /home/ubuntu/free5gc/test/registration_test.go:59 +0x299
testing.tRunner(0xc00071b680, 0x17bce38)
        /usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1168 +0x2b3
exit status 2
FAIL    test    1.742s
2022-03-19T21:19:55Z [INFO][UPF][Util] Removing DNN routes

**Comment by ianchen0119** [comment]
@TulebaevTemirlan 

I found the similar question on the forum, maybe you can try to replace the amfcfg with original file:

https://forum.free5gc.org/t/testregistration-failed/92/2

**Comment by sergiobarra** [comment]
Hi @free5gc-org,

I am experiencing a similar issue.

Environment:
```
free5GC Version: v3.1.0
OS: Ubuntu 20.04.4 LTS
Kernel version: 5.4.0-1059-kvm
go version: go1.14.4 linux/amd64
```

Error logs:
```
(...)
2022-04-04T08:11:33Z [ERRO][AMF][NGAP] Failed to listen: protocol not supported
(...)
=== RUN   TestRegistration
    TestRegistration: registration_test.go:50:
                Error Trace:    registration_test.go:50
                Error:          Expected nil, but got: 0x5d
                Test:           TestRegistration
--- FAIL: TestRegistration (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa41f8e]
```

Thanks!

**Comment by TulebaevTemirlan** [comment]
> Hi @free5gc-org,
> 
> I am experiencing a similar issue.
> 
> Environment:
> 
> ```
> free5GC Version: v3.1.0
> OS: Ubuntu 20.04.4 LTS
> Kernel version: 5.4.0-1059-kvm
> go version: go1.14.4 linux/amd64
> ```
> 
> Error logs:
> 
> ```
> (...)
> 2022-04-04T08:11:33Z [ERRO][AMF][NGAP] Failed to listen: protocol not supported
> (...)
> === RUN   TestRegistration
>     TestRegistration: registration_test.go:50:
>                 Error Trace:    registration_test.go:50
>                 Error:          Expected nil, but got: 0x5d
>                 Test:           TestRegistration
> --- FAIL: TestRegistration (0.01s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
>         panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa41f8e]
> ```
> 
> Thanks!

Hello, Could try use go version as recommended on the website of free5gc in installation section? Probably it was go 1.15..

In my case version 3.1.0 of free5gc fixed my problem and all 11 of 11 tested were PASS

**Comment by sergiobarra** [comment]
Hi @TulebaevTemirlan,

I am actually using the Go version (1.14.4) suggested in the installation [document](https://github.com/free5gc/free5gc/wiki/Installation#installation). In fact, I have followed each of the steps in such document.

Any ideas? Thanks
