### ISSUE TITLE
[Bugs] COMMIT_TIME of the Makefile is incorrect when the local time zone is not UTC.

### ISSUE THREAD

**Issue by matsumu-y** [free5gc/free5gc#320]
## Describe the bug
COMMIT_TIME of the Makefile is incorrect when the local time zone is not UTC.

## To Reproduce
1. Compile network function services in free5gc
```
$ cd ~/free5gc
# make
Start building amf....
cd NFs/amf && \
CGO_ENABLED=0 go build -gcflags "" -ldflags "-X github.com/free5gc/version.VERSION=v3.0.6-10-gfa56062 -X github.com/free5gc/version.BUILD_TIME=2022-03-08T08:54:07Z -X github.com/free5gc/version.COMMIT_HASH=+5e6d957 -X github.com/free5gc/version.COMMIT_TIME=2022-03-01T16:25:59Z" -o /home/l5gc/free5gc/bin/amf amf.go
    ：
```
The option "-X github.com/free5gc/version.COMMIT_TIME=2022-03-01T16:25:59Z" is incorrect, "2022-03-01T07:25:59Z" is correct.

## Expected behavior
The value converted to UTC is set to COMMIT_TIME.

## Environment (please complete the following information):
- free5GC Version: v3.0.6
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/free5gc/pull/319) for the fix.

**Comment by noormohammedli** [comment]
I change the Time zone  in my VM but still have the same issues
I cannot build the core

**Comment by matsumu-y** [comment]
@noormohammedli
Timezone on the local machine is irrelevant.
This is an issue that ignores the commit log timezone and treats it as UTC.
It has nothing to do with not being able to build.
I can build it.

**Comment by free5gc-org** [comment]
Thanks for the PR.
