### ISSUE TITLE
Install free5gc on AWS VM 

### ISSUE THREAD

**Issue by noormohammedli** [free5gc/free5gc#321]
Hello, 

I am trying install the 5G core  on AWS and i get this error with build 

![Screenshot 2022-03-16 at 4 54 01 pm](https://user-images.githubusercontent.com/34620715/158645054-e40b2d78-051a-4363-b3d7-150abd1a8c63.png)
)

**Comment by ianchen0119** [comment]
Hi @noormohammedli,

I think the root cause is: go module hasn't been enabled on your OS environment. 
You can try setting the environment variable `GO11MMODULES=on`.

Thanks.
