### ISSUE TITLE
[Question] How to trigger network (from AMF) initiated PDU SESSION RESOURCE SETUP REQUEST

### ISSUE THREAD

**Issue by anvi55** [free5gc/free5gc#324]
How do we trigger new PDU Session Resource Setup Request from AMF for different 5QIs. please let us know if any documentation available to refer
3GPP TS 38.413 V15.13.0  Section 8.2.1.2

**Comment by ianchen0119** [comment]
Refer to the source of AMF,
`SendPDUSessionResourceSetupRequest()` will be invoked in `sendServiceAccept()` when AMF respond the service request, which is sent from CM-IDLE UE.
I think you can try to add the flow rule via the webconsole when UE is in the CM-IDLE state and initiate the service request by using the `ping` command.

**Comment by ianchen0119** [comment]
Some Infos for you:
1\. Establish the PDU session in the UERANSIM by using the command below:
```sh
./nr-cli imsi-208930000000003 --exec "ps-establish IPv4 --sst 1 --sd 66051 --dnn internet"
```
- `0x010203(16)` = `66051(10)`
