### ISSUE TITLE
[Bugs] The 5G-GUTI on the Registration Accept for the Initial Registration Request has not been updated.

### ISSUE THREAD

**Issue by matsumu-y** [free5gc/free5gc#325]
## Describe the bug
When receiving an Initial Registration Request from the UE using 5G-GUTI, the AMF returned a Registration Accept using the 5G-GUTI configured in the Initial Registration Request and did not update the 5G-GUTI.

According to the following description, 5G-GUTI must be updated.
cf. TS 33.501 6.12.3 Subscription temporary identifier
> Upon receiving Registration Request message of type "initial registration" or "mobility registration update" from a UE, the AMF shall send a new 5G-GUTI to the UE in the registration procedure.

## To Reproduce
1. Run  test.sh -o TestGUTIRegistration
2. Check the pcap after the test is finished.
When an Initial Registration Request (Second Registration) was received, a Registration Accept was returned in the same 5G-GUTI IE.

## Expected behavior
The updated 5G-GUTI is set to Registration Accept.

## Environment (please complete the following information):
- free5GC Version: v3.0.6
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Pull Request
Pull Requests for the fix.
[amf](https://github.com/free5gc/amf/pull/66)
[lib/idgenerator](https://github.com/free5gc/idgenerator/pull/1)

**Comment by free5gc-org** [comment]
Thanks for the PR!
