### ISSUE TITLE
[Bugs] When NF is terminated, the "href" element remains in the "urilist" collection in mongodb.

### ISSUE THREAD

**Issue by matsumu-y** [free5gc/free5gc#326]
## Describe the bug
The profiles of all NFs are deregistered at the NF termination, but the "href" element remains in the "urilist" collection in mongodb.
Therefore, "href" increases every time it starts.

## To Reproduce
1. Clear the contents of MongoDB.
```
$ mongo free5gc
> db.dropDatabase()
{ "dropped" : "free5gc", "ok" : 1 }
>
```
2. Run ./test.sh TestRegistration
3. See "urilist" in MongoDB.
```
$ mongo free5gc
> db.urilist.find()
{ "_id" : ObjectId("62392f65ce950983572692c5"), "nfType" : "AMF", "_link" : { "item" : [ { "href" : "http://127.0.0.10:8000/nnrf-nfm/v1/nf-instances/100b1ecb-2f72-4e0f-a46e-969f0bcdb453" } ] } }
　　：
```
4. By repeating 2-3, you can see that "href" is not deleted, but is increasing.

## Expected behavior
When NF terminated, "href" of "urilist" is deleted.

## Environment (please complete the following information):
- free5GC Version: v3.0.6
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Pull Request
Pull Requests for the fix.
[lib/MongoDBLibrary](https://github.com/free5gc/MongoDBLibrary/pull/1)
[nrf](https://github.com/free5gc/nrf/pull/4)
Note: If you don't include the Pull Request from MongoDBLilibrary, you won't be able to compile NRF.

**Comment by free5gc-org** [comment]
Thanks for the PR.
