### ISSUE TITLE
[Docs] Fix default UPF config file

### ISSUE THREAD

**Issue by ebucchianeri** [free5gc/free5gc#329]
## Suggestion

The default UPF config file is no more `free5gc/NFs/upf/build/config/upfcfg.yaml`, as reported here https://github.com/free5gc/free5gc/wiki/Installation#c-install-user-plane-function-upf
looking at UPF logs, it seems to be `free5gc/config/upfcfg.yaml`

**Comment by free5gc-org** [comment]
The wiki is updated. Thanks.
