### ISSUE TITLE
[Bugs] WebConsole cannot correctly register the IMSI with a leading 0

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#330]
Hi @free5gc-org 

WebConsole cannot correctly register the IMSI with a leading `0`.

For example, `PLMN=00101`. 

According to the following code, `SUPI (IMSI)` specified on the `New Subscriber` screen is treated as a numerical value once, so if it is treated as a character string again, the leading `0` number will be deleted. 

`free5gc/webconsole/frontend/src/pages/Subscribers/SubscriberOverview.js`
```
  async addSubscriber(subscriberData) {
    this.setState({ subscriberModalOpen: false });
    let userNumber = subscriberData["userNumber"];
    delete subscriberData["userNumber"];
    let imsi = subscriberData["ueId"].substr(5, subscriberData["ueId"].length - 5);
    for(let i = 0; i < userNumber; i++){
-->   let newImsi = Number(imsi) + i;
      subscriberData["ueId"] = `imsi-${newImsi}`;
      if (!await ApiHelper.createSubscriber(subscriberData)) {
        alert("Error creating new subscriber when create user");
      }
      ApiHelper.fetchSubscribers().then();
    }
  }
```
As a result,

`imsi-001010000000001`

when try to register the above, in fact 

`imsi-1010000000001`

above another value will be registered. 

The IMSI as part of the subscriber information is registered correctly, but the incorrect `ueId` of the subscriber information is registered, and the DB cannot be searched correctly. 

Also, if `PLMN=20893`, such a problem does not occur.

Therefore, WebConsole must add up to 6 digits of  `0` (for MCC and MNC) once to the beginning of the `newImsi`, and then extract the last 15 digits of the IMSI, as shown below. This will prevent the `0` from being removed from the IMSI that contains a leading `0`. 
```
--- SubscriberOverview.js.orig  2022-04-01 20:26:06.867594518 +0900
+++ SubscriberOverview.js       2022-04-02 17:32:57.504229887 +0900
@@ -43,6 +43,7 @@
     let imsi = subscriberData["ueId"].substr(5, subscriberData["ueId"].length - 5);
     for(let i = 0; i < userNumber; i++){
       let newImsi = Number(imsi) + i;
+      newImsi = ("000000" + newImsi).slice(-15);
       subscriberData["ueId"] = `imsi-${newImsi}`;
       if (!await ApiHelper.createSubscriber(subscriberData)) {
         alert("Error creating new subscriber when create user");
```
In my environment, this change handles the IMSI with a leading `0` correctly. 

FYI.

**Comment by free5gc-org** [comment]
Fix in https://github.com/free5gc/webconsole/pull/24
