### ISSUE TITLE
[Bugs] LogLevel is not applied when the test is run.

### ISSUE THREAD

**Issue by RyuichiNamba-fj** [free5gc/free5gc#333]
## Describe the bug
LogLevel and ReportCaller are not applied when the test is run.

## To Reproduce
1. Change LogLevel and ReportCaller setting at `free5gc/test/ngsetup_test.go`.
2. Run the test.(ex. TestRegistration)

## Expected behavior
LogLevel and ReportCaller are applied when the test is run.

## Environment (please complete the following information):
- free5GC Version: v3.1.0
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Additional context
I have sent PRs
- [free5gc](https://github.com/free5gc/free5gc/pull/332)
- [amf](https://github.com/free5gc/amf/pull/67)
- [ausf](https://github.com/free5gc/ausf/pull/5)
- [nrf](https://github.com/free5gc/nrf/pull/5)
- [nssf](https://github.com/free5gc/nssf/pull/4)
- [pcf](https://github.com/free5gc/pcf/pull/6)
- [smf](https://github.com/free5gc/smf/pull/48)
- [udm](https://github.com/free5gc/udm/pull/11)
- [udr](https://github.com/free5gc/udr/pull/5)

**Comment by free5gc-org** [comment]
Thanks for the PR!
