### ISSUE TITLE
[Bugs] TestRegistration NGAP error

### ISSUE THREAD

**Issue by sergiobarra** [free5gc/free5gc#334]
### Describe the bug
Hi, I have followed the [installation document](https://github.com/free5gc/free5gc/wiki/Installation#installation) and cannot pass test `TestRegistration`. I also commented in closed issue #318, but I have just realized the problem may be slightly different.

### Environment
- free5GC Version: v3.1.0
- OS: Ubuntu 20.04.4 LTS
- Kernel version: 5.4.0-1059-kvm
- go version: go1.14.4 linux/amd64
- gcc version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

### To Reproduce
1. Perform "all-in-one" installation as in [installation document](https://github.com/free5gc/free5gc/wiki/Installation#installation)
2. Installation is correct (including 5G GTP-U kernel)
3. Run command `./test.sh TestRegistration`

### Expected behavior
The TestRegistration should be passed.

### Outcome
The test fails. It seems something related to NGAP "protocol not supported".
```
(...)
2022-04-04T08:11:33Z [ERRO][AMF][NGAP] Failed to listen: protocol not supported
(...)
=== RUN   TestRegistration
    TestRegistration: registration_test.go:50:
                Error Trace:    registration_test.go:50
                Error:          Expected nil, but got: 0x5d
                Test:           TestRegistration
--- FAIL: TestRegistration (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa41f8e]
```

Thanks!

**Comment by ianchen0119** [comment]
Hi @sergiobarra 
Please refer to https://forum.free5gc.org/t/testregistration-failed/92/17:
Modification point：
```
configuration:
amfName: AMF # the name of this AMF
ngapIpList: # the IP list of N2 interfaces on this AMF
- 127.0.0.1 #127.0.0.18
```
it might be helpful for you.

**Comment by sergiobarra** [comment]
Hi @ianchen0119,

Thanks for the reply. I still have the same problem when making the modification you suggest.

Best

**Comment by ianchen0119** [comment]
Hi @sergiobarra 
Did you check the sctp module has been loaded in the kernel or not?
```sh
lsmod | grep sctp
```
If no, the link below may be useful for you:
Ref: https://www.linuxquestions.org/questions/linux-kernel-70/protocol-not-supported-886650/

**Comment by sergiobarra** [comment]
Hi @ianchen0119,
It was the sctp module indeed. Thanks.
I was not able to install the sctp module in Ubuntu 20.04.4, so I have tried with Ubuntu 18.04, and now the test is passed.
I close the issue. Thanks.
