### ISSUE TITLE
[Feat] webconsole to support arm64 architecture

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#335]
## Issue Description
webconsole does not work on arm64 architecture

### What's the version are you using
* free5GC Version: v3.1.0
* OS: Ubuntu 20.04.4 LTS
* Kernel version: 5.4.0-108
* go version: go1.18 linux/arm64

### Is your feature request related to a problem? Please describe.
Almost of modules of v3.1.0 works fine on arm64 architecture except webconsole.

### Describe the solution you'd like
Make webconsole to work on arm64 architecture.  Currently webconsole frontend uses `node-sass` library which does not support arm64.  Instead, we can use `sass` library which support arm.

### If willing to resolve an issue by submitting Pull request, please consider the points below.
here is link to [PR](https://github.com/free5gc/webconsole/pull/23)

**Comment by free5gc-org** [comment]
@kishiguro 

Build error happened when executing `make webconsole`:

```
Start building webconsole....
cd webconsole/frontend && \
yarn install && \
yarn build && \
rm -rf ../public && \
cp -R build ../public
yarn install v1.22.5
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
error sass@1.50.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Makefile:64: recipe for target 'webconsole/bin/webconsole' failed
make: *** [webconsole/bin/webconsole] Error 1
```

**Comment by free5gc-org** [comment]
@kishiguro 

This issue is already fixed after re-installing nodjs:

`sudo apt-get install -y nodejs`

Use `node -v` to check if version >= `12.0.0`

**Comment by kishiguro** [comment]
@free5gc-org thanks for confirmation.  good to hear it works!
