### ISSUE TITLE
[Bugs] TestRequestTwoPDUSessions: ICMP Echo Request was not forwarded

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#338]
## Describe the bug

In TestRequestTwoPDUSessions, 2nd ICMP Echo Request was not forwarded by UPF2.
```
[WARN][UPF][Util] GTP-U payload length mismatch: expected:60, gotten:88
```

## To Reproduce
Run TestRequestTwoPDUSessions.
```
./test_ulcl.sh TestRequestTwoPDUSessions
```

## Expected behavior

All ICMP Echo Requests and Replies are forwarded by UPFs.

## Environment (please complete the following information):
 - free5GC Version: v3.1.0
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version go1.14.4 linux/amd64

### PCAP File
[TestRequestTwoPDUSessions_UPF01.zip](https://github.com/free5gc/free5gc/files/8470005/TestRequestTwoPDUSessions_UPF01.zip)
[TestRequestTwoPDUSessions_UPF02.zip](https://github.com/free5gc/free5gc/files/8470004/TestRequestTwoPDUSessions_UPF02.zip)

## Additional context
[Pull Request](https://github.com/free5gc/free5gc/pull/337) for the fix.

**Comment by free5gc-org** [comment]
Thanks for the PR.
