### ISSUE TITLE
[Bugs] UPF throw errors when more than 10 UE's are connected

### ISSUE THREAD

**Issue by MichalzDev** [free5gc/free5gc#344]
## Describe the bug
UPF is throwing errors when more that 10 UE's (tunnel interfaces) are created
## To Reproduce
1. Setup Free5gc and UERANSIM (I'm using towards5gs Helm charts)
2. Register more than 10 UE's in webUI
3. Watch UPF logs
4. Enter UE pod and execute _./nr-ue -c ../config/ue-config.yaml -i imsi-2089300000000XX_ 10 or more times each time with different registered imsi
5. At 11th UE UPF will throw error

## Expected behavior
 Successfully register N number of UE's e.g. 20, 100, 1000 without issues
## Screenshots
<img width="391" alt="upf_new_error" src="https://user-images.githubusercontent.com/51170703/167392368-4ead5824-05b2-47ab-ac98-0be9d25a2524.PNG">

## Environment:
 - free5GC Version: v3.1.1
 - OS: Ubuntu 20.04 Server
 - Kernel version: 5.4.0-109-generic
 - go version: go1.17.8 linux/amd64

**Comment by ianchen0119** [comment]
@MichalzDev 
You can try to increase the buffer size of the UPF:

https://forum.free5gc.org/t/how-many-number-of-ues-does-an-free5gc-support/144/14

**Comment by MichalzDev** [comment]
Yes, it worked. Thank you.
