### ISSUE TITLE
[Docs] Please provide information how to configure multiple DNNs

### ISSUE THREAD

**Issue by anvi55** [free5gc/free5gc#345]
## Documentation request

What was unclear/insufficient/not covered in the documentation.
-- how to configure multiple DNN in amfcfg.yaml,smfcfg.yaml and upfcfg.yaml is not mentioned. please provide information how to add multiple DNN configuration 

## Additional context
when i try to add multiple DNN i could see UE ip is allocating the latest DNN. attached my config

[config.zip](https://github.com/free5gc/free5gc/files/8705289/config.zip)

**Comment by ianchen0119** [comment]
https://youtu.be/AEMrjKRWarw

**Comment by anvi55** [comment]
I had gone through the video and observed that to support multiple DNN we need to have multiple SMF and UPF instances.
But i am looking for single SMF and UPF instance handling multiple DNNs. Is this supported?
