### ISSUE TITLE
[Docs] QoS, 5QI and UPF selection based on NSSAI

### ISSUE THREAD

**Issue by agalvan002** [free5gc/free5gc#346]
## Documentation request
Hello, 

Does free5GC support QoS, 5QI and UPF selection based on NSSAI?

Thanks in advanced.

**Comment by ianchen0119** [comment]
Hi @agalvan002 

free5GC doesn't support 5QI, 5QI and QFI always are `9` (non-GBR) by default.
As for QoS, free5GC doesn't support it so far but on the planning.

Moreover, 
You can refer to the [Configuration page](https://github.com/free5gc/free5gc/wiki/Configuration) for configuring the UPF selection.

Thanks.
