### ISSUE TITLE
[Question] How gtp5g module works between nodes ?

### ISSUE THREAD

**Issue by MichalzDev** [free5gc/free5gc#348]
My scenario: I'm using free5gc with k8s on 3 node cluster. (1 node for Core Network, 1 node for UPF, 1 node for UE + gnB)
Question: Do I have to install gtp5g module only on UPF node or also on UE + gnB node ?
Question 2: Why is gtp5g supported on old OS only for old kernels 5.0/5.4 ? Right now we have Ubuntu 22 and kernel 5.18. Maybe it's good idea to update.

**Comment by ianchen0119** [comment]
@MichalzDev 

1. You only need to install gtp5g on the UPF node.
2. It's due to Linux API name always be changed.
    if you are interested in, you could submit the pull request for supporting kernel `5.18^`
