### ISSUE TITLE
[Bugs] State mismatch happens if AMF receives InitialUEMessage while waiting for RegistrationComplete.

### ISSUE THREAD

**Issue by RyuichiNamba-fj** [free5gc/free5gc#350]
## Describe the bug
State mismatch happens if AMF receives InitialUEMessage(with 5gs-tmsi) while waiting for RegistrationComplete.

## To Reproduce
Happens in a quasi-normal sequence as follows.  
1. RegistrationRequest ~ RegistrationAccept
2. UE dose not return RegistrationComplete and sending Initial ServiceRequest without ANRelease.
3. State mismatch happens at AMF.

## Expected behavior
- If T3550 timer is run, stop it and set the state to Registered.
- Stop the related NAS timer.
- Perform ANRelease for old RanUE.

## Environment (please complete the following information):
- free5GC Version: v3.1.1
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

### PCAP File
[Statemismatch.zip](https://github.com/free5gc/free5gc/files/8804105/Statemismatch.zip)

### Log File
The following is a console log of when UE sends InitialServiceRequest without ANRelease.
```
2022-05-31T09:46:30Z [INFO][AMF][NGAP][127.0.1.1:9784] Handle Initial UE Message (/home/fujitsu/Origin/free5gc/NFs/amf/internal/ngap/handler.go:854 github.com/free5gc/amf/internal/ngap.HandleInitialUEMessage)
2022-05-31T09:46:30Z [INFO][AMF][NGAP][127.0.1.1:9784][AMF_UE_NGAP_ID:1] Implicit Deregistration - RanUeNgapID[1] (/home/fujitsu/Origin/free5gc/NFs/amf/internal/context/amf_ue.go:300 github.com/free5gc/amf/internal/context.(*AmfUe).AttachRanUe)
2022-05-31T09:46:30Z [INFO][LIB][FSM] Handle event[Gmm Message], transition from [ContextSetup] to [ContextSetup] (/home/fujitsu/go/pkg/mod/github.com/free5gc/util@v1.0.3/fsm/fsm.go:95 github.com/free5gc/util/fsm.(*FSM).SendEvent)
2022-05-31T09:46:30Z [ERRO][AMF][GMM][AMF_UE_NGAP_ID:2][SUPI:imsi-2089300007487] state mismatch: receieve gmm message[message type 0x4c] at ContextSetup state (/home/fujitsu/Origin/free5gc/NFs/amf/internal/gmm/sm.go:379 github.com/free5gc/amf/internal/gmm.ContextSetup)
```

## Additional context
I have sent a [PR](https://github.com/free5gc/amf/pull/70)

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 

Which UE did you use? Did the UE always not reply RegistrationComplete when receiving RegistrationAccept?
Why did RAN send Initial ServiceRequest without ANRelease?

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
The UE usually returns Registration Complete, but in this case, it seems that the RRC was established and the Service Request was sent before the gNB sends AN Release due to poor radio conditions, etc.

**Comment by free5gc-org** [comment]
@RyuichiNamba-fj 

We think AMF should send ServiceRequest Reject to UE and remove the amfUe because Registration is not completed.
UE should re-register when receiving ServiceRequest Reject.

**Comment by RyuichiNamba-fj** [comment]
@free5gc-org 
According to TS24.501(v16.12.0) 5.5.1.2.8.
> g) REGISTRATION REQUEST message with 5GS registration type IE set to "mobility registration updating" or "periodic registration updating" received before REGISTRATION COMPLETE message, if the REGISTRATION COMPLETE message is expected.
>Timer T3550 shall be stopped. The allocated 5G-GUTI in the registration procedure for initial registration shall be considered as valid and the registration procedure for mobility and periodic update shall be progressed as described in subclause 5.5.1.3.

It says that while waiting for RegistrationComplete, if a mobility registration updating RegistrationRequest is received, it does not return a Reject and continues processing. Therefore, I think that ServiceRequest should be processed in the same way.
TS24.501 (v15.7.0) says that it does not continue processing and returns a Reject, but I think this was corrected in v16 because it does not match the other description (5.5.1.2.8.d)).

**Comment by free5gc-org** [comment]
Thanks for the PR!
