### ISSUE TITLE
[Bugs] Optional Query parameters with empty values are included in API path (supported-features)

### ISSUE THREAD

**Issue by ubrovc** [free5gc/free5gc#352]
## Describe the bug
In case of not received supported-features query parameter from AMF or SMF, UDM includes empty query parameter in request URI path. Problem was detected in several API calls: 

- /nudr-dr/v1/subscription-data/ueId/plmnId/provisioned-data/am-data
- /nudr-dr/v1/subscription-data/ueId/plmnId/provisioned-data/smf-selection-subscription-data
- /nudr-dr/v1/subscription-data/ueId/context-data/smf-registrations

Problematic case:

- /nudr-dr/v1/subscription-data/ueId/plmnId/provisioned-data/am-data?supported-features=
- /nudr-dr/v1/subscription-data/ueId/plmnId/provisioned-data/smf-selection-subscription-data?supported-features=
- /nudr-dr/v1/subscription-data/ueId/context-data/smf-registrations?supported-features=

This could also occur on other API calls and query parameters.

## To Reproduce
Needed AMF/SMF that is sending following requests to UDM without supported-features query parameter (at least for detected problems):

- /nudm-sdm/v1/ueId/am-data
- /nudm-sdm/v1/ueId/smf-select-data
- /nudm-sdm/v1/ueId/ue-context-in-smf-data

## Expected behavior
Optional query parameters shall not be included in API request path, if are empty. This is not strictly specified by any standard, but it is good pattern to avoid possible errors on server side, if it is not expecting key:value pairs without value.
It is suggested to add additional check, if value exists, to openapi library, for all query parameters with type optional.String. 
Current isSet will not cover the case with empty string.

Example without check:
```
if localVarOptionals != nil && localVarOptionals.SupportedFeatures.IsSet() {
		localVarQueryParams.Add("supported-features", openapi.ParameterToString(localVarOptionals.SupportedFeatures.Value(), ""))
}
```
Example with additional value check:
```
if localVarOptionals != nil && localVarOptionals.SupportedFeatures.IsSet() && localVarOptionals.SupportedFeatures.Value() != "" {
		localVarQueryParams.Add("supported-features", openapi.ParameterToString(localVarOptionals.SupportedFeatures.Value(), ""))
}
```

## Environment (please complete the following information):
 - openapi Version: v1.0.4
 - OS: Ubuntu 20.04.4 LTS
 - Kernel version: Linux 5.4.0-109-generic
 - go version: 1.18.1 linux/amd64

### PCAP File
Part of trace file with problematic flow (plaint text):
[supp_feature_bug.txt](https://github.com/free5gc/free5gc/files/8900768/supp_feature_bug.txt)

## Additional context
[PR](https://github.com/free5gc/openapi/pull/6)

**Comment by free5gc-org** [comment]
Thanks for the PR.
