### ISSUE TITLE
Unable to connect to n3iwf using a UE by non-3gpp 

### ISSUE THREAD

**Issue by san-san-hub** [free5gc/free5gc#353]
### Describe the bug
Unable to connect to n3iwf using a UE by non-3gpp 
### Environment:
free5GC Version: v3.1.1
OS: ubuntu18.04
UE: Iused the following UE "[https://github.com/my5G/my5G-non3GPP-access]to connect to free5gc n3iwf;
### report an error
trying to trigger_initial_registration.sh，but n3iwf show Unmarshalling EAP-5G packet failed: Unmatched GUAMI length ;
Note: The connection between n3iwf and free5gc is normal;
![2022-05-12 16-15-29 的屏幕截图](https://user-images.githubusercontent.com/74893464/174822324-c1d5a884-6804-4bd0-b371-5f9ebc9e2ad9.png)

who can  give me some advice, I would be very grateful!

**Comment by san-san-hub** [comment]
However, my5G stopped updating 2 years ago, and it seems that only my5G-core can work with non-3gpp properly;

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/help-connect-ue-and-n3iwf-please/832/10

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/can-i-connect-actual-real-wifi-ue-to-free5gc-setup-using-n3iwf-to-test-non-3gpp-access/1841/2

**Comment by SaiPrathyushaa** [comment]
Hi,

Can i connect actual/real WiFi UE N3IWF to test non 3GPP access.
Actually we are able to attach UE in Simulator mode, 
Now we are looking into hardware part to establish Wi-Fi by using N3IWF and need to connect with 5g core,
Could you please suggest suitable hardware which is useful for N3IWF?

Thanks in advance

**Comment by alishir** [comment]
Hi @SaiPrathyushaa,
Did you find any solution?
