### ISSUE TITLE
[Bugs] Wrong unit of AMBR on UE registration info (web console)

### ISSUE THREAD

**Issue by ast9501** [free5gc/free5gc#360]
## Describe the bug
The aggregate maximum bit rate (AMBR) configurations on UE registration info (web console) may have wrong unit.

I set UL/DL AMBR of UE to 2 **Mbps** through web console, then test the bandwidth with iper3. The average bandwidth of iperf3 is about 16 Mbits/sec (2 **MBytes/sec**). I think the unit of AMBR configuration may be fixed to MB/sec ?

## To Reproduce
1. Config UE UL/DL AMBR to 2 Mbps through web console (See the first screenshot on ##Screenshots)
2. Use iperf3 connect to iper3 server (client and server at same local network), select uesimtun0 as client interface
```
# iperf3 Server
iperf3 -s

# UE
iperf3 -c <iperf3-server ip> -B <uesimtun0 ip> -t 15
```

## Expected behavior
The bitrate should be limited to less than 2 Mbits/sec.

## Screenshots
* Web console config
![image](https://user-images.githubusercontent.com/90389266/177339687-46c71708-5d94-421a-9c9f-3772e7546c88.png)

* Iperf3 result
![image](https://user-images.githubusercontent.com/90389266/177340397-e8518778-0b93-4ffc-a6e5-d18a95a99b37.png)

## Environment (please complete the following information):
 - free5GC Version: v3.1.1
 - OS: Ubuntu 20.04.4-server
 - Kernel version: 5.4.0-121-generic
 - go version: 1.15.8 linux/amd64
 - c compiler version (Option): 9.4.0

## System architecture (Option)
OpenStack initiates two VMs, one as free5GC core network and another as UERANSIM.

## Additional context
The free5GC environment setup follows the [installation guideline](https://www.free5gc.org/installations/stage-3-sim-install-tw/) on free5GC website.

**Comment by MIKibrahim** [comment]
do you solve this issue?

**Comment by ianchen0119** [comment]
Hi @MIKibrahim & @ast9501 
As I know,
AMBR enforcement is implemented in RAN side, Core network is just delivery the required parameter.
AMF:
```go
ueAmbrUL := ngapConvert.UEAmbrToInt64(ue.AmfUe.AccessAndMobilitySubscriptionData.SubscribedUeAmbr.Uplink)
```
NGAP:
```go

func UEAmbrToInt64(modelAmbr string) int64 {
	tok := strings.Split(modelAmbr, " ")
	if ambr, err := strconv.ParseFloat(tok[0], 64); err != nil {
		logger.NgapLog.Warnf("Parse AMBR failed %+v", err)
		return int64(0)
	} else {
		return int64(ambr * getUnit(tok[1]))
	}
}

func getUnit(unit string) float64 {
	switch unit {
	case "bps":
		return 1.0
	case "Kbps":
		return 1000.0
	case "Mbps":
		return 1000000.0
	case "Gbps":
		return 1000000000.0
	case "Tbps":
		return 1000000000000.0
	}
	return 1.0
}
```
Moreover, 
According to TS 38.413, it shows that we should use bps ad basic unit of bit rate:

![image](https://user-images.githubusercontent.com/42661015/192452419-09251a27-c2aa-4289-a0c4-bfd892b2509e.png)

![image](https://user-images.githubusercontent.com/42661015/192452212-683e2b39-e12f-4c5d-9246-58302c7a1770.png)

For validating the result, I also captured the pcap file on n2 interface:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/42661015/192452747-be49dbf5-a58b-4007-a4d5-e16559c69b7b.png">

![image](https://user-images.githubusercontent.com/42661015/192452845-868a6d8a-fbb9-4b3a-ab4c-4ee599bb9e8c.png)

if you are using the UERANSIM as radio simulator,
Maybe you can submit the new issue to the UERANSIM project.

Thanks.

**Comment by tim-ywliu** [comment]
@ast9501 @MIKibrahim 

I use the latest UERANSIM and free5GC v3.2.1 and there is no this issue.
Please update your UERANSIM and free5GC to try again.

![螢幕擷取畫面 2022-09-27 152526](https://user-images.githubusercontent.com/68043973/192461464-f0fbd193-4c0e-4514-adad-6ccdf0673529.png)
![螢幕擷取畫面 2022-09-27 152628](https://user-images.githubusercontent.com/68043973/192461480-91f266dd-9d46-43f1-9f05-f4942080c9c2.png)

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/ambr-enforcement-with-free5gc-ueransim/1762/2
