### ISSUE TITLE
[Bugs]Can free5gc support multiple SMF or AMF

### ISSUE THREAD

**Issue by xiaobinggan-zmh** [free5gc/free5gc#362]
I have tried to realize multiple UPF. Can free5gc support multiple SMF or AMF。

**Comment by xiaobinggan-zmh** [comment]
@ianchen0119 


I tried the network slice of free5gc. The two slices use separate SMF and UPF, which are shared by other NF, and the terminal is successfully connected.

But I encountered a problem, that is, the two terminals access the Internet through two slices. When the first terminal can access the Internet, the second terminal cannot access the Internet, and when the second terminal can access the Internet, the first terminal cannot access the Internet, that is, the two terminals cannot access the Internet at the same time. Is this reasonable? What is the solution?

**Comment by ayoub-tl** [comment]
hello @xiaobinggan-zmh  can you please share with me the configuration file for different slices, I tried to do this but the second ue end up connecting to the first slice , even though there have different  snssai configured 
thank you
