### ISSUE TITLE
[Bugs]Nausf_UEAU Authenticate Request Error: 404 is not a valid status code in UeAuthenticationsPost

### ISSUE THREAD

**Issue by xiaobinggan-zmh** [free5gc/free5gc#363]
Hello, I tried to replace the AUSF of OAI with the AUSF of Free5GC, but the terminal could not access it, so the problem occurred
The free5GC version I use is 3.0.6。

2022-07-06T13:53:47Z [ERRO][AMF][GMM][AMF_UE_NGAP_ID:3] Nausf_UEAU Authenticate Request Error: 404 is not a valid status code in UeAuthenticationsPost

**Comment by wilson30139** [comment]
Hello @xiaobinggan-zmh . I see 404 in the error message. I think that SBI producer doesn't response, you can check whether the IP address and port are set correctly. If it is convenient for you, can you provide the configuration or log files? Thanks.
