### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by RamzahRehmanPAK** [free5gc/free5gc#366]
## Documentation request

I want to learn if UE to UE connectivity is possible in free5gc.

## Suggestion

I would really appreciate if there's some documentation on how we can enable one UE to ping another. 

## Additional context
None

**Comment by danielh1204** [comment]
Yes, it is possible to use one UE to ping another UE.
You can create another virtual machine and run ueransim on it. 
Here is the list of things to watch out for while setting up the second ueransim:
1. Host-only network interface IP address should be different from that of the first ueransim (e.g. 192.168.56.103)
2. The aforementioned address should be consistent with the one in free5gc-gnb.yaml and free5gc-ue.yaml
3. In free5gc-ue.yaml, the supi of the second UE should be different from the first one (e.g. 208930000000004)
4. After registered to free5gc successfully, open another terminal on this vm. run `ifconfig` to check if interface uesimtun0 is created, and its address should be different from that of the first UE.
5. Ping the first UE using `ping -I uesimtun0 <address of first UE's uesimtun0 interface>`
![image](https://github.com/free5gc/free5gc/assets/80144195/db0eb0a9-2e35-4255-a7b0-edebf5a108da)
7. To check if the first UE is being pinged, you can use 
`sudo tcpdump -i <pinged interface> icmp and icmp[icmptype]=icmp-echo` 
on the first UE. e.g. 
`sudo tcpdump -i 10.60.0.1 icmp and icmp[icmptype]=icmp-echo`

For setting up ueransim, you can refer to https://free5gc.org/guide/5-install-ueransim/#1-install-ueramsim-vm
For pinging and other network operations, you can refer to https://free5gc.org/guide/6-simple-app/

**Comment by ianchen0119** [comment]
Hi @RamzahRehmanPAK 
This issue would be closed due to there being no interaction for 2 weeks.
If you have any further questions,
please let me know, and I will re-open this issue.

Thanks a lot.
