### ISSUE TITLE
[Bugs]The terminal joins freee5gc and cannot download the video on the server in the LAN

### ISSUE THREAD

**Issue by xiaobinggan-zmh** [free5gc/free5gc#367]
I have deployed free5gc in k8s, and in my LAN, the terminal is successfully connected to the core network and can connect to the Internet.

Then, the terminal can access the HTML web page on the nginx server in the local LAN, but cannot access the video on the nginx server in the local LAN. How to solve this problem.

PS：The docker where UPF is located can download videos from nginx servers in the local LAN.

The free5GC version I use is latest。

**Comment by brianchennn** [comment]
This issue is the same as the [Forum Question](https://forum.free5gc.org/t/upf-failed-to-access-the-video-server/1635), so we decided to close it.
