### ISSUE TITLE
TestRegistration Test failing with invalid memory address

### ISSUE THREAD

**Issue by ameet-17** [free5gc/free5gc#37]
Hi!

I ran ./test.sh TestRegistration and it is failing. Error message is shown in the attachment. Please advise!

[TestRegistration_error.txt](https://github.com/free5gc/free5gc/files/4578550/TestRegistration_error.txt)

**Comment by daniel-garciasanchez** [comment]
I faced a similar issue triggering segmentation fault each run. I solved it reinstalling and running as **regular user, not root.** Give it a try with a non-root user.

**Comment by free5gc-org** [comment]
Hi @ameet-17 
If there still any problem?
Or maybe we can close the issue.

**Comment by ameet-17** [comment]
The issue still exists.

Thanks for your help!

Ameet

**Comment by free5gc-org** [comment]
Hi,
Can you provide more information?
Such as your OS, are you running in container, your kernel version, etc.

**Comment by ameet-17** [comment]
Hi,
I am not running 5GC and test script as root and using another account. 
OS version is Ubuntu 18.04.4 LTS
I am running this on a VM and not a container. 
Kernel version is 5.0.0-23-generic

**Comment by free5gc-org** [comment]
Seems to be the same problem on issue #67.

We'll try to work on the issue there.
