### ISSUE TITLE
[Docs] Misaligned test snippets

### ISSUE THREAD

**Issue by konradkar2** [free5gc/free5gc#370]
## Documentation request
Last two tests from this section https://github.com/free5gc/free5gc/wiki/Test have incorrect snippets, which results in errors.

## Additional context
Tested on 3.2.0

./test_ulcl.sh -om 3 TestRegistration
Usage: ./test_ulcl.sh [ TestRequestTwoPDUSessions ]

/test.sh TestReSynchronisation 
Usage: ./test.sh [ TestRegistration | TestGUTIRegistration | TestServiceRequest | TestXnHandover | TestN2Handover | TestDeregistration | TestPDUSessionReleaseRequest | TestPaging | TestNon3GPP | TestReSynchronization | TestDuplicateRegistration | TestEAPAKAPrimeAuthentication ]

**Comment by ianchen0119** [comment]
@konradkar2 

Thanks for your report.
I have updated the related contents.

thanks.
