### ISSUE TITLE
[Bugs] SMF sends PDU Session Establishment Reject to UE when it fails to release the old PDU session with duplicated PSI

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#371]
## Describe the bug
In PDU session establishment procedure, SMF sends PDU Session Establishment Reject to the UE when it fails to release the old PDU session with duplicated PSI by [#349](https://github.com/free5gc/free5gc/issues/349).   
As the issue comments say, according to "TS 24.501 5.4.5.2.5  case 12)" this release is "local release". And "local release" means "Release of a PDU session without peer-to-peer signalling between the network and the UE"(from TS 24.501 3.1 Definitions) .
Therefore, in this case, I think that it is incorrect to send PDU Session Establishment Reject.
I will rollback [PR#69](https://github.com/free5gc/amf/pull/69) in AMF, and modify SMF.

## To Reproduce
1. Establish PDU Session
2. Set smContext.SMContextState=4(ModificationPending) with debugger
3. Establish PDU Session with same PDU session ID in step 1

## Expected behavior
AMF sends back PDU Session Establishment Request with cause="Payload was not forwarded" to the UE.

## Environment
 - free5GC Version: v3.2.1
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version go1.14.4 linux/amd64

### PCAP File
[EstablishmentReject_DuplicatedPSI.zip](https://github.com/free5gc/free5gc/files/9187051/EstablishmentReject_DuplicatedPSI.zip)

## Additional context
I have sent PRs
* [amf](https://github.com/free5gc/amf/pull/74)
* [smf](https://github.com/free5gc/smf/pull/59)

**Comment by ianchen0119** [comment]
Hi @mariakagi 
I left a comment on your proposed PR of the AMF.
please help to check this when you feel free.

Thanks for your contributions!

**Comment by tim-ywliu** [comment]
Thanks for the PR.
