### ISSUE TITLE
[Feat]  Deployment using pure Linux network namespaces

### ISSUE THREAD

**Issue by konradkar2** [free5gc/free5gc#376]
I've created easy way of deploying free5gc and UERANSIM - inspired by your ./test.sh script

https://github.com/konradkar2/netns5g

This kind of deployment is really convenient if ones only wants to inspect free5gc or UERANSIM.
The big advantage over running it on localhost interface is that egress traffic gets proper IP address, so it's easy to recognize which service is sending a request.

If you have any ideas to improve the project then let me know.
Feel free to mention the project in your documentation if you want to.

ps.
Not sure whether I should place it here or somewhere else.

**Comment by free5gc-org** [comment]
@konradkar2 

We put it on our wiki. Thanks for your contribution.
