### ISSUE TITLE
[Feat] Change gtp5gnl library in test_multiUPF.sh

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#378]
## Issue Description

`free5gc/libgtp5gnl` is used in `test_multiUPF.sh`, but go-upf uses `free5gc/go-gtp5gnl`.
I think it is better to replace `free5gc/libgtp5gnl` with `free5gc/go-gtp5gnl` in this script.

### What's the version are you using

v3.2.1

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

[Pull Request](https://github.com/free5gc/free5gc/pull/377) for the feature.

### Describe alternatives/workarounds you've considered

None

### Additional context

None

**Comment by tim-ywliu** [comment]
Thanks for the PR!
