### ISSUE TITLE
[Bugs]If XnHandover is repeated, the NCC value will overflow.

### ISSUE THREAD

**Issue by RyuichiNamba-fj** [free5gc/free5gc#379]
## Describe the bug
According to TS33.501 6.2.3.2 Key identification.
>The next hop chaining count, NCC, represents the 3 least significant bits of this counter. 

With the current implementation, if the NCC value exceeds 7 after repeated XnHandover, the value will be set to more than 3 bits.

## To Reproduce
I have not tested the operation, but from reading the source, it is clear that it is not in accordance with the specifications.
I assume that repeating Xnhandover will cause the problem.

## Expected behavior
Behave according to the specifications written below.
>The next hop chaining count, NCC, represents the 3 least significant bits of this counter. 

## Environment (please complete the following information):
- free5GC Version: v3.2.1
- OS: Ubuntu 18.04
- Kernel version: 5.0.0-23-generic
- go version go1.14.4 linux/amd64

## Additional context
I have sent a [PR](https://github.com/free5gc/amf/pull/77)

**Comment by tim-ywliu** [comment]
Thanks for the PR.
