### ISSUE TITLE
test registration on wireshark shows "Destination unreachable"

### ISSUE THREAD

**Issue by ywang06** [free5gc/free5gc#38]
Hi Everyone,

We are working on using wireshark to observe the package while running test.sh registration, and all the packages on wireshark with filter"pfcp||icmp||gtp" shows "Destination Unreachable(Host unreachable)".  The destination address shows on wireshark is 192.168.1. xxx, protocol is ICMP.  I think it is related to the ip address settings in the configure file. We didn't change any ip address in the smfcfg.conf and uerouting.yaml file. Could you help us to take a look at this issue? 

Thank you,
Best Regards,
Ying

**Comment by free5gc-org** [comment]
Hi @ywang06 ,

Have you modify the config file maybe on other NF's?

**Comment by ywang06** [comment]
Thank you for the quick reply. We didn't modify any config file except adding ulcl:true at the end of smfcfg.conf.

**Comment by calee0219** [comment]
Can I check if the destination unreachable is 192.168 or 192.188?

**Comment by ywang06** [comment]
one of the destination unreachable is "192.168.1.160", others are "192.168.1.244" etc. 

When executing sudo iptables -t nat -A POSTROUTING -o ${DN_INTERFACE} -j MASQUERADE
, we replace ${DN_INTERFACE} with one of the network interface on the computer .

**Comment by ywang06** [comment]
we are running test.sh

**Comment by calee0219** [comment]
If it possible to provide your pcap file and your network setting on your host so that it's more easier for us to check the issue.

**Comment by free5gc-org** [comment]
If it possible to provide your pcap file and your network setting on your host so that it's more easier for us to check the issue.

**Comment by ywang06** [comment]
[registration.zip](https://github.com/free5gc/free5gc/files/4590330/registration.zip)
[Uploading test_registration_log.txt…]()
Both the pcap file and log file are attached. Thank yo so much for the help !

**Comment by ywang06** [comment]
[test_registration_log.txt](https://github.com/free5gc/free5gc/files/4590337/test_registration_log.txt)
Sorry, I think the log file wasn't uploaded properly.

**Comment by free5gc-org** [comment]
Which NIC are you trying to capture for your pcap file?

**Comment by ywang06** [comment]
all three network interfaces plus the loopback

**Comment by free5gc-org** [comment]
Can you try to listen "any" interface again

Because for our test, SMF and UPF will create an new veth while running the test script. I'm wondering if you can log on this interface or not.

**Comment by ywang06** [comment]
[registration_anyport.zip](https://github.com/free5gc/free5gc/files/4590427/registration_anyport.zip)
The file of any ports is uploaded. Thank you for the great help!

**Comment by free5gc-org** [comment]
I think now the gtp and pfcp have been successfully captured. Isn't it?

**Comment by ywang06** [comment]
Thank you very much for checking it. Yes, it does! Another question is do you think the destination unreachable for the ICMP message is expected?

**Comment by free5gc-org** [comment]
No,
The IP of your message event have no any relationship with our core network = =
