### ISSUE TITLE
[Bugs]Failed to send skb to unix domain socket PDR(4) (unable to ping ue after becoming idle)

### ISSUE THREAD

**Issue by ayoub-tl** [free5gc/free5gc#381]
Unable to ping the ue after becoming idle, 
after the uernaism ue become idle , when trying to ping the ue to trigger paging it doesn't work , but the service request by ping using the ue IP work normally , 
after debugging the kernel message started showing this message 

![image](https://user-images.githubusercontent.com/68382823/183452553-9b301e5d-0065-4ba6-bc89-cbcf460d7148.png)

**Comment by ianchen0119** [comment]
Hi @ayoub-tl 

Could you please provide more informations (e.g. free5gc log, pcap, OS version, free5GC version...)

Thanks.

**Comment by ianchen0119** [comment]
Hi @ayoub-tl 
This issue would be closed due to there being no interaction for 2 weeks.
If you have any further questions,
please let me know, and I will re-open this issue.

Thanks a lot.
