### ISSUE TITLE
Http wrapper - usage optimization

### ISSUE THREAD

**Issue by ubrovc** [free5gc/free5gc#382]
Hello,

I would have one question/suggestion regarding usage of http wrapper in internal/sbi modules. 
Please, could you comment suggestions (described below) and explain what is the purpose of this intermediate wrapper. 
Additionally, could you please let me know, if such optimization would be accepted, if we provide pull request for it.

# Problem description

Wrapper is used on all NF's during processing of incoming request (also for transferring relevant data from one function to another). On receipt of incoming request, following execution steps are performed:
- incoming request is matched in router.go. Appropriate function is called (function with HTTP prefix, e.g HTTPAmfContext3gpp on UDR),
- called HTTP function basic execution steps:
      - gets required values from parameters, headers or body (from gin.Context) and saves it in local variables (or directly to new HTTP request in some cases). 
      - creates new HTTP request with http wrapper (e.g. req := httpwrapper.NewRequest...)
      - inserts previously retrieved values from local variables into this new request as parameters, headers or body (if not yet included in new HTTP request during creation).
      - calls handle function from producer module (e.g. HandleAmfContext3gpp). Function is called with new HTTP request in input.
- called Handle function basic execution steps:
   - gets required values from input HTTP request (created with http wrapper in previous function) and saves them to local variables.
   - calls function, which executes business logic, so called 'final' procedure (e.g. AmfContext3gppProcedure). Function is called only with local variables in input (HTTP request is not relevant anymore in this part!)
- called 'final' procedure function provides business logic based on input variables.

According to defined execution steps, there are two things, which seems redundant from my point of view:
- usage of wrapper: all values are already retrieved, before calling Handle function. Instead of just passing required values to Handle function, wrapper is introduced to create new HTTP request, just for the sake of transferring required variable values to Handle function. In this step I would suggest to call Handle functions with all needed variable values only (not with HTTP request).
- Handle function is used for retrieving values from input HTTP request. If we would not use HTTP request as input, we don't need this part of code or special handle function. In this case we could make all processing in single function (Handle and Procedure function can be one single function).

This suggestion is issued mainly because of:
- Usage of http wrapper introduces additional performance cost, which is not necessary in this case.
- Code is more compact without intermediate functions (Handle functions). Code is also more readable in this case.

# Example
To be more exact, there is example of old and new suggested code optimization.

Old code (check comments for more info):
```
// Router.go calls HTTP function. Function location: internal/sbi/datarepository/api_smf_registrations_collection.go
func HTTPQuerySmfRegList(c *gin.Context) {
	req := httpwrapper.NewRequest(c.Request, nil)
	
	// Parameter is retrieved from received Gin context and inserted to newly created HTTP request
	req.Params["ueId"] = c.Params.ByName("ueId")  

	rsp := producer.HandleQuerySmfRegList(req)

	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := models.ProblemDetails{
			Status: http.StatusInternalServerError,
			Cause:  "SYSTEM_FAILURE",
			Detail: err.Error(),
		}
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody)
	}
}

// HTTPQuerySmfRegList calls this function. Function location: internal/sbi/producer/data_repository.go
func HandleQuerySmfRegList(request *httpwrapper.Request) *httpwrapper.Response {
	logger.DataRepoLog.Infof("Handle QuerySmfRegList")

	collName := "subscriptionData.contextData.smfRegistrations"
	
	// We are again retrieving ueId from HTTP request. This value was already defined in HTTPQuerySmfRegList function!
	ueId := request.Params["ueId"]  
	
	// 'final' procedure function is called, but not with HTTP request! 
	response := QuerySmfRegListProcedure(collName, ueId)

	if response == nil {
		return httpwrapper.NewResponse(http.StatusOK, nil, []map[string]interface{}{})
	} else {
		return httpwrapper.NewResponse(http.StatusOK, nil, response)
	}
}

// 'final' function procedure - called from HandleQuerySmfRegList. Function location: internal/sbi/producer/data_repository.go
func QuerySmfRegListProcedure(collName string, ueId string) *[]map[string]interface{} {
	
	// Using only input variables. Http request in not needed in this part!
	filter := bson.M{"ueId": ueId}
	smfRegList, err := mongoapi.RestfulAPIGetMany(collName, filter)
	if err != nil {
		logger.DataRepoLog.Errorf("QuerySmfRegListProcedure err: %+v", err)
		return nil
	}

	if smfRegList != nil {
		return &smfRegList
	}
	return nil
}
```

New code with suggested optimization (check comments for more info):
```
// Router.go calls HTTP function. Function location: internal/sbi/datarepository/api_smf_registrations_collection.go
func HTTPQuerySmfRegList(c *gin.Context) {

	// Retrive ueID. Additionally there is also performed validity of UeId value structure. 
	ueID := models.VarUeId(c.Params.ByName("ueId"))
	if err := ueID.Valid(); err != nil {
		pd := models.NewProblemDetails(models.ProblemDetailsCause_MANDATORY_QUERY_PARAM_INCORRECT)
		pd.AppendInvalidParams(err)
		c.JSON(int(err.Status), pd)
	}

	// Calling httpwrapper is removed!!

	// Call procedure directly with UeID. Handle function is not required!
	response := producer.QuerySmfRegListProcedure(collName, string(ueID))

	if response == nil {
		c.Status(http.StatusOK)
		return
	} else {
		c.JSON(http.StatusOK, response)
		return
	}
}

// HTTPQuerySmfRegList calls this function. Function location: internal/sbi/producer/data_repository.go
func QuerySmfRegListProcedure(ueId string) *[]map[string]interface{} {
	
	// Define collection name, set filter...
	collName := "subscriptionData.contextData.smfRegistrations"
	filter := bson.M{"ueId": ueId}
	
	smfRegList, err := mongoapi.RestfulAPIGetMany(collName, filter)
	if err != nil {
		logger.DataRepoLog.Errorf("QuerySmfRegListProcedure err: %+v", err)
		return nil
	}

	if smfRegList != nil {
		return &smfRegList
	}
	return nil
}

```

**Comment by Leon777-coder** [comment]
Hello:
What you said is correct, in fact, we were biased toward your idea at the beginning. It’s just that we think that the Handle function and gin’s architecture can be designed separately to have better scalability in the future, but it doesn't look like there will be any more schema changes for now. So of course your idea would work, but our team has no plans to change this part for the time being. In addition, if it is convenient, can you please provide a benchmark test? We also want to know how much performance will be lost in this part.

Thanks
