### ISSUE TITLE
FYI: Sample configurations - Select UPF based on S-NSSAI & ULCL

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#383]
Hi all,

I wrote two very simple configurations using free5GC v.3.2.1 and UERANSIM v3.2.6.

- [Select UPF based on S-NSSAI](https://github.com/s5uishida/free5gc_ueransim_snssai_upf_sample_config)
- [ULCL](https://github.com/s5uishida/free5gc_ueransim_ulcl_sample_config)

I think that these are the basic and minimal configurations to confirm these features.

For your reference.

**Comment by free5gc-org** [comment]
@s5uishida 

Thanks! Already add them to free5gc wiki page.

**Comment by s5uishida** [comment]
Thanks!

**Comment by s5uishida** [comment]
Hi @free5gc-org 

If you don't mind, I would be very glad if you could add to your wiki a link of the following I wrote earlier.

[One SMF, Multiple DNN and UPF (without ULCL)](https://github.com/s5uishida/free5gc_ueransim_sample_config)

Many thanks to free5GC's excellent efforts.

Best regards,

--Shigeru
