### ISSUE TITLE
[Bugs] checksum mismatch for Gin library

### ISSUE THREAD

**Issue by ubrovc** [free5gc/free5gc#386]
## Describe the bug
During installation of free5gc core (following: https://github.com/free5gc/free5gc/wiki/Installation), error is reported during compile of NF's:
```
verifying github.com/gin-gonic/gin@v1.7.3: checksum mismatch
        downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
        go.sum:     h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=
```

Problem is reported for NF's, which are using gin library: directly specified in go.mod or indirectly via another library which is using gin package (e.g. github.com/free5gc/util). 

According to gin library issues, there was a checksum mismatch produced by them and later resolved: https://github.com/gin-gonic/gin/releases/tag/v1.7.4 
Therefore, I would suggest usage of new version 1.7.4 (at least or higher), which is not causing those problems anymore.
In case of 1.7.4 or higher gin version, compilation is successful also with higher go versions.

## To Reproduce
1. Use Go with higher version as recommended in installation guides (e.g. 1.18.1)
2. Follow steps defined in installation guides (except go version):  https://github.com/free5gc/free5gc/wiki/Installation
3. During compilation of all NF's (use 'make' without specified NF name), error shall be displayed.

## Expected behavior
Compilation shall be successful for all NF's, also on higher go versions.

## Environment (please complete the following information):
 - free5GC Version: v3.2.1
 - OS: Ubuntu 20.04.4 LTS
 - Kernel version: Linux 5.4.0-109-generic
 - go version: 1.18.1 linux/amd64

**Comment by linpoyi** [comment]
Hi @ubrovc ,

thanks for reporting this problem, we've already updated the installation steps, so maybe take a look if you're still interested in this problem. Also, we have updated free5GC to v3.3.0, and it would be nice if you check that out too. 

BRs,
linpoyi

**Comment by brianchennn** [comment]
@ubrovc
