### ISSUE TITLE
Add docker-free5gc to free5gc organization

### ISSUE THREAD

**Issue by abousselmi** [free5gc/free5gc#39]
Hi,

This project [abousselmi/docker-free5gc](https://github.com/abousselmi/docker-free5gc) simplifies the deployment of Free5GC using docker. Each entity has its own image/container and a docker-compose file is used to launch the whole thing :rocket: . Tell me what you think of it and if it would be ok to make a free5gc project :smile: 

Cheers,

**Comment by free5gc-org** [comment]
Hi,
We have release our version of compose file.
Maybe you can help us to improve it! 💪 
Thanks a lot!!!

**Comment by abousselmi** [comment]
Hi,

That's a very good news :+1: :clap:. So what do you think about:
  - optimizing the generated docker images :whale2: : we could use a multi stage build to generate binaries and create an image that we call `base` which will be used to generate NFs images such as [here](https://github.com/abousselmi/docker-free5gc/blob/master/base/Dockerfile). NFs images will be pretty lightweight (roughly 90M each)
  - use [network aliases](https://docs.docker.com/compose/compose-file/compose-file-v2/#aliases) instead of fixed IP addresses
  - update the structure of the project to create a dockerfile per network function (for maintainability and adaptability with the style of main free5gc project)

Those are few things that I could think about :bulb:right now :smiley: 

Bests,

**Comment by ywang06** [comment]
May I ask the detailed information for the released docker image? 

> Hi,
> We have release our version of compose file.
> Maybe you can help us to improve it! 💪
> Thanks a lot!!!

**Comment by free5gc-org** [comment]
@abousselmi 
The first two suggestion sounds great, I think we can do it.
But I'm not quite understand the third one?

**Comment by free5gc-org** [comment]
@ywang06 

You can check it on https://github.com/free5gc/free5gc-compose

**Comment by abousselmi** [comment]
@free5gc-org 
For the 3rd one, the idea is to have a structure like the following:

```console
/
+-- base
¦   +-- Dockerfile
+-- amf
¦   +-- Dockerfile
+-- smf
¦   +-- Dockerfile
+-- upf
¦   +-- Dockerfile
+-- ...
¦   +-- Dockerfile
+-- config/
¦   +-- amfcfg.conf
¦   +-- smfcfg.conf
¦   +-- upfcfg.yaml
¦   +-- ...
+-- ...
+-- docker-compose.yml
```
In a second step, this will ease creating a docker hub auto build to publish images.

**Comment by free5gc-org** [comment]
This sound useful if we comes to step 2.

Another question is that is it possible to separate by docker file instead of separate by folder for multiple docker image building?

**Comment by abousselmi** [comment]
That's also a good option. Let's do it in that way !

**Comment by free5gc-org** [comment]
Accurately this is a question 😅 , because I'm not familiar with docker hub auto build.
I'm not sure if it's better to use file separate or using folder to separate the building image.

**Comment by abousselmi** [comment]
Yes both options can be used with auto build on docker hub. But I think that folders is more like the default/common way of doing different builds (independently from docker hub). Dockerfiles with different names on the root of the project is also possible. I like the first option, but the second one is ok also.

**Comment by free5gc-org** [comment]
Through I'm still not sure which one is better, I think we can obey the public and use the folder structure.

**Comment by free5gc-org** [comment]
Thanks to @abousselmi , we improve this issue
