### ISSUE TITLE
[Question] Integrity NIA0 is emergency

### ISSUE THREAD

**Issue by zmkglb** [free5gc/free5gc#390]
Hello everyone. 
I'm trying to connect free5gc with gNB and UE.
While connecting i get the following errors:
![image](https://user-images.githubusercontent.com/71176172/187458635-62906bd9-7351-4549-81c0-90d1f6f1f2d1.png)
What could be the problem? I checked all the parameters of the subscriber, the correctness of the NF configs too.

**Comment by zmkglb** [comment]
AMF: 
info:
  version: 1.0.3
  description: AMF initial local configuration

configuration:
  amfName: AMF # the name of this AMF
  ngapIpList:  # the IP list of N2 interfaces on this AMF
    - 10.2.0.32
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.18 # IP used to register to NRF
    bindingIPv4: 127.0.0.18  # IP used to bind the service
    port: 8000 # port used to bind the service
    tls: # the local path of TLS key
      pem: config/TLS/amf.pem # AMF TLS Certificate
      key: config/TLS/amf.key # AMF TLS Private key
  serviceNameList: # the SBI services provided by this AMF, refer to TS 29.518
    - namf-comm # Namf_Communication service
    - namf-evts # Namf_EventExposure service
    - namf-mt   # Namf_MT service
    - namf-loc  # Namf_Location service
    - namf-oam  # OAM service
  servedGuamiList: # Guami (Globally Unique AMF ID) list supported by this AMF
    # <GUAMI> = <MCC><MNC><AMF ID>
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      amfId: cafe00 # AMF identifier (3 bytes hex string, range: 000000~FFFFFF)
  supportTaiList:  # the TAI (Tracking Area Identifier) list supported by this AMF
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      tac: 1 # Tracking Area Code (uinteger, range: 0~16777215)
  plmnSupportList: # the PLMNs (Public land mobile network) list supported by this AMF
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      snssaiList: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
  supportDnnList:  # the DNN (Data Network Name) list supported by this AMF
    - default
  nrfUri: http://127.0.0.10:8000 # a valid URI of NRF
  security:  # NAS security parameters
    integrityOrder: # the priority of integrity algorithms
       - NIA2
      # - NIA0
      # - NIA0
    cipheringOrder: # the priority of ciphering algorithms
       - NEA0
  networkName:  # the name of this core network
    full: free5GC
    short: free
  locality: area1 # Name of the location where a set of AMF, SMF and UPFs are located
  networkFeatureSupport5GS: # 5gs Network Feature Support IE, refer to TS 24.501
    enable: true # append this IE in Registration accept or not
    length: 1 # IE content length (uinteger, range: 1~3)
    imsVoPS: 0 # IMS voice over PS session indicator (uinteger, range: 0~1)
    emc: 0 # Emergency service support indicator for 3GPP access (uinteger, range: 0~3)
    emf: 0 # Emergency service fallback indicator for 3GPP access (uinteger, range: 0~3)
    iwkN26: 0 # Interworking without N26 interface indicator (uinteger, range: 0~1)
    mpsi: 0 # MPS indicator (uinteger, range: 0~1)
    emcN3: 0 # Emergency service support indicator for Non-3GPP access (uinteger, range: 0~1)
    mcsi: 0 # MCS indicator (uinteger, range: 0~1)
  t3502Value: 720  # timer value (seconds) at UE side
  t3512Value: 3600 # timer value (seconds) at UE side
  non3gppDeregistrationTimerValue: 3240 # timer value (seconds) at UE side
  # retransmission timer for paging message
  t3513:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Deregistration Request message
  t3522:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Registration Accept message
  t3550:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Authentication Request/Security Mode Command message
  t3560:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Notification message
  t3565:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission
  # retransmission timer for NAS Identity Request message
  t3570:
    enable: true     # true or false
    expireTime: 6s   # default is 6 seconds
    maxRetryTimes: 4 # the max number of retransmission

# the kind of log output
# debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
# ReportCaller: enable the caller report or not, value: true or false
logger:
  AMF:
    debugLevel: debug
    ReportCaller: false
  NAS:
    debugLevel: info
    ReportCaller: false
  FSM:
    debugLevel: info
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false

**Comment by zmkglb** [comment]
[amfcfg.txt](https://github.com/free5gc/free5gc/files/9453708/amfcfg.txt)

**Comment by tim-ywliu** [comment]
@zmkglb 

Which version of free5gc did you use?
Please provide the full log and pcap file.

**Comment by zmkglb** [comment]
Log file. It's the log of another run, but with the same configuration and
errors

вт, 20 сент. 2022 г. в 13:19, Глеб Замковой ***@***.***>:

**Comment by zmkglb** [comment]
> @zmkglb
> 
> Which version of free5gc did you use? Please provide the full log and pcap file.
Free5gc 3.2.1
[free5gc.zip](https://github.com/free5gc/free5gc/files/9606656/free5gc.zip)

**Comment by zmkglb** [comment]
Hello, this is the complete pcap file. Right now I can't send you the full
log file, maybe later if it is necessary

вт, 20 сент. 2022 г. в 06:35, tim-ywliu ***@***.***>:

**Comment by jay16213** [comment]
I think this issue is due to the context mismatch between AMF and your UE

From the pcap file, the UE think it registered to the core network before, so it uses old context to try to register to AMF again

but at AMF side, it does not had the old context for this UE (because free5gc NFs does not store the context if you restart them), so AMF assign a already in used ngKSI to it.

Now, UE send an Authentication failure with cause "NgKSI already in use" to AMF, and this message is integrity protected by UE's NAS security context (the requirement from 3gpp spec)

![image](https://user-images.githubusercontent.com/17217471/195122338-d3111b1f-7336-4148-b9b5-dde081c9d36a.png)

Finally, AMF receive an security protected NAS message and can not verify the message integrity because AMF can not find the old context for this UE (NIA0 is the default algorithm if AMF can not find any NAS security context for UEs)

Fortunately, the registration procedure still can be done because authentication procedure would be retried, then AMF and UE finally authenticate each other and finish registration.

![image](https://user-images.githubusercontent.com/17217471/195123332-89bd5cfd-def9-469d-93be-fc4dc0d065fc.png)


To solve this problem, you need to clear the old context on your UE (maybe restart it, or enter flight mode, etc.) or you can just ignore this warning if the registration is success.
