### ISSUE TITLE
[Bugs] Multiple PDU session on single UPF - ip route

### ISSUE THREAD

**Issue by konradkar2** [free5gc/free5gc#395]
There's a little bug in free5gc 3.2.1 which denies packet going out of upfgtp interface for any additional DNN on the UPF.
It is fixed in this UPF's patch https://github.com/free5gc/go-upf/commit/235f16c8e9a2250df22d03beb0bea4274288401f
The patch is not yet included in free5gc, but it you can manually apply it - just recompile free5gc.

Just leaving this for anyone having the same problem, I believe it will be soon included in free5gc.

**Comment by tim-ywliu** [comment]
Thanks for reminding. The UPF hash of free5gc was already updated.
