### ISSUE TITLE
[Question]: UDM Event Exposure 

### ISSUE THREAD

**Issue by Aharonez** [free5gc/free5gc#396]
Hey,
does UDM EE is supported?
also, while I do get-response for AMF EE (just a response, not a constant subscription notification), will the notification to the uri is expected to be supported?

Thanks

**Comment by Jerry0666** [comment]
Hello, UDM event exposure is not supported.
In AMF event exposure, now you can only get event report in subscription response, the notification to the uri is not supported(We haven't implemented notify yet.).
