### ISSUE TITLE
[Bugs] amf3gppAccess: Unnecessary fields are added by deregistration

### ISSUE THREAD

**Issue by mariakagi** [free5gc/free5gc#398]
## Describe the bug

"Guami" field is added to subscriptionData.contextData.amf3gppAccess by UE deregistration.

## To Reproduce
1. Run TestRegistration
2. Dump subscriptionData.contextData.amf3gppAccess
    ```
    {
      "_id" : ObjectId("631ad12430bd5dd58d2999b9"),
      "amfInstanceId" : "eaddf73d-d2ef-41d8-98f2-46959fec65b0",
      "imsVoPs" : "HOMOGENEOUS_NON_SUPPORT",
      "deregCallbackUri" : "",
      "initialRegistrationInd" : true,
      "guami" : {
        "plmnId" : {
          "mcc" : "208",
          "mnc" : "93"
        },
        "amfId" : "cafe00"
      },
      "ratType" : "",
      "ueId" : "imsi-2089300007487"
    }
    ```
3. Run TestDeregistration
4. Dump subscriptionData.contextData.amf3gppAccess
    ```
    {
      "_id" : ObjectId("631ad54aad7a0ffc9f09c736"),
      "amfInstanceId" : "3e187a21-a49c-4b50-b3cf-1c3c9806a029",
      "imsVoPs" : "HOMOGENEOUS_NON_SUPPORT",
      "deregCallbackUri" : "",
      "initialRegistrationInd" : true,
      "guami" : {
        "amfId" : "cafe00",
        "plmnId" : {
          "mcc" : "208",
          "mnc" : "93"
        }
      },
      "ratType" : "",
      "ueId" : "imsi-2089300007487",
      "Guami" : {                        // added
        "amfId" : "cafe00",
        "plmnId" : {
          "mcc" : "208",
          "mnc" : "93"
        }
      },
      "PurgeFlag" : true                 // added
    }
    ```
5. Compare the results of 2 and 4 (Except value of _id and amfInstanceId).

## Expected behavior

Only "purgeFlag" is added by UE deregistration.

## Environment (please complete the following information):
 - free5GC Version: v3.2.1
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version go1.14.4 linux/amd64

## Additional context
[Pull Request](https://github.com/free5gc/udm/pull/15) for the fix.

**Comment by tim-ywliu** [comment]
Thanks for the PR.
