### ISSUE TITLE
Test.sh Inconsistantly Failed for upfgtp0 create fail 

### ISSUE THREAD

**Issue by ywang06** [free5gc/free5gc#40]
Hi Everyone, 

When running test.sh, we have seen this error very often(please see follow log information and attached file). The way to fix it currently is get the entire folder of free5gc from git and recompile. 
It seems like some configure file got changed when running free5gc. May I ask any suggestions on this? 

[failed_log.txt](https://github.com/free5gc/free5gc/files/4594005/failed_log.txt)
[pass_log.txt](https://github.com/free5gc/free5gc/files/4594006/pass_log.txt)

Best Regards,
Ying
--------------------------------------Failed Test---------------------------------------

_INFO[2020-05-07T11:03:36-04:00] /home/parallels/go/src/free5gc/src/upf/src/upf_init.c:35 UpfInit() Config: /home/parallels/go/src/free5gc/src/upf/build/config/upfcfg.test.yaml  UPF=Util
INFO[2020-05-07T11:03:36-04:00] Set log level: info                           UPF=Util
ERRO[2020-05-07T11:03:36-04:00] /home/parallels/go/src/free5gc/src/upf/lib/gtpv1/src/gtp_link.c:27 GtpLinkCreate() GTP device named upfgtp0 Create fail  UPF=Util_

--------------------------------------Passed Test---------------------------------------
_parallels@parallels-Parallels-Virtual-Platform:~/go/src/free5gc$ ./test.sh TestRegistration
INFO[2020-05-06T22:09:24-04:00] /home/parallels/go/src/free5gc/src/upf/src/upf_init.c:35 UpfInit() Config: /home/parallels/go/src/free5gc/src/upf/build/config/upfcfg.test.yaml  UPF=Util
INFO[2020-05-06T22:09:24-04:00] Set log level: info                           UPF=Util
INFO[2020-05-06T22:09:24-04:00] /home/parallels/go/src/free5gc/src/upf/src/up/up_path.c:40 UpRouteInit() APN routes added, main routing table:  UPF=Util
INFO[2020-05-06T22:09:24-04:00] /home/parallels/go/src/free5gc/src/upf/lib/knet/src/route.c:202 KnetPrintRoutes() DstIp               Gateway        Iface     Priority RtProto   Type         UPF=Util
INFO[2020-05-06T22:09:24-04:00] /home/parallels/go/src/free5gc/src/upf/lib/knet/src/route.c:237 KnetPrintRoutes() 10.200.200.0 /24    0.0.0.0        veth1     0        kernel_

**Comment by free5gc-org** [comment]
Hi,

When it comes to Failed Test, is your gtp5g module insert into kernel?

**Comment by ywang06** [comment]
how can I test whether gtp5g is inserted?  
According to our observation, after a clean install, if run test.sh directly, the test pass. If run run.sh first and then run test.sh , the test.sh will not work anymore, as in failed log

**Comment by free5gc-org** [comment]
You can use `lsmod | grep gtp5g` to check if the module has been inserted

**Comment by ywang06** [comment]
Thank you very much for the great help. When the error shows up, there is no respond when input lsmod | grep gtp5g, when there is no error, the response is  "udp_tunnel 16384 1 gtp5g".   should we re-install the gtp5g when the error shows up?

**Comment by free5gc-org** [comment]
@ywang06 
The UPF depend on gtp5g module. You should always have gtp5g before you run the UPF.
