### ISSUE TITLE
[Docs] Implementing a new NF from OpenAPI generated code

### ISSUE THREAD

**Issue by arieldll** [free5gc/free5gc#401]
**If the design issue template is not followed, the issue might be closed.**

## Documentation request

Hi all,

I am started to work with free5gc in the last two weeks. I am trying to implement a simple new NF (NEF - TS29591_Nnef_EventExposure) based on the 3GPP function using OpenAPI generated from the yaml file,  using go as the programming language. 
Is there a step-by-step way to deploy a new NF using OpenAPI? If there aren't a step-by-step, where is the starting point to make it?  

## Additional context
Someone can help me? Thank ou so much, Best regards

**Comment by ianchen0119** [comment]
Maybe you can try this:
```
$ git clone https://github.com/jdegre/5GC_APIs.git
$ cd 5GC_APIs
$ docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i TS29522_5GLANParameterProvision.yaml -g go-gin-server -o /local/output
```
