### ISSUE TITLE
Disable NAS message encryption

### ISSUE THREAD

**Issue by ekoops** [free5gc/free5gc#403]
Hi folks! How can I disable NAS message encryption?

**Comment by Jerry0666** [comment]
Hello! Do you want to read the content of NAS messages in pcap file? If you want to do that, in wireshark go to preferences -> Protocols -> NAS-5GS -> check the box "Try to detect and decode 5G-EA0 ciphered message".

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/session-getting-instantly-released-when-using-real-gnb-and-ue-semantic-error-in-the-qos-operation/2757/9
