### ISSUE TITLE
[Question] How to set Flow rules (IP filtering) in webconsole?

### ISSUE THREAD

**Issue by konradkar2** [free5gc/free5gc#405]
I’d like to control Flow Rules by Webconsole, are there any examples for that?

I’ve tried following
https://forum.free5gc.org/uploads/default/original/1X/177986a36431070a2a9e7d438fd535c79fa12a20.png

I was expecting that bandwidth would be limited to 5 Mbps, but nothing changed, tested with iperf3 (tcp).
I have also tried following rules:

permit in 6 from any to any
permit out 6 from any to any

permit in 6 from any to 10.100.201.11
permit out 6 from 10.100.201.11 to any

permit out 6 from any to any

Am I using invalid syntax or is this not implemented yet?

**Comment by ianchen0119** [comment]
Close this issue due to it's duplicated with the free5gc forum.
