### ISSUE TITLE
Question about multiple UPF

### ISSUE THREAD

**Issue by sing1020** [free5gc/free5gc#406]
Hello All,

I followed the video below to try to set it up, but I got error when run UPFs.
[Environment setup of multiple SMF, DNN, and UPF](https://www.youtube.com/watch?v=AEMrjKRWarw&ab_channel=free5GC)

![image](https://user-images.githubusercontent.com/111422226/198243730-dfdd3e4d-a6b2-46d8-80ec-ee0a73b3e410.png)
I got the error when run the I-UPF, PSA-UPF1 and PSA-UPF2.
I don't understand why there is this problem? I even gave the absolute path to the file and still have this error.

Linux version: ubuntu-20.04.5-live-server-amd64
free5GC version: v3.2.1

Any suggestions and help are appreciated~:) 

Best Regrad
Hsin

**Comment by konradkar2** [comment]
Have you tried to provide config directly to the executable? 
e.g:
sudo ./bin/upf -c ./config/upfcfg.yaml
If you did and it's still not working, you could try to change linux file permissions for the config.

**Comment by sing1020** [comment]
Hi, @konradkar2 

Thanks for your help, I tried "sudo ./bin/upf -c ../config/upfcfg.yaml" to solve the error above.
But I got another error...
![image](https://user-images.githubusercontent.com/111422226/198923241-153c0373-a80a-42ce-855b-2bd6b2651be7.png)

I tried to search related issues on free5gc forum/issue and google, but I couldn't find any relevant solutions.

Any suggestions and helps are appreciated:)

Thanks

Best Regrad
Hsin

**Comment by tim-ywliu** [comment]
@sing1020 

Did you compile and install gtp5g? If no, please follow https://github.com/free5gc/free5gc/wiki/Installation#c-install-user-plane-function-upf.

**Comment by sing1020** [comment]
Hi @tim-ywliu 

I installed and compiled gtp5G then it could work.
Thank you.
