### ISSUE TITLE
Sending PFCP messages from SMF

### ISSUE THREAD

**Issue by rp00751** [free5gc/free5gc#407]
Just wondering if anyone can help with any suggestions. I am trying to send different PFCP messages to the UPF to simulate attacks where a session modification or deletion request is generated from the SMF.

I have had a look at modifying some of the test scenarios but I am a bit confused as these are implemented via the AMF but I want to generate directly from the SMF to simulate a malicious SMF.

I also considered sending the PFCP message via the CLI as would be done with the http CURL command but I am lost in how to achieve it this way.

Any ideas are appreciated!

**Comment by ianchen0119** [comment]
Hi @rp00751 

> I am a bit confused as these are implemented via the AMF but I want to generate directly from the SMF to simulate a malicious SMF.

UPF & SMF only accept the PFCP message sent from the remote node which has already established the n4 association.
So, the malicious SMF is hard to be a threat (The operator often deploys the 5GC in the private network environment, so, the attacker wants to send a malicious packet to UPF via SMF directly is impossible).
