### ISSUE TITLE
[Docs] Document changing the webconsole-password

### ISSUE THREAD

**Issue by kelke** [free5gc/free5gc#409]
## Documentation request

I could not find any information about changing the webconsole-password.
Hardcoding user and password information is obviously a bad idea and completely defeats the use of passwords. Maybe I have missed something, but if not, this is a serious problem.

## Suggestion

Include documentation on changing the webconsole-password in the wiki.

## Additional context

Since this is an open-source project, one can obviously change the password somehow. An easier option would still be very much appreciated.

**Comment by kelke** [comment]
I found the source file, containing the password:
https://github.com/free5gc/webconsole/blob/main/frontend/src/config/config.js

But only being able to change the password before building is not a great security practice in my opinion

**Comment by ianchen0119** [comment]
Hi @kelke 

Thanks for your suggestions.

I agree with you that we hard code the password in the webconsole is insecure.
But the webconsole is not born for commercial purpose.
If you want to enhance the security of the webconsole, you could try to modify the existing JWT authentication mechanism for multi-tenant :)

**Comment by tim-ywliu** [comment]
@kelke 

We welcome any PR for this.
