### ISSUE TITLE
unsupported: aper.Enumerated error

### ISSUE THREAD

**Issue by sothy** [free5gc/free5gc#41]
Hello,
When I'm using <<go test -v -vet=off -run TestNGSetup>>
I'm getting this error:unsupported: aper.Enumerated error
It is happening here:
 ngap.Encoder(message)

Do you any clue?

Thanks
Sothy

**Comment by free5gc-org** [comment]
Hi,

TestNGSetup is not for testing. It's just for separating the function we need in our test.
