### ISSUE TITLE
[Bugs] AMF doesnt reroute the registration to another amf  when it cant handle the NSSAI

### ISSUE THREAD

**Issue by ayoub-tl** [free5gc/free5gc#413]
the amf doesnt  reroute the registration to another amf  when it cant handle the NSSAI , and the amf doesn't check the NSSAi parameter rather it accept everything and authenticate the UE, 
the normal behavior is :
During Registration, the initial AMF using the information, e.g. Requested NSAAI and subscribed NSSAI received from the device and UDM respectively and as well as inquiry from NSSF (Network Slice Selection Function) is able to check whether it can handle the registration process or it should re-route the registration request to another AMF (target AMF) for the further action. The target AMF then prepares the allowed and configured NSAAI and delivers it to the device via NAS-5GMM Registration Accept message.

**Comment by lin310581031** [comment]
Hi,

Did you mean that newest free5GC doesn't switch to another AMF when current AMF can't handle the NSSAI?

**Comment by linpoyi** [comment]
Hi @ayoub-tl,
Thanks for reporting this bug, we'll be working on the AMF selection and rerouting.

BRs,
Linpoyi

**Comment by ianchen0119** [comment]
Hi @ayoub-tl 

This issue has been solved on main branch.
Please help to test it when you feel free.

Thanks.
