### ISSUE TITLE
[Bugs] wrong smContextNotifyUri in SMF after Mobility Update Request

### ISSUE THREAD

**Issue by giuliocarot0** [free5gc/free5gc#414]
## Describe the bug
After the Mobile Update Request from the UE, the UE TMSI can be refreshed by the AMF. Consequently the GUTI will change.
The SMF uses the following uri to send smContext Status related notifications from the AMF: /namf-callbacks/v1/smContextStatus/<UE-GUTI>/<PDU_SESSION_ID>.
After the GUTI changes, the SMF is not informed about so it will keep sending notifications to the old GUTI triggering a 404 error in the AMF. This will result in several procedure failings. 
Is there something from the Specification side that I am not getting? Or is it a bug?

## To Reproduce
1. Mobility Update Request Initiated by the UE
2. Initiate a PDUSessionRelease procedure from the UE.

**Comment by mariakagi** [comment]
I have sent a [PR](https://github.com/free5gc/amf/pull/81) for this problem.

**Comment by tim-ywliu** [comment]
Thanks for the PR.
