### ISSUE TITLE
Question to your Security Policy

### ISSUE THREAD

**Issue by tobiasfunke1** [free5gc/free5gc#417]
Hello free5GC Team,

we have found a security vulnerability in free5GC and would like to report it to you. Which communication channel do you prefer to be informed about it?

Best regards
Tobias Funke, Radix Security

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/whats-your-security-vulnerability-disclosure-policy/1848/1

**Comment by tobiasfunke1** [comment]
Any updates on this issue?

**Comment by YouShengLiu** [comment]
Hi @tobiasfunke1,

It looks like that your question was solved in [http://forum.free5gc.org/t/whats-your-security-vulnerability-disclosure-policy/1848/1](http://forum.free5gc.org/t/whats-your-security-vulnerability-disclosure-policy/1848/1).

**Comment by tobiasfunke1** [comment]
Hi,

I was able to reach a person via the free5gc forum to send my report to. The vulnerability has also been fixed, but for the future it would be useful to use the cool [Github vulnerability reporting feature](https://github.com/free5gc/free5gc/security). This will make it easier to report vulnerabilities in the future instead of having to search for weeks for the right person to contact.
