### ISSUE TITLE
[Bugs] After N2 Handover, if new PDU Session Req AMF sends Initial Context Set Req

### ISSUE THREAD

**Issue by giuliocarot0** [free5gc/free5gc#418]
## Description
I am implementing LADN support in free5GC, but after a N2 Handover, when I try instantiate a new PDU Session for a new available LADN, it takes some extra time due to the AMF sending an Initial Context Setup Request. 
The request is sent from the N1N2Transfer Procedure because the flag "SentInitialContextSetupRequest" is set to false inside the UE AMF Context.
Would it be sufficient to set this parameter to true after that the HO Procedure is completed? Or am I missing something? I guess the InitialContextSetupReq is not necessary after a N2 HO Procedure, since the t-gNB is already aware of the new UE Context...

## To Reproduce
1. Execute a N2 Handover
2. Request a new PDU Session from the UE

**Comment by ianchen0119** [comment]
Hi @giuliocarot0 

Could you provide the pcap over n1/n2 interface?

thanks.

**Comment by ianchen0119** [comment]
Hi @giuliocarot0 

This issue would be closed due to there being no interaction for 2 weeks.
If you have any further questions,
please let me know, and I will re-open this issue.

Thanks a lot.
