### ISSUE TITLE
How to deploy N2IWF in docker

### ISSUE THREAD

**Issue by Sivanesh1992** [free5gc/free5gc#419]
Hi All,

I want know how to deploy N3IWF code in docker to connect amf and upf.

what are the configuration need to change ?

**Comment by ianchen0119** [comment]
Hi @Sivanesh1992 
Do you mean N3IWF?

Thanks.

**Comment by Sivanesh1992** [comment]
yes N3IWF

**Comment by ianchen0119** [comment]
Hi @Sivanesh1992 

Please refer to https://github.com/free5gc/free5gc-compose/tree/master
It might be help to you.


Thanks.

**Comment by Sivanesh1992** [comment]
Thankyou

**Comment by Sivanesh1992** [comment]
is this possible to deploy N3iwf by using raspberrypi4B board without usrp  to transmit WLAN signal

**Comment by wilson30139** [comment]
Hello @Sivanesh1992 , I think N3IWF can be deployed on the raspberrypi4B board because the software and hardware are independent. We are not responsible for testing the board here. I think you can try to use WLAN to connect to N3IWF for testing by yourself.
