### ISSUE TITLE
[Bugs] UPF Cli Run Error: open Gtp5g: open link: create: file exists

### ISSUE THREAD

**Issue by tywofxd** [free5gc/free5gc#420]
**We will advise people to follow the issue template set, otherwise the issue might be disregarded.**
**free5GC mainly uses GitHub for issue tracking. Information regarding to general questions or technical support. It will be highly considered if forward to the [forum](https://forum.free5gc.org).**
**free5GC will appreciate it, if people can refer to [TS](https://github.com/free5gc/free5gc/wiki/Trouble_Shooting) and [forum](https://forum.free5gc.org) prior to bug reporting**

## Describe the bug
I use UERANSIM to open multiple UE threads to interact with the 5G core. The python script for opening such UE threads is like the following:
os.system("nohup " + UERANSIM_build_dir + "nr-ue -c ./config/%s &" % file)
Then I use UERANSIM's nr-cli to make the UE thread to interact with the 5g core:
os.system(UERANSIM_build_dir +"nr-cli -e '%s' %s" % (command, ueId))

However, when the number of UE thread is up to 50, the UPF pod crashes, throwing the following error.
2023-01-03T00:36:39Z [ERRO][UPF][Main] UPF Cli Run Error: open Gtp5g: open link: create: file exists

Less UE threads will not lead to this error.

## To Reproduce
1. Use this helm repo to deploy the 5g core and 5g RAN on a K8s cluster: https://github.com/Orange-OpenSource/towards5gs-helm
2. kubectl exec -it into the ue pod, and use this repository (https://github.com/tywofxd/5GLogGenerator) to generate multiple UE threads to interact with the 5g core.
3. run command: python3 run.py --ue 50 --sec 36000
4. UPF crashes after several minutes.

## Expected behavior
I want the 5g core to operate normally with many UE threads interacting with it.

## Screenshots
![image](https://user-images.githubusercontent.com/39151745/210288781-d53cb9f3-15eb-446d-8a92-bea927230237.png)

## Environment (please complete the following information):
 - free5GC Version: v3.2.0
 - OS: Ubuntu 18.04 Server
 - Kernel version: 5.4.0-131-generic
 - helm chart: https://github.com/Orange-OpenSource/towards5gs-helm
 - k8s version: v1.23.4
 - go version: [e.g. 1.10.0 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 1.1.0]

### Configuration File
[free5gc-charts.zip](https://github.com/free5gc/free5gc/files/10334033/free5gc-charts.zip)

### PCAP File
Dump the packet and provide the pcap file here.

If not clear of what to do, this command can be used `sudo tcpdump -i any -w free5gc.pcap` prior to running bug reproduce. Then upload the pcap file `free5gc.pcap`.

### Log File
![image](https://user-images.githubusercontent.com/39151745/210292174-19e6c89b-8a7a-467a-990b-2e14ffa7ae10.png)

## System architecture (Option)
Please provide the draft architecture, including the scenario, use cases, installation environment(bare metal, vm, container, or k8s), etc.

## Walkthrough (Option)
free5GC will be interested on the research or finding in brief.

## Additional context
My repository for generating UE threads is here: https://github.com/tywofxd/5GLogGenerator

**Comment by tim-ywliu** [comment]
you can use `./force_kill.sh` or `sudo ip link del upfgtp` to recover it when the error happened.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/upf-cli-run-error/1781/2
