### ISSUE TITLE
Unstable PDU session

### ISSUE THREAD

**Issue by orion-belt** [free5gc/free5gc#423]
## Describe the bug
I am using below setup - 
srsenb in band 3 + Free5GC Core + Industrial Router (Quectel Module - RM500Q-GL)
PDU session is okay and able to perform traffic test also. But, connection is unstable. I see that there is periodic registration request sent by UE (RAN), after every 2 min.
Do you think it is because of radio connection or some configuration is missing here.

There are two reasons so far for unstability.
1. There is UE context release by AMF, but still service request/pdu session request is successful and data traffic is fine.
2. There is periodic registration sent by RAN. I have increased RRC inactivity timer in Gnb but still there is registration request triggered by RAN in interval of 2 minutes. <br/>
Do you think it is because of radio connection or some configuration is missing at Core Network.

## Expected behavior
Stable PDU session

## Environment (please complete the following information):
 - free5GC Version: [v3.0.100]
 - OS: [Ubuntu 200.04 Server]
 - Kernel version: [5.4.0-132-generic]
 - go version: [using docker images as [illustrated here](https://github.com/free5gc/free5gc-compose)]
 - c compiler version (Option): [gcc version 9.4.0 ]

### PCAP File
[pdu_session__okay_free5gc.zip](https://github.com/free5gc/free5gc/files/10354421/pdu_session__okay_free5gc.zip)

### Log File
[Free5GC_AMF_log.txt](https://github.com/free5gc/free5gc/files/10354417/Free5GC_AMF_log.txt)

**Comment by JiMMyMatrix** [comment]
Hi, according to your pcap and log file, it seems like some problems in your setup.
1. There are two Registration Request in one InitialUEMessage. 

<img width="1427" alt="截圖 2023-05-18 12 02 33" src="https://github.com/free5gc/free5gc/assets/112857368/1a6b6646-c6e1-40b4-a446-199fcc72a405">

2. Follow-On Request bit of both Registration Requests are 0. That means AMF will not maintain connection with UE, it will drop the connection after Registration Accept. In my opinion, this is the reason why you have periodic registration. 

<img width="841" alt="截圖 2023-05-18 12 04 40" src="https://github.com/free5gc/free5gc/assets/112857368/585291bc-60f0-4476-8a6e-57395fb8cb1d">


Could you check your UE and RAN connection configuration ?
