### ISSUE TITLE
PDU session status in signalling Service request is not processed

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/free5gc#424]
In the current free5gc, if the AMF receives the service request whose service type is signalling, it does not process the PDU session status in this service request and immediately sends the service accept without the PDU session status.
Is this behavior correct?

https://github.com/free5gc/amf/blob/e839de03774f7c5b06dbaaa368ea6f0813a4d0d9/internal/gmm/handler.go#L1643
```
	if serviceType == nasMessage.ServiceTypeSignalling {
		err := sendServiceAccept(ue, anType, ctxList, suList, nil, nil, nil, nil)
		return err
	}
```

**Comment by iamelisahi** [comment]
Hi, based on the picture captured from spec 23.502 4.2.3.2, it appears that the behavior is correct. If the Service Request is triggered by the UE for signaling only, the UE does not identify any List Of PDU Sessions To Be Activated.
![image](https://github.com/free5gc/free5gc/assets/135607537/e665a66e-7526-4722-b98b-298eac950da9)
