### ISSUE TITLE
PFCP Session Establishment Request missing Forwarding Parameters IE

### ISSUE THREAD

**Issue by daniel-garciasanchez** [free5gc/free5gc#44]
Dear Team, 

Using test scripts and all core Stage3 functions with a different vendor UPF, this was complaining about lack of Forwarding Parameters IE when creating the tunnel. As per specification TS. 29.244, if FAR indicates FORW within Apply Action IE the forwarding rule shall include Forwarding Parameters IE. I checked captures from Stage 2 and SMF was correctly generating this IE.

It can be reproduced just running the default
./test.sh -o TestRegistration 

![image](https://user-images.githubusercontent.com/47662494/81792214-0ab2fa00-9508-11ea-8ed2-7e02f39a74bf.png)

Therein I think as in Stage2 it should include Destination Interface and Network Instance (APN).

**Comment by free5gc-org** [comment]
I think that is a bug, we'll working on it.

Thanks for your report!

**Comment by free5gc-org** [comment]
Dear @daniel-garciasanchez ,

free5GC has fix this bug on v3.0.3. Please try and test it.

Thanks for your report!

**Comment by Qxff** [comment]
The parameter below should be "Core", not "Access", right?
As it's for PDR ID 1(uplink traffics) and should be forward to DN(Core). Thanks!

![PCFP_FAR_error](https://user-images.githubusercontent.com/37206778/88896541-8bb69d80-d27c-11ea-8922-3bd100a4afb7.png)

**Comment by free5gc-org** [comment]
Hi @Qxff ,

This seems to be free5GC's bug.

Thanks for your report.

**Comment by ardzoht** [comment]
@free5gc-org Trying the same test on v3.1.0 and same issue happens: 
![image](https://user-images.githubusercontent.com/6800940/188989124-592974dc-25ea-4fd3-978b-85183ee517ee.png)

**Comment by louisroyer** [comment]
Related issue on smf repository: https://github.com/free5gc/smf/issues/55
