### ISSUE TITLE
Does free5GC support GWCN scenario?

### ISSUE THREAD

**Issue by JoaoFerreira5** [free5gc/free5gc#440]
Hi,

I´m working in a project where I'm studying 5G, and in my pratical project I want to achieve a scenario like a GWCN. So is free5GC (Core Network) support multiple connections between more than one free5GC (Core Network) to test those scenarios?

Best reggards,
JoaoFerreira5

**Comment by JoaoFerreira5** [comment]
Hi, @BENHSU0723. What I was trying to ask is if free5gc support connection between different core, p.e, sharing one AMF to serve different core networks, with different PLMN's. 
Similar to roaming where you can share your core to different operators.

**Comment by BENHSU0723** [comment]
@JoaoFerreira5, I think it's feasible to make multiple core network(free5GC) connecting to AMF, beacuse any NF like AMF only know the location of NRF. As loog as your **NRF which modifyed by yourself can distribute any consumer NF's request into different core network** then return the coresponding  producer NF location, it would achieve your demend. You can give it a try, but we don't promiss the feasibility.

BRs, Ben

**Comment by JoaoFerreira5** [comment]
Thank you for the help.

Best reggards,
João Ferreira

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/failing-selecting-sn-with-multiple-plmn/1938/2

**Comment by JoaoFerreira5** [comment]
Hi @BENHSU0723,
This question is in line with the one above. Is it possible to connect two NRF's of different core (free5gc)? If yes, how do I do it?

Best reggards,
João Ferreira

**Comment by BENHSU0723** [comment]
Hello, @JoaoFerreira5. I have concerned about the requirements of the GWCN architecture. In my opinion, I believe a better approach to achieving it would be to deploy all NFs of multiple core networks in the same SBI. For instance, if you only want a single AMF connecting to multiple NRFs, you can configure the nrfuri from a single string of URI to an array of URIs and distribute the searching task to suitable NRFs. Therefore, you need to modify the configuration file and the NF you want to share. This is just a suggestion from me, and we cannot guarantee its feasibility. We do not have plans to develop anything related to GWCN in the future. Will you be taking care of it? Thank you very much. By the way, the attached photo is my suggested architecture based on the GWCN from 3GPP specifications.![free5fc-GWCN](https://github.com/free5gc/free5gc/assets/66531635/fd02e12b-792f-41aa-9e7d-e7d21e06df41)
