### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by niloysh** [free5gc/free5gc#441]
**If the design issue template is not followed, the issue might be closed.**

## Documentation request

How to use gtp5g usage report?

## Suggestion

In the gtp5g code, I see 
```
enum gtp5g_usage_report_attrs {
    GTP5G_UR_URRID = 3,
    GTP5G_UR_USAGE_REPORT_TRIGGER,
    GTP5G_UR_URSEQN,
    GTP5G_UR_VOLUME_MEASUREMENT,
    GTP5G_UR_QUERY_URR_REFERENCE,
    GTP5G_UR_START_TIME,
    GTP5G_UR_END_TIME,
    GTP5G_UR_SEID,

    __GTP5G_UR_ATTR_MAX,
};
```
How to enable these features and how to collect usage reports?

**Comment by JiMMyMatrix** [comment]
Hi,
Since the features of urr are developing, usage report not supports at present.

**Comment by ianchen0119** [comment]
Hi @niloysh 

The free5GC supports Usage Report feature now!
Please upgrade to the version `3.3.0` and set the urrPeriod in the smfcfg.yaml.

Thanks.
