### ISSUE TITLE
Ask about https

### ISSUE THREAD

**Issue by mark6969** [free5gc/free5gc#442]
Hello, I would like to know if the webconsole of free5gc is designed to use HTTPS. I couldn't find any related documentation and when I looked through the code, I didn't see any use of HTTPS modules.

**Comment by ianchen0119** [comment]
Hi @mark6969 
Currently we don't have a plan to support this feature.
But you can consider using reverse proxy to achieve your requirements, please see https://github.com/free5gc/free5gc-compose/issues/55 for more information.

**Comment by mark6969** [comment]
Okay, I understand. Thank you.
