### ISSUE TITLE
[Docs] 您好，想请教一下openapi是怎么生成的？是使用的openapi-generator-cli吗

### ISSUE THREAD

**Issue by xiongkai0920** [free5gc/free5gc#445]
目前想将R15升级到R18，但是感觉生成的不太对

**Comment by Jerry0666** [comment]
沒錯，我們是用openapi-genrator-cli。
openapi-genrator-cli：https://github.com/OpenAPITools/openapi-generator
請問是哪裡覺得不太對？

**Comment by ianchen0119** [comment]
Hi @xiongkai0920 

This issue would be closed due to there being no interaction for 2 weeks.
If you have any further questions, 
please let me know, and I will re-open this issue.

Thanks a lot.

**Comment by lycheezhou** [comment]
您好，情况是这样的：在free5gc中使用PCF的SBI服务，是支持Notification的，如下图：

![image](https://github.com/free5gc/free5gc/assets/33309728/58c42d13-47a3-474c-99bc-7bdc843ef112)


但是当我使用openapi-genrator-cli生成R18的版本时候发现没有这个API了，如下图：

![image](https://github.com/free5gc/free5gc/assets/33309728/2620d894-5100-4031-af99-512336ec9556)


对应R18的yaml地址：https://github.com/jdegre/5GC_APIs/blob/Rel-18/TS29512_Npcf_SMPolicyControl.yaml
  
使用的生成脚本如下：
```
for specs in $(ls ./5GC_APIs/TS29512_Npcf*.yaml); do
    package_name=$(basename "${specs%.*}" | cut -d'_' -f2- | tr '-' '_')
    package_name="$package_name" # Adding the prefix openapi_ to avoid conflicts with numbers in the name (e.g. 5GC_APIs/1.yaml)
    echo "Generating $package_name"
    rm -rf ./"$package_name" # Removing the folder if it already exists
    java -Xmx1024M -jar openapi-generator-cli-6.6.0.jar generate -i "$specs" -g go -o ./"TS29512_$package_name"  --skip-validate-spec  --additional-properties=enumClassPrefix=true,generateGoMod=false,packageName="$package_name"
    rm -rf ./"$package_name"/go.* # Removing the go.mod and go.sum files
    echo "Done"
done
```

openapi-genrator-cli的客户端版本如下：
[openapi-generator-cli-6.6.0.jar.zip](https://github.com/free5gc/free5gc/files/12657688/openapi-generator-cli-6.6.0.jar.zip)

**Comment by Jerry0666** [comment]
你好，你R15 SmPolicyUpdateNotification是在哪裡的function，我使用R15的yaml也一樣沒有生成那個function，我想那個function應該是要再另外寫。

**Comment by Jerry0666** [comment]
你好，在我測試下來，openapi的callback function沒有辦法生成相對應的程式碼，這樣你應該要再去問openapi generator的開發人員。
