### ISSUE TITLE
Registration times latency and concurency

### ISSUE THREAD

**Issue by pzeina** [free5gc/free5gc#456]
Hello, here is a concern about the registration procedure I would like to share.
When I connect 2 UEs at the same time, the time it for the first one to register is ~1s, and the second one needs additional **0.7s** to complete registration (see the green dots on figure 1).
When I connect 4 UEs at the same time, the first UE takes ~1.5s, and each following one takes **0.7s** more to register (see green dots on figure 2).
This **0.7s** delay for each next initial registration is always the same when I try similar experiments. It seems that the core is processing one registration at a time and each one takes 0.7s in my case. Is it correct? To speed up the registration of multiple UEs, is it possible to make use of concurrency on the network functions? Or is there anything else you would recommend to do?

Figure 1
![image](https://github.com/free5gc/free5gc/assets/115324914/58ba5f12-ead9-42ca-8dfb-921f57978300)

Figure 2
![image](https://github.com/free5gc/free5gc/assets/115324914/f17f5808-e94c-495b-a778-05a5b1932116)

**Comment by ianchen0119** [comment]
Hi @pzeina 

According to your question:
> Is it possible to make use of concurrency on the network functions? Or is there anything else you would recommend to do?

The answer is:
Yes, it is possible to optimize the network function by using concurrency.
I suggest you can try to refactor the implementation of the AMF.

```
when the SCTP connection comes, the processing flow of AMF be like this:
listenAndServe
  handleConnection (create goroutine for each conneciton)
    HandleMessage -> Dispatch (for ngap message)
      dispatchMain
        specific ngap msg handler (e.g. handlerNGSetupRequest, handlerPDUSessionResourceSetupRequest..)
           NAS message handler (if needed)
```

The simplest way is to use a new goroutine for each new UE:
- Create the specific worker (new goroutine) and channel when a new RanUE Context is created (in `NewRanUe()`)
  - worker runs forever and always accepts the new job from the channel when the previous job done 
- When msg comes from the UE, send msg to the specific worker via the channel
  - May use the buffered channel for preventing the `HandleMessage` goroutine be blocked by worker

**Comment by ianchen0119** [comment]
Hi @pzeina 
This issue would be closed due to there being no interaction for 2 weeks.
If you have any further questions,
please let me know, and I will re-open this issue.

Thanks a lot.
