### ISSUE TITLE
[Info] Xn Handover simulation

### ISSUE THREAD

**Issue by IgnacioCTO** [free5gc/free5gc#458]
## Performing the Xn Handover manually
Hello all, I am interested in simulating the Xn Handover behavior. If I understood right, this functionality is already implemented in free5GC since I was able to run the Test (./test.sh TestXnHandover), which seems to work. However, I would like to trigger the handover by myself. 

So far, I have deployed the full core network, 2 gNBs and one user connected to one of them. Is there a way to send a command to perform the Xn Handover from one to the other gNB?

Thank you for time,

Ignacio

**Comment by wilson30139** [comment]
&emsp;&emsp; Hello @IgnacioCTO , can you provide more detailed information about the UE and RAN test environment? Thank you. In addition, according to the content of spec 23.502 figure 4.9.1.2.2-1, the target NG RAN sends the N2 path switch request to the AMF during HO. I guess NG-RAN provides relevant commands. The command is able to inform CN that target NG-RAN will replace source NG-RAN as the N2 endpoint. If you use software related to UERANSIM, I think you go to UEANSIM issue and ask about it.
