### ISSUE TITLE
Adding communication round between UE and AMF

### ISSUE THREAD

**Issue by zbh888** [free5gc/free5gc#459]
Hello free5GC team.

I want to add a communication round between UE and AMF inside `SendUEAuthenticationAuthenticateRequest` (The phase AMF direct SUCI to AUSF)

I want AMF send something like "Hello UE" to UE, and UE respond with "Hello AMF" before AMF direct SUCI to AUSF.

I checked the workflow of sending RAND||AUTN to UE. The AMF make use of `SendDownlinkNasTransport` and build the bytes using method in `internal/gmm/message/build.go`. But it is complicated for me to do the same and I am also worried if my change will require some timer or lock.

So, I guess it's best to ask experts. Can you suggest me a way to implement such new round, please?

Thank you very much.

**Comment by Leon777-coder** [comment]
Dear zbh888:

We appreciate your question, however, the functionality you need is not defined in the spec, maybe you can find some useful information in 24.501 and make your own by tracing the code we provided. Unfortunately, we are unable to provide further assistance as your request is too uncommon and not related to our main topic.

Wish you good luck

leon
