### ISSUE TITLE
[Docs] Update version in clone command

### ISSUE THREAD

**Issue by LaumiH** [free5gc/free5gc#461]
## Documentation request

The [current docs](https://free5gc.org/guide/3-install-free5gc/#b-install-control-plane-elements) for version 3.3.0 still want you to clone v3.2.1.

## Suggestion

Change the command from 
```
git clone --recursive -b v3.2.1 -j `nproc` https://github.com/free5gc/free5gc.git
```
to 
```
git clone --recursive -b v3.3.0 -j `nproc` https://github.com/free5gc/free5gc.git
```

## Additional context
None

**Comment by ianchen0119** [comment]
Hi @LaumiH 

Thanks for your remind.
I've updated the installation guide.
