### ISSUE TITLE
free5gc 4G support

### ISSUE THREAD

**Issue by FearlessHyena** [free5gc/free5gc#465]
Hi,
Apologize for a very basic question but does free5gc have support for 4G as well?
We're planning on using it for a project that would require both 4G and 5G connectivity so just wanted some clarification on this
Thanks

**Comment by YouShengLiu** [comment]
Hi @FearlessHyena,

free5GC is a 5G core network that supports standalone architecture, therefore it didn't support 4G.

**Comment by FearlessHyena** [comment]
Hi @YouShengLiu 
Thanks a lot for the clarification. That resolves my question so I'll go ahead and close this issue 🙏
