### ISSUE TITLE
[Bugs]pass but have error when running all test

### ISSUE THREAD

**Issue by juanjuan2** [free5gc/free5gc#466]
## Describe the bug
When I follow the link(https://free5gc.org/guide/3-install-free5gc/) to install and run all tests, it shows pass but then have a error for all tests.([ERRO][UPF][Pfcp][10.200.200.101:8805] read udp 10.200.200.101:8805: use of closed network connection)

## To Reproduce
1. Change config: no change
2. Code patch: no change
3. Run command : ./test.sh TestRegistration etc
4. Dump packet: I don't have that.(How can I get it?)

## Expected behavior
Pass all tests in tutorial (https://free5gc.org/guide/4-test-free5gc/) and have no error.

## Screenshots
1.
./test.sh TestRegistration.
![image](https://github.com/free5gc/free5gc/assets/45665083/6f13756f-6917-4e26-b0bb-2e1a67b9c8c1)
2.
./test.sh TestGUTIRegistration
![image](https://github.com/free5gc/free5gc/assets/45665083/2c08f4f4-faff-4365-8c96-ae11a92ba570)
![image](https://github.com/free5gc/free5gc/assets/45665083/72f0a3ac-e40e-4de9-b3f3-1479d1f2c7b0)
3.
./test.sh TestNon3GPP
![image](https://github.com/free5gc/free5gc/assets/45665083/bf2e5f50-be17-4847-b466-8fd777f08ebb)

## Environment (please complete the following information):
 - free5GC Version: v3.3.0
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
 - go version: go1.17.8 linux/amd64
 - c compiler version (Option): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### Configuration File
no change
[config.zip](https://github.com/free5gc/free5gc/files/12035187/config.zip)

### PCAP File
[free5gc.zip](https://github.com/free5gc/free5gc/files/12035253/free5gc.zip)
(I compress free5gc.pcap into a .zip file)

### Log File
Provide the program log file here.
If not clear of what to do, copy the printed log on the screen and upload it here.
[TestNon3GPP.txt](https://github.com/free5gc/free5gc/files/12035238/TestNon3GPP.txt)

**Comment by yashihh** [comment]
Hi @juanjuan2,
It's normal that the error appear after the test success.
If the result of test is pass, you can ignore the fail message.
It's fine to keep testing.

Please feel free to let me know any question.

BR
yashihh.
