### ISSUE TITLE
Q：May I know how to change the CipheringAlg from default NEA2 to NEA0? (Because I want to decode nas message)

### ISSUE THREAD

**Issue by gprshome** [free5gc/free5gc#47]
Dear gentleman：
Thanks for your great project first.
I found the nas message is encrypted after authentication response. May I know how to decode NAS meassage? Thanks very much.
Or maybe this is another question:  How to change the CipheringAlg from default NEA2 to NEA0? 
![11](https://user-images.githubusercontent.com/44839608/82756442-f37be280-9e0c-11ea-9c3b-b83c161884cd.png)

**Comment by free5gc-org** [comment]
Hi,

We're not implement other two encryption type for now, It is welcome to contribute with different types of NEA and NIA 😃

**Comment by mrlnc** [comment]
In `config/amfcfg.conf` change `cipheringOrder` to prefer `NEA0`:
```
- NEA0
- NEA2
```

The UE still needs to support NEA0, but I guess it does. You can check in the `Registration Request`:
```
UE security capability
    Element ID: 0x2e
    Length: 8
    1... .... = 5G-EA0: Supported
...
```

**Comment by gprshome** [comment]
> In `config/amfcfg.conf` change `cipheringOrder` to prefer `NEA0`:
> 
> ```
> cipheringOrder:
> - NEA0
> - NEA2
> ```
> 
> The UE still needs to support NEA0, but I guess it does. You can check in the `Registration Request`:
> 
> ```
> UE security capability
>     Element ID: 0x2e
>     Length: 8
>     1... .... = 5G-EA0: Supported
> ...
> ```

Thanks mrlnc. But it seems doesn't work. Anyway , Thanks for your advice.

**Comment by gprshome** [comment]
> Hi,
> 
> We're not implement other two encryption type for now, It is welcome to contribute with different types of NEA and NIA 😃

Sorry, maybe I confused you. I just want to decode the NAS message(e.g Registartion accept) in anyway. But I'm a begeinner of Go, don't know which go file I should modify. 
Do you have any method? I'm really appreciated.

**Comment by free5gc-org** [comment]
Hi,
In our opinion, 3GPP required that all NAS message should be protected after completing security mode control procedure, so we reject any plain nas message after that procedure. At this moment, NEA0/NIA0 can not be enabled even if you change AMF config.
You may check `amf/src/nas/nas_security/security.go` and modify the code to enable plain NAS.

**Comment by mrlnc** [comment]
For debugging in the lab it certainly is very handy. Last time I checked, Wireshark didn't support NAS decryption even if you have the NAS session keys.

I think the standard requires NEA0 support but encourages you to activate it, whenever possible:
> 5.5 Requirements on the AMF
> 5.5.1 Signalling data confidentiality
> The AMF shall support ciphering of NAS-signalling.
> The AMF shall support the following ciphering algorithms:
> -    NEA0, 128-NEA1, 128-NEA2 as defined in  Annex D of the present document.
> The AMF may support the following ciphering algorithm: 
> -    128-NEA3 as defined in Annex D of the present document.
> Confidentiality protection NAS-signalling is optional to use.
> Confidentiality protection should be used whenever regulations permit.

_3GPP TS 33.501 version 15.7.0 Release 15_

So outside of productive use, it's fine.

**Comment by bjoern-r** [comment]
@gprshome You have to enable the option in wireshark to even show NEA0 encoded messages: 
Edit > Preferences > Protocols > NAD5-GS > [x] Try to detect and decode 5G-EA0 Ciphered messages.

Any real UE i've come acreoss does not work with NIA0.. So integrity is needed but NEA0 it totally fine.

**Comment by free5gc-org** [comment]
Hi all,

We have release our new version v3.0.3 and add NEA0 as feature. We also set NEA0 as default on test script now.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/packet-is-corrupted-with-nia0/1404/2
