### ISSUE TITLE
[Bugs?] why does this even happen webconsole [404 page not found]

### ISSUE THREAD

**Issue by mark6969** [free5gc/free5gc#473]
## Describe the bug
Hello, I follow the installation instructions https://free5gc.org/guide/3-install-free5gc/ to install according to the steps, the version is 3.3.0, there is no error in the process, except that there will be warnings during the webconsole installation process, such as As shown in the first picture, but I don’t think this is the reason. When I execute the webconsole browser after the installation is complete, the browser will return 404
![圖片](https://github.com/free5gc/free5gc/assets/36353259/7bbc7416-df7f-4b57-8a68-1afb22851ee9)

## To Reproduce
I follow the installation instruction https://free5gc.org/guide/3-install-free5gc/ Follow the steps to install until the last step，In order to execute the webconsole I execute the following command

`
cd /webconsole/bin
./webconsole
`
But it will report an error
![圖片](https://github.com/free5gc/free5gc/assets/36353259/6bb20097-691a-4a9d-91e7-d5d2514ef5d2)

So I copy a copy from /free5gc/config/webuicfg.yaml to webconsole/bin/config/webuicfg.yaml, config is a folder created by myself
execute it again
show
![圖片](https://github.com/free5gc/free5gc/assets/36353259/36ec2c33-3fcb-4401-ae0c-12a9698eacf7)
Looks like it was executed successfully，Then I try to go to the browser and enter http://10.20.1.7:5000/, 10.20.1.7 is the machine ip for my deployment service. After inputting, an error 404 page not found will be reported, as shown in the figure below
<img width="424" alt="圖片" src="https://github.com/free5gc/free5gc/assets/36353259/a1328982-5ca8-48cb-8bb2-614b3e2b90c0">
![圖片](https://github.com/free5gc/free5gc/assets/36353259/17c12f76-e365-4343-a1d0-2b5bd1817b0c)

## Environment:
 - free5GC Version:3.3.0
 - OS: Ubuntu 20.04 Server
 - Kernel version: 5.4.0-153-generic
 - go version: go version go1.17.8 linux/amd64

Please let me know if you need any other information, thank you

**Comment by mark6969** [comment]
By the way, I recently had a need to add a packet filtering function to UPF and maybe modify it to ULCL.  how do you usually modify the code and test it? Is there a SOP? Thanks for answering

**Comment by brianchennn** [comment]
@mark6969 
It's better to execute `go run server.go` in `free5gc/webconsole`.

**Comment by brianchennn** [comment]
@mark6969 
Packet filtering is not implemented in free5gc yet. If you set the **IP filter** in webconsole, it's effectless now.

**Comment by mark6969** [comment]
> @mark6969 It's better to execute `go run server.go` in `free5gc/webconsole`. See https://free5gc.org/guide/5-install-ueransim/?h=uera#4-use-webconsole-to-add-an-ue

It is possible to implement according to your suggestion, I should not have noticed, thank you

**Comment by brianchennn** [comment]
@mark6969 
I checked again and found that IP filter will exist in PFCP Session Establishment Request -> PDI -> SDF Filter. But we don't write relevant test yet. I use the webconsole [PR #47](https://github.com/free5gc/webconsole/pull/47) 
![image](https://github.com/free5gc/free5gc/assets/46628572/3d1cbf52-5562-4114-9cb6-19cd96d7108f)
![image](https://github.com/free5gc/free5gc/assets/46628572/7b210ff9-e6d4-4ee1-b99a-a6dbe4988e0b)

**Comment by mark6969** [comment]
@brianchennn 
Thanks for the reply, I have a question, whether the function of SDF FILTER has the function of filtering GTP-U, such as judging whether it is legal traffic based on the source and destination IP of the traffic

**Comment by brianchennn** [comment]
@mark6969 
For IP Filter test, you can:
- Config DNN in webconsole, setting IP Filter to : `permit out ip from 10.10.0.80 to 10.60.0.1` 
    - make sure 10.10.0.80 can ping from UPF, you can change yourself
    - make sure your UE's IP is `10.60.0.1`
![image](https://github.com/free5gc/free5gc/assets/46628572/bfda1e43-7d4d-496b-9736-39ae880b3088)
- In free5gc machine, 
    - `cd free5gc/test/go-gtp5gnl/bin`; 
    - `sudo su`
    - `./gtp5g-tunnel list far`
    - You will find that there are 4 FAR rules:
    ```
{
    "ID": 3,
    "Action": 2,
    "Param": null,
    "PDRIDs": [
      3
    ],
    "BARID": null,
    "SEID": 1
  },
  {
    "ID": 1,
    "Action": 1,
    "Param": null,
    "PDRIDs": [
      1
    ],
    "BARID": null,
    "SEID": 1
  },
  {
    "ID": 2,
    "Action": 1,
    "Param": {
      "Creation": {
        "Desc": 256,
        "TEID": 1,
        "PeerAddr": "10.10.0.82",
        "Port": 2152
      },
      "Policy": null
    },
    "PDRIDs": [
      2
    ],
    "BARID": null,
    "SEID": 1
  },
  {
    "ID": 4,
    "Action": 2,
    "Param": {
      "Creation": {
        "Desc": 256,
        "TEID": 1,
        "PeerAddr": "10.10.0.82",
        "Port": 2152
      },
      "Policy": null
    },
    "PDRIDs": [
      4
    ],
    "BARID": null,
    "SEID": 1
  }
```
    - In UERANSIM, connect to free5gc:
        - (terminal 1): `build/nr-gnb -c config/free5gc-gnb.yaml`
        - (terminal 2): `sudo build/nr-ue -c config/free5gc-ue.yaml`
        - (terminal 3): `ping -I uesimtun0 8.8.8.8` **(success)**
        - (terminal 4): `ping -I uesimtun0 10.10.0.80` (success)
    - In free5gc, Drop the default FAR 1,2: format `./gtp5g-tunnel [get/del/add/mod] [PDR/FAR/QER] [interface_name] [seid]:[id] [option]`
        - `./gtp5g-tunnel mod far upfgtp 1:1 --action 1` (`1` means drop, `2` means forward)
        - `./gtp5g-tunnel mod far upfgtp 1:2 --action 1`
        -  - (terminal 3): `ping -I uesimtun0 8.8.8.8` **(failed)**
        - (terminal 4): `ping -I uesimtun0 10.10.0.80` (success)
   - You will find that you can't ping to 8.8.8.8 anymore, but still can ping to 10.10.0.80. It means that IP Filter Rule is successfully installed in upf.

**Comment by mark6969** [comment]
ok, i'm trying it out, thanks
