### ISSUE TITLE
[Question] Is it possible to connect n3iwf to real UE using free5gc?

### ISSUE THREAD

**Issue by ex8664** [free5gc/free5gc#477]
Is it possible to connect n3iwf to real UE using free5gc?
If you have any achievements, please let us know.

Actually, I wanted to check it on the forum, but it seems that the forum is under maintenance, so I'm asking here.

**Comment by brianchennn** [comment]
Hi @ex8664, we haven't do the experiment by real UE before. You can try to use [my5G-non3GPP-access](https://github.com/my5G/my5G-non3GPP-access) or [NWu-Non3GPP-5GC](https://github.com/fasferraz/NWu-Non3GPP-5GC) to simulate it.

BTW, the forum is resumed.
