### ISSUE TITLE
[Question] Can I send API to 5gc AMF to delete pdu session?

### ISSUE THREAD

**Issue by mark6969** [free5gc/free5gc#479]
As the title, can I send an api to AMF to delete the pdu session
As the specification says, the API below
`/namf-comm/v1/ue-contexts/imsi-208930000000004/release`
If so, can you please provide me with the payload and process I should enter?
Thanks

**Comment by brianchennn** [comment]
@mark6969 
The `/namf-comm/v1/ue-contexts/imsi-208930000000004/release` API is used to release supi:imsi-208930000000004's UE Context in AMF. The payload should like below:

```
curl --location 'http://127.0.0.18:8000/namf-comm/v1/ue-contexts/imsi-208930000000004/release?ueContextId=imsi-208930000001003' \
--header 'Content-Type: application/json' \
--data '{
    "unauthenticatedSupi": false,
    "ngapCause": {}
}'
```

**Comment by mark6969** [comment]
Ok, I understand, thank you for your reply
