### ISSUE TITLE
[Bugs] Add CHF NF submodule

### ISSUE THREAD

**Issue by abousselmi** [free5gc/free5gc#480]
## Describe the bug
CHF NF is not included in submodules

## To Reproduce

ls ./NFs/

## Expected behavior

Find CHF submodule

**Comment by brianchennn** [comment]
@abousselmi 
It's because this PR https://github.com/free5gc/free5gc/pull/478 has not been merged yet.

**Comment by abousselmi** [comment]
Hi @brianchennn 

Thanks for the tip !

Compose project CI is failing because of it.
I'll take a look at this PR and let you know.

**Comment by infinitydon** [comment]
@brianchennn - By the way, are you using an opensource charging gateway to test the CHF functionality? If yes, you can share which charging solution you are using to test the CHF.

Thanks

**Comment by brianchennn** [comment]
@infinitydon 
@Roy-Hu use landslide to test the functionality, but we are still reviewing [SMF PR 76](https://github.com/free5gc/smf/pull/76)
