### ISSUE TITLE
DefaultServiceIP Configuration

### ISSUE THREAD

**Issue by infinitydon** [free5gc/free5gc#49]
Hi,

Is it possible to configure `DefaultServiceIP` in other components like the NRF?

![image](https://user-images.githubusercontent.com/6318992/82842892-900cb600-9edb-11ea-8888-e7aefd1fc78e.png)

The reason for this is to be able to configure a separate IP/URL apart from the listening IP address, this will make deploying free5gc easier in a service mesh.

I tried to add the `DefaultServiceIP` parameter just like the NRF to other components configuration but this did not reflect in the NF profiles that is advertised to the NRF.

**Comment by endrigoshi** [comment]
You would have to manually add the parameter in the config file and then in config-parsing files for each of the NFs. Indeed it is quite useful when deploying the core network in k8s. I have done it previously but not for the latest version of the code.

**Comment by infinitydon** [comment]
@endrigoshi Thanks for the response, can you please show me where the config-parsing files for each of the NFs are located?

**Comment by endrigoshi** [comment]
@infinitydon I noticed that they are in the same files for each of the NFs (probably different persons coded the NFs) but for AMF for e.g. I had to modify the following files:
`amf_context/context.go`, `amf_service/amf_init.go`, `amf_util/initContext.go` and `factory/config_configuration`.

It would be nice if @free5gc-org would consider to have add this feature in the code.

**Comment by free5gc-org** [comment]
We're not quite understand,

So the feature is asking for listen on, for example, IPA, and register to nrf with IPB?

**Comment by infinitydon** [comment]
Yes..

An example of how I configured the NRF in k8s is this:

```
  nrfcfg.conf: |
    info:
      version: 3.0.2
      description: NRF initial local configuration

    configuration:
      MongoDBName: "free5gc"
      MongoDBUrl: "mongodb://mongodb-svc:27017"
      DefaultServiceIP: "free5gc-nrf-service"
      sbi:
        scheme: http
        ipv4Addr: 0.0.0.0
        port: 29510
      DefaultPlmnId:
        mcc: "208"
        mnc: "93"
      serviceNameList:
        - nnrf-nfm
        - nnrf-disc
```
So the remaining 5GC components communicates to the NRF  using service name **_free5gc-nrf-service_** instead of the POD IP

**Comment by endrigoshi** [comment]
@free5gc-org Is this something that fits with your vision for free5gc? If so I can work on this and have a PR by next week. Or if you plan to release a new version of the code I can wait for that and do the changes there.

**Comment by free5gc-org** [comment]
Hi,
We have no plane to release our new version in recent weeks. We're glad to see someone who can help us to implement this feature. 💪

**Comment by endrigoshi** [comment]
@free5gc-org I did the necessary modifications and I sent the PR for each of the NFs.
When they are merged, I can create a PR for the `free5gc` repo as well, since there are changes that need to be done to the configurations in `config` folder as well.

**Comment by free5gc-org** [comment]
Dear @endrigoshi ,

Sorry for the lat reply. This PR seems good and we'll start to review recently.

Thanks a lot!

**Comment by sothy** [comment]
Hello @infinitydon 
sorry for asking this question in this thread. 
I am also thinking to deploy Free5GC on k8s. I see your work.
https://bitbucket.org/infinitydon/virtual-4g-simulator/src/master/free5gc/
I can deploy only NRF. others are giving error. 
For example when I deploying AUSF

`ubuntu@localhost:~$ kubectl logs free5gc-ausf-deployment-7647cc7cd9-fsrhf
Error from server (BadRequest): container "myapp-container" in pod "free5gc-ausf-deployment-7647cc7cd9-fsrhf" is waiting to start: PodInitializing
`
 Do you know why it is happening?
Thanks
Sothy

**Comment by infinitydon** [comment]
Hi @sothy ,

The deployment uses **sdnvortex/network-controller** to add a second network interface to the container and this requires that bridge interface exists in the worker node, can you check if there is a bridge **br0** in the worker node?

Also open-v-switch needs to be installed in the worker nodes.

_**N.B - The bridge should be created with open-v-switch.**_

NRF uses the default k8s interface, I think this is why it is running without any issues.

**Comment by sothy** [comment]
Hello @infinitydon 
There is no **br0**. 
`ubuntu@localhost:~$ sudo ovs-vsctl list-br
br-int`

I see your 
`ubuntu@localhost:~$ kubectl describe daemonsets network-controller-server-unix -n kube-system 
Name:           network-controller-server-unix
Selector:       name=network-controller-server-unix
Node-Selector:  <none>
Labels:         <none>
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Scheduled with Up-to-date Pods: 1
Number of Nodes Scheduled with Available Pods: 1
Number of Nodes Misscheduled: 0
Pods Status:  1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  name=network-controller-server-unix
  Containers:
   network-controller-server-unix:
    Image:      sdnvortex/network-controller:v0.4.9
    Port:       <none>
    Host Port:  <none>
    Command:
      /go/bin/server
    Args:
      -unix=/tmp/vortex.sock
      -netlink-gc
    Environment:  <none>
    Mounts:
      /tmp/ from grpc-sock (rw)
      /var/run/docker.sock from docker-sock (rw)
      /var/run/docker/netns:shared from docker-ns (rw)
      /var/run/openvswitch/db.sock from ovs-sock (rw)
  Volumes:
   docker-ns:
    Type:          HostPath (bare host directory volume)
    Path:          /run/docker/netns
    HostPathType:  
   docker-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/docker.sock
    HostPathType:  
   ovs-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/openvswitch/db.sock
    HostPathType:  
   grpc-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/vortex
    HostPathType:  
Events:
  Type    Reason            Age    From                  Message
  ----    ------            ----   ----                  -------
  Normal  SuccessfulCreate  5m44s  daemonset-controller  Created pod: network-controller-server-unix-fp5m6
`

I dnt know why it is not possible to create br0?

Best regards
Sothy

**Comment by infinitydon** [comment]
@sothy 

The bridge needs manually on the worker node, you can do this via

**sudo ovs-vsctl add-br br0**

**Comment by sothy** [comment]
Thanks @infinitydon 
It worked for me.
``ubuntu@localhost:~$ kubectl get pods
NAME                                       READY   STATUS             RESTARTS   AGE
free5gc-amf-deployment-94cf8b957-9kfmp     1/1     Running            0          10m
free5gc-ausf-deployment-7647cc7cd9-d95wx   1/1     Running            0          14m
free5gc-nrf-deployment-76cf5587b5-bgfvv    1/1     Running            4          59m
free5gc-pcf-deployment-6c6976c67d-ffxlm    1/1     Running            0          10m
free5gc-smf-deployment-77c94bc9bb-bz8kw    1/1     Running            0          10m
free5gc-udm-deployment-748fcb4944-zqbxd    1/1     Running            0          10m
free5gc-udr-deployment-796b5969c-274fw     1/1     Running            0          5m40s
free5gc-upf-deployment-86d88fc86d-9l5jl    0/1     CrashLoopBackOff   5          5m32s
``

I guess UPF is not working. I dont install gtp plugin the host and kernel version is matched. 
``ubuntu@localhost:~$ kubectl logs free5gc-upf-deployment-86d88fc86d-9l5jl
INFO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:35 UpfInit() Config: /go/src/free5gc/src/upf/build/config/upfcfg.yaml  UPF=Util
INFO[2020-08-16T12:42:18Z] Set log level: info                           UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/gtpv1/src/gtp_link.c:27 GtpLinkCreate() GTP device named upfgtp0 Create fail  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:49 GtpTunCreate() GtpLinkCreate fail  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:144 GtpDevListCreate() GTPv1 tunnel create fail : IP[192.168.2.10], ifname[upfgtp0]  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/up/up_path.c:74 GTPv1ServerInit() GtpLinkListCreate Fail  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf.c:32 main() UPF failed to initialize  UPF=Util
INFO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:85 UpfTerminate() Terminating UPF...  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/up/up_path.c:233 BufferServerTerminate() epoll deregister error  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:88 UpfTerminate() Buffer Sock resource free failed  UPF=Util
INFO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/up/up_path.c:52 UpRouteTerminate() Removing APN routes  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/knet/src/route.c:131 AddKnetDelRoute() if_nametoindex  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:91 UpfTerminate() GTP routes removal failed  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/pfcp/src/pfcp_xact.c:53 PfcpXactTerminate() PFCP Xact already finalized  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:94 UpfTerminate() PFCP Transaction terminate failed  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/utlt/src/utlt_epoll.c:58 EpollDeregisterEvent() Socket 5 delete event in epoll error : No such file or directory  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:162 GtpDevListFree() GTPv1 tunnel deregister to epoll fail : IP[192.168.2.10]  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/gtpv1/src/gtp_link.c:43 GtpLinkFree() GTP device destroy fail  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:70 GtpTunFree() GTP tunnel device named upfgtp0 free fail  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/lib/gtpv1/src/gtp_path.c:166 GtpDevListFree() GTPv1 tunnel free fail : IP[192.168.2.10]  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/up/up_path.c:84 GTPv1ServerTerminate() GTPv1 tunnel list free fail  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:100 UpfTerminate() GTPv1 server terminate failed  UPF=Util
INFO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:225 PacketReceiverThread() Packet receiver thread terminated  UPF=Util
INFO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf_init.c:119 UpfTerminate() UPF failed to terminate  UPF=Util
ERRO[2020-08-16T12:42:18Z] /go/src/free5gc/src/upf/src/upf.c:40 main() UPF terminate error  UPF=Util
``

Kernel
ubuntu@localhost:~$ uname -a
Linux localhost 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sothy** [comment]
Hello @infinitydon 
I see many times NRF failed.
`ubuntu@localhost:~$ kubectl get pods
NAME                                       READY   STATUS             RESTARTS   AGE
free5gc-amf-deployment-94cf8b957-9kfmp     1/1     Running            0          36m
free5gc-ausf-deployment-7647cc7cd9-d95wx   1/1     Running            0          39m
free5gc-nrf-deployment-76cf5587b5-bgfvv    0/1     CrashLoopBackOff   7          85m
free5gc-pcf-deployment-6c6976c67d-ffxlm    1/1     Running            0          35m
free5gc-smf-deployment-77c94bc9bb-bz8kw    1/1     Running            0          36m
free5gc-udm-deployment-748fcb4944-zqbxd    1/1     Running            0          35m
free5gc-udr-deployment-796b5969c-274fw     1/1     Running            0          30m
`

When I see logs of NRF,
`INFO[2020-08-16T13:04:17Z]/src/nrf/Management/api_management.go:700 free5gc/src/nrf/Management.setLocationHeader() UriList create                                NRF=ManagementLog
FATA[2020-08-16T13:05:47Z]/lib/MongoDBLibrary/api_mongoDB.go:53 free5gc/lib/MongoDBLibrary.RestfulAPIGetMany() server selection error: server selection timeout
current topology: Type: Unknown
Servers:
Addr: mongodb-svc:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: dial tcp: lookup mongodb-svc on 10.244.0.3:53: no such host  MongoDB=MongoDB
ubuntu@localhost:~$ 
`

Do I need to do for mongdb?

**Comment by infinitydon** [comment]
@sothy 

I suggest you should delete the whole free5gc deployment and start afresh..

Kindly use the issues page to continue the discussion: https://bitbucket.org/infinitydon/virtual-4g-simulator/issues?status=new&status=open

**Comment by endrigoshi** [comment]
Hi @free5gc-org ,

I just tested it in my setup and it work correctly.

On another note, I noticed that we may need to change the `config` inside the `compose` folder.

**Comment by free5gc-org** [comment]
The config of compose has been fixed now.
