### ISSUE TITLE
[Docs] Troubleshooting for GTP-U and UPF/SMF communication & ufw cmd on install guide

### ISSUE THREAD

**Issue by oliveiraleo** [free5gc/free5gc#492]
## Documentation request

After a OS crash or reboot or kernel update, the GTP-U module might have to be reinstalled to start to work again.

## Suggestion

Provide instructions to solve the issue in case it happens.

## Additional context
PR created on the other repo. To avoid opening another issue here, I added the command to disable the UFW firewall utility permanently on another PR there.

**Comment by brianchennn** [comment]
@oliveiraleo 
Thanks for your PR, and I did some adjustment. See: https://github.com/free5gc/free5gc.github.io/commit/ce81a7b35d6ca87761c99338c796a7b986e4b303
