### ISSUE TITLE
[Docs] Update the Appendix F URLs

### ISSUE THREAD

**Issue by oliveiraleo** [free5gc/free5gc#499]
## Documentation request

The URLs on the bottom of the page https://free5gc.org/guide/Appendix/#appendix-f-program-the-sim-card or more specifically the sysmocom and card reader ones are broken.

## Suggestion

Update those URLs.

## Additional context

I couldn't find new URLs (that matched exactly the old referenced models) by myself so I hope you guys can update them for us.

**Comment by yashihh** [comment]
Hi @oliveiraleo ,
Thank you for the reminder, we will update the URL as soon as possible.

BRs,
yashih

**Comment by yashihh** [comment]
Link updated.

**Comment by oliveiraleo** [comment]
For future reference, this is the commit that fixed it: https://github.com/free5gc/free5gc.github.io/commit/974767b42d66cef0c74ae17e91006b59e53469df
