### ISSUE TITLE
web-ui dependency error

### ISSUE THREAD

**Issue by infinitydon** [free5gc/free5gc#50]
Hi,

I am getting errors finding `webconsole/backend/factory` when I try to run the web-ui.

Checking the _webui_init.go_ [code:](https://github.com/free5gc/webconsole/raw/26e43dd070964f541cd47446eaabe540f3b79215/backend/webui_service/webui_init.go)

![image](https://user-images.githubusercontent.com/6318992/82843864-e3ccce80-9ede-11ea-863f-20d1cf22e1b0.png)

I think **"free5gc/src/webconsole/backend/factory"**  should be **"free5gc/webconsole/backend/factory"**

**Comment by free5gc-org** [comment]
Oh,

That's right, thanks a lot!

**Comment by free5gc-org** [comment]
Hi,

We have update the webconsole.

Thanks a lot for your report and errata~
