### ISSUE TITLE
How to broadcast wifi using 5g core network

### ISSUE THREAD

**Issue by Sivanesh1992** [free5gc/free5gc#504]
hi team,
i am planning to test 5g wifi by using n3iwf  in free5gc and connect to commercial UE . i want to know you guys are tested 5g wifi by using free5gc?

if yes please send me the link .

if no please give me some suggestion

**Comment by Jerry0666** [comment]
We have our own n3ue, used to test and simulate user equipment connected to the Internet via n3iwf. But it won't be open-sourced in the near future.
