### ISSUE TITLE
[Bugs] UPF build error with go 1.21

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/free5gc#505]
## Describe the bug
UPF cannot be build with go 1.21

## Expected behavior
Can build with go 1.21

## Screenshots
```
$ go version
go version go1.21.4 linux/amd64
$ make upf
Start building upf....
cd NFs/upf/cmd && \
CGO_ENABLED=0 go build -gcflags "" -ldflags "-X github.com/free5gc/util/version.VERSION=v3.3.0-22-ge48e933 -X github.com/free5gc/util/version.BUILD_TIME=2023-11-08T05:41:37Z -X github.com/free5gc/util/version.COMMIT_HASH=4fe9ca39 -X github.com/free5gc/util/version.COMMIT_TIME=2023-10-24T14:52:58Z" -o /home/nishi/free5gc-deb/free5gc/bin/upf main.go
go: updates to go.mod needed; to update it:
        go mod tidy
make: *** [Makefile:47: bin/upf] Error 1
$
```

## Environment (please complete the following information):
 - free5GC Version: e48e933dde6bad3a83f6cd327003eeba6992abfa
 - OS: Ubuntu 20.04.6 LTS
 - Kernel version: 5.15.0-88-generic
 - go version: 1.21.4

**Comment by brianchennn** [comment]
@ShouheiNishi 
Thank you for reporting this issue. However, the recommended Go version for the free5gc official website is **go1.18.10**. Currently, the versions in the `go.mod` files of all NFs except for upf are set to `go 1.17`. We may consider upgrading upf to version **1.17** first to synchronize it with the other NFs.

**Comment by tim-ywliu** [comment]
@ShouheiNishi Thanks for the PR.
