### ISSUE TITLE
[Question] UEIP&FTUP Options

### ISSUE THREAD

**Issue by arxxm** [free5gc/free5gc#509]
Hello! Please tell me, are you going to add support for the UEIP and FTUP options in the near future?

**Comment by brianchennn** [comment]
@arxxm 
Currently, we don't have this plan.

**Comment by yoursunny** [comment]
Since release-16, the FTUP feature is mandatory, see [TS 129 244](https://www.etsi.org/deliver/etsi_ts/129200_129299/129244/16.05.00_60/ts_129244v160500p.pdf) section 5.5.
Has free5GC team's position on not supporting FTUP feature changed?
