### ISSUE TITLE
UPF GTP packets fails, Whether GTP is implemented

### ISSUE THREAD

**Issue by rijilrose** [free5gc/free5gc#51]
Error handling UP socket  UPF=Util
WARN[2020-05-24T17:09:36+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:09:36+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:09:45+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:09:45+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:10:08+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:10:08+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:10:10+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:10:10+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:14:59+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:14:59+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:15:02+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:15:02+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:30:52+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:30:52+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet  UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket  UPF=Util

**Comment by free5gc-org** [comment]
What's your OS, kernel version, configuration, system architecture?

Is there any pcap file provided?

**Comment by rijilrose** [comment]
Hi team,

Kernel version : 5.0.0-23-generic
Os : ubuntu 18.04
System Architecture : i3
Configuration file upf config which is in github.

Actually we are sending GPDU  as a header type to send data from one system
to outside system. But it says not implemented.

Regards,
Rigiel

**Comment by free5gc-org** [comment]
Can you provided the pcap file so that we can check whether the header we need to handle or not?

**Comment by rijilrose** [comment]
Hi Team,

Header type is 255. As per specification 29.281, data transfer is send in
gtp as GPDU. But in program it is not handled.

Regards,
Rigiel

**Comment by rijilrose** [comment]
Hi Team,

Please do reply for the message.


Regards,
Rigiel

**Comment by rijilrose** [comment]
Whether GTP supported or not? User plane routing is happening or not?

**Comment by linefive2007** [comment]
Hi Team and rijilrose 

We got same issue.
In our test, this issue is only occurs when start C-plane functions manually.
If we use "test.sh TestRegistration" (i.e. C-plane functions is started by ngsetup_test.go in src/test), this issue is not occur.

The error is happned by "GtpHandler" function (line 104 -120 on up_path.c), but we seem there is no case define for gtp header 255.

We don't understand whetehr GtpHandler should be upped when recived user packet, but I wonder why test.sh "TestRegistration" (test ping) is success.

BR,

**Comment by rijilrose** [comment]
Hi Team,

Yes actually as per specification user packet header type is 255. And in
your case ping works means whether it goes through upf ran and then UE. It
may work if you binded UE IP in a system. please confirm as by sharing the
pcap file of it. So that will check on ping packet.

Regards,
Rigiel

**Comment by free5gc-org** [comment]
Hi @rijilrose and @linefive2007,

In our implementation, the rules set by SMF will be handled directly by kernel module gtp5g and are transparent to user space process. That is to say, you will not see any rule specified in user space code handling type 255 gtp messages.
If the gtp5g didn't handle the messages due to some problem, the messages would then be passed to user space for additional handling. If the handling failed again, the error events would be generated.

However, we are still not sure what the problem is, so we suggest you provide us your pcap files and config files of SMF and UPF so that we can find the problem correctly.

**Comment by rijilrose** [comment]
What is dn interface in this command? sudo iptables -t nat -A POSTROUTING -o <dn_interface> -j MASQUERADE

**Comment by free5gc-org** [comment]
Dear @rijilrose ,

For questions and support please use the [official forum](https://forum.free5gc.org). The issue list of this repo is exclusively for bug reports and feature requests.

Also, please provide the pcap file, config zip file, kernel version, whether you have installing gtp5g module, using docker, or other useful information for debugging so that we can check what the problem is caused by.

Thanks a lot.

**Comment by rijilrose** [comment]
> In our implementation, the rules set by SMF will be handled directly by kernel module gtp5g and are transparent to user space process. That is to say, you will not see any rule specified in user space code handling type 255 gtp messages.
> If the gtp5g didn't handle the messages due to some problem, the messages would then be passed to user space for additional handling. If the handling failed again, the error events would be generated.
> 
> However, we are still not sure what the problem is, so we suggest you provide us your pcap files and config files of SMF and UPF so that we can find the problem correctly.

Please We are trying to do this as well. But still it is not happening. But the issue is closed. Means whether it is working? If i do iperf from the outer system, data is not transferred to ran. Dropping at ran only

**Comment by rijilrose** [comment]
> 
> 
> > In our implementation, the rules set by SMF will be handled directly by kernel module gtp5g and are transparent to user space process. That is to say, you will not see any rule specified in user space code handling type 255 gtp messages.
> > If the gtp5g didn't handle the messages due to some problem, the messages would then be passed to user space for additional handling. If the handling failed again, the error events would be generated.
> > However, we are still not sure what the problem is, so we suggest you provide us your pcap files and config files of SMF and UPF so that we can find the problem correctly.
> 
> Please We are trying to do this as well. But still it is not happening. But the issue is closed. Means whether it is working? If i do iperf from the outer system, data is not transferred to ran. Dropping at ran only

Dropping at **upf only**
