### ISSUE TITLE
mongodb is not found

### ISSUE THREAD

**Issue by fcahyadi** [free5gc/free5gc#513]
Hi,
I tried to follow the steps from the wiki here, but it failed when I tried to install mongodb.

ubuntu@free5gc:~$ sudo apt -y install mongodb wget git
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package mongodb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mongodb' has no installation candidate

Here is my go version:
ubuntu@free5gc:~$ go version
go version go1.21.4 linux/amd64

How can I install mongodb here? appreciate any assistance and help.

Regards,
Fajar

**Comment by brianchennn** [comment]
@fcahyadi 
Try: 
```
sudo apt update
sudo apt remove --purge mongodb
sudo apt -y install mongodb
```

BTW, there's no dependency between MongoDB & Golang.

**Comment by fcahyadi** [comment]
Hi,
it still doesnt seem to work.
Here are the logs:

***@***.***:~$ go version
go version go1.21.5 linux/amd64
***@***.***:~$ sudo apt -y update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Fetched 229 kB in 1s (409 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
***@***.***:~$ sudo apt -y install mongodb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package mongodb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mongodb' has no installation candidate
***@***.***:~$ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
***@***.***:~$
***@***.***:~$ sudo apt remove --purge mongodb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'mongodb' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
***@***.***:~$ sudo apt -y install mongodb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package mongodb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mongodb' has no installation candidate
***@***.***:~$

**Comment by brianchennn** [comment]
@fcahyadi 
Try this solution: https://stackoverflow.com/questions/72803345/unable-to-locate-package-mongodb-org

**Comment by oliveiraleo** [comment]
@fcahyadi Could you please confirm if this solution works on your installation too?

https://free5gc.org/guide/Appendix/#appendix-g-install-mongodb-70x-on-ubuntu-server-220403
