### ISSUE TITLE
[Docs] Add information regarding MongoDB installation on Ubuntu Server 22.04

### ISSUE THREAD

**Issue by oliveiraleo** [free5gc/free5gc#515]
## Documentation request

The [installation instructions](https://free5gc.org/guide/3-install-free5gc/#a-prerequisites) don't cover (yet) the installation of MongoDB on Ubuntu Server 22.04

## Suggestion

Add instructions regarding the matter on the appendix section of the docs website.

## Additional context

It's been some time since MongoDB is having issues in Ubuntu 22.04.x [[1](https://www.reddit.com/r/Ubuntu/comments/10rxme8/how_to_install_mongo_db_in_xubuntu_2204/?rdt=50063), [2](https://askubuntu.com/questions/1402179/not-able-to-install-mongodb-in-ubuntu-22-04), [3](https://stackoverflow.com/questions/72803345/unable-to-locate-package-mongodb-org)] and recently (while migrating my free5GC installation to Ubuntu 22.04.3) I've faced similar issues. As seen by me and pointed out by someone else (see https://github.com/free5gc/free5gc/issues/513), it might affect free5GC installations that are using Ubuntu 22.04 as MongoDB is a dependency.

So, I could fix the issue in my installation and wanted to share the knowledge with the community.

**Comment by brianchennn** [comment]
@oliveiraleo 
Thank you so much for saving our life!
