### ISSUE TITLE
Establish Wi-Fi signal using non 3GPP access to connect 5G core network

### ISSUE THREAD

**Issue by SaiPrathyushaa** [free5gc/free5gc#520]
Hi,

Can i connect actual/real UE to core network using non 3GPP access N3IWF.
Actually we are able to attach UE in Simulator mode,
Now we are looking into hardware part to establish Wi-Fi by using N3IWF and need to connect with 5g core,

Could you please suggest suitable hardware which is useful for N3IWF?

Thanks in advance.

**Comment by a3828162** [comment]
Because secure association authentication needs to be conducted over WiFi, it's not possible to connect using the ready-made N3UE. It may be necessary to implement a custom UE to enable authentication through WiFi. You can refer to wpa_supplicant for guidance.
