### ISSUE TITLE
About 2020-03-31-01 in upf directory

### ISSUE THREAD

**Issue by SaiPrathyushaa** [free5gc/free5gc#522]
Hi @brianchennn,

What is the meaning of 2020-03-31-01 in upf directory Version.sh file.
How to get this version?

Thanks in advance

**Comment by andy89923** [comment]
Is the file you indicate located at https://github.com/free5gc/upf/blob/main/version/version.sh? 

Just to let you know, free5GC is now using UPF at **https://github.com/free5gc/go-upf** instead of https://github.com/free5gc/upf.

**Comment by SaiPrathyushaa** [comment]
okay thank you
