### ISSUE TITLE
[Feat] 您好，想咨询一下AF和NEF功能大约什么时候发布？

### ISSUE THREAD

**Issue by xiongkai0920** [free5gc/free5gc#533]

**Comment by andy89923** [comment]
Hello, 

If everything goes smoothly, the NEF will be released shortly.

**Comment by andy89923** [comment]
Hello, 

We have uploaded the roadmap on the official website. 
You can see the schedule for our upcoming features there: https://free5gc.org/. 

Thanks for your support to free5GC!
