### ISSUE TITLE
Is multicast feature supported on V3.3.0 ?

### ISSUE THREAD

**Issue by rajendra1124** [free5gc/free5gc#537]
Hello free5gc team,

I need to test the multicast service through the 5G core and want to know if it is supported on the data plane. 
I am using 5G V3.3.0 in an emulated environment and I want to test the IPTV service through the 5G core to the UE.
Thanks,

**Comment by andy89923** [comment]
Hi, 

No, the multicast feature is **not** supported in v3.3.3 and the main branch. We would consider this in the future. 
Thanks.
