### ISSUE TITLE
[Docs] How to add subscriber via REST-API

### ISSUE THREAD

**Issue by Stainless2k** [free5gc/free5gc#539]
## Documentation request

Simple documentation of the REST-API.

## Suggestion

Just add endpoints and how to use them, like any other REST-API

## Additional context
We need to add lots of generated Subscriber data (100-1000 UEs), but right now it just seems to be possible via the Web-Ui. We just need a simple description of the REST-endpoint that handles the creation of the subscribers, so we can do it via a shell script (just curl the api...)

**Comment by yccodr** [comment]
You can make a POST request on '\<uri\>/api/subscriber/\<ueId\>/\<plmnId\>' with subscription info put in the request body (json format).

For more detail, see the [postman collection](https://github.com/free5gc/webconsole/blob/main/free5gc-Webconsole.postman_collection.json) on our repo.

For the request body schema, see the `Subscription` on this [site](https://petstore3.swagger.io/?url=https://raw.githubusercontent.com/free5gc/webconsole/main/frontend/webconsole.yaml)

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/add-lots-of-generated-subscriber-data-via-script/2327/2
