### ISSUE TITLE
[Feat]How can I set a static IP address for a UE?

### ISSUE THREAD

**Issue by ex8664** [free5gc/free5gc#543]
According to the following URL, free5gc should support the setting of static IP addresses.

https://free5gc.org/guide/features/#supported-features
- Dynamic/Static IPv4 address allocation

I interpret this as referring to the IP address allocation for PDU sessions assigned to UEs. However, I could not find where to configure this in the version 3.4.0 web console.

What changes are needed to set a static IP for PDU sessions allocated to a UE?

**Comment by ianchen0119** [comment]
Hi @ex8664 

Sorry for late reply.
It seems like the related component in webconsole has been removed during the React upgrade work.
We will add this feature back asap, Thanks.

**Comment by ex8664** [comment]
Hi @ianchen0119

Thank you for your response. 
I am looking forward to the feature being available.

**Comment by andy89923** [comment]
Hello, 

The UI will be added back via https://github.com/free5gc/webconsole/pull/85.
