### ISSUE TITLE
[Bugs] N3IWUE fails to stablish network connection with N3IWF in v3.4.0

### ISSUE THREAD

**Issue by oliveiraleo** [free5gc/free5gc#545]
## Describe the bug
I tried to run the N3IWF on free5GC, however it doesn't start. When I run the TestNon3GPP, the test passes (logs attached on trace file section). When I start free5GC with the N3IWF (both with the default config or after following the instructions from [here](https://free5gc.org/guide/n3iwue-installation/) ), then it fails to load N3IWF with the error "[ERRO][N3IWF][NGAP] [SCTP] DialSCTP(): connection refused"

## To Reproduce
1. Clone  and install free5GC
2. Start the `run.sh` script with `-n3iwf` parameter
3. N3IWF can't start

## Expected behavior
free5GC and N3IWF load correctly.

## Screenshots

![image](https://github.com/free5gc/free5gc/assets/25849028/87ddad00-4def-4862-8bd7-d1c3ba5634ef)

## Environment:
 - free5GC Version: v3.4.0*
 - OS: Ubuntu Server 20.04.6
 - Kernel version: 5.4.0-173-generic
 - go version: go1.21.6 linux/amd64
 - c compiler version (Option): gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

\* I also have tried with nightly (commit https://github.com/free5gc/free5gc/commit/8bfdd817c44fd1342accb6e7af5f73a5f0edc223) too with the same result

### Configuration File
[free5gc-config.zip](https://github.com/free5gc/free5gc/files/14601425/free5gc-config.zip)

### PCAP File
[free5gc.pcap.zip](https://github.com/free5gc/free5gc/files/14601351/free5gc.pcap.zip)

### Log File
[free5gc.log](https://github.com/free5gc/free5gc/files/14601103/free5gc.log)

[free5gc-TestNon3GPP-log.txt](https://github.com/free5gc/free5gc/files/14601470/free5gc-TestNon3GPP-log.txt)

The N3IWF slice of the `free5gc.log` file is below:
```
2024-03-13T23:46:42.716519029Z [INFO][N3IWF][Main] N3IWF version:  
	free5GC version: v3.4.0-17-g8bfdd81
	build time:      2024-03-13T21:15:35Z
	commit hash:     a4088a87
	commit time:     2023-12-19T09:23:50Z
	go version:      go1.21.6 linux/amd64
2024-03-13T23:46:42.716575719Z [INFO][N3IWF][CFG] Read config from [./config/n3iwfcfg.yaml]
2024-03-13T23:46:42.717434421Z [INFO][N3IWF][Main] Log enable is set to [true]
2024-03-13T23:46:42.717449811Z [INFO][N3IWF][Main] Log level is set to [info]
2024-03-13T23:46:42.717461991Z [INFO][N3IWF][Main] Report Caller is set to [false]
2024-03-13T23:46:42.717469251Z [INFO][N3IWF][Init] Server started
2024-03-13T23:46:42.717647921Z [WARN][N3IWF][CTX] Parse PKCS8 private key failed: x509: failed to parse private key (use ParsePKCS1PrivateKey instead for this key format)
2024-03-13T23:46:42.717669251Z [INFO][N3IWF][CTX] Parse using PKCS1...
2024-03-13T23:46:42.741264847Z [WARN][N3IWF][Init] netlink.RouteAdd: file exists
2024-03-13T23:46:42.741299217Z [INFO][N3IWF][Init] Setup XFRM interface xfrmi-default
2024-03-13T23:46:42.742817060Z [ERRO][N3IWF][NGAP] [SCTP] DialSCTP(): connection refused
2024-03-13T23:46:42.742880450Z [INFO][N3IWF][NGAP] Retry to connect AMF after 1 second...
2024-03-13T23:46:43.744089769Z [ERRO][N3IWF][NGAP] [SCTP] DialSCTP(): connection refused
2024-03-13T23:46:43.744122919Z [INFO][N3IWF][NGAP] Retry to connect AMF after 1 second...
2024-03-13T23:46:44.777509353Z [ERRO][N3IWF][NGAP] [SCTP] DialSCTP(): connection refused
2024-03-13T23:46:44.777553264Z [INFO][N3IWF][NGAP] NGAP receiver stopped
2024-03-13T23:46:44.777562624Z [ERRO][N3IWF][NGAP] Failed to connect to AMF.
2024-03-13T23:46:44.777572284Z [ERRO][N3IWF][Init] Start NGAP service failed: NGAP service run failed
```

## System architecture (Option)

VM running on Oracle Virtual Box

free5GC's VM has a fixed IP (10.0.0.110)

## Additional context
I tried to change `Nwu interfaces parameters` and the `GTPBindAddress` IP but without success. I've also tried to run my setup on another local network address (172.16.x.x) to avoid IP conflicts and I get the same error.

Another thing I tried was to run N3IWF after the other NFs (as suggested [here](https://forum.free5gc.org/t/n3iwf-connection-to-amf-fails/1337) ) to make sure AMF is already running when N3IWF starts. This [other post](https://forum.free5gc.org/t/testnon3gpp-network-interface-help/2164/7) suggested to use the recommended software (Ubuntu 20.04 and kernel 5.4.x) which is what I'm currently using (see screenshot above)

PS: I didn't post my issue on free5GC forum because I couldn't get the confirmation mail (is protonmail blocked there?)

TIA, Leo.

**Comment by a3828162** [comment]
Hi @oliveiraleo ,
In your  `amfconfig.yaml`, you set the `ngapIPList ` from `127.0.0.18 ` to `10.0.0.100`. But in your `n3iwfconfig.yaml` , `AMFSCTPAddresses ` still 127.0.0.18, you should set `AMFSCTPAddresses` same as `ngapIPList 10.0.0.100 ` in `amfconfig.yaml` . That is why your n3iwf can't connect to AMF.

Best regard,
James

**Comment by oliveiraleo** [comment]
Hello @a3828162 thanks for the promptly reply.

I've applied your suggestion to my configuration and now N3IWF starts correctly.

I didn't think about changing it because the instructions [here](https://free5gc.org/guide/5-install-ueransim/#5-setting-free5gc-and-ueransim-parameters) tell to update `ngapIPList` however this information isn't present on N3IWUE instructions contained [here](https://free5gc.org/guide/n3iwue-installation/#4-setting-n3iwf-config). I can update this information there and make a PR on the docs repo :)

BTW, I'd like to know how to deal correctly with the `IPSecTunnelAddress` parameter on `n3iwfcfg.yaml` because on the current configuration, its IP (10.0.0.x) conflicts with 10.0.0.110 which is where my 5GC is hosted. If I change it to something else (let's say 172.16.0.1), I should update `IPsecInnerAddr` inside `n3ue.yaml` file accordingly, right? Is there something else I need to change?

Regards, Leo.

**Comment by oliveiraleo** [comment]
Hello,

> Because if you only want to test N3IWUE, you don't need to modify `ngapList` to make it work, so I didn't include it in the article.
 
So, "test N3IWUE" in this case means running N3IWUE and free5GC + N3IWF on the same VM, right? Anyway, I'd like to suggest to add this information on the docs (I'll send a suggestion on the coming days so we can review it on the docs repo)

> That's right, and you also need to change `UEIPAddressRange` , for example, `172.16.0.0/24`.

I did that (config files attached below) but no lucky getting the ping to work on the N3IWUE machine (see the slice below):

```
2024-03-16T23:39:31Z [INFO][N3UE][APP] --- 8.8.8.8 ping statistics ---
2024-03-16T23:39:31Z [INFO][N3UE][APP] 5 packets transmitted, 0 packets received, 100% packet loss
2024-03-16T23:39:31Z [INFO][N3UE][APP] round-trip min/avg/max/stddev = 0s/0s/0s/0s
2024-03-16T23:39:32Z [ERRO][N3UE][APP] ping fail : Ping Failed
```

I've noticed on the logs that N3IWF loads correctly, and the IP is correctly set to `172.16.0.1` on the interface. On N3IWUE side it authenticates and establishes a PDU session  correctly (`10.0.0.110` is the free5GC VM DN interface IP and N3IWUE is hosted at `10.0.0.112`). BTW, the ping test works correctly on UERANSIM, so I guess there's no problem with firewall configuration on free5GC's side.

Is there something else I need to change to run N3IWUE (as suggested by [the guide page](https://free5gc.org/guide/n3iwue-installation/#1-install-n3iwue-vm)) on its own machine?

### Attachments

Config files: [free5gc-n3iwf-configs.zip](https://github.com/free5gc/free5gc/files/14625563/free5gc-n3iwf-configs.zip)

Log files: [free5gc-n3iwf-logs.txt](https://github.com/free5gc/free5gc/files/14625586/free5gc-n3iwf-logs.txt) / [free5gc-n3iwue-logs.txt](https://github.com/free5gc/free5gc/files/14625587/free5gc-n3iwue-logs.txt)

Best regards, Leo.

**Comment by a3828162** [comment]
Hi @oliveiraleo ,
> So, "test N3IWUE" in this case means running N3IWUE and free5GC + N3IWF on the same VM, right? Anyway, I'd like to suggest to add this information on the docs (I'll send a suggestion on the coming days so we can review it on the docs repo)


I mean that one VM run n3iwue, and another VM run free5gc+n3iwf. In this case, you don't need to change the `ngapListIP` of the AMF, you just need to change the `IKEBindAddress` in `n3iwueconfig.yaml`.

I checked that your config file is correct,Please verify if the following is accurate.

Can your n3ue VM ping the n3iwf+free5gc VM correctly? And have you executed the following commands on your free5gc VM? If the VM is restarted, these commands need to be executed again.
```
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o <dn_interface> -j MASQUERADE
# e.g. sudo iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
sudo systemctl stop ufw
sudo systemctl disable ufw
```
and make sure `IPSecIfaceName` in `n3ue.config` correctly.

Best regards,
James

**Comment by oliveiraleo** [comment]
Hello @a3828162,

> I mean that one VM run n3iwue, and another VM run free5gc+n3iwf. In this case, you don't need to change the ngapListIP of the AMF, you just need to change the IKEBindAddress in n3iwueconfig.yaml.

First, now I get it. That already was the kind of setup I was trying to replicate.

PS: IG you meant `n3iwfcfg.yaml` instead of `n3iwueconfig.yaml` (just leaving this here to future reference)

So, I've done other tests and decided to record a video to help explain the issue. Even after getting a ping fail on N3IWUE, I tried to run some pings on the interfaces created by its execution (I'm not sure if I did it correctly as the interface returned a `No such device` error). 

> Can your n3ue VM ping the n3iwf+free5gc VM correctly? And have you executed the following commands on your free5gc VM? If the VM is restarted, these commands need to be executed again.

I did run pings from N3IWUE machine to the free5GC one using the default network interface and they succeeded. During the recording I apply the firewall rules before execution so I think this is not the issue.

I'm attaching below the execution logs of the machines involved and a screenshot depicting the N3IWUE configuration on WebConsole.

If any other information is required, just ping me.

### Attachments

Video recording URL: https://www.youtube.com/watch?v=livdY2dqZpA

Log files: [free5gc-video-n3iwue-logs-and-webconsole.zip](https://github.com/free5gc/free5gc/files/14628950/free5gc-video-n3iwue-logs-and-webconsole.zip)

TIA, Leo.

**Comment by a3828162** [comment]
Hi @oliveiraleo ,
We are currently addressing this issue. You can switch free5gc to V3.3.0, which is functioning normally.

Best Regards,
James

**Comment by oliveiraleo** [comment]
Hello,

I've reverted my installation to free5GC v3.3.0 and I can confirm that N3IWUE works correctly with it (screenshot below)

![image](https://github.com/free5gc/free5gc/assets/25849028/d5407179-9a3e-4ebf-ad29-a0825c75def5)

I've manually tested  the ping functionality (screen below) and traceroute and they both work too.

![image](https://github.com/free5gc/free5gc/assets/25849028/9f8b3d2e-b844-4955-a3f2-8a430c02e8e4)

Once the issue is solved, I'd be happy to help testing it, please, just ping me here. BTW, thanks for your time.

Best regards, Leo.

**Comment by andy89923** [comment]
Hi,

I'm happy to announce that **free5GC v3.4.1** has been released.

After my testing, I can confirm that N3IWUE is working normally. Thanks to the free5GC team for their great work!
![n3ue](https://github.com/free5gc/free5gc/assets/28786462/e05e8410-948f-487d-9428-dda058aa72ad)



If you have any further questions, please feel free to ask.

**Comment by oliveiraleo** [comment]
Hello,

I've tested the new version v3.4.1 and I can confirm that now both the ping test and interface pings work in N3IWUE's VM (screenshots attached below for future reference). As soon as I have time I'll try to help to update/improve the docs.

Thanks a lot for the work and the promptly replies.

Regards, Leo.

## Screenshots

N3IWUE ping test:

![image](https://github.com/free5gc/free5gc/assets/25849028/71f76000-8357-4674-9332-adb87598ca78)

Virtual interface ping test to other sources:

![image](https://github.com/free5gc/free5gc/assets/25849028/ebf88b23-dbee-4c59-96e0-ecfca16b68c4)
