### ISSUE TITLE
[Feat]Options for Creating an sslkey.log

### ISSUE THREAD

**Issue by ex8664** [free5gc/free5gc#549]
I need the XXXsslkey.log file, but it wasn't generated as default. (v3.4.0)

I started the AMF with the following option:
./bin/amf -l log/amf.log

By doing this, the following two files were generated
log/amf.log
log/key/amfsslkey.log

I find it counterintuitive that log/key/amfsslkey.log is generated with -l log/amf.log.
Is this the expected behavior?

I think it would be better to have sslkey.log created by default or to have a more intuitive option for specifying its creation.

**Comment by andy89923** [comment]
Hello, 

> By doing this, the following two files were generated
> log/amf.log
> log/key/amfsslkey.log
> Is this the expected behavior?

Yes, it's the current behavior for each NF now. 

Thanks for the advice. 
We would consider refactoring each NF to have a more intuitive way to generate log files.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/xxsslkey-log-location-with-helm-deployment/2570/2
