### ISSUE TITLE
Profile B not implemented

### ISSUE THREAD

**Issue by FatimaaIsmail27** [free5gc/free5gc#556]
Hello,
while I was trying to implement profile A and profile B schemes, I changed the configuration in free5gc-ue.yaml in UERANSIM and chose protection scheme 1 and profile A was implemented successfully.. when I tried profile B, I got the following error:

![Capture](https://github.com/free5gc/free5gc/assets/139501201/189c6622-0dea-4f2e-9037-957c3436cbd7)

So profile B is not implemented in free5gc? I'm wondering because I saw public and private key corresponding to profile B in udmconfig..

Thank you in advance..

**Comment by andy89923** [comment]
Hello, 

The free5GC had implemented Profile B in UDM.

However, the reason for "Protection Scheme 2 not implemented" was produced by UERANSIM; you can refer to this [line](https://github.com/aligungr/UERANSIM/blob/9082957b430ae772c399ac94b8a33eb80d6dfb63/src/ue/nas/mm/identity.cpp#L122).
