### ISSUE TITLE
[Bugs] Wrong Interface Type in PFCP Session Establishment Request for IP Based PDU Session

### ISSUE THREAD

**Issue by bertuola** [free5gc/free5gc#557]
## Describe the bug
The **Source Interface Type** used in PFCP Session Establishment Request should be **Core** for IP based PDU Session; instead, the value is **SGi-LAN/N6-LAN**, referring to a Ethernet based PDU Session (3GPP 29.244, 8.2.2-1).

Also the 3GPP Interface Type IE is missing (3GPP 29.244, 8.2.118).

## To Reproduce
1. Run a TestRegistration scenario and check the wireshark trace.

## Expected behavior
Here how the PFCP Establishment Request should look like:

[PFCP_Establishment_Request_Reference.txt](https://github.com/free5gc/free5gc/files/15021414/PFCP_Establishment_Request_Reference.txt)

## Screenshots

![PFCP_Wrong_Source_Interface](https://github.com/free5gc/free5gc/assets/19303811/430be266-a305-4f63-bff7-f99539755dee)

![3GPP_29 244_SourceInterfacepng](https://github.com/free5gc/free5gc/assets/19303811/d3f29886-2845-48bf-a01c-3a53f26682af)

![3GPP_29 244_3gppSourceInterface](https://github.com/free5gc/free5gc/assets/19303811/fe33804f-cc2d-446c-bfc5-14da2e393ce3)

## Environment (please complete the following information):
 - free5GC Version: 3.4.1
 - OS: Ubuntu 20.04.6
 - Kernel version: 5.4.0-174-generic

### PCAP File
[TestRegistration.zip](https://github.com/free5gc/free5gc/files/15021380/TestRegistration.zip)

**Comment by ming-hsien** [comment]
Hello, Tks for you for your questions.
May I ask if you can provide the version of 3GPP 29.244 for reference?

**Comment by bertuola** [comment]
The **Interface Value** has been defined since beginning, while **Interface Type** is defined starting from [v15.6.0](https://www.etsi.org/deliver/etsi_ts/129200_129299/129244/15.06.00_60/ts_129244v150600p.pdf) released on 2019-06-13.

**Comment by ianchen0119** [comment]
Hi @bertuola 

Refer to 5.4.8 Traffic Steering in 3GPP TS 29.244

> The CP function shall control the processing of the traffic received from the (S)Gi-LAN or N6-LAN in the UP function
as specified in the rest of this specification for traffic received from any other interface, but with PDR(s) including a
PDI with the Source Interface indicating "SGi-LAN/N6-LAN". The UP function shall distinguish packets coming from
(S)Gi-LAN/N6-LAN based on local configuration. 

I think our current implementation is correct.
As for the interface CORE, it be used to indicate the data from the anchor UPF (You will see in the dl pdr, applied to I-UPF, in ULCL deployment).

> Also the 3GPP Interface Type IE is missing (3GPP 29.244, 8.2.118).

![image](https://github.com/free5gc/free5gc/assets/42661015/c104ae77-62b3-4588-b65b-a669c2fcebb0)

Refer to Table 7.5.2.2-2: PDI IE within PFCP Session Establishment Request, described in TS 29.244
The Source Interface Type IE is optional.
Is this IE should be set in your use case?
If yes, please let us know.

Thank you.

**Comment by bertuola** [comment]
Hi.

I agree **Interface Type IE** is optional; regarding the **Source Interface Type**, I don't.

There are different PDU Session Types that can be established in 5GC: **IP Based** (Source Interface Type=Core), or **Ethernet Based** (Source Interface Type=SGi-LAN/N6-LAN), or Unstructured.

To confirm it, here the same request made by LoadCore/Ixia simulator:

![image](https://github.com/free5gc/free5gc/assets/19303811/673964e2-78ea-4285-8116-69661fb3d8d1)

**Comment by ianchen0119** [comment]
Hi @bertuola 

I think you were right.
we will fix this issue, thanks for your information.

**Comment by ianchen0119** [comment]
Hi @bertuola 

This issue will be fixed in the incoming release v3.4.2.

FYR
https://github.com/free5gc/smf/pull/110

Thanks.
