### ISSUE TITLE
[Bugs] LGPL module is used in CHF

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/free5gc#565]
## Describe the bug
The LGPL-licensed module "github.com/juju/fslock" is used in CHF.

## Walkthrough (Option)
This module is used by the field CdrFileLock in the struct ChfUe in the file "NFs/chf/internal/context/ue_context.go".

**Comment by ianchen0119** [comment]
Hi @ShouheiNishi 
This issue just been fixid by https://github.com/free5gc/chf/pull/27
Thanks for your information.
