### ISSUE TITLE
[Bugs] Registration Status Update Error when connecting to a physical UE

### ISSUE THREAD

**Issue by osamirabo** [free5gc/free5gc#567]
## Describe the bug
Currently we are trying to deploy a physical setup using the following components: 

- Samsung S21 Ultra as UE
- srsRAN and USRP B210 kit as gNB
- free5GC as a core network

but this doesn't happen and instead we got the following error :
amf       | 2024-05-20T12:10:42.713761098Z [ERRO][AMF][Gmm][amf_ue_ngap_id:RU:0,AU:1(3GPP)][supi:SUPI:imsi-001010000000001] Registration Status Update Error[: server no response]

## To Reproduce
1. Change config as described in the configs file
2. Add the subscriber in the web console with the corresponding values
3. Run free5GC: docker compose -f docker-compose-build.yaml up 
4. Run srsRAN:  docker compose -f srsgnb.yaml down
5. Change UE from airplane mode to data

## Expected behavior
UE shall connects to 5G network but this don't happen.

## Screenshots
![Screenshot from 2024-05-20 16-23-09](https://github.com/free5gc/free5gc/assets/28990543/816893c8-346d-43dd-ae3d-2386a491648e)

## Environment (please complete the following information):
 - free5GC Version: v3.4.1
 - OS: Ubuntu 20.04.6 LTS 
 - Kernel version: 5.15.0-97-generic
 - go version: 1.22.3 linux/amd64
 - c compiler version (Option): gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

### Configuration File
[config.zip](https://github.com/free5gc/free5gc/files/15377092/config.zip)

### PCAP File
[wireshark_free5g_pcap.zip](https://github.com/free5gc/free5gc/files/15377075/wireshark_free5g_pcap.zip)

### Log File
[amf.log.txt](https://github.com/free5gc/free5gc/files/15377489/amf.log.txt)

amf       | 2024-05-20T12:10:42.713761098Z [ERRO][AMF][Gmm][amf_ue_ngap_id:RU:0,AU:1(3GPP)][supi:SUPI:imsi-001010000000001] Registration Status Update Error[: server no response]
nrf       | 2024-05-20T12:10:42.714954709Z [INFO][NRF][DISC] Handle NFDiscoveryRequest
nrf       | 2024-05-20T12:10:42.717942641Z [INFO][NRF][GIN] | 200 |   10.100.200.10 | GET     | /nnrf-disc/v1/nf-instances?requester-nf-type=AMF&target-nf-type=AMF |
amf       | 2024-05-20T12:10:42.718718668Z [INFO][AMF][Ngap][amf_ue_ngap_id:RU:0,AU:1(3GPP)][ran_addr:10.100.200.250:45511] Send Reroute Nas Request
amf       | 2024-05-20T12:10:42.719221065Z [ERRO][AMF][Gmm] AMF can not select an target AMF by NRF

## System architecture
free5GC is deployed using docker

## Walkthrough
It seems that the mobile RequestedNssai - ServingSnssai: &{Sst:1 Sd:}, but we cannot configure free5GC to accept Sd = "". We tried to reset ore set SD from the mobile but we don't succeeded.

**Comment by ianchen0119** [comment]
Hi @osamirabo 

This issue will be fixed in the next release.
Thanks for your information.

**Comment by linouxis9** [comment]
Hi @osamirabo,

In the meanwhile, does it work if you configure your network functions with sd: "ffffff"

Valentin

**Comment by osamirabo** [comment]
@ianchen0119 Great to hear it will be fixed in next release. Thank you for your quick response.

**Comment by osamirabo** [comment]
@linouxis9 I tried using sd: "ffffff" but still have the same issue

**Comment by ianchen0119** [comment]
@osamirabo 
Did you set the related slice (sd: `ffffff`) in NF configurations?

Thanks.

**Comment by osamirabo** [comment]
@ianchen0119 

Yes I set it in the configuration files and in the webconsole interface also. Please find the config files attached 
[config_0xffffff.zip](https://github.com/free5gc/free5gc/files/15454499/config_0xffffff.zip)


Thank You

**Comment by andy89923** [comment]
Hi,
Sorry for the late reply, we are fixing this issue now. 
It may took couples of week, I would update info here.

**Comment by andy89923** [comment]
Hi, the PR had been merged. You can checkout to latest commit and test it. 

If you encounter any problems, just post it here and reopen the issue.

Best, 
Andy
