### ISSUE TITLE
[Bugs] N1N2 Transfer Fail while testing 45K UE in a loop .

### ISSUE THREAD

**Issue by sambitcom** [free5gc/free5gc#569]
**We will advise people to follow the issue template set, otherwise the issue might be disregarded.**
**free5GC mainly uses GitHub for issue tracking. Information regarding to general questions or technical support. It will be highly considered if forward to the [forum](https://forum.free5gc.org).**
**free5GC will appreciate it, if people can refer to [TS](https://github.com/free5gc/free5gc/wiki/Trouble_Shooting) and [forum](https://forum.free5gc.org) prior to bug reporting**

## Describe the bug
I am getting N1N2 Transfer fail while running 45K UE from HP Packer rusher (UE simulator) in a loop.

## To Reproduce
1. Setup 5GC with ./run.sh
2. Run packet rusher command ./PacketRusher/packetrusher multi-ue -n 45000 -l
3. Please make sure you do the  below setting before execution both at UE and 5GCORE
sudo echo 268435455 > /proc/sys/net/core/wmem_max
#sudo echo 268435455 > /proc/sys/net/core/wmem_max
#sudo echo 268435455 > /proc/sys/net/core/rmem_max
#sudo echo 268435455 > /proc/sys/net/core/wmem_default
#sudo echo 268435455 > /proc/sys/net/core/rmem_default
#sudo echo 20000000 > /proc/sys/net/core/netdev_max_backlog
4. This behaviour can reproduced in lower number of UE too.
[Uploading free5gc.zip…]()

## Expected behavior
it should continuously run in loop without any issue.

## Screenshots
If applicable, add screenshots to help explain the problem.

## Environment (please complete the following information):
 - free5GC Version: [e.g. v3.0.100]
 - OS: [e.g. Ubuntu 200.04 Server]
 - Kernel version: [e.g. 5.200.0-0-generic]
 - go version: [e.g. 1.10.0 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 1.1.0]

### Configuration File
Provide the configuration file here.

If not clear of what to do, the `config` folder can be zip and upload it here.

### PCAP File
Dump the packet and provide the pcap file here.

If not clear of what to do, this command can be used `sudo tcpdump -i any -w free5gc.pcap` prior to running bug reproduce. Then upload the pcap file `free5gc.pcap`.

### Log File
Provide the program log file here.

If not clear of what to do, copy the printed log on the screen and upload it here.

## System architecture (Option)
Please provide the draft architecture, including the scenario, use cases, installation environment(bare metal, vm, container, or k8s), etc.

## Walkthrough (Option)
free5GC will be interested on the research or finding in brief.

## Additional context
It will be appreciated if other context can be added here.

**Comment by sambitcom** [comment]
[free5gc.zip](https://github.com/free5gc/free5gc/files/15417743/free5gc.zip)

**Comment by sambitcom** [comment]
I have added the logs.zip again. 

I want to add few points on my side. This issue is visible sooner when CP traffic TP is around 10Mbps. I have created multiple instances of packetrushrer to simulate 5K UE /instance. I have created a bash script to run packet rusher in multiple instances. below is the sample script.

./PacketRusher/packetrusher multi-ue -n 5000 -l  &
./PacketRusher_1/packetrusher multi-ue -n 5000 -l &
./PacketRusher_2/packetrusher multi-ue -n 5000 -l  &
./PacketRusher_3/packetrusher multi-ue -n 5000 -l &
./PacketRusher_4/packetrusher multi-ue -n 5000 -l  &
./PacketRusher_5/packetrusher multi-ue -n 5000 -l  &
./PacketRusher_6/packetrusher multi-ue -n 5000 -l  &
./PacketRusher_7/packetrusher multi-ue -n 5000 -l &
./PacketRusher_8/packetrusher multi-ue -n 5000 -l &
./PacketRusher_9/packetrusher multi-ue -n 5000 -l  &

**Comment by sambitcom** [comment]
CPU at 5G cote
![image](https://github.com/free5gc/free5gc/assets/28478999/986b9cec-aa4e-4011-9dea-db17fe90f84b)
![image](https://github.com/free5gc/free5gc/assets/28478999/00e25d25-8ec3-4411-bf95-290e9005cfd7)

CPU at PacketRusher 
![image](https://github.com/free5gc/free5gc/assets/28478999/f7d973d5-744c-499f-a2b5-4ae65d30e6da)

**Comment by sambitcom** [comment]
I have a new logs. But size is big.  below is the stack tarce.Can you let me know how to upload the entire logs  Git allowing only 

o" msg="Handle UplinkNASTransport (RAN UE NGAP ID: 2722)" CAT="Ngap" NF="AMF" amf_ue_ngap_id="RU:2722,AU:24537(3GPP)" ran_addr="10.35.52.52:9493"
time="2024-05-23T14:28:12.693598625Z" level="info" msg="AmfUe[imsi-208930000032721] is removed" CAT="CTX" NF="AMF"
time="2024-05-23T14:28:12.693687918Z" level="fatal" msg="panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 48 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/free5gc/amf/internal/ngap/service.handleConnection.func1()\n\t/home/sambit/free5gc/NFs/amf/internal/ngap/service/service.go:183 +0x58\npanic({0xc13e00, 0x1359c40})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\ngithub.com/free5gc/amf/internal/nas.HandleNAS(0xc00a4e7a40, 0xc010e7d680?, {0xc00ff098c0, 0x39, 0x40}, 0x50?)\n\t/home/sambit/free5gc/NFs/amf/internal/nas/handler.go:36 +0x18c\ngithub.com/free5gc/amf/internal/ngap.handleUplinkNASTransportMain(0xc011ed0f50?, 0xc00a4e7a40, 0xc0126148d0?, 0xc00e160100?)\n\t/home/sambit/free5gc/NFs/amf/internal/ngap/handler.go:120 +0x6a\ngithub.com/free5gc/amf/internal/ngap.handlerUplinkNASTransport(0xc00050c000, 0xc004039dc0)\n\t/home/sambit/free5gc/NFs/amf/internal/ngap/handler_generated.go:11251 +0x8b0\ngithub.com/free5gc/amf/internal/ngap.dispatchMain(0xc00050c000, 0x66?)\n\t/home/sambit/free5gc/NFs/amf/internal/ngap/dispatcher_generated.go:112 +0x45f\ngithub.com/free5gc/amf/internal/ngap.Dispatch({0xe85690?, 0xc000503140}, {0xc01420c000, 0x66, 0x40000})\n\t/home/sambit/free5gc/NFs/amf/internal/ngap/dispatcher.go:49 +0x214\ngithub.com/free5gc/amf/internal/ngap/service.handleConnection(0xc000503140, 0x40000, {0xd84778?, 0xd84788?, 0xd84780?})\n\t/home/sambit/free5gc/NFs/amf/internal/ngap/service/service.go:236 +0x419\ncreated by github.com/free5gc/amf/internal/ngap/service.listenAndServe\n\t/home/sambit/free5gc/NFs/amf/internal/ngap/service/service.go:157 +0xa0a\n" CAT="Ngap" NF="AMF"
time="2024-05-23T14:28:12.694394983Z" level="info" msg="Handle NFDiscoveryRequest" CAT="DISC" NF="NRF"
time="2024-05-23T14:28:12.695024772Z" level="info" msg="| 200 |       127.0.0.1 | GET     | /nnrf-disc/v1/nf-instances?requester-nf-type=UDM&target-nf-type=UDR | " CAT="GIN" NF="NRF"
time="2024-05-23T14:28:12.695617707Z" level="info" msg="Handle QueryAuthSubsData" CAT="DataRepo" NF="UDR"

**Comment by andy89923** [comment]
> [free5gc.zip](https://github.com/free5gc/free5gc/files/15417743/free5gc.zip)

Hello, 
Thanks for reporting this issue. 
Could you provide which version of free5GC you are using? (AMF specifically). 

I found the panic in this file was occurring at `free5gc/NFs/amf/internal/gmm/handler.go:2215`.
But in the latest version of this line, there is nothing.

**Comment by sambitcom** [comment]
I am using below version
   free5GC version: v3.3.0-28-ga96346f
        build time:      2024-01-24T06:50:28Z
        commit hash:     9458f795
        commit time:     2024-01-09T10:35:18Z
        go version:      go1.18.10 linux/amd64

**Comment by sambitcom** [comment]
any finding ?

**Comment by andy89923** [comment]
Sorry for the late reply. We are working on fixing another bug. 
Could you try to use free5gc v3.4.1 or the latest version on the main branch and see if the same problem occurs?

**Comment by sambitcom** [comment]
Is it okay to upgrade only AMF? Because at least for 1 week I will not able to upgrade the entire system due to ongoing test at my end.

**Comment by andy89923** [comment]
> Is it okay to upgrade only AMF? Because at least for 1 week I will not able to upgrade the entire system due to ongoing test at my end.

I think it's ok to upgrade only AMF.
Using the latest version of AMF could be helpful for us to address the bug.
