### ISSUE TITLE
Raising an Error instead of using default IP (localhost)

### ISSUE THREAD

**Issue by endrigoshi** [free5gc/free5gc#57]
As I am using a distributed deployment of the free5gc, I have noticed in many cases that the setup doesn’t work due to the hardcoding of the IP addresses in the code.

I would suggest that in places where the IP is resolved or checked if it is provided in the config (e.g. AMF searching for SMF in NFR), instead of assuming that all NFs run in the same machine and basically hardcoding the IP, an Error to be raised to notify that there is a problem with the provided IP address.

To illustrate, I was getting an Error that SMF could not be fetched in the NRF, but the problem instead was that for that procedure the AMF was trying to search in the localhost (assuming NRF runs locally) instead of raising an error that there was a problem with resolving the IP address of NRF.

**Comment by free5gc-org** [comment]
I think this issue is similar to [Suggestion for adjusting hardcode and question](https://forum.free5gc.org/t/suggestion-for-adjusting-hardcode-and-question/47).

Maybe we can collect all hardcode bug in this issue and then we can gradually fix it?

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/suggestion-for-adjusting-hardcode-and-question/47/3

**Comment by free5gc-org** [comment]
Webconsole hardcode: UEInfo

https://github.com/free5gc/webconsole/blob/cbf7ec1ccb163e3d51dc03d98e1c1dd8dcc3e5fb/frontend/src/util/UEInfoApiHelper.js#L11

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/fetch-registered-ue-request-fail-no-amf-found/112/2
