### ISSUE TITLE
请问怎么测试N3iwf这个网元

### ISSUE THREAD

**Issue by lycheezhou** [free5gc/free5gc#570]
您好，目前运行可以和AMF建立SCTP连接并注册，但是想测试PDU会话建立，请问需要怎么测试？

**Comment by a3828162** [comment]
Hi, @lycheezhou 
您可以參考這篇文章: [N3iwue installation](https://free5gc.org/guide/n3iwue-installation/)

謝謝

**Comment by andy89923** [comment]
You could use [N3IWUE](https://github.com/free5gc/n3iwue) to test the connection with N3IWF. 
[Here](https://free5gc.org/guide/n3iwue-installation/) is the document for setting up N3IWUE on the free5GC Official Website.
