### ISSUE TITLE
[Question] Is it possible to connect SMSF to Free5GC (support for N20/21 interface)?

### ISSUE THREAD

**Issue by lucker7777** [free5gc/free5gc#572]
Hello,

In order to have Free5GC utilizing SMSF, AMF needs n20 and UDM needs n21 interface, right.
I do not see those interfaces being supported by Free5GC, but maybe I am missing something.
Just want to make sure it is really not supported.

Thank you.

**Comment by andy89923** [comment]
Hi,

I checked SMSF spec (TS29.540), which indicates that the SMSF also provides service on **SBI architecture**. 

The SBI architecture is based on simple HTTP requests and responses. 

So, if you want to let free5GC support your SMSF, you need to modify AMF to create a new client that targets your SMSF, and so does UDM.

**Comment by linouxis9** [comment]
Hi @andy89923,

Maybe it would be great if Free5GC could generate and release the API Clients from the OpenAPI specs in https://github.com/free5gc/openapi even for services / NFs currently not yet supported by Free5GC?
It would maybe encourage people to contribute new NFs or services to existing NF :-)

Valentin

**Comment by andy89923** [comment]
He, 

We decided not to generate code for the function we haven't implemented because we can't test the functionalities. 

However, the free5GC is welcome for all the contributions. 
If you are willing to implement SMSF for free5GC, we are welcome. 

Thanks, 
Andy

**Comment by lucker7777** [comment]
Thanks for answer :)
