### ISSUE TITLE
Do it possible to remove "QoS rule 2" under PDU session establishment accept	

### ISSUE THREAD

**Issue by zachtan23** [free5gc/free5gc#578]
Do it possible to remove "QoS rule 2" under PDU session establishment accept? or do it can be configure under yaml file? thanks 
![Uploading 2024-06-24_103948.jpg…]()

**Comment by andy89923** [comment]
Hello, 
Could you reupload the screenshot?

**Comment by zachtan23** [comment]
![2024-06-24_103948](https://github.com/free5gc/free5gc/assets/122967784/b00d7df7-6d87-4f9d-a557-fd69605700b6)

**Comment by ian60509** [comment]
This data exists within the process itself. To delete this QoS rule, you will need to modify the code.

**Comment by ian60509** [comment]
May I ask the reason for wanting to delete this QoS rule?

**Comment by zachtan23** [comment]
this issue seen found in 3.4.1, but 3.4.0 is not this issue.

**Comment by ian-cs12-NYCU** [comment]
The second QoS rule is for charging. Starting from version 3.4.1, free5gc began supporting the charging feature.
