### ISSUE TITLE
[Bugs] AMF returned 500 Internal Server Error for a Event Exposure POST API request 

### ISSUE THREAD

**Issue by sathiyajith** [free5gc/free5gc#579]
## Describe the bug
An Event Exposure POST API request without the mandatory subscription eventlist parameter returns a 500 Internal Server Error, instead of the ideal 4xx error. The Internal Server Error is caused by a panic during null pointer dereference.

## To Reproduce
1. Run free5gc components with default config.
2. Check for the IP and Port for AMF component
3. Now give the below mentioned Event exposure API POST request to the determined IP and PORT through curl:

`curl -v -H 'Content-Type: application/json' -d "{\"subscription\":{\"fuzz\":false}, \"supportedFeatures\": \"fuzzstring\"}" -X POST http://AMF_IP:AMF_PORT/namf-evts/v1/subscriptions`

## Expected behavior
Since the above mentioned api request misses a mandatory parameter, it should have been handled and returned a 400 Bad request.

## Screenshots
The attached screenshot is the AMF container logs with the panic error raised by the null pointer dereference.

![image](https://github.com/free5gc/free5gc/assets/49834846/0556a671-cf6f-494d-b131-cb25f13c1712)

## Environment (please complete the following information):
 - free5GC Version: v3.4.1  
 - Docker images  free5gc/amf:v3.4.1,  free5gc/nrf:v3.4.1, mongo:latest

### Configuration File

Use the default configuration file.

### PCAP File

Attaching pcap file generated from `sudo tcpdump -i any -w free5gc.pcap`
[free5gcpcap.zip](https://github.com/user-attachments/files/16019418/free5gcpcap.zip)

### Log File
`2024-06-26T21:51:13.753307893Z [ERRO][AMF][GIN] panic: runtime error: invalid memory address or nil pointer dereference
goroutine 64 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/free5gc/util/logger.ginRecover.func1.1()
        /go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:284 +0x1a5
panic({0xc19600, 0x135fbc0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/free5gc/amf/internal/sbi/producer.CreateAMFEventSubscriptionProcedure({0xc0001d44d0?, {0xc0003b4050?, 0xc000518090?}})
        /go/src/free5gc/NFs/amf/internal/sbi/producer/event_exposure.go:64 +0x249
github.com/free5gc/amf/internal/sbi/producer.HandleCreateAMFEventSubscription(0xc000152100?)
        /go/src/free5gc/NFs/amf/internal/sbi/producer/event_exposure.go:17 +0x45
github.com/free5gc/amf/internal/sbi/eventexposure.HTTPCreateSubscription(0xc000152200)
        /go/src/free5gc/NFs/amf/internal/sbi/eventexposure/api_subscriptions_collection_document.go:56 +0x299
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/free5gc/util/logger.ginRecover.func1(0xc000152200)
        /go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:316 +0x7b
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/free5gc/util/logger.ginToLogrus.func1(0xc000152200)
        /go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:251 +0x87
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000137380, 0xc000152200)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x671
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000137380, {0xe8a250?, 0xc00021e0e0}, 0xc000152100)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0xe864a0?, 0xc000137380?}, 0xc000726190?}, {0xe8a250, 0xc00021e0e0}, 0xc000152100)
        /go/pkg/mod/golang.org/x/net@v0.17.0/http2/h2c/h2c.go:125 +0x59b
net/http.serverHandler.ServeHTTP({0xe88a98?}, {0xe8a250, 0xc00021e0e0}, 0xc000152100)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003f2140, {0xe8aa48, 0xc00061f710})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
2024-06-26T21:51:13.753374373Z [INFO][AMF][GIN] | 500 |    10.100.200.2 | POST    | /namf-evts/v1/subscriptions |`

## Walkthrough 
- The POST method called the HTTPCreateSubscription method, which called HandleCreateAMFEventSubscription method in api_subscriptions_collection_document.go file.
- In CreateAMFEventSubscriptionProcedure function, there is an attempt to dereference EventList which is a NULL pointer (a mandatory parameter which is not provided in the request)
            for _, events := range *subscription.EventList {
- This raised a panic and it is logged. The response status must have been marked as 500 Internal Server Error in api_subscriptions_collection_document.go:62.

## Bug fix
-  The bug fix would be to check whether EventList is null before dereferencing it, and returns an appropriate error code if it is null. 

## Additional context
An attacker can deliberately raise this panic attack posing a security risk.  I'll create a pull request to fix this issue shortly.

**Comment by andy89923** [comment]
Thanks for the PR!

**Comment by sathiyajith** [comment]
Thank you @andy89923
