### ISSUE TITLE
[Bugs] UEs can be context released by a second UE without authentication

### ISSUE THREAD

**Issue by liuxiaoxinxinxin** [free5gc/free5gc#580]
## Describe the bug
If we try to register two UEs with the same SUPI, the first UE's context is being released after the first unauthenticated Registration Request from the second UE, instead of being released after second UE sends an Registration Request with a security context.
## To Reproduce
1. Perform a normal UE registration
2. Replay the initial UE message and registration request from the first UE registration
## Expected behavior
Instead, first UE's context should be released after second UE valid authentification response or an Registration Request with a security context, else there is a risk of DoS from unauthenticated parties.
## Screenshots
<img width="770" alt="screenshot" src="https://github.com/free5gc/free5gc/assets/103559845/b6783202-8aae-4f0d-a195-9bb2064c3d77">

## Environment (please complete the following information):
 - free5GC Version: v3.4.1
 - OS: Ubuntu 20.04.1 Server
 - Kernel version: 5.200.0-0-generic
 - go version: go1.21.8 linux/amd64

### Log File
Provide the program log file here.
<img width="431" alt="ue" src="https://github.com/free5gc/free5gc/assets/103559845/b03f2c3b-976b-4554-8252-dd4dabeaac22">
We found that the replayed UE registration request  stopped the original UE from connecting to the core network.

**Comment by linouxis9** [comment]
Here is a similar issue I had found on Open5GS and how we resolved it: https://github.com/open5gs/open5gs/issues/2786

**Comment by tim1207** [comment]
Thank you for finding this problem, we will fix it soon!

**Comment by ianchen0119** [comment]
Hi @liuxiaoxinxinxin @linouxis9 

Thanks for your information.
Can you help me to know whether the UE RAN NGAP ID of the first Reg req and the relayed Reg req is the same?

As I know, RAN should allocate different identifier for two devices, so we may use UE RAN ID to decide should we release the existing UE context.

**Comment by liuxiaoxinxinxin** [comment]
Hi,
Thanks for your attention to the problem.
Yes, the UE RAN NGAP ID of the first Reg req and the relayed Reg req is the same.


Xinyu


lxx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "free5gc/free5gc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月7日(星期天) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [free5gc/free5gc] [Bugs] UEs can be context released by a second UE without authentication (Issue #580)





 
Hi @liuxiaoxinxinxin @linouxis9
 
Thanks for your information.
 Can you help me to know whether the UE RAN NGAP ID of the first Reg req and the relayed Reg req is the same?
 
As I know, RAN should allocate different identifier for two devices, so we may use UE RAN ID to decide should we release the existing UE context.

**Comment by donald1218** [comment]
Hi, is this behavior what you expected?
![image](https://github.com/user-attachments/assets/31ffcff9-8f89-433f-8393-a6d7b466138f)
[output.zip](https://github.com/user-attachments/files/16408106/output.zip)

**Comment by ianchen0119** [comment]
Hi @linouxis9 

@donald1218 created the PR https://github.com/free5gc/amf/pull/136 for this issue.
Please help to check when you feel free.

Many thanks.

**Comment by linouxis9** [comment]
Hi @ianchen0119,

No problem, I'll take a look this week.

Thanks and cheers,
Valentin
