### ISSUE TITLE
[Bugs] Error response of PDUSessionSMContextCreate

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/free5gc#583]
## Describe the bug
When PDUSessionSMContextCreate was failed with PDUSessionEstablishmentReject GSM message, the SMF of the free5GC v3.4.1 returns this GSM message in MIME multipart.
But in the free5GC 3.4.2, this GSM message is returns in JSON object directly without MIME multipart.
Is it correct behavior?

## To Reproduce
1. Uninstall gtp5g
2. Build NFs
3. Run command `./test.sh -o TestRegistration`

## Environment (please complete the following information):
 - free5GC Version: v3.4.2
 - OS: Ubuntu 20.04.6 LTS
 - Kernel version: 5.15.0-107-generic
 - go version: go version go1.22.5 linux/amd64
 - c compiler version (Option): gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

[cap.tar.gz](https://github.com/user-attachments/files/16139173/cap.tar.gz)

**Comment by pf-lin** [comment]
@ShouheiNishi Thank you for the report.
@ianchen0119 We are working on it.

**Comment by andy89923** [comment]
https://github.com/free5gc/smf/pull/111
