### ISSUE TITLE
NR-U support starting from 3GPP R16

### ISSUE THREAD

**Issue by ohault** [free5gc/free5gc#585]
The question of using unlicensed sprectrum for mobile networks in the dedicaded ISM bands is not new.
3GPP R16 has defined for 5G how to use a few ISM sub bands like n46, n96 in good citizenship as NR-U.
Meanwhile, it is mainly a RAN question, would be the impact of NR-U support for 5GC NFs ?

**Comment by andy89923** [comment]
There wouldn't be any impact on NFs if RAN were using NR-U. 
Also, all the protocols or data transmission follow standards, either the control plane or the data plane.
