### ISSUE TITLE
[Bugs]AMF returned 500 Internal Server Error for a Event Exposure POST API request

### ISSUE THREAD

**Issue by ashwin63** [free5gc/free5gc#586]
## Describe the bug
An Event Exposure POST API request without the mandatory subscription parameter returns a 500 Internal Server Error, instead of the ideal 4xx error. The Internal Server Error is caused by a panic during null pointer dereference.

## To Reproduce
Run free5gc components with default config.
Check for the IP and Port for AMF component
Now give the below mentioned Event exposure API POST request to the determined IP and PORT through curl:

curl -X POST http://AMF_IP:AMF_PORT/namf-evts/v1/subscriptions HTTP/1.1\r\nAccept: application/json\r\nHost: amf:8000\r\nContent-Type: application/json\r\n\r\n{ \"fuzz\" : false }

## Expected behavior
Since the above mentioned api request misses a mandatory parameter, it should have been handled and returned a 400 Bad request.

## Screenshots
<img width="1351" alt="Screenshot 2024-07-20 at 11 21 53 AM" src="https://github.com/user-attachments/assets/3225cd1a-3b5a-475b-bc59-362b9f76f3c1">

## Environment (please complete the following information):
free5GC Version: v3.4.1
Docker images free5gc/amf:v3.4.1, free5gc/nrf:v3.4.1, mongo:latest

### Configuration File
Use the default configuration file.

### PCAP File
[free5gc.pcap.txt](https://github.com/user-attachments/files/16321579/free5gc.pcap.txt)

### Log File
2024-07-16T19:10:08.041273026Z [INFO][AMF][GIN] | 500 |    10.100.200.4 | POST    | /namf-evts/v1/subscriptions |
2024-07-16T19:16:04.129107075Z [ERRO][AMF][GIN] panic: runtime error: invalid memory address or nil pointer dereference
goroutine 97 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/free5gc/util/logger.ginRecover.func1.1()
	/go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:284 +0x1a5
panic({0xc19600, 0x135fbc0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/free5gc/amf/internal/sbi/producer.CreateAMFEventSubscriptionProcedure({0x0?, {0x0?, 0xc000336060?}})
	/go/src/free5gc/NFs/amf/internal/sbi/producer/event_exposure.go:40 +0xa0
github.com/free5gc/amf/internal/sbi/producer.HandleCreateAMFEventSubscription(0xc0001a6000?)
	/go/src/free5gc/NFs/amf/internal/sbi/producer/event_exposure.go:17 +0x45
github.com/free5gc/amf/internal/sbi/eventexposure.HTTPCreateSubscription(0xc0001a6100)
	/go/src/free5gc/NFs/amf/internal/sbi/eventexposure/api_subscriptions_collection_document.go:56 +0x299
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/free5gc/util/logger.ginRecover.func1(0xc0001a6100)
	/go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:316 +0x7b
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/free5gc/util/logger.ginToLogrus.func1(0xc0001a6100)
	/go/pkg/mod/github.com/free5gc/util@v1.0.6/logger/logger.go:251 +0x87
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000683520, 0xc0001a6100)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x671
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000683520, {0xe8a250?, 0xc0004700e0}, 0xc0001a6000)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0xe864a0?, 0xc000683520?}, 0xc0000205a0?}, {0xe8a250, 0xc0004700e0}, 0xc0001a6000)
	/go/pkg/mod/golang.org/x/net@v0.17.0/http2/h2c/h2c.go:125 +0x59b
net/http.serverHandler.ServeHTTP({0xe88a98?}, {0xe8a250, 0xc0004700e0}, 0xc0001a6000)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0005a00a0, {0xe8aa48, 0xc000501260})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db

## Walkthrough (Option)
The POST method called the HTTPCreateSubscription method, which called HandleCreateAMFEventSubscription method in api_subscriptions_collection_document.go file.
In CreateAMFEventSubscriptionProcedure function, there is an attempt to dereference subscription which is a NULL pointer (a mandatory parameter which is not provided in the request)
	contextEventSubscription.EventSubscription = *subscription

This raised a panic and it is logged. The response status must have been marked as 500 Internal Server Error.

Bug fix
The bug fix would be to check whether subscription is null before dereferencing it, and returns an appropriate error code if it is null.

## Additional context
An attacker can deliberately raise this panic attack posing a security risk. I'll create a pull request to fix this issue shortly.

**Comment by andy89923** [comment]
Hi, 

The problem had been resolved in v3.4.2. You can refer to #579 .

**Comment by ashwin63** [comment]
Hey Andy,

There is a slight difference between the two issues. In #579 , subscription was sent, without event List which lead to exception in line 64. 
However, in this current issue, even the subscription parameter was not sent which lead to null pointer exception in line 40.
Can you please check with the URL mentioned above.

**Comment by andy89923** [comment]
@ashwin63 Thanks for your info. 
These two issues have different causes for panic.

Since I saw you create a bug fix in AMF, thanks for your PR.
https://github.com/free5gc/amf/pull/135.
