### ISSUE TITLE
[Bugs] SMF crash when CHF is not running

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/free5gc#587]
## Describe the bug
The CHF is registered to the NRF, but this CHF is not running. Then the SMF will be crashed.

## To Reproduce

1. Apply diff in attached log to test_multiUPF.sh
2. Run `./test_multiUPF.sh TestULCLAndMultiUPF`

## Expected behavior
Not crash SMF

## Environment (please complete the following information):
 - free5GC Version: v3.4.2
 - OS: Ubuntu 20.04.6 LTS
 - Kernel version: 5.15.0-116-generic
 - go version: Ubuntu go1.22.5 linux/amd64
 - c compiler version (Option): Ubuntu 9.4.0-1ubuntu1~20.04.2

### Log File
[SMF-crash.log](https://github.com/user-attachments/files/16344613/SMF-crash.log)

**Comment by andy89923** [comment]
Thanks for reporting this bug. This PR may fix the issue. 
https://github.com/free5gc/smf/pull/112/files
