### ISSUE TITLE
[Bugs]There is data sent to MongoDB when the Create button is pressed without being deleted using the Delete button in the web console

### ISSUE THREAD

**Issue by ex8664** [free5gc/free5gc#589]
When the DELETE button on the web console is pressed, the UI shows that the data has been deleted. 
However, in reality, the data that should have been deleted remains and is sent when the CREATE button is pressed. 
As a result, the data that should have been deleted is added to the MongoDB table.

The data that remains and is sent in the message includes the following five items:
     AccessAndMobilitySubscriptionData
     SmfSelectionSubscriptionData
     SmPolicyData
     FlowRules
     QosFlows

Additionally, this issue affects the following entries:
     policyData.ues.chargingData
     policyData.ues.flowRule
     policyData.ues.qosFlow
     subscriptionData.provisionedData.amData

To confirm the parameters sent from the web console, follow these steps:
 1. Open the Chrome browser.
 2. Access the web console.
 3. Navigate to the relevant UI display screen.
 4. Press the F12 button to open DevTools.
 5. Select the Network tab (the one labeled with Sources, Network, Performance >>).
 6. Select the Payload tab (the section labeled with Headers, Payload, Preview).
 7. Perform the relevant test.
 8. Check the message content when there is a change in the Request Payload information.

**Comment by ex8664** [comment]
free5gc:
 free5GC Version: v3.4.2
 OS: Ubuntu 20.04.6 LTS
 Kernel version: 5.4.0-125-generic
 go version: Ubuntu go1.21.8 linux/amd64

webconsole:
 OS: Windows10
 Browser:Google Chrome 126.0.6478.57

**Comment by andy89923** [comment]
Thanks for reporting this bugs. 
We are refactoring webconsole to make it more easier to debug at the frontend.

**Comment by andy89923** [comment]
Hi, 

The latest webconsole should solved the problem. You could try the latest webconsole (https://github.com/free5gc/webconsole/tree/94a0f1a77f241f72ca96e59cac2a1257037b966a).
