### ISSUE TITLE
[Feat] PFCP Session Establishment request does not carry USER ID in N4 interface

### ISSUE THREAD

**Issue by sambitcom** [free5gc/free5gc#592]
**We will advise people to follow the issue template set, otherwise the issue might be disregarded.**
**free5GC mainly uses GitHub for issue tracking. Information regarding to general questions or technical support. It will be highly considered if forward to the [forum](https://forum.free5gc.org).**
**free5GC will appreciate it, if people can refer to [TS](https://github.com/free5gc/free5gc/wiki/Trouble_Shooting) and [forum](https://forum.free5gc.org) prior to bug reporting**

## Describe the bug
PFCP Session Establishment request  does not carry USER ID in v3.4.2 Releases.

## To Reproduce
1.Run any scenario and check PFCP  PFCP Session Establishment request

## Expected behavior

please include USERID in frames

![image](https://github.com/user-attachments/assets/c73de48b-5629-48cc-99ad-c689784f2095)

## Screenshots
If applicable, add screenshots to help explain the problem.

## Environment (please complete the following information):
 - free5GC Version: v3.4.2
 - OS: [e.g. Ubuntu 200.04 Server]
 - Kernel version: [e.g. 5.200.0-0-generic]
 - go version: [e.g. 1.10.0 linux/amd64]
 - c compiler version (Option): [e.g. gcc version 1.1.0]

### Configuration File
Provide the configuration file here.

If not clear of what to do, the `config` folder can be zip and upload it here.

### PCAP File
Dump the packet and provide the pcap file here.

If not clear of what to do, this command can be used `sudo tcpdump -i any -w free5gc.pcap` prior to running bug reproduce. Then upload the pcap file `free5gc.pcap`.

### Log File
Provide the program log file here.

If not clear of what to do, copy the printed log on the screen and upload it here.

## System architecture (Option)
Please provide the draft architecture, including the scenario, use cases, installation environment(bare metal, vm, container, or k8s), etc.

## Walkthrough (Option)
free5GC will be interested on the research or finding in brief.

## Additional context
It will be appreciated if other context can be added here.

**Comment by ian-cs12-NYCU** [comment]
"In TS 29.244 7.5.2.1, User ID is **optional**. We believe it is not a bug, but we will discuss the necessity of this feature."
![image](https://github.com/user-attachments/assets/246477e7-ea73-4c78-ad88-e1ce49a66a8c)

**Comment by sambitcom** [comment]
I understand that it is an Optional field. Is there any workaround to include it. I am okay to convert it as a feature.

**Comment by andy89923** [comment]
Hi, 

I had convert the title to 'feature' tag. 
Also, we are not sure if there is workaround without modifying the code. 
Could you provide more info for why you like to include USER ID?

**Comment by sambitcom** [comment]
I am testing a tool using free5gc where I need to display IMSI to user in a field for N4 interface

**Comment by ian60509** [comment]
After our discussion, we are currently bustling and do not plan to support this feature. If you have the need and research experience, we highly encourage you to contribute to the free5GC open-source community through a pull request.
Thanks.

**Comment by sambitcom** [comment]
OK. Let me check in my team who can contribute this.
