### ISSUE TITLE
[Bugs] Body in http response is doublly closed

### ISSUE THREAD

**Issue by ShouheiNishi** [free5gc/free5gc#593]
## Describe the bug
In some codes, Body fields in http.Response are closed twice.

For example, the function CreateUEContextRequest in file NFs/amf/internal/sbi/consumer/amf_service.go calls CreateUEContext() to perform http access, and then close variable httpResp whose type is *http.Response and was return from CreateUEContext().
https://github.com/free5gc/amf/blob/9443d1b98ccbeb490a34b5d7e80fe68f7c4a9139/internal/sbi/consumer/amf_service.go#L164-L172
```
	res, httpResp, localErr := client.IndividualUeContextDocumentApi.CreateUEContext(ctx, ue.Guti, req)
	defer func() {
		if httpResp != nil {
			if rspCloseErr := httpResp.Body.Close(); rspCloseErr != nil {
				logger.ConsumerLog.Errorf("CreateUEContext response body cannot close: %+v",
					rspCloseErr)
			}
		}
	}()
```

But since http response is closed in CreateUEContext(), double release occurs.
https://github.com/free5gc/openapi/blob/4abe61151d3c60732c2e350a9f85d0af2474e8f8/Namf_Communication/api_individual_ue_context_document.go#L95-L104
```
	localVarHttpResponse, err := openapi.CallAPI(a.client.cfg, r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}
```

## Environment (please complete the following information):
 - free5GC Version: v3.4.2

**Comment by andy89923** [comment]
Hi, 

Thanks for repoting this issue. 
We close httpResponse in NFs because the linter would ask to close response to ensure it's close. 

Currentely we are upgrading openapi to R17 version, which doesn't include httpResponse in response.
