### ISSUE TITLE
[Docs] Is it not necessary to add `configuration.pfcp.HeartbeatInterval` to smfcfg.yaml in the configuration example?

### ISSUE THREAD

**Issue by matsu2254** [free5gc/free5gc#597]
## Documentation request

What was unclear/insufficient/not covered in the documentation.

This is a configuration example suggestion rather than documentation.

Is it not necessary to add `configuration.pfcp.HeartbeatInterval` to smfcfg.yaml in the configuration example?

## Suggestion

I suppose I could write an example setup like this

~~~
# ...etc...
configuration:
  # ...etc...
  pfcp: # the IP address of N4 interface on this SMF (PFCP)
    # addr config is deprecated in smf config v1.0.3, please use the following config
    nodeID: 127.0.0.1 # the Node ID of this SMF
    listenAddr: 127.0.0.1 # the IP/FQDN of N4 interface on this SMF (PFCP)
    externalAddr: 127.0.0.1 # the IP/FQDN of N4 interface on this SMF (PFCP)
    # HeartbeatInterval: 10s # Specifies the PFCP heartbeat interval. If not set or 0, the function will not be enabled
#...etc...
~~~

## Additional context

Add any other context or screenshots about the issue here.

In V1.2.0 of smf [Add PFCP Heartbeat Procedure #63](https://github.com/free5gc/smf/pull/63)
has been implemented.

[smf - releases/v1.2.0](https://github.com/free5gc/smf/releases/tag/v1.2.0)

>Add PFCP Heartbeat Procedure by @mariakagi in #63

There seems to be a few changes, but the configuration items are defined in the ↓.

https://github.com/free5gc/smf/blob/772cdc8750d53afa5ed25eaf6deba4daa9227b95/pkg/factory/config.go#L258

↓It seems to be used in this area

https://github.com/free5gc/smf/blob/772cdc8750d53afa5ed25eaf6deba4daa9227b95/internal/sbi/processor/association.go#L32

**Comment by andy89923** [comment]
Hi, 

Thanks for reporting this issue.  The `HeartbeatInterval` will add to the sample SMF config in the following PR.
