### ISSUE TITLE
[Docs] whether it supports communication betwreen upf

### ISSUE THREAD

**Issue by MrPluto0** [free5gc/free5gc#600]
As general mode, traffic is flow from upf to target. But i have a lab in much traffic scene. The much traffic flows to one upf, it will increase the pressure of the server, so i want to know if it's possible to support horizontal traffic between upfs?

Thanks!

**Comment by ian60509** [comment]
If you want to distribute the load across multiple UPFs, you can refer to the load control procedure described in TS 29.244 Section 6.2.3. In this procedure, the UPF can send its load status to the SMF via an N4 message. Additionally, in cases of heavy loading, the overload control procedure in TS 29.244 Section 6.2.4 allows the UPF to proactively send a signal to the SMF. For further details on how to manage multiple UPFs through the SMF, you can refer to TS 29.501 Section 6.3.3 on UPF selection.

**Comment by MrPluto0** [comment]
Thanks! 
If it means free5gc now doesn't support it ? If so, i will try to code it.

**Comment by MrPluto0** [comment]
OK，Thansk
