### ISSUE TITLE
[Bugs]Error during N2 Handover (direct) 

### ISSUE THREAD

**Issue by Tommy021477** [free5gc/free5gc#603]
## Describe the bug
When performing N2-Handover (direct), a warning log “IE DirectForwardingPathAvailability is not implemented” is output upon receiving HandoverRequired. However, the handover completes, and it appears that communication is possible with the target gNB.
Does this mean that N2-Handover (direct) is not implemented in v3.4?

## To Reproduce
Perform N2-Handover (direct)

## Expected behavior
N2-Handover (direct) can be performed.

## Screenshots
log
![image](https://github.com/user-attachments/assets/6aedeee7-6642-4ebd-ad7a-1eeb24ef20f2)

capture
　A warning log is output, but it appears that N2-Handover is completed.
　![image](https://github.com/user-attachments/assets/c1873901-8dab-41ea-9584-cec49adb2605)

　Before EndMarker (No.2705)
　UL communication via the source gNB.
　![image](https://github.com/user-attachments/assets/439b2112-3210-4692-91cc-0b4182da0e41)

　After EndMarker (No.2762).
　UL communication via the target gNB.
　![image](https://github.com/user-attachments/assets/82584244-a1f3-4396-9425-5aa06b703eaf)

## Environment (please complete the following information):
free5GC Version: v3.4.2
OS: Ubuntu 20.04.6 LTS
Kernel version: 5.4.0-125-generic
go version: Ubuntu go1.21.8 linux/amd64

**Comment by donald1218** [comment]
Hi, @Tommy021477 
The IE DirectForwardingPathAvailability is defined as optional in the spec. Currently, it is not implemented in free5GC, but this does not mean that we haven't implemented handover. You can refer to section 9.2.3.1 of TS 38.413 for more details.
![image](https://github.com/user-attachments/assets/a55f7246-e309-4674-b249-8c18f988902d)
