### ISSUE TITLE
[Bugs]When performing N2-Handover (direct), the UE Context Release Command is sent twice.

### ISSUE THREAD

**Issue by Tommy021477** [free5gc/free5gc#604]
## Describe the bug
When performing N2-Handover (direct), after the handover, the UE Context Release Command is sent twice to the source gNB (release-due-to-ngran-generated-reason (3) / normal-release (0)). Additionally, a warning log “AmfUe is nil” is output when sending the UE Context Release Command.

## To Reproduce
Perform N2-Handover (direct)

## Expected behavior
After the handover, the UE Context Release Command (release-due-to-ngran-generated-reason (3)) is sent once to the source gNB.

## Screenshots
　Capture
　![image](https://github.com/user-attachments/assets/c8207e23-98a6-4af8-8f04-ffcc23c41e9d)
　　　![image](https://github.com/user-attachments/assets/f4468102-7520-4f7a-a0c4-7d1e76a4b428)

　log
　![image](https://github.com/user-attachments/assets/ebdce660-c647-4ee6-88f3-4fbb882b31d4)

## Environment (please complete the following information):
free5GC Version: v3.4.2
OS: Ubuntu 20.04.6 LTS
Kernel version: 5.4.0-125-generic
go version: Ubuntu go1.21.8 linux/amd64

**Comment by donald1218** [comment]
Hi, @Tommy021477 
Can you tell me how you triggered the N2 handover?Also, could you let me know which UE and gNB you used for reference?"

**Comment by donald1218** [comment]
Hi, @Tommy021477 
I have fixed this issue in this PR.

https://github.com/free5gc/amf/pull/143

 I believe the warning log is normal because it checks if ranue.amfue is empty when sending to RAN. However, since we are sending a release UE context request this time, ranue.amfue should indeed be empty.
