### ISSUE TITLE
[Bugs]Uplink AMBR,  the speed is regulated to a value smaller than the set value for UDP when the rate is high.

### ISSUE THREAD

**Issue by Tommy021477** [free5gc/free5gc#605]
## Describe the bug
When registering Uplink AMBR as 10Mbps in the web console and sending data with iperf, the speed is regulated to a value smaller than the set value for UDP when the rate is high. For TCP, the speed is regulated to the set value of 10Mbps.

## To Reproduce
Register Uplink AMBR at 10Mbps and send UDP traffic with iperf3 at a throughput of over 50Mbps.

## Expected behavior
The speed will be close to the throughput value set for Uplink AMBR in the web console.

## Screenshots
　webconsole
　
![image](https://github.com/user-attachments/assets/8dc64fdb-b0a6-490a-9c54-46d52963a0ca)
![image](https://github.com/user-attachments/assets/47b183b5-2cd4-4be8-a1d9-d9b9963e25ae)

iperf Execution Results
![image](https://github.com/user-attachments/assets/8f612e51-a8b7-4d7b-8b26-cca269f1752a)

## Environment (please complete the following information):
free5GC Version: v3.4.2
OS: Ubuntu 20.04.6 LTS
Kernel version: 5.4.0-125-generic
go version: Ubuntu go1.21.8 linux/amd64

**Comment by ian60509** [comment]
Can you tell me if this problem exists in all the gtp5g versions you've tested?

**Comment by ian60509** [comment]
Have you set **flow GBR, MBR,** and other values in these four scenarios?

**Comment by Tommy021477** [comment]
>Please provide me with all the tested gtp5g versions, and is this situation present in all versions?

Conducted using gtp5g version: v0.8.9. Other versions have not been tested.

>Have you set flow GBR, MBR, and other values in these four scenarios?

According to the results of the following view, Flow Rules are deleted upon registration by DELETE. 
However, it seems that they are still registered in the DB even if they are deleted during creation due to #589.
※The fix for #589 has not been incorporated yet.

![image](https://github.com/user-attachments/assets/c5c751cf-cda8-4b55-a45f-487dc03e1368)
![image](https://github.com/user-attachments/assets/f857fb3b-ef75-4efb-a56f-1e379f9cff22)

**Comment by andy89923** [comment]
@yccodr Help check the webconsole bugs; thanks!

**Comment by andy89923** [comment]
@Tommy021477 The v3.4.3 webconsole didn't have the problem you had mentioned.
