### ISSUE TITLE
[Bugs]Regarding the PDU session release process during IDLE state

### ISSUE THREAD

**Issue by Tommy021477** [free5gc/free5gc#606]
## Describe the bug
When airplane mode is turned on during the IDLE state, a PDUSessionResourceReleaseCommand, DL NAS transport, PDU session release command (pcap No.3217) is sent in response to the NAS PDU session release request (pcap No.3048).

The PDUSession should be in Deactivation state due to the UEContextReleaseRequest (Cause RadioNetwork:20 user-inactivity) (pcap No.2914).
 In the Service Request (Service type: Signalling (0)) (pcap No.3043), the PDUSession remains in Deactivation state. 
Therefore, instead of sending a PDUSessionResourceReleaseCommand, DL NAS transport, PDU session release command in response to the PDU session release request (pcap No.3048), 
shouldn’t a DownlinkNASTransport, DL NAS transport, PDU session release command be sent? (Isn’t the NGAP PDUSessionResourceReleaseCommand part of pcap No.3217 unnecessary?)

## To Reproduce
Turning on airplane mode during the IDLE state

## Expected behavior
When airplane mode is turned on during the IDLE state, a DownlinkNASTransport, DL NAS transport, PDU session release command is sent in response to an UplinkNASTransport, UL NAS transport, PDU session release request.

Current
PDUSessionResourceReleaseCommand, DL NAS transport, PDU session release command

Expected
DownlinkNASTransport, DL NAS transport, PDU session release command

## Screenshots
pcap
![image](https://github.com/user-attachments/assets/b60048cb-715d-4824-aad2-9201c805e002)

No.2914 UEContextRelease(user inactivity)
![image](https://github.com/user-attachments/assets/b388cd2c-5ec1-4f22-b588-8ce41c5db459)

No.3043 Service Request(Service type: Signalling (0))
![image](https://github.com/user-attachments/assets/edbfeb55-a98d-4c81-80af-2518ab363407)

No.3217
According to TS23.502 section 4.3.4.2, it is stated that an N2 SM resource release request is included when the PDU session is active.
In No.3043 Service Request (Service type: Signalling (0)), the PDU session does not become active, so the NGAP PDU Session Resource Release Command in No.3217 in response to No.3048 is unnecessary. 
Instead of sending a PDUSessionResourceReleaseCommand, DL NAS transport, PDU session release command, a DownlinkNASTransport, DL NAS transport, PDU session release command should be sent.

Excerpt from TS23.502 4.3.4.2 3a
3a.(If the PDU Session Release is initiated by the UE in step 1a or has been triggered by (R)AN in step 1d) **_The SMF responds to the AMF with the Nsmf_PDUSession_UpdateSMContext response (N2 SM Resource Release request_,** 

N1 SM container (PDU Session Release Command)). **_N2 SM Resource Release request is included if the PDU Session Release is initiated by the UE and if the UP connection of the PDU Session is active._** 

## Environment (please complete the following information):
free5GC Version: v3.4.2
OS: Ubuntu 20.04.6 LTS
Kernel version: 5.4.0-125-generic
go version: Ubuntu go1.21.8 linux/amd64

**Comment by tim1207** [comment]
Our understanding
No.2914 UEContextReleaseRequest (user inactivity ) ,PDUSession should be deactivated.
No.3043 Service Request because PDUSession is still inactive at this time.
No.3044 Service Accept spec PDU session status should already be activation.
No.3048 PDU session release request The PDU session status is activation/re-activation when initiated by the UE.
I think there should be no error in this part.

**Comment by Tommy021477** [comment]
Sorry for the late reply. There are some points in your comment that need to be confirmed.
Regarding the state of the PDU session between the terminal and the 5G core, your understanding based on the comments is correct.
What we want to check is the state of the PDU session Resource between the gNB and the 5G core (N3 interface).
Specifically, this corresponds to the SMF processing related to upCnxState described in TS29.502 5.2.2.3.2 Activation and Deactivation of the User Plane connection of a PDU session.
Since upCnxState is already Deactivated, we understand that the NGAP PDU session Release Command is not necessary.
In the case of this incident, the NGAP PDU Session Resource Release Command in packet No. 3217 is not necessary,
and instead of sending the PDUSessionResourceReleaseCommand, DL NAS transport, PDU session release command, the DownlinkNASTransport, DL NAS transport, PDU session release command should be sent.

In pdu_session.go(HandlePDUSessionSMContextUpdate), BuildPDUSessionResourceReleaseCommandTransfer is called without checking the state of upCnxState,
but in association.go(requestAMFToReleasePDUResources) etc., BuildPDUSessionResourceReleaseCommandTransfer is called depending on the state of upCnxState.
I think the state of upCnxState should also be determined in pdu_session.go(HandlePDUSessionSMContextUpdate)

![image](https://github.com/user-attachments/assets/95239b9d-2ced-45f4-8fd4-a7bc43618193)

**Comment by Tommy021477** [comment]
I added additional comments on 12/9. Should I register a new issue?

**Comment by andy89923** [comment]
> I added additional comments on 12/9. Should I register a new issue?

Hi,

Yes, I recommend creating a new issue for a new discussion. 
Thanks!
