### ISSUE TITLE
[Feat] UP Function Features in PFCP Association Setup Response from go-upf

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#607]
Hi @free5gc-org 

free5GC SMF includes `CP Function Features` in `PFCP Association Setup Request`, but do you have a plan to include `UP Function Features` in `PFCP Association Setup Response` from go-upf?

**Comment by ian60509** [comment]
We have plans to develop this feature, but we cannot provide a definitive completion date at this time.
