### ISSUE TITLE
[Bugs]error if a 6-digit PLMNID in the webconsole

### ISSUE THREAD

**Issue by Tommy021477** [free5gc/free5gc#608]
## Describe the bug
In version 3.4.3, specifying a 6-digit PLMNID from the web console results in an error.
(a fixed 5-digit error message is displayed)
*In v3.4.2, specifying a 6-digit PLMNID did not result in an error and registration was successful.

## To Reproduce
Specifying a 6-digit PLMNID in the webconsole

## Expected behavior
Just like in version 3.4.2, it should be possible to register a 5-digit or 6-digit PLMNID from the web console without encountering an error

## Screenshots
webconsole
![image](https://github.com/user-attachments/assets/560480fd-48bd-440f-842c-5205da9ea40c)

## Environment (please complete the following information):
free5GC Version: v3.4.3
OS: Ubuntu 20.04.6 LTS
Kernel version: 5.4.0-125-generic
go version: Ubuntu go1.21.8 linux/amd64

**Comment by andy89923** [comment]
Thanks for reporting this bug. 
The latest webconsole will allow 5 - 6 digit PLMNID.
