### ISSUE TITLE
UPF GTP packets failed

### ISSUE THREAD

**Issue by rijilrose** [free5gc/free5gc#61]
GtpHandler() This type[255] of GTPv1 header does not implement yet UPF=Util
ERRO[2020-05-24T17:15:02+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket UPF=Util
WARN[2020-05-24T17:30:52+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet UPF=Util
ERRO[2020-05-24T17:30:52+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket UPF=Util
WARN[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/up/up_path.c:119 GtpHandler() This type[255] of GTPv1 header does not implement yet UPF=Util
ERRO[2020-05-24T17:33:51+05:30] /home/free5gc/go/src/free5gc/src/upf/src/upf_init.c:210 PacketReceiverThread() Error handling UP socket UPF=Util

Please find the configuration file 

[config_smf_upf.zip](https://github.com/free5gc/free5gc/files/4728973/config_smf_upf.zip)

**Comment by free5gc-org** [comment]
Hi,

For questions and support please use the [official forum](https://forum.free5gc.org). The issue list of this repo is exclusively for bug reports and feature requests.

What we means is that for GitHub issue list is exclusively for bug reports and feature requests.
Please forward question to our [official forum](https://forum.free5gc.org) with some reference such as your log, pcap file, the OS and kernel version you used, etc.

Best Regards

**Comment by rijilrose** [comment]
This is a issue I am facing. I have submitted the smf and upf config

**Comment by free5gc-org** [comment]
What we mean is the issue seems to be not related to a bug report or a feature request. The question seems to be the result of mis-configuration.

To get quick technical support from this issue from our team, I will advise you to forward it to our official forum with some supporting information such as pcap files so that our team can check the error log. Without pcap files, our team cannot do any debugging issue.

**Comment by Mkishore1** [comment]
When I try to run
~/go/src/free5gc$ sudo ./run.sh
I got he same error.
 

ERRO[2020-06-17T10:54:54+05:30] /home/crrao-aimscs/go/src/free5gc/src/upf/lib/utlt/src/utlt_mq.c:29 MQCreate() Error creating message queue: Too many open files  UPF=Util
ERRO[2020-06-17T10:54:54+05:30] /home/crrao-aimscs/go/src/free5gc/src/upf/src/upf_init.c:170 UpfInit() UPF - Event Queue error when UPF initializes  UPF=Util
ERRO[2020-06-17T10:54:54+05:30] /home/crrao-aimscs/go/src/free5gc/src/upf/src/upf.c:28 main() UPF failed to initialize  UPF=Util
ERRO[2020-06-17T10:54:54+05:30] /home/crrao-aimscs/go/src/free5gc/src/upf/src/up/up_path.c:233 BufferServerTerminate() epoll deregister error  UPF=Util
ERRO[2020-06-17T10:54:54+05:30] /home/crrao-aimscs/go/src/free5gc/src/upf/src/upf_init.c:183 UpfTerm() UPF - Buffer Server error when UPF terminates  UPF=Util
ERRO[2020-06-17T10:54:54+05:30] /home/crrao-aimscs/go/src/free5gc/src/upf/src/upf.c:36 main() UPF terminate error  UPF=Util
Cannot find device "upfgtp0"


when I post it in forum there is no response
