### ISSUE TITLE
[Bugs] TNGF dies instead of cleanly exiting on terminate

### ISSUE THREAD

**Issue by oliveiraleo** [free5gc/free5gc#612]
## Describe the bug
TNGF panics on free5gc exit with the message:
```
[FATA][TNGF][NGAP] panic: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/free5gc/tngf/internal/ngap/service.listenAndServe.func1()
	/home/xxxx/free5gc/NFs/tngf/internal/ngap/service/service.go:50 +0x38
panic({0x8e0920?, 0xd90730?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/free5gc/tngf/internal/ngap/service.listenAndServe(0x0?, 0x0?, 0x0?)
	/home/xxxx/free5gc/NFs/tngf/internal/ngap/service/service.go:121 +0x665
created by github.com/free5gc/tngf/internal/ngap/service.Run in goroutine 1
	/home/xxxx/free5gc/NFs/tngf/internal/ngap/service/service.go:36 +0xe5
./run.sh: line 69: wait: pid 15589 is not a child of this shell
The free5GC terminated successfully!
```

## To Reproduce
1. Install free5GC v3.4.3
2. Run free5GC using `./run.sh -tngf` and wait for it to fully load
3.  Send SIGTERM (kill) free5GC
4. TNGF will crash

## Expected behavior
TNGF should shutdown correctly, together with the other NFs.

## Screenshots
N/A

## Environment (please complete the following information):
 - free5GC Version: v3.4.3
 - OS: Ubuntu 20.04.6 LTS
 - Kernel version: 5.4.0-196-generic
 - go version: go1.21.8 linux/amd64
 - c compiler version (Option): 9.4.0

### Configuration File
[free5gc-tngf-config-folder.zip](https://github.com/user-attachments/files/17259958/free5gc-tngf-config-folder.zip)

### PCAP File
N/A

### Log File
[free5gc-logs.zip](https://github.com/user-attachments/files/17258377/free5gc-logs.zip)

## Additional context
N/A

**Comment by blackcat-118** [comment]
Hi, @oliveiraleo,

We will trace this issue, thank you!

Best regards,
