### ISSUE TITLE
[Bugs] Resource Leak in AMF when Unexpected InitialUEMessage Service Request Received

### ISSUE THREAD

**Issue by ex8664** [free5gc/free5gc#615]
## Describe the bug
The AMF experiences a resource leak after logging "No Security Context : SUPI[]" when receiving an InitialUEMessage Service Request at an unexpected timing.

## To Reproduce
If the following sequence occurs for the same 5G-S-TMSI, the AmfUe is not released, leading to a resource leak:

  1.   UE Context Release Request (NG-RAN node initiated) (gNB -> AMF)
  2.   UEContextReleaseCommand (AMF -> gNB)
  3.   InitialUEMessage Service Request (gNB -> AMF)
  3.1. AMF attaches new ranUe
  4.   UEContextReleaseComplete (gNB -> AMF)

## Expected behavior
AMF should release old resources and then switch to new resources:

  1.   UE Context Release Request (NG-RAN node initiated)(gNB -> AMF)
  2.   UEContextReleaseCommand(AMF -> gNB)
  3.   InitialUEMessage Service Request(gNB -> AMF)
  3.1 AMF should detach old ranUe
  3.2 AMF should attach new ranUe

## Walkthrough
The resource leak occurs when the else case in the HandleNAS function is executed. It seems that the leak happens because the old AmfUe is not released, and a new AmfUe ("") is used instead.

Note1.
  The evaluation result of this if statement is the behavior of evaluating if(true && false).
>         if ranUe.HoldingAmfUe != nil && !ranUe.HoldingAmfUe.CmConnect(ranUe.Ran.AnType) { 　
        
```
func HandleNAS(ranUe *amf_context.RanUe, procedureCode int64, nasPdu []byte, initialMessage bool) {
    ...
    if ranUe.AmfUe == nil {
        // Only the New created RanUE will have no AmfUe in it
        if ranUe.HoldingAmfUe != nil && !ranUe.HoldingAmfUe.CmConnect(ranUe.Ran.AnType) { 　
            // If the UE is CM-IDLE, there is no RanUE in AmfUe, so here we attach new RanUe to AmfUe.
            gmm_common.AttachRanUeToAmfUeAndReleaseOldIfAny(ranUe.HoldingAmfUe, ranUe)
            ranUe.HoldingAmfUe = nil
        } else { //
            // Assume we have an existing UE context in CM-CONNECTED state. (RanUe <-> AmfUe)
            // We will release it if the new UE context has a valid security context(Authenticated) in line 50.
            ranUe.AmfUe = amfSelf.NewAmfUe(“”)
            gmm_common.AttachRanUeToAmfUeAndReleaseOldIfAny(ranUe.AmfUe, ranUe)
        }
    }
    ...
}
```

Note2.
If you pass NewAmfUe("") as the first argument to the AttachRanUeToAmfUeAndReleaseOldIfAny function,
the evaluation result of if will be false, which may result in a resource leak.

```
func AttachRanUeToAmfUeAndReleaseOldIfAny(amfUe *context.AmfUe, ranUe *context.RanUe) {
  if oldRanUe := amfUe.RanUe[ranUe.Ran.AnType]; oldRanUe != nil {
    oldRanUe.Log.Infof("Implicit Deregistration - RanUeNgapID[%d]", oldRanUe.RanUeNgapId)
    oldRanUe.DetachAmfUe()
    if amfUe.T3550 != nil {
      amfUe.State[ranUe.Ran.AnType].Set(context.Registered)
    }
    StopAll5GSMMTimers(amfUe)
    causeGroup := ngapType.CausePresentRadioNetwork
    causeValue := ngapType.CauseRadioNetworkPresentReleaseDueToNgranGeneratedReason
    ngap_message.SendUEContextReleaseCommand(oldRanUe, context.UeContextReleaseUeContext, causeGroup, causeValue)
  }
  amfUe.AttachRanUe(ranUe)
}
```

## Bug fix
If changing the arguments is acceptable, the following fix is ​​suggested:
```
func AttachRanUeToAmfUeAndReleaseOldIfAny(ranUe *context.RanUe) {

  if ranUe.amfUe != nil && oldRanUe := ranUe.amfUe.RanUe[ranUe.Ran.AnType]; oldRanUe != nil {
    amfUe := ranUe.amfUe
   
    oldRanUe.Log.Infof("Implicit Deregistration - RanUeNgapID[%d]", oldRanUe.RanUeNgapId)
    oldRanUe.DetachAmfUe()
    if amfUe.T3550 != nil {
      amfUe.State[ranUe.Ran.AnType].Set(context.Registered)
    }
    StopAll5GSMMTimers(amfUe)
    causeGroup := ngapType.CausePresentRadioNetwork
    causeValue := ngapType.CauseRadioNetworkPresentReleaseDueToNgranGeneratedReason
    ngap_message.SendUEContextReleaseCommand(oldRanUe, context.UeContextReleaseUeContext, causeGroup, causeValue)
   
  }
 
  ranUe.amfUe = amfSelf.NewAmfUe("")
  ranUe.amfUe.AttachRanUe(ranUe)
}
```

## Additional Context
This issue may be related to the changes introduced in the following fix: https://github.com/free5gc/free5gc/issues/580

## Environment
free5GC Version: v3.4.3
OS: Ubuntu 20.04.6 LTS
Kernel Version: 5.4.0-125-generic
Go Version: Ubuntu go1.21.8 linux/amd64

**Comment by donald1218** [comment]
Hi, @ex8664 
In Note 1, you mentioned, "The resource leak occurs when the else case in the HandleNAS function is executed." However, in this else case, ranUE.HoldingUE is not immediately cleared. It is only after line 50, when SecurityContextIsValid() == true, that the old amfue is detached and the SendUEContextReleaseCommand is issued. This is to prevent the same 5G-S-TMSI from affecting the UE in the CM-connected state before authentication is complete. If this is the case, does the issue you mentioned still exist?
