### ISSUE TITLE
[Bugs] Receiving a PDU session modification request from the UE, the AMF/SMF returns an error.

### ISSUE THREAD

**Issue by Tommy021477** [free5gc/free5gc#617]
## Describe the bug
After the AMF receives a "delete existing QoS rule" from the gNB/UE, a QoS parsing error occurs in the SMF. As a result, the PDU session fails to update correctly.

## To Reproduce
After sending a PDUSessionResourceSetupRequest with QoS rule 2 from AMF to gNB/UE, if the gNB sends a "Syntactical error in the QoS operation," a parsing error occurs in SMF.

1. PDUSessionResourceSetupRequest, DL NAS transport, PDU session establishment accept(AMF -> gNB/UE) 
amf send the QoS rule 2
 
2. UplinkNASTransport, UL NAS transport, PDU session modification request (Syntactical error in the QoS operation) (gNB/UE -> AMF)

3. PDU session modification request (Syntactical error in the QoS operation) (AMF -> SMF)

4. PDU session modification reject (Message type non-existent or not implemented) (SMF -> AMF)

5. DownlinkNASTransport, DL NAS transport, PDU session modification reject (Message type non-existent or not implemented) (AMF -> gNB/UE)

## Walkthrough 
Tracing the SMF reveals that an error occurs in the reqQoSRules.UnmarshalBinary inside the HandlePDUSessionModificationRequest function. 	The root cause of the UnmarshalBinary error is currently unknown.
![image](https://github.com/user-attachments/assets/317f3fdb-df56-4395-a9f3-b8f0ff5b2965)

func (p *Processor) HandlePDUSessionModificationRequest(
    smCtx *smf_context.SMContext, req *nasMessage.PDUSessionModificationRequest,
) (*nas.Message, error) {
    logger.GsmLog.Infof("Handle Pdu Session Modification Request")

    // Retrieve PTI (Procedure transaction identity)
    smCtx.Pti = req.GetPTI()

    rsp := nas.NewMessage()
    rsp.GsmMessage = nas.NewGsmMessage()
    rsp.GsmHeader.SetMessageType(nas.MsgTypePDUSessionModificationCommand)
    rsp.GsmHeader.SetExtendedProtocolDiscriminator(nasMessage.Epd5GSSessionManagementMessage)
    rsp.PDUSessionModificationCommand = nasMessage.NewPDUSessionModificationCommand(0x00)
    pDUSessionModificationCommand := rsp.PDUSessionModificationCommand
    pDUSessionModificationCommand.SetExtendedProtocolDiscriminator(nasMessage.Epd5GSSessionManagementMessage)
    pDUSessionModificationCommand.SetPDUSessionID(uint8(smCtx.PDUSessionID))
    pDUSessionModificationCommand.SetPTI(smCtx.Pti)
    pDUSessionModificationCommand.SetMessageType(nas.MsgTypePDUSessionModificationCommand)

    reqQoSRules := nasType.QoSRules{}
    reqQoSFlowDescs := nasType.QoSFlowDescs{}

    if req.RequestedQosRules != nil {
        qosRuleBytes := req.GetQoSRules()
        if err := reqQoSRules.UnmarshalBinary(qosRuleBytes); err != nil { <-
            smCtx.Log.Warning("QoS rule parse failed:", err)
        }
    }

## Additional context
The error occurs only when the UE, which does not support QoS rule 2, sends "Rule operation code: Delete existing QoS rule (2)" to the AMF.

## Screenshots
![image](https://github.com/user-attachments/assets/72f51a48-cd89-4368-91f9-711abefcafe8)

01 pcap No.2185
![image](https://github.com/user-attachments/assets/9c22538f-e22a-41af-b2a3-150d18637363)

02 pcap No.2614
![image](https://github.com/user-attachments/assets/be1c0526-71b6-436a-b372-af7549278057)

## Environment (please complete the following information):
　free5GC Version: v3.4.3
　OS: Ubuntu 20.04.6 LTS
　Kernel version: 5.4.0-125-generic
　go version: Ubuntu go1.21.8 linux/amd64

**Comment by donald1218** [comment]
Hi, @Tommy021477 
Could you please provide me with the PCAP packet?

**Comment by Tommy021477** [comment]
I will attach the PCAP file, so please check it.
[Merge_Modifi.zip](https://github.com/user-attachments/files/17565934/Merge_Modifi.zip)

**Comment by Tommy021477** [comment]
Apart from the fact that SMF returns a QoS parsing error in response to a PDU session modification request from the UE/gNB, there is an additional related item to check.
This is about the QoS rule parameters to be set in the PDU session establishment accept from the 5G core.
1. There are two QoS rules, but both QoS rule identifiers are "1". Based on the description below, wouldn't the QoS rule identifiers be unique?
2. As with 1, there are two QoS rules, and both packet filter identifiers are "1". Based on TS24.501 6.4.1.3 d) 1, wouldn't they be unique?

【QoS Rule Identifier】
TS 23.501 5.7.1.4   QoS Rules
An explicitly signalled QoS rule contains a QoS rule identifier which is unique within the PDU Session and is generated by SMF.

TS24.501 6.2.5.1.1.2    Signalled QoS rules
Each signalled QoS rule contains:
a)an indication of whether the QoS rule is the default QoS rule;
b)a QoS rule identifier (QRI);
c)a QoS flow identifier (QFI);
d)optionally, a set of packet filters; and
e)a precedence value.
Within a PDU session:
a)each signalled QoS rule has a unique QRI;

TS24.501 6.4.1.3    UE-requested PDU session establishment procedure accepted by the network
a)    Semantic errors in QoS operations:
5)    When the rule operation is "Create new QoS rule" and two or more QoS rules associated with this PDU session would have identical QoS rule identifier values.

【Packet filter Identifier】
TS24.501 6.4.1.3    UE-requested PDU session establishment procedure accepted by the network
d)    Syntactical errors in packet filters:
1)    When the rule operation is "Create new QoS rule" and two or more packet filters in the resultant QoS rule would have identical packet filter identifiers.

![image](https://github.com/user-attachments/assets/2ae2cfb3-82f3-4c30-a4d8-d740a9d6f9e8)

**Comment by ming-hsien** [comment]
Hello @Tommy021477,
Could you please provide the packet format used for sending a PDUSessionModificationRequest from the UE?
Alternatively, could you provide your code related to actively triggering a PDUSessionModificationRequest from the UE?
Because I think the issue might be due to an incorrect QoS Modification Request format.
tks~

**Comment by Tommy021477** [comment]
Hello @ming-hsien
Thank you for your comment. Regarding the information in No.2614 of the previously attached “Merge_Modifi.pcapng,” is it insufficient? If it is insufficient, could you please specify what additional information is needed?
###################################################################
Plain NAS 5GS Message
    Extended protocol discriminator: 5G session management messages (46)
    PDU session identity: PDU session identity value 1 (1)
    Procedure transaction identity: 19
    Message type: PDU session modification request (0xc9)
    5GSM cause
        Element ID: 0x59
        5GSM cause: Syntactical error in the QoS operation (84)
    QoS rules - Requested QoS rules
        Element ID: 0x7a
        Length: 4
        QoS rule 1
            QoS rule identifier: 1
            Length: 1
            010. .... = Rule operation code: Delete existing QoS rule (2)
            ...0 .... = DQR: The QoS rule is not the default QoS rule
            .... 0000 = Number of packet filters: 0
###################################################################

**Comment by ming-hsien** [comment]
Hello @Tommy021477 ,
I reviewed the pcap file you attached, specifically frame No. 2185. In the PDUSessionResourceSetupRequest, only one QoS Rule is included, which differs from the screenshot you provided. Could you let me know if you still have the screenshot file saved?
![image](https://github.com/user-attachments/assets/017cd644-7ef3-48d1-bc35-50b6bdf3adbf)

Additionally, I have some questions regarding the issue you raised. You mentioned: “The error occurs only when the UE, which does not support QoS rule 2.” I’d like to ask why you need to delete a QoS rule that doesn’t exist. This could potentially be the cause of the issue.

**Comment by Tommy021477** [comment]
Hello @ming-hsien
The screenshot I provided in No. 2185 shows the NAS parameters section. Two QoS Rule parameters are set in the QuS rules of the NAS parameters. The parameters you commented on are NGAP parameters set in the QoSFlowSetupRequestList, so I think they are different from the parameters I want to check. Could you please check again?

![NAS_QoS](https://github.com/user-attachments/assets/e3d17e8a-b080-4ac0-a5bc-7a191154eb5f)
