### ISSUE TITLE
[Bugs]PDUSessionResourceModifyRequestTransfer编码失败

### ISSUE THREAD

**Issue by kai0920** [free5gc/free5gc#623]
## Describe the bug
![image](https://github.com/user-attachments/assets/e19c7aa0-b282-4e6e-a01f-91db58e2b88e)
![image](https://github.com/user-attachments/assets/7f1b257c-6688-4181-aa3b-95b2e729e594)
QosFlowDesc list有2组数据
	qosFlowDesc.QowFlowInd = 2
	qosFlowDesc.Cause.Type = 2
	qosFlowDesc.Cause.Value = 0

	qosFlowDesc2.QowFlowInd = 3
	qosFlowDesc2.Cause.Type = 2
	qosFlowDesc2.Cause.Value = 0
正确编码结果应该是000001008900050406401100，但是用aper编码出来的是000001008900050404800680，码流不对
麻烦帮忙看看是哪里的问题

**Comment by williamlin0518** [comment]
Hi @kai0920, is this code part of our smf internal codebase?

**Comment by kai0920** [comment]
> Hi @kai0920, is this code part of our smf internal codebase?

是的，已经解决了，
![image](https://github.com/user-attachments/assets/b0c18b3a-58f0-4adb-b2e4-e0bc2096006c)
这样改下就行，

**Comment by andy89923** [comment]
Hi @kai0920, Thanks for your report! 

@williamlin0518 Please create a correction PR in the ngap repo if needed.
