### ISSUE TITLE
SMF crashing

### ISSUE THREAD

**Issue by sanihitha** [free5gc/free5gc#64]
[detach.pcapng.gz](https://github.com/free5gc/free5gc/files/4733983/detach.pcapng.gz)

Hi Team,

when I am sending Deregistration request to free5gc ,it is sending Deregistration accept to RAN  but, the smf is crashing and it is storing as nill in message.

Please find below the smf logs and pcaps of deregistration.

[SMF logs.txt](https://github.com/free5gc/free5gc/files/4733978/SMF.logs.txt)

## To Reproduce
1. Change config '...'
2. Code patch '...' (You can fork the project and give us the patch diff you have modify)
3. Run command '...'
4. Dump packet '...'

## Environment (please complete the following information):
 - free5GC Version [e.g. v3.0.2]
 - OS: [e.g. Ubuntu 18.04 Server]
 - Kernel version [e.g. 5.0.0-23-generic]
- go version [e.g. 1.12.9 linux/amd64]
 - c compiler version (Option) [e.g. gcc version 7.5.0]

### Configuration File
Provide your configuration here.

### PCAP File
Dump the packet and provide the pcap file here.

### Log File
Provide the program log file here.

## System architecture (Option)
Give the draft of your architecture. What's your scenario, bare metal use case or using k8s, etc.

## Walkthrough (Option)
What you have find or research for short.

**Comment by free5gc-org** [comment]
The issue didn't follow the issue template.
