### ISSUE TITLE
[Bugs] V3.0.2. Test ./test.sh TestRegistration fails 

### ISSUE THREAD

**Issue by davidrupprecht** [free5gc/free5gc#65]
## Describe the bug
With the new release 3.0.2 the` ./test.sh TestRegistration
` fails with `ERRO[2020-06-05T16:50:00+02:00]/home/free5gc/go/src/free5gc/src/amf/nas/handler.go:41 free5gc/src/amf/nas.HandleNAS() Send to Nas Error: server no response         AMF=NGAP
` 
[testRegistration_fail.txt](https://github.com/free5gc/free5gc/files/4736768/testRegistration_fail.txt)

## To Reproduce
Followed the install instructions as described. 

## Expected behavior
The AMF shall send an Authentication Request, but it seems that the AMF does not get an authentication vector from the AUSF. 

## Environment (please complete the following information):
 - free5GC Version v3.0.2
 - OS: Ubuntu 18.04
 - Kernel version 5.0.0-23-generic
- go version 1.12.9 linux/amd64

### Configuration File
Provide your configuration here.

### PCAP File
Dump the packet and provide the pcap file here.

### Log File
Provide the program log file here.

## System architecture (Option)
Give the draft of your architecture. What's your scenario, bare metal use case or using k8s, etc.

## Walkthrough (Option)
What you have find or research for short.

**Comment by free5gc-org** [comment]
Hi @davidrupprecht ,

Please provide your pcap file and config file while running. If not am afraid it will it take a long time for our team to identify the course of the issue.

**Comment by davidrupprecht** [comment]
Please find the configs and pcap attached. 


[config_pcap.zip](https://github.com/free5gc/free5gc/files/4736951/config_pcap.zip)

**Comment by davidrupprecht** [comment]
It looks like the AMF sends a bad request to the AUSF. The response packet 2297 indicates a 400 bad request, which comes from the AUSF and after the initial registration request.

**Comment by free5gc-org** [comment]
hi @davidrupprecht ,

Can you try to use `mongo --eval "db.NfProfile.drop()" free5gc` command to clear db and run again?

**Comment by davidrupprecht** [comment]
Thanks that works :)
