### ISSUE TITLE
[Bugs] RUN  TestServiceRequest Error

### ISSUE THREAD

**Issue by kk8421** [free5gc/free5gc#67]
## Describe the bug
I got the segmentation fault.
I can not run any test script.

## To Reproduce
1. power on 
2. install gtp5g
3. cd free5gc
4../test.sh TestRegistration
5../test.sh TestServiceRequest
6....

## Expected behavior
same test script outcome

## Screenshots
=== RUN   TestServiceRequest
--- FAIL: TestServiceRequest (0.00s)
    registration_test.go:478: 
        	Error Trace:	registration_test.go:478
        	Error:      	Expected nil, but got: 0x6f
        	Test:       	TestServiceRequest
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa3b72f]

goroutine 252 [running]:
testing.tRunner.func1(0xc0025fde00)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1338fc0, 0x2317770)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).fd(...)
	/home/james/go/src/git.cs.nctu.edu.tw/calee/sctp/sctp.go:373
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).SCTPWrite(0x0, 0xc0030e2680, 0x39, 0x40, 0x0, 0x0, 0x0, 0x1)
	/home/james/go/src/git.cs.nctu.edu.tw/calee/sctp/sctp_linux.go:88 +0x4f
git.cs.nctu.edu.tw/calee/sctp.(*SCTPConn).Write(...)
	/home/james/go/src/git.cs.nctu.edu.tw/calee/sctp/sctp.go:385
free5gc/src/test_test.TestServiceRequest(0xc0025fde00)
	/home/james/go/src/free5gc/src/test/registration_test.go:483 +0x1fd
testing.tRunner(0xc0025fde00, 0x1574b80)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
exit status 2
FAIL	free5gc/src/test	1.645s

## Environment (please complete the following information):
 - free5GC Version: v3.0.2
 - OS: Ubuntu 18.04 desktop 
 - Kernel version  5.0.0-23-generic
- go version 1.12.9 linux/amd64
 - c compiler version (Option)  gcc version 7.5.0

### Configuration File
no modifcation, using default configuration

### PCAP File
Dump the packet and provide the pcap file here.
[TestRegistration20200609_fail.zip](https://github.com/free5gc/free5gc/files/4751150/TestRegistration20200609_fail.zip)

### Log File
[TestRegistration_faill_20200609.txt](https://github.com/free5gc/free5gc/files/4751175/TestRegistration_faill_20200609.txt)

If you do not know what to do, copy the log print on the screen and put it here.

## System architecture (Option)
Give the draft of your architecture. What's your scenario, bare metal use case or using k8s, etc.

## Walkthrough (Option)
What you have find or research for short.

**Comment by free5gc-org** [comment]
Seems to be the same error with issue #37.

We'll try to work on this issue.

**Comment by free5gc-org** [comment]
Hi @kk8421 @ameet-17,

Can you find any similarity between your system? Because we still cannot find the way to reproduce this.

**Comment by free5gc-org** [comment]
The problem seems to be caused by [sctp](https://git.cs.nctu.edu.tw/calee/sctp)

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/testregistration-failed/92/3

**Comment by kk8421** [comment]
@free5gc-org 
Yes, the issue is caused by sctp, because I modify ngapIpList IP address in amf.config.
So the Test needs run in 127.0.0.1, can't change any configuration.

Is it add error handling in test script?

**Comment by free5gc-org** [comment]
@kk8421 
If you change the config file, do you set the IP manually to your OS?

We don't need to set IP in range 127.0.0.0/24 in test because all of these IP will bind to localhost by default. But if you use the IP rather then 127.0.0.0/24, you may need to set IP to OS manually.
The program will not set the IP on runtime automatically.

**Comment by kk8421** [comment]
@kk8421 
Thank you for your reply.
I don't have modification OS' IP(e.g. ifconfig), only recover default free5gc configure.

**Comment by kk8421** [comment]
Hi, @free5gc-org 
I reply at the same time in [https://forum.free5gc.org/t/how-the-simulated-ue-provided-by-free5gc-can-ping-google-com/93/5](https://forum.free5gc.org/t/how-the-simulated-ue-provided-by-free5gc-can-ping-google-com/93/5)

My ngapIpList is blow:
info:
  version: 1.0.0
  description: AMF initial local configuration

configuration:
  amfName: free5GC-AMF
  ngapIpList:
    - 127.0.0.1
  sbi:
    scheme: http
    ipv4Addr: 127.0.0.1
    port: 29518
  serviceNameList:
    - namf-comm
    - namf-evts
    - namf-mt
    - namf-loc
    - namf-oam
  servedGuamiList:
    - plmnId:
        mcc: 208
        mnc: 93
      amfId: cafe00
  supportTaiList:
    - plmnId:
        mcc: 208
        mnc: 93
      tac: 1
  plmnSupportList:
    - plmnId:
        mcc: 208
        mnc: 93
      snssaiList:
        - sst: 1
          sd: 010203
        - sst: 1
          sd: 112233
  supportDnnList:
    - internet
  nrfUri: http://localhost:29510
  security:
    integrityOrder:
      - NIA2
      - NIA0
    cipheringOrder:
      - NEA2
      - NEA0
  networkName:
    full: free5GC
    short: free
  t3502: 720
  t3512: 3600
  non3gppDeregistrationTimer: 3240

**Comment by free5gc-org** [comment]
How about trying to use [origin sctp package](https://github.com/ishidawataru/sctp) instead of [new one](https://git.cs.nctu.edu.tw/calee/sctp)?

Maybe we can test to replace git.cs.nctu.edu.tw/calee/sctp with github.com/ishidawataru/sctp and check if it fix the problem.

**Comment by free5gc-org** [comment]
It's unable to reproduce it on our environment. Is it possible for you to send the VM image that will cause this issue to free5gc.org@gmail.com ?

Thanks a lot

**Comment by kk8421** [comment]
HI, 
VM image is more large, I can't send it.

**Comment by free5gc-org** [comment]
I think I found the problem.

After you run TestNon3GPP, the test script will modify the ngapIpList. Although the scrip will auto recover the amf config file, if you terminate the test manually, the ngapIpList will not be recover. After that, if you run other test (e.g. TestRegistration), the sctp will bind to an IP that are not exist so it will failed.

This issue might not relate to different version or different sctp packet.

Refer to the trouble shooting:

https://github.com/free5gc/free5gc/wiki/Trouble_Shooting#2-testnon3gpp

**Comment by free5gc-org** [comment]
Hi @kk8421 ,

Can you help us to verify the cause?

Thanks a lot

**Comment by chenxianpeng** [comment]
Hi everyone,
Is there an VM image installed and running successfully?
Can you share it with me?

**Comment by chenxianpeng** [comment]
您好！您的邮件我已收到，感谢您的来信
