### ISSUE TITLE
[Bugs] UE attach to free5gc, but UE does not send registration complete messages to free5gc

### ISSUE THREAD

**Issue by chenhao5651** [free5gc/free5gc#69]
## Describe the bug
UE attach to free5gc, but UE does not send Registration complete message to free5gc，Timer T3512 will expired, and  free5gc will resend Registration Accept message to UE. In fact, the test UE can attach to another commercial 5GC. I will offer free5GC  and the commercial 5GC signalings. Please checkout what I miss. By the way , I've add '5gs network feature support' in free5gc.

## To Reproduce
1. no config changes
2. releases v3.0.2
3. Run command '...'
4. Dump packet '...'

## Environment (please complete the following information):
 - free5GC Version [ v3.0.2]
 - OS: [Ubuntu 18.04 Server]
 - Kernel version [e.g. 5.0.0-23-generic]
- go version [e.g. 1.12.9 linux/amd64]
 - c compiler version (Option) [e.g. gcc version 7.5.0]

### Configuration File
Provide your configuration here.

If you don't know what to do, you can zip the `config` folder and upload the zip file here.

### PCAP File
Dump the packet and pr
[signaling.zip](https://github.com/free5gc/free5gc/files/4774428/signaling.zip)

ovide the pcap file here.

If you don't know what to do, you can use `sudo tcpdump -i any -w free5gc.pcap` before you run the bug reproduce. After that, upload the free5gc.pcap file here.

### Log File
Provide the program log file here.

If you do not know what to do, copy the log print on the screen and put it here.

## System architecture (Option)
Give the draft of your architecture. What's your scenario, bare metal use case or using k8s, etc.

## Walkthrough (Option)
What you have find or research for short.

**Comment by free5gc-org** [comment]
The problem seems to be we mis-fill the NAS security header in registration accept. The correct header must be plain in inner 5GS message. But we fill in integrity protected and ciphered security header in inner 5GS message so the UE will not be able to decode it.

We'll try to fix this issue. Thanks for reporting it. 👍 

![image](https://user-images.githubusercontent.com/60502770/84721685-d1145980-afb3-11ea-965e-cb5bfd8292d8.png)

**Comment by adejavel** [comment]
Hello,
We had the same issue in our lab and fixed it by changing file `src/amf/gmm/message/build.go` line 441 from 
`registrationAccept.SpareHalfOctetAndSecurityHeaderType.SetSecurityHeaderType(nas.SecurityHeaderTypeIntegrityProtectedAndCiphered)`
to 
`registrationAccept.SpareHalfOctetAndSecurityHeaderType.SetSecurityHeaderType(nas.SecurityHeaderTypePlainNas)`
Have a good day.

**Comment by chenhao5651** [comment]
> 
> 
> Hello,
> We had the same issue in our lab and fixed it by changing file `src/amf/gmm/message/build.go` line 441 from
> `registrationAccept.SpareHalfOctetAndSecurityHeaderType.SetSecurityHeaderType(nas.SecurityHeaderTypeIntegrityProtectedAndCiphered)`
> to
> `registrationAccept.SpareHalfOctetAndSecurityHeaderType.SetSecurityHeaderType(nas.SecurityHeaderTypePlainNas)`
> Have a good day.

Hi adejavel , Thanks for your reply.
I've changed file `src/amf/gmm/message/build.go', but the UE still do not send Registration complete message to free5gc. Could you help me to check the signaling and log ?
[log.zip](https://github.com/free5gc/free5gc/files/4807746/log.zip)

**Comment by free5gc-org** [comment]
Dear all,

We have correct NAS security encode/decode procedure in free5gc v3.0.3. Please check and try it!

Thanks for your report!

**Comment by 359859461** [comment]
we fix our problem(UE still not send Registration complete message to free5gc)
we find out that the gNB does not support NAS optional items.(Item 6: id-MobilityRestrictionList and Item 7: id-MaskedIMEISV)
so,we delete line1059-1070 1101-1120 in amf/amf_ngap/ngap_message/build.go(V3.0.1)
