### ISSUE TITLE
[Bugs]SMF returned an invalid PDU session type value when UE tried to establish a PDU session with the sessiont type IPv4v6

### ISSUE THREAD

**Issue by am677** [free5gc/free5gc#72]
## Describe the bug
I expected SMF to return a PDU session establishment accept with type IPv4 when the SM data was provisioned with `"pduSessionTypes" : { "allowedSessionTypes" : [ "IPV4" ], "defaultSessionType" : "IPV4" }` and an UE requested a PDU session with the session type IPv4v6.

However SMF returned an accept message with PDU session type: Unknown. (See Screenshots.)

## To Reproduce
1. Change config 'See Configs'
2. Run command './run.sh'
3. Requests a PDU session with the session type IPv4v6.

## Expected behavior
The SMF return a PDU session establishment accept with type: IPv4 and include the 5GSM cause value `#50` "PDU session type IPv4 only allowed" in the 5GSM cause IE when an UE requested a PDU session with the session type IPv4v6.

#### PDU session establishment request
![request](https://user-images.githubusercontent.com/66290148/85100371-f4046f00-b23a-11ea-9e68-b741cbfe3fe3.png)

#### PDU session establishment accept
![accept](https://user-images.githubusercontent.com/66290148/85100380-fb2b7d00-b23a-11ea-88b8-acf9b56e50ec.png)

## Environment (please complete the following information):
 - free5GC Version [v3.0.2]
 - OS: [Ubuntu 18.04 Server]
 - Kernel version [5.0.0-23-generic]
 - go version [1.12.9 linux/amd64]

### Configuration File
config/nssfcfg.conf
```
+    - snssai:
+        sst: 1
+        sd: 112233
+      nsiInformationList:
+        - nrfId: https://localhost:29510/nnrf-nfm/v1/nf-instances
+          nsiId: 23
```
mongodb (See pduSessionTypes. `"allowedSessionTypes" : [ "IPV4" ], "defaultSessionType" : "IPV4" `)
```
db.subscriptionData.provisionedData.smData.insert({"servingPlmnId" : "46000", "singleNssai" : { "sst" : 1, "sd" : "112233" }, "dnnConfigurations" : { "internet" : { "pduSessionTypes" : { "allowedSessionTypes" : [ "IPV4" ], "defaultSessionType" : "IPV4" }, "sscModes" : { "defaultSscMode" : "SSC_MODE_1", "allowedSscModes" : [ "SSC_MODE_1", "SSC_MODE_2", "SSC_MODE_3" ] }, "5gQosProfile" : { "5qi" : 9, "arp" : { "priorityLevel" : 8, "preemptCap" : "", "preemptVuln" : "" }, "priorityLevel" : 8 }, "sessionAmbr" : { "uplink" : "1000 Kbps", "downlink" : "1000 Kbps" } } }, "ueId" : "imsi-460000012200000" })
db.subscriptionData.provisionedData.smData.insert({"servingPlmnId" : "46000", "singleNssai" : { "sst" : 1, "sd" : "010203" }, "dnnConfigurations" : { "internet" : { "pduSessionTypes" : { "allowedSessionTypes" : [ "IPV4" ], "defaultSessionType" : "IPV4" }, "sscModes" : { "defaultSscMode" : "SSC_MODE_1", "allowedSscModes" : [ "SSC_MODE_1", "SSC_MODE_2", "SSC_MODE_3" ] }, "5gQosProfile" : { "5qi" : 9, "arp" : { "priorityLevel" : 8, "preemptCap" : "", "preemptVuln" : "" }, "priorityLevel" : 8 }, "sessionAmbr" : { "uplink" : "1000 Kbps", "downlink" : "1000 Kbps" } } }, "ueId" : "imsi-460000012200000" })
```
Other changes are only IP and PLMN settings.

### PCAP File
[free5gc_ngap.zip](https://github.com/free5gc/free5gc/files/4802620/free5gc_ngap.zip)

### Log File
[free5gc_log.txt](https://github.com/free5gc/free5gc/files/4802622/free5gc_log.txt)

## Additional context
There is the following description in the section '6.4.1.3 UE-requested PDU session establishment procedure accepted by the network' of 3GPP TS 24.501.

> If the PDU SESSION ESTABLISHMENT REQUEST message includes a PDU session type IE set to "IPv4v6", the SMF shall select "IPv4", "IPv6" or "IPv4v6" as the selected PDU session type IE of the PDU session. If the subscription, the SMF configuration, or both, are limited to IPv4 only or IPv6 only for the requested DNN, the SMF shall include the 5GSM cause value `#50` "PDU session type IPv4 only allowed", or `#51` "PDU session type IPv6 only allowed", respectively, in the 5GSM cause IE of the PDU SESSION ESTABLISHMENT ACCEPT message. 

I hope that the handling of PDU session type on SMF will be fixed soon.
Because some real UE always requests a PDU session with the session type IPv4v6.

**Comment by free5gc-org** [comment]
Hi @am677 ,

free5GC has handle PDU Session Type IPv4v6 in v3.0.3. Please try and test it.

Thanks for your report!

**Comment by am677** [comment]
Thank you for successful implementation!

I confirmed that free5gc return PDU session establishment accept with cause value `#50` "PDU session type IPv4 only allowed" when an UE requested a PDU session with the session type IPv4v6.
![image](https://user-images.githubusercontent.com/66290148/89614472-79151780-d8bf-11ea-9303-a1507795efa4.png)
