### ISSUE TITLE
[Bugs] Initital Registration fails with NAS decode

### ISSUE THREAD

**Issue by tonid7** [free5gc/free5gc#73]
## Describe the bug

The AMF fails to decode an Initital Registration request with a 5G-TMSI with: <br/>
`NAS decode Fail: MsgType[27] doesn't exist in GMM Message`

During multiple runs, the MsgType doesnt seem consistent  <br/>
`NAS decode Fail: MsgType[228] doesn't exist in GMM Message`
`NAS decode Fail: MsgType[244] doesn't exist in GMM Message`

## To Reproduce
1. Start all NFs
2. NGAP Setup complete from a gNB
3. Initiate Registration from a UE

## Expected behavior
The AMF decodes the GMM message and continues with the registration procedure. If it doesnt have the 5G-TMSI it needs to invoke identity request to the UE.

## Screenshots
N/A

## Environment (please complete the following information):
 - free5GC Version: nightly version, master branch
 - OS: Ubuntu 18.04.4 LTS
 - Kernel version: 5.0.0-23-generic
- go version: go1.12.9 linux/amd64

### Configuration File
[config_delta.log](https://github.com/free5gc/free5gc/files/4817686/config_delta.log)

### PCAP File
[InitialRegistration.zip](https://github.com/free5gc/free5gc/files/4817698/InitialRegistration.zip)

### Log File

INFO[2020-06-19T15:24:40Z]/src/amf/ngap/handler.go:883 free5gc/src/amf/ngap.HandleInitialUEMessage() [AMF] Initial UE Message                      AMF=NGAP
ERRO[2020-06-19T15:24:40Z]/src/amf/nas/handler.go:28 free5gc/src/amf/nas.HandleNAS() NAS decode Fail: MsgType[27] doesn't exist in GMM Message  AMF=NAS
INFO[2020-06-19T15:24:45Z]/src/amf/ngap/handler.go:267 free5gc/src/amf/ngap.HandleNGReset() [AMF] NG Reset                                AMF=NGAP
WARN[2020-06-19T15:24:45Z]/src/amf/ngap/handler.go:4058 free5gc/src/amf/ngap.printAndGetCause() Cause Misc[5]                                 AMF=NGAP
INFO[2020-06-19T15:24:45Z]/src/amf/ngap/message/send.go:121 free5gc/src/amf/ngap/message.SendNGResetAcknowledge() [AMF] Send NG Reset Acknowledge               AMF=NGAP

DEBUG LEVEL:

DEBU[2020-06-19T15:30:03Z]/src/amf/ngap/sctp/sctp.go:100 free5gc/src/amf/ngap/sctp.(*SCTPListener).forwardData() Packet get: 0x000f407b0000040055000340294400260055547e01e4f0e589057e004149000bf202f459380899780000012e04f070f0707100337e004149000bf202f459380899780000011001032e04f070f0705202f459000bb91707f070c0401980b01801017400005301010079000f4002f459004e3c001002f459000bb9005a400118  AMF=NGAP
INFO[2020-06-19T15:30:03Z]/src/amf/ngap/handler.go:883 free5gc/src/amf/ngap.HandleInitialUEMessage() [AMF] Initial UE Message                      AMF=NGAP
DEBU[2020-06-19T15:30:03Z]/src/amf/ngap/handler.go:952 free5gc/src/amf/ngap.HandleInitialUEMessage() New RanUe [RanUeNgapID: 10564]                AMF=NGAP
ERRO[2020-06-19T15:30:03Z]/src/amf/nas/handler.go:28 free5gc/src/amf/nas.HandleNAS() NAS decode Fail: MsgType[228] doesn't exist in GMM Message  AMF=NAS
DEBU[2020-06-19T15:30:08Z]/src/amf/ngap/sctp/sctp.go:100 free5gc/src/amf/ngap/sctp.(*SCTPListener).forwardData() Packet get: 0x00140011000002000f40018a005800054001242944  AMF=NGAP
INFO[2020-06-19T15:30:08Z]/src/amf/ngap/handler.go:267 free5gc/src/amf/ngap.HandleNGReset() [AMF] NG Reset                                AMF=NGAP
WARN[2020-06-19T15:30:08Z]/src/amf/ngap/handler.go:4058 free5gc/src/amf/ngap.printAndGetCause() Cause Misc[5]                                 AMF=NGAP
INFO[2020-06-19T15:30:08Z]/src/amf/ngap/message/send.go:121 free5gc/src/amf/ngap/message.SendNGResetAcknowledge() [AMF] Send NG Reset Acknowledge               AMF=NGAP
DEBU[2020-06-19T15:30:08Z]/src/amf/ngap/message/send.go:32 free5gc/src/amf/ngap/message.SendToRan() [NGAP] Send To Ran [IP: 10.1.4.97:38412]      AMF=NGAP

another debug take:
DEBU[2020-06-19T15:31:06Z]/src/amf/ngap/sctp/sctp.go:100 free5gc/src/amf/ngap/sctp.(*SCTPListener).forwardData() Packet get: 0x000f407b0000040055000340294500260055547e01f44efdd9067e004149000bf202f459380899780000012e04f070f0707100337e004149000bf202f459380899780000011001032e04f070f0705202f459000bb91707f070c0401980b01801017400005301010079000f4002f459004e3c001002f459000bb9005a400118  AMF=NGAP
INFO[2020-06-19T15:31:06Z]/src/amf/ngap/handler.go:883 free5gc/src/amf/ngap.HandleInitialUEMessage() [AMF] Initial UE Message                      AMF=NGAP
DEBU[2020-06-19T15:31:06Z]/src/amf/ngap/handler.go:952 free5gc/src/amf/ngap.HandleInitialUEMessage() New RanUe [RanUeNgapID: 10565]                AMF=NGAP
ERRO[2020-06-19T15:31:06Z]/src/amf/nas/handler.go:28 free5gc/src/amf/nas.HandleNAS() NAS decode Fail: MsgType[244] doesn't exist in GMM Message  AMF=NAS
DEBU[2020-06-19T15:31:12Z]/src/amf/ngap/sctp/sctp.go:100 free5gc/src/amf/ngap/sctp.(*SCTPListener).forwardData() Packet get: 0x00140011000002000f40018a005800054001242945  AMF=NGAP
INFO[2020-06-19T15:31:12Z]/src/amf/ngap/handler.go:267 free5gc/src/amf/ngap.HandleNGReset() [AMF] NG Reset                                AMF=NGAP
WARN[2020-06-19T15:31:12Z]/src/amf/ngap/handler.go:4058 free5gc/src/amf/ngap.printAndGetCause() Cause Misc[5]                                 AMF=NGAP
INFO[2020-06-19T15:31:12Z]/src/amf/ngap/message/send.go:121 free5gc/src/amf/ngap/message.SendNGResetAcknowledge() [AMF] Send NG Reset Acknowledge               AMF=NGAP
DEBU[2020-06-19T15:31:12Z]/src/amf/ngap/message/send.go:32 free5gc/src/amf/ngap/message.SendToRan() [NGAP] Send To Ran [IP: 10.1.4.97:38412]      AMF=NGAP

## System architecture (Option)
control-plane VM with all SBA NFs, user-plane VM with UPF

## Walkthrough (Option)
See steps.

## Additional context
N/A

**Comment by free5gc-org** [comment]
Dear all,

We have correct NAS security encode/decode procedure in free5gc v3.0.3. Please check and try it!

Thanks for your report!
