### ISSUE TITLE
[Feat] NIA1/NEA1 snow3g algorithm implement！

### ISSUE THREAD

**Issue by 359859461** [free5gc/free5gc#74]
## Describe the bug
free5gc doesnot support  NIA1 and NEA1 algorithm
we implement snow3g by golang，but did't verify on free5gc

## Expected behavior
verify the code on free5gc we support,and share how to use this on free5gc
@free5gc-org 

## Environment (please complete the following information):
 - free5GC Version [e.g. v3.0.2]
 - OS: [e.g. Ubuntu 18.04 Server]
 - Kernel version [e.g. 5.0.0-23-generic]
- go version [e.g. 1.12.9 linux/amd64]
 - c compiler version (Option) [e.g. gcc version 7.5.0]

## Additional context
[snow3g.zip](https://github.com/free5gc/free5gc/files/4824417/snow3g.zip)

**Comment by 359859461** [comment]
please tell me when this issue solved(359859461@qq.com).thx!

**Comment by free5gc-org** [comment]
Dear @359859461 ,

We think this might be a feature request. It is kindly of you to create the issue with feature request template instead of bug report.

**Comment by free5gc-org** [comment]
Hi @359859461,

We have release the latest free5gc v3.0.3 and add NEA1 and NIA1 algorithm.

Thanks a lot
