### ISSUE TITLE
[Bugs] max no.of ues supported by free5gc

### ISSUE THREAD

**Issue by sanihitha** [free5gc/free5gc#75]
## issue
when i tried to attach multiple ues only 22 ues are attaching after giving 23 rd supi value of ue the udm is giving warning like ID is not matched and in upf segmantion fault is occuring, even after the supi value of 23rd ue is updated in database.

## To Reproduce
1. Change config '...'
2. Code patch '...' (You can fork the project and give us the patch diff you have modified)
3. Run command '...'
4. Dump packet '...'

## Screenshots
udm warning log:
<img width="829" alt="i1" src="https://user-images.githubusercontent.com/66457136/85537063-42e24800-b631-11ea-959a-c6f2a71a9dfb.PNG">

upf error log:
<img width="833" alt="i2" src="https://user-images.githubusercontent.com/66457136/85537657-c9972500-b631-11ea-8c8e-22ff0e1508c9.PNG">

## Environment (please complete the following information):
 - free5GC Version [e.g. v3.0.1]
 - OS: [e.g. Ubuntu 18.04 Server]
 - Kernel version [e.g. 5.0.0-23-generic]
- go version [e.g. 1.12.9 linux/amd64]
 - c compiler version (Option) [e.g. gcc version 7.3.0]

### Configuration File
Provide your configuration here.

If you don't know what to do, you can zip the `config` folder and upload the zip file here.

### PCAP File
Dump the packet and provide the pcap file here.

If you don't know what to do, you can use `sudo tcpdump -i any -w free5gc.pcap` before you run the bug reproduce. After that, upload the free5gc.pcap file here.

### Log File
Provide the program log file here.

If you do not know what to do, copy the log print on the screen and put it here.

## System architecture (Option)
Give the draft of your architecture. What's your scenario, bare metal use case or using k8s, etc.

## Walkthrough (Option)
What you have find or research for short.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/how-many-number-of-ues-does-an-free5gc-support/144/2

**Comment by JingqiHuang** [comment]
Hi! Has this issue been solved? I use docker-compose version of free5gc and I can only attach 10 UEs..

**Comment by wilson30139** [comment]
Hello, the current version of free5GC is 3.3.0, this problem has been solved.
Link: https://github.com/free5gc/free5gc

**Comment by brianchennn** [comment]
@noormohammedli 
The latest version of free5gc v3.3.0 has fixed this issue. I use latest **UERANSIM (commit: 3a96298)** to test **100 UEs** and set Registration interval time to **10 ms**. The Test Result is fine and no error happened. So I will close this issue.
![image](https://github.com/free5gc/free5gc/assets/46628572/adb2ebc7-810f-437c-9700-62b48005597e)
