### ISSUE TITLE
Error when UE registration 

### ISSUE THREAD

**Issue by 20sandra** [free5gc/free5gc#79]
**If you don't follow the issue template, your issue may be closed.**

### What's the version are you using

free5GC Stage 3

### Is your feature request related to a problem? Please describe.

When I try to register a user I get an error on the AMF

### Describe the solution you'd like

Know what is causing the error and how to fix it 

### Additional context
Logs

INFO[2020-07-11T20:05:51+02:00]/src/amf/amf_nas/nas_security/security.go:38 free5gc/src/amf/amf_nas/nas_security.Encode() NasPdu Security: Integrity Protected With New 5gNasSecurityContext  AMF=NAS
INFO[2020-07-11T20:05:51+02:00]/src/amf/amf_ngap/ngap_message/send.go:138 free5gc/src/amf/amf_ngap/ngap_message.SendDownlinkNasTransport() [AMF] Send Downlink Nas Transport             AMF=NGAP
INFO[2020-07-11T20:05:51+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:185 free5gc/src/amf/amf_ngap/ngap_handler.HandleUplinkNasTransport() [AMF] Uplink Nas Transport                    AMF=NGAP
WARN[2020-07-11T20:05:51+02:00]/src/amf/amf_nas/nas_security/security.go:171 free5gc/src/amf/amf_nas/nas_security.Decode() NAS MAC verification failed(0x58af4411 != 0x59429c0e)  AMF=NAS
ERRO[2020-07-11T20:05:51+02:00]/src/amf/amf_nas/handler.go:28 free5gc/src/amf/amf_nas.HandleNAS() Extended Protocol Discriminator[203] is not allowed in Nas Message Deocde  AMF=NAS
INFO[2020-07-11T20:05:57+02:00]/src/amf/gmm/gmm_message/send.go:165 free5gc/src/amf/gmm/gmm_message.SendSecurityModeCommand() [NAS] Send Security Mode Command              AMF=Gmm
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_nas/nas_security/security.go:38 free5gc/src/amf/amf_nas/nas_security.Encode() NasPdu Security: Integrity Protected With New 5gNasSecurityContext  AMF=NAS
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_ngap/ngap_message/send.go:138 free5gc/src/amf/amf_ngap/ngap_message.SendDownlinkNasTransport() [AMF] Send Downlink Nas Transport             AMF=NGAP
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:1615 free5gc/src/amf/amf_ngap/ngap_handler.HandleInitialContextSetupResponse() [AMF] Initial Context Setup Response          AMF=NGAP
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:185 free5gc/src/amf/amf_ngap/ngap_handler.HandleUplinkNasTransport() [AMF] Uplink Nas Transport                    AMF=NGAP
WARN[2020-07-11T20:05:57+02:00]/src/amf/amf_nas/nas_security/security.go:171 free5gc/src/amf/amf_nas/nas_security.Decode() NAS MAC verification failed(0x70dd43a7 != 0x9cc96503)  AMF=NAS
ERRO[2020-07-11T20:05:57+02:00]/src/amf/amf_nas/handler.go:28 free5gc/src/amf/amf_nas.HandleNAS() Extended Protocol Discriminator[61] is not allowed in Nas Message Deocde  AMF=NAS
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:185 free5gc/src/amf/amf_ngap/ngap_handler.HandleUplinkNasTransport() [AMF] Uplink Nas Transport                    AMF=NGAP
WARN[2020-07-11T20:05:57+02:00]/src/amf/amf_nas/nas_security/security.go:171 free5gc/src/amf/amf_nas/nas_security.Decode() NAS MAC verification failed(0xb8418386 != 0x699de904)  AMF=NAS
ERRO[2020-07-11T20:05:57+02:00]/src/amf/amf_nas/handler.go:28 free5gc/src/amf/amf_nas.HandleNAS() Extended Protocol Discriminator[59] is not allowed in Nas Message Deocde  AMF=NAS
INFO[2020-07-11T20:05:57+02:00]/src/amf/gmm/gmm_message/send.go:165 free5gc/src/amf/gmm/gmm_message.SendSecurityModeCommand() [NAS] Send Security Mode Command              AMF=Gmm
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_nas/nas_security/security.go:38 free5gc/src/amf/amf_nas/nas_security.Encode() NasPdu Security: Integrity Protected With New 5gNasSecurityContext  AMF=NAS
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_ngap/ngap_message/send.go:138 free5gc/src/amf/amf_ngap/ngap_message.SendDownlinkNasTransport() [AMF] Send Downlink Nas Transport             AMF=NGAP
INFO[2020-07-11T20:05:57+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:1059 free5gc/src/amf/amf_ngap/ngap_handler.HandlePDUSessionResourceSetupResponse() [AMF] PDU Session Resource Setup Response     AMF=NGAP
ERRO[2020-07-11T20:05:57+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:1115 free5gc/src/amf/amf_ngap/ngap_handler.HandlePDUSessionResourceSetupResponse() SendUpdateSmContextN2Info[PDUSessionResourceSetupResponseTransfer] Error:
[AMF] pduSessionId : 10 is not in Ue  AMF=NGAP
2020/07/11 20:05:57 timer closed
INFO[2020-07-11T20:05:58+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:185 free5gc/src/amf/amf_ngap/ngap_handler.HandleUplinkNasTransport() [AMF] Uplink Nas Transport                    AMF=NGAP
WARN[2020-07-11T20:05:58+02:00]/src/amf/amf_nas/nas_security/security.go:171 free5gc/src/amf/amf_nas/nas_security.Decode() NAS MAC verification failed(0xf5a176f6 != 0x4befbeb9)  AMF=NAS
ERRO[2020-07-11T20:05:58+02:00]/src/amf/amf_nas/handler.go:28 free5gc/src/amf/amf_nas.HandleNAS() Extended Protocol Discriminator[74] is not allowed in Nas Message Deocde  AMF=NAS
INFO[2020-07-11T20:06:03+02:00]/src/amf/gmm/gmm_message/send.go:165 free5gc/src/amf/gmm/gmm_message.SendSecurityModeCommand() [NAS] Send Security Mode Command              AMF=Gmm
INFO[2020-07-11T20:06:03+02:00]/src/amf/amf_nas/nas_security/security.go:38 free5gc/src/amf/amf_nas/nas_security.Encode() NasPdu Security: Integrity Protected With New 5gNasSecurityContext  AMF=NAS
INFO[2020-07-11T20:06:03+02:00]/src/amf/amf_ngap/ngap_message/send.go:138 free5gc/src/amf/amf_ngap/ngap_message.SendDownlinkNasTransport() [AMF] Send Downlink Nas Transport             AMF=NGAP
INFO[2020-07-11T20:06:03+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:435 free5gc/src/amf/amf_ngap/ngap_handler.HandleUEContextReleaseComplete() [AMF] UE Context Release Complete             AMF=NGAP
INFO[2020-07-11T20:06:03+02:00]/src/amf/amf_ngap/ngap_handler/handler.go:575 free5gc/src/amf/amf_ngap/ngap_handler.HandleUEContextReleaseComplete() Release UE[imsi-2089300007487] Con

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X ] No, I don't have the time and I wouldn't even know how to start.

**Comment by free5gc-org** [comment]
This is not a feature request but a question or bug report.

Please ask question on [forum](https://forum.free5gc.org/) or report bugs with the [bugs report template](https://github.com/free5gc/free5gc/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBugs%5D).
