### ISSUE TITLE
[Bugs] The key file for "http/tls" messages didn't generate under ‘’free5gc/testkeylog”

### ISSUE THREAD

**Issue by Qxff** [free5gc/free5gc#81]
Dear Free5GC team,

Thanks for your great job of this excellent project!

I setup the Free5GC environment and all the test cases were passed. 
But I met the issue that no key file was generated under folder: "free5gc/testkeylog". All the key file are **empty**.

Could you please help check the reason? Many thanks!

![key_file_size_all_0](https://user-images.githubusercontent.com/37206778/88267560-9795e300-cd03-11ea-8d0d-b1f3582d3b16.png)

**Comment by calee0219** [comment]
Is your SBI using TLS encryption or just http without encrypt?

**Comment by free5gc-org** [comment]
This issue doesn't follow the issue template.

**Comment by Qxff** [comment]
> 
> 
> Is your SBI using TLS encryption or just http without encrypt?

How can I check this configuration please? Thanks. In the amf/smf/etc... config file, it's http, not https.

**Comment by calee0219** [comment]
There is a scheme filed in config. If it is http, then the sbi is sending via http without TLS encryption. You don't need to decrypt it by key files.

**Comment by Qxff** [comment]
> 
> 
> There is a scheme filed in config. If it is http, then the sbi is sending via http without TLS encryption. You don't need to decrypt it by key files.

Many thanks!  Yes, the scheme in all the config files are "http". But the sbi http are still TLS encrypted.
I attached the config file and pcap file here. Thanks!

![amf_scheme](https://user-images.githubusercontent.com/37206778/88367656-e18fcf00-cdbe-11ea-80cc-0ae6b16b2984.png)

[TestRegistration_pcap_file.zip](https://github.com/free5gc/free5gc/files/4970545/TestRegistration_pcap_file.zip)

**Comment by calee0219** [comment]
Which interface are you capturing?

**Comment by Qxff** [comment]
> 
> 
> Which interface are you capturing?

Command as below, interface is any.
 **tcpdump -i any -w test1.pcap**

**Comment by calee0219** [comment]
I found that if you are using wireshark to check it, you can see WS view http2 as TLS. But checking in the raw data, it is not encrypted. I thank you should modify the preferences of WS for example:

![image](https://user-images.githubusercontent.com/12643673/88371809-56670700-cdc7-11ea-85fb-2119c63e959e.png)

**Comment by Qxff** [comment]
> 
> 
> I found that if you are using wireshark to check it, you can see WS view http2 as TLS. But checking in the raw data, it is not encrypted. I thank you should modify the preferences of WS for example:
> 
> ![image](https://user-images.githubusercontent.com/12643673/88371809-56670700-cdc7-11ea-85fb-2119c63e959e.png)
> 
> And WS will help yo to decode the SBI

Oh, I see. It's not the default port number of HTTP. We need to add the configuration in wireshark.
Now it works! Really appreciated for your great help today!!!

BTW, rececntly I am reading the src code of UPF/SMF/AMF etc...
Do you have any document that describe the src code of each node? Such as the software development document, code structure, fuctions realization method or anything else that can help me better understand the src code. Great thanks!

![Decode as HTTP2](https://user-images.githubusercontent.com/37206778/88379613-ddbb7700-cdd5-11ea-8148-f0e5c2bc798b.png)
