### ISSUE TITLE
[Docs] Does mnc and mcc in "*cfg.conf" need to specify zero-padded three-digit numbers?

### ISSUE THREAD

**Issue by s5uishida** [free5gc/free5gc#82]
## Suggestion

I would like to report something that I noticed about the format of `mcc` and `mnc` in `*cfg.conf`.

For example, "`5G:mnc093.mcc208.3gppnetwork.org`". (mcc=208, mnc=93)
`free5gc/src/amf/factory/factory.go`:
```
func InitConfigFactory(f string) {
        content, err := ioutil.ReadFile(f)
        checkErr(err)

        AmfConfig = Config{}

        err = yaml.Unmarshal([]byte(content), &AmfConfig) <==
        checkErr(err)

        logger.InitLog.Infof("Successfully initialize configuration %s", f)
}
```
As a result of `yaml.Unmarshal([]byte(content), &AmfConfig)`, if `amfcfg.conf` contains `mnc: 93`, as a result of reading, the `AmfConfig` instance will contain the `93` string.

However, when `NGSetupRequest` is received from RAN, the following log is displayed and it fails because the received `mnc=093` and `mnc=93` in `amfcfg.conf` do not match.

"`NG-Setup failure: Cannot find Served TAI in AMF AMF=NGAP`"

So, it seems good to write `mcc` and `mnc` in `*cfg.conf` with three digits with zero padding.

I'm sorry if I had any misunderstanding.

**Comment by free5gc-org** [comment]
Hi @s5uishida ,

According to TS 23.003, MCC is a 3 digits of id and MNC is a 2 or 3 digits of id. So yes, it may be good to write mcc with zero padding but not on mnc. How do you think? 😃

**Comment by s5uishida** [comment]
I will briefly explain the background.

I noticed it when I used [aligungr/ue-ran-sim](https://github.com/aligungr/ue-ran-sim). ==> [issues/59](https://github.com/aligungr/ue-ran-sim/issues/59)

To see the process of matching the pLMNIdentity received from RAN to that in amfcfg.conf, I tried changing the source as follows:
```
root@free5gc06:~/free5gc/src/amf/ngap# diff -u handler.go.orig handler.go
--- handler.go.orig     2020-07-22 01:53:18.387325381 +0000
+++ handler.go  2020-07-27 05:53:18.701284155 +0000
@@ -126,8 +126,12 @@
                        Value: ngapType.CauseMiscPresentUnspecified,
                }
        } else {
+               for _, tai := range context.AMF_Self().SupportTaiLists {
+                       logger.NgapLog.Tracef("[AMF_Self] MCC:%s MNC:%s TAC:%s", tai.PlmnId.Mcc, tai.PlmnId.Mnc, tai.Tac)
+               }
                var found bool
                for i, tai := range ran.SupportedTAList {
+                       logger.NgapLog.Tracef("[RAN] MCC:%s MNC:%s TAC:%s", tai.Tai.PlmnId.Mcc, tai.Tai.PlmnId.Mnc, tai.Tai.Tac)
                        if context.InTaiList(tai.Tai, context.AMF_Self().SupportTaiLists) {
                                logger.NgapLog.Tracef("SERVED_TAI_INDEX[%d]", i)
                                found = true
```
**1) When `amfcfg.conf` was used as is, `NGSetupRequest` from ue-ran-sim failed with the following log.**
```
INFO[2020-07-28T03:20:14Z]/src/amf/ngap/sctp/sctp.go:42 free5gc/src/amf/ngap/sctp.Server.func1() [AMF] NGAP SCTP Accept from: 127.0.0.1/192.168.100.40/10.100.200.1/172.17.0.1/10.0.0.1:32847  AMF=NGAP
DEBU[2020-07-28T03:20:17Z]/src/amf/ngap/sctp/sctp.go:100 free5gc/src/amf/ngap/sctp.(*SCTPListener).forwardData() Packet get: 0x00150029000003001b000900020839500000000100660010000000000100020839000010080102030015400120  AMF=NGAP
INFO[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:49 free5gc/src/amf/ngap.HandleNGSetupRequest() [AMF] NG Setup request                        AMF=NGAP
TRAC[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:55 free5gc/src/amf/ngap.HandleNGSetupRequest() [NGAP] Decode IE GlobalRANNodeID              AMF=NGAP
TRAC[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:62 free5gc/src/amf/ngap.HandleNGSetupRequest() [NGAP] Decode IE SupportedTAList              AMF=NGAP
TRAC[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:76 free5gc/src/amf/ngap.HandleNGSetupRequest() [NGAP] Decode IE DefaultPagingDRX             AMF=NGAP
TRAC[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:89 free5gc/src/amf/ngap.HandleNGSetupRequest() PagingDRX[1]                                  AMF=NGAP
TRAC[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:111 free5gc/src/amf/ngap.HandleNGSetupRequest() PLMN_ID[MCC:208 MNC:093] TAC[000001]          AMF=NGAP
TRAC[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:130 free5gc/src/amf/ngap.HandleNGSetupRequest() [AMF_Self] MCC:208 MNC:93 TAC:000001          AMF=NGAP               <== MNC:93
TRAC[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:134 free5gc/src/amf/ngap.HandleNGSetupRequest() [RAN] MCC:208 MNC:093 TAC:000001              AMF=NGAP               <== MNC:093
WARN[2020-07-28T03:20:17Z]/src/amf/ngap/handler.go:142 free5gc/src/amf/ngap.HandleNGSetupRequest() NG-Setup failure: Cannot find Served TAI in AMF  AMF=NGAP
INFO[2020-07-28T03:20:17Z]/src/amf/ngap/message/send.go:91 free5gc/src/amf/ngap/message.SendNGSetupFailure() [AMF] Send NG-Setup failure                   AMF=NGAP
DEBU[2020-07-28T03:20:17Z]/src/amf/ngap/message/send.go:32 free5gc/src/amf/ngap/message.SendToRan() [NGAP] Send To Ran [IP: 127.0.0.1/192.168.100.40/10.100.200.1/172.17.0.1/10.0.0.1:32847]  AMF=NGAP
```
**2) When `amfcfg.conf` changed to mnc=093 is used, the following log is output and `NGSetupRequest` from ue-ran-sim succeeds.**
```
INFO[2020-07-28T03:22:17Z]/src/amf/ngap/sctp/sctp.go:42 free5gc/src/amf/ngap/sctp.Server.func1() [AMF] NGAP SCTP Accept from: 127.0.0.1/192.168.100.40/10.100.200.1/172.17.0.1/10.0.0.1:56617  AMF=NGAP
DEBU[2020-07-28T03:22:19Z]/src/amf/ngap/sctp/sctp.go:100 free5gc/src/amf/ngap/sctp.(*SCTPListener).forwardData() Packet get: 0x00150029000003001b000900020839500000000100660010000000000100020839000010080102030015400120  AMF=NGAP
INFO[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:49 free5gc/src/amf/ngap.HandleNGSetupRequest() [AMF] NG Setup request                        AMF=NGAP
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:55 free5gc/src/amf/ngap.HandleNGSetupRequest() [NGAP] Decode IE GlobalRANNodeID              AMF=NGAP
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:62 free5gc/src/amf/ngap.HandleNGSetupRequest() [NGAP] Decode IE SupportedTAList              AMF=NGAP
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:76 free5gc/src/amf/ngap.HandleNGSetupRequest() [NGAP] Decode IE DefaultPagingDRX             AMF=NGAP
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:89 free5gc/src/amf/ngap.HandleNGSetupRequest() PagingDRX[1]                                  AMF=NGAP
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:111 free5gc/src/amf/ngap.HandleNGSetupRequest() PLMN_ID[MCC:208 MNC:093] TAC[000001]          AMF=NGAP
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:130 free5gc/src/amf/ngap.HandleNGSetupRequest() [AMF_Self] MCC:208 MNC:093 TAC:000001         AMF=NGAP               <== MNC:093
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:134 free5gc/src/amf/ngap.HandleNGSetupRequest() [RAN] MCC:208 MNC:093 TAC:000001              AMF=NGAP               <== MNC:093
TRAC[2020-07-28T03:22:19Z]/src/amf/ngap/handler.go:136 free5gc/src/amf/ngap.HandleNGSetupRequest() SERVED_TAI_INDEX[0]                           AMF=NGAP
INFO[2020-07-28T03:22:19Z]/src/amf/ngap/message/send.go:79 free5gc/src/amf/ngap/message.SendNGSetupResponse() [AMF] Send NG-Setup response                  AMF=NGAP
DEBU[2020-07-28T03:22:19Z]/src/amf/ngap/message/send.go:32 free5gc/src/amf/ngap/message.SendToRan() [NGAP] Send To Ran [IP: 127.0.0.1/192.168.100.40/10.100.200.1/172.17.0.1/10.0.0.1:56617]  AMF=NGAP
```
However, if `mnc` in `*cfg.conf` is changed `93` to `093`, for example, `./test.sh TestRegistration` failed.

Could you know why `./test.sh XXX` failed?

**Comment by free5gc-org** [comment]
If you change the config an re-run test again, you may need to modify the test file such as

https://github.com/free5gc/free5gc/blob/master/src/test/registration_test.go#L129

**Comment by s5uishida** [comment]
Thank you for your advisement.

Modifying `src/test/*` while maintaining consistency is a bit hard.
\# The test does not pass as expected.

Also, regarding the case of zero padding, if the high-order digit is zero, it is good to omit it and then match?
Is this approach appropriate??

**Comment by s5uishida** [comment]
For the time being, when `mnc` in `amfcfg.conf` was changed from `93` to `093`, **TestNGSetup** in `ngsetup_test.go` successfully passed by changing `build.go` as follows.
```
root@free5gc06:~/free5gc/src/test/ngapTestpacket# diff -u build.go.orig build.go
--- build.go.orig       2020-07-28 02:29:21.893039749 +0000
+++ build.go    2020-07-28 11:11:22.885438546 +0000
@@ -41,7 +41,7 @@
        globalRANNodeID.GlobalGNBID = new(ngapType.GlobalGNBID)
 
        globalGNBID := globalRANNodeID.GlobalGNBID
-       globalGNBID.PLMNIdentity.Value = aper.OctetString("\x02\xf8\x39")
+       globalGNBID.PLMNIdentity.Value = aper.OctetString("\x02\x08\x39")
        globalGNBID.GNBID.Present = ngapType.GNBIDPresentGNBID
        globalGNBID.GNBID.GNBID = new(aper.BitString)
 
@@ -79,7 +79,7 @@
        broadcastPLMNList := &supportedTAItem.BroadcastPLMNList
        // BroadcastPLMNItem in BroadcastPLMNList
        broadcastPLMNItem := ngapType.BroadcastPLMNItem{}
-       broadcastPLMNItem.PLMNIdentity.Value = aper.OctetString("\x02\xf8\x39")
+       broadcastPLMNItem.PLMNIdentity.Value = aper.OctetString("\x02\x08\x39")
 
        sliceSupportList := &broadcastPLMNItem.TAISliceSupportList
        // SliceSupportItem in SliceSupportList
```

**Comment by tim-ywliu** [comment]
Hi s5uishida,

Could you change mnc back to 93 and modify ue-ran-sim as below to build and try again?

    timliu@timliu-ubuntu:~/github/ue-ran-sim$ git diff
    diff --git a/core/src/main/java/tr/havelsan/ueransim/core/Constants.java 
    b/core/src/main/java/tr/havelsan/ueransim/core/Constants.java
    index f0978006..4130b379 100644
    --- a/core/src/main/java/tr/havelsan/ueransim/core/Constants.java
    +++ b/core/src/main/java/tr/havelsan/ueransim/core/Constants.java
    @@ -35,5 +35,5 @@ public final class Constants {
         public static final int DEFAULT_STREAM_NUMBER = 1;
    
         // here assumed always 3 digit, but it can be changed to false for actual production, no problem.
    -    public static final boolean ALWAYS_LONG_MNC = true;
    +    public static final boolean ALWAYS_LONG_MNC = false;
     }

**Comment by s5uishida** [comment]
@tim-ywliu Thank you very much! It worked fine!!

As an aside, I changed the following configs and test codes, and confirmed that Test a-i (except h.TestNon3GPP) passed successfully with the setting of mnc=093.

That was hard :-)
```
- free5gc/config/*
- free5gc/src/test/*
```

Is 5GC responsible for the interpretation of zero-padded numbers of mcc and mnc? Or UE/RAN? All?

**Comment by tim-ywliu** [comment]
@s5uishida 

The mnc CAN NOT be auto zero-padded by 5GC because it is fixed setting from SIM and Operator.
You can refer to this wiki to know more about mcc and mnc:
https://en.wikipedia.org/wiki/International_mobile_subscriber_identity

BTW, I use the latest ue-ran-sim and want to set up PDU session with free5gc 3.0.3, but it failed:

    [2020-07-29 06:36:32.103] [DEBUG] [SYSTEM] UeSimContext has started: 892fa08e-ff51-41d6-9af8-f031b985d604
    [2020-07-29 06:36:32.104] [DEBUG] [SYSTEM] GnbSimContext has started: 4fa715f8-ec6d-49c7-8a2b-95cb732e5e67
    [2020-07-29 06:36:32.104] [INFO] [CONNECTION] Trying to establish SCTP connection... (127.0.0.1:38412)
    [2020-07-29 06:36:32.122] [INFO] [CONNECTION] SCTP connection established
    [2020-07-29 06:36:32.217] [ERROR] [SYSTEM] java.lang.OutOfMemoryError: Java heap space
            at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:61)
            at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:348)
            at tr.havelsan.ueransim.sctp.SctpClient.receiverLoop(SctpClient.java:87)
            at tr.havelsan.ueransim.core.threads.SctpRecevierThread.run(SctpRecevierThread.java:50)

Could you share all your configurations and modifications for me to try?
Many thanks.

**Comment by s5uishida** [comment]
OK. Thank you for the information.

It happened here as well. However, it disappeared when the OS was restarted. (Why?)

The configsand test codes when mcc=208 and mnc=093 are as follows.

[config_mcc208_mnc093.tar.gz](https://github.com/free5gc/free5gc/files/4993309/config_mcc208_mnc093.tar.gz)
[test_mcc208_mnc093.tar.gz](https://github.com/free5gc/free5gc/files/4993311/test_mcc208_mnc093.tar.gz)

I set the various log levels of `free5GC.conf` to `trace` and used.

**Comment by tim-ywliu** [comment]
@s5uishida 

I found the root cause: the RECEIVER_BUFFER_SIZE is too large.
Here's my all modifications for ue-ran-sim (no modification for free5gc) and finally get **[SUCCESS] [PROCEDURE_RESULT] NGSetup procedure is successful**.

    diff --git a/core/src/main/java/tr/havelsan/ueransim/core/Constants.java 
    b/core/src/main/java/tr/havelsan/ueransim/core/Constants.java
    index f0978006..4130b379 100644
    --- a/core/src/main/java/tr/havelsan/ueransim/core/Constants.java
    +++ b/core/src/main/java/tr/havelsan/ueransim/core/Constants.java
    @@ -35,5 +35,5 @@ public final class Constants {
         public static final int DEFAULT_STREAM_NUMBER = 1;

         // here assumed always 3 digit, but it can be changed to false for actual production, no problem.
    -    public static final boolean ALWAYS_LONG_MNC = true;
    +    public static final boolean ALWAYS_LONG_MNC = false;
     }

    diff --git a/sctp/src/main/java/tr/havelsan/ueransim/sctp/SctpClient.java 
    b/sctp/src/main/java/tr/havelsan/ueransim/sctp/SctpClient.java
    index cdc7c7fa..14d6f544 100644
    --- a/sctp/src/main/java/tr/havelsan/ueransim/sctp/SctpClient.java
    +++ b/sctp/src/main/java/tr/havelsan/ueransim/sctp/SctpClient.java
    @@ -36,7 +36,7 @@ import java.net.InetSocketAddress;
     import java.nio.ByteBuffer;
    
     public class SctpClient implements ISctpClient {
    -    private static final int RECEIVER_BUFFER_SIZE = 1073741824;
    +    private static final int RECEIVER_BUFFER_SIZE = 64000;

         private final String host;
         private final int port;

    diff --git a/yaml/gnb.yaml b/yaml/gnb.yaml
    index 2ee982be..19546953 100644
    --- a/yaml/gnb.yaml
    +++ b/yaml/gnb.yaml
    @@ -1,34 +1,34 @@
     gnbId: 1

     gnbPlmn:
    -  mcc: 1
    -  mnc: 1
    +  mcc: 208
    +  mnc: 93
    
     amfConfigs:
       - guami:
    -      mcc: 1
    -      mnc: 1
    +      mcc: 208
    +      mnc: 93
           amfRegionId:
             hex: '2a'
           amfSetId:
             hex: '5580'
           amfPointer:
             hex: 'a8'
    -    host: 10.154.14.19
    -    port: 38421
    +    host: 127.0.0.1
    +    port: 38412
         isMocked: false
         mockingFile: mockedAmf.yaml

     supportedTAs:
       - tac:
    -      hex: '000075'
    +      hex: '000001'
         broadcastPlmns:
           - plmn:
    -          mcc: 1
    -          mnc: 1
    +          mcc: 208
    +          mnc: 93
             taiSliceSupportNssais:
               - sst:
                   value: 1
    -#            sd:
    -#              value:
    -#                hex: '09afaf'
    \ No newline at end of file
    +            sd:
    +              value:
    +                hex: '010203'

**Comment by free5gc-org** [comment]
Hi @s5uishida @tim-ywliu ,

So as discussion, I think we don't need to add auto zero-padded on mcc and mnc, right?

**Comment by s5uishida** [comment]
@tim-ywliu Thank you for your information.

The next time OOM occurs, I will try it, too.

> BTW, do you know how to trigger UE registration and PDU session establishment?
```
root@free5gc06:~/LONGOFF/sim# java -jar ueransim-1.0.8.jar 
WARNING: All logs are written to: app.log
Possible events:[
  "initial-registration",
  "periodic-registration"
]
Type event:
New association setup with 5 outbound streams, and 3 inbound streams.
initial-registration       <== input & return
Event pushed.
Type event:
```
It may be  appropriate to change to the ue-ran-sim repository about this.

**Comment by s5uishida** [comment]
> So as discussion, I think we don't need to add auto zero-padded on mcc and mnc, right?

I think so, too.

**Comment by tim-ywliu** [comment]
@free5gc-org 

It depends.
If mnc is used in FQDN or Identifier, it might be 3-digit format:

TS 23.003 -
In order to guarantee inter-PLMN DNS translation, the <MNC> and <MCC> coding used in the "n3iwf.5gc. mnc<MNC>.mcc<MCC>.pub.3gppnetwork.org" format of the Operator Identifier based N3IWF FQDN shall be:
-	<MNC> = 3 digits
-	<MCC> = 3 digits

In this case, if the original mnc is 2 digit only, the N3IWF should use zero padded mnc to generate the FQDN.
If the mnc is used for identify plmn, it should not be zero padded.

**Comment by tim-ywliu** [comment]
@s5uishida 

Did you pass the initial-registration event test?
I failed the initial-registration event test.
Could you share the ue-ran-sim configuration and modification for me?
Many thanks.
