### ISSUE TITLE
[Feat] Supporting CentOS/RHEL 

### ISSUE THREAD

**Issue by subharobin** [free5gc/free5gc#83]
### What's the version are you using
We would like to test free5gc over CentOS. is there any recommendation to do this?

### Is your feature request related to a problem? Please describe.
No, not related to a problem

### Describe the solution you'd like
Availability of free5GC software qualified on RHEL/CentOS

### Describe alternatives/workarounds you've considered
None

### Additional context
We have a platform that has been validated for CENTOS, it is difficult to 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X ] No, I don't have the time and I wouldn't even know how to start.

We dont have the expertise to do this.

**Comment by calee0219** [comment]
How about trying to use container to run free5GC on CentOS?

https://github.com/free5gc/free5gc-compose

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/free5gc-installation-on-centos/2173/3
