### ISSUE TITLE
[BUG]Error while building UPF build 

### ISSUE THREAD

**Issue by anshu-s** [free5gc/free5gc#87]
## Describe the bug
I am facing below  error while building upf build in ubuntu os after following mentioned upf build commands 
gtp5g-link.o: In function `main':
/home/anshu/cn/core_network/free5gc/src/upf/lib/libgtp5gnl/tools/gtp5g-link.c:81: undefined reference to `gtp_dev_create_ran'
/home/anshu/cn/core_network/free5gc/src/upf/lib/libgtp5gnl/tools/gtp5g-link.c:83: undefined reference to `gtp_dev_create'
/home/anshu/cn/core_network/free5gc/src/upf/lib/libgtp5gnl/tools/gtp5g-link.c:56: undefined reference to `gtp_dev_destroy'
collect2: error: ld returned 1 exit status
Makefile:356: recipe for target 'gtp5g-link' failed
make[5]: *** [gtp5g-link] Error 1
Makefile:470: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
Makefile:378: recipe for target 'all' failed
make[3]: *** [all] Error 2
lib/gtpv1/CMakeFiles/libgtp5gnl.dir/build.make:60: recipe for target 'libgtp5gnl/lib/libgtp5gnl.so' failed
make[2]: *** [libgtp5gnl/lib/libgtp5gnl.so] Error 2
CMakeFiles/Makefile2:239: recipe for target 'lib/gtpv1/CMakeFiles/libgtp5gnl.dir/all' failed
make[1]: *** [lib/gtpv1/CMakeFiles/libgtp5gnl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

## To Reproduce
cd ~/free5gc/src/upf
mkdir build
cd build
cmake ..
make -j`nproc`

## Expected behavior
binary should be generated for upf

.

## Environment (please complete the following information):
 - free5GC Version [e.g. v3.0.2]
 - OS: [ Ubuntu 18.04 Server]
 - Kernel version [ 5.0.0-23-generic]
- go version [1.12.9 linux/amd64]
 - c compiler version () [ gcc version 7.5.0]

**Comment by anshu-s** [comment]
Hi

I have installed below linux kernel header , but still facing same issue .
x kernel version 5.0.0
ii  linux-headers-5.0.0-23-generic             5.0.0-23.24~18.04.1                              amd64        Linux kernel headers for version 5.0.0 on 64 bit x86 SMP
ii  linux-headers-5.4.0-050400                 5.4.0-050400.201911242031                        all          Header files related to Linux kernel version 5.4.0

**Comment by free5gc-org** [comment]
Can you check (with `uname -ra` command) which kernel version are you using?

**Comment by anshu-s** [comment]
uname -ra :-
Linux ggnlabvm-oran03 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Regards
Anshula

**Comment by anshu-s** [comment]
> Can you check (with `uname -ra` command) which kernel version are you using?

**Comment by anshu-s** [comment]
Hi 

i am using kernel version :-  5.0.0-23-generic

**Comment by anshu-s** [comment]
working now .. was issue with linux header
