### ISSUE TITLE
[Feat] Supporting TUAK algorithm set as the AKA algorithm

### ISSUE THREAD

**Issue by am677** [free5gc/free5gc#93]
### What's the version are you using
v3.0.3

### Is your feature request related to a problem? Please describe.
Free5GC currently supports only the MILENAGE algorithm set in 5G-AKA.
There are SIM cards that use the TUAK algorithm instead of the MILENAGE.
An UE with this SIM card can not be registered to the free5GC system.

### Describe the solution you'd like
Free5GC will support the TUAK algorithm and I will choose a SIM authentication algorithm between MILLENAGE and TUAK in each SIM card.

### Describe alternatives/workarounds you've considered
None.

### Additional context
3GPP TS 35.231 specify the TUAK algorithm set.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by iamelisahi** [comment]
@am677 Hi, I wanted to inform you that we have decided not to implement the TUAK algorithm at the moment. However, if you have already implemented it, we would appreciate it if you could share your implementation with us.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

http://forum.free5gc.org/t/authentication-request-authentication-failure-mac-failure-authentication-reject/2207/12
