### ISSUE TITLE
[Bugs] QosRules in the PDU Session establishment Accept is wrong coded

### ISSUE THREAD

**Issue by 22vlapp** [free5gc/free5gc#95]
## Describe the bug
The default Qos Rule sent by the AMF in the payload container of the pDUSessionNAS-PDU of the PDU session establishment accept is wrong coded :
     - The length value of the default QoS rule is set to 1585 bytes instead of the expected value 6 bytes.
     - The packet filter component type is coded with an unspecified value (0 – Unknown) instead of one of the values specified in the 3gpp 24.501.
     - The last byte of the Qos Rule which define the Qos Flow Identifier and segregration is missing.
     - In consequence, the length values of the of QoS rules and Payload containers IEs are also wrong coded.

The current hexa stream of the pDUSessionNAS-PDU is set as follow (the wrong code in bold ) :

7e00680100**1d**2e0a00c21100**08**01**0631**3101010009xx0601e80301e8032905013c3c0001120a

## To Reproduce
1. Change config 'default Config'
2. Code patch 'no patch' 
3. Run command './test.sh TestPDUSessionReleaseRequest or ./run.sh''
4. Dump packet 'Qos Rule in the pDUSessionNAS-PDU of the PDU session establishment accept'

## Expected behavior
the AMF sends a QoS rule right coded in the pDUSessionNAS-PDU of the PDU session establishment accept as the following proposition (the wrong code in bold) :

7e00680100**1e**2e0a00c21100**09**010006310101**01**09**06**0601e80301e8032905013c3c0001120a

## Screenshots
 - QoS rule is set to 1585 bytes
![image](https://user-images.githubusercontent.com/70031867/90928344-fd56b700-e3f6-11ea-9d5f-cabdd71172df.png)

 - The packet filter component type is coded with an unspecified value (0 – Unknown)
![image](https://user-images.githubusercontent.com/70031867/90928467-32630980-e3f7-11ea-963e-bba9424b299e.png)

## Environment (please complete the following information):
 - free5GC Version: [v3.0.2]
 - OS: [Ubuntu 18.04 Server]
 - Kernel version: [5.0.0-23-generic]
 - go version: [1.12.9 linux/amd64]

### Configuration File
[config.zip](https://github.com/free5gc/free5gc/files/5110894/config.zip)

### PCAP File

[20200821_TestPDUSessionReleaseRequest_f5gc302.zip](https://github.com/free5gc/free5gc/files/5110906/20200821_TestPDUSessionReleaseRequest_f5gc302.zip)

### Log File

[20200821_TestPDUSessionReleaseRequest_f5gc302.txt](https://github.com/free5gc/free5gc/files/5110910/20200821_TestPDUSessionReleaseRequest_f5gc302.txt)

**Comment by free5gc-org** [comment]
The issue seems to relate to the PR

https://github.com/free5gc/smf/pull/3

We'll check and merge it.

**Comment by free5gc-org** [comment]
Sorry, seems that this is not the same issue as SMF PR#3.

How about using free5gc v3.0.3, will there still remind the same bug?

**Comment by 22vlapp** [comment]
Hi,

The bug seems to be fixed in the free5gc V3.0.3

![image](https://user-images.githubusercontent.com/70031867/91172978-5d8e7700-e6dd-11ea-888b-f21055b77f48.png)

However, a fix in the v3.0.2  could be interesting for UE simulators which don't support yet the NAS security mechanisms (AMF doesn't check security mode #60)

**Comment by free5gc-org** [comment]
We're sorry about that we don't maintain different branch(version) now due to the lack of our resource.

You can make the patch yourself and it might be easy due to free5GC is totally open source. 😃
