### ISSUE TITLE
[Feat] Using go modules also for the other lib packages.

### ISSUE THREAD

**Issue by endrigoshi** [free5gc/free5gc#99]
Hi guys,

I opened this issue for a feature request regarding the use of `go modules` also for other libs such as `ngap`, `nas` etc.

As in the latest version you changed to using `go modules` for the dependencies of free5gc, I was thinking whether it would be better to apply the came approach for the other packages as well. 

Would it be possible to rename the `free5gc` module to smth like `github.com/free5gc/free5gc` and then use this format when importing all the modules inside the code? I suppose this will require to change the import format inside packages such as `ngap` as well.

BR,
Endri

**Comment by free5gc-org** [comment]
This may be a good issue. But the over head is a little large. It will not be our first priority if there is not a strong reason to do it. 🤔

**Comment by endrigoshi** [comment]
Yes I also think its not very important for now, but it is somehow necessary when reusing the libraries (e.g. nas, ngap) for other projects. But I suppose we can leave it on hold for now.

**Comment by free5gc-org** [comment]
This issue has been mentioned on **free5GC**. There might be relevant details there:

https://forum.free5gc.org/t/go-modules-for-git-submodules/338/2

**Comment by free5gc-org** [comment]
We're now working on it.

**Comment by free5gc-org** [comment]
All modules in free5gc v3.0.5 release are already changed to Go modules.
